WIP-CHANGELOG.md, helmfile/charts/harbor/harbor-backup/templates/harbor-backup-job.yaml
Since v1beta1 isn't included in Kubernetes v1.25.
**Checklist:**
=> apps sc: Update harbor backup job api version

WIP-CHANGELOG.md, release/README.md
To better constrain what different types of releases may contain, especially for patch releases.
fixes #1374
**Checklist:**
=> docs: Add release constraints

WIP-CHANGELOG.md, helmfile/charts/user-rbac/templates/rolebindings/workload-admin.yaml, migration/v0.29/README.md, migration/v0.29/apply/50-user-rbac.sh, scripts/deploy-wc.sh, scripts/migration/lib.sh
We can't have it where it is right now as it tries to create it before the namespaces exists, and I like to keep everything in helm charts so I came up with a different solution.
It will only try to install it on install/upgrade if it doesn't already exists and it has the annotation to kept so in subsequent runs it's just ignored.
We could employ this trick more to remove the need for the deploy script completely.
**Checklist:**
- …
=> apps wc: Move rolebinding to user-rbac chart

scripts/bom/get-bom.py
We sometimes gets questions around the Compliant Kubernetes Bill of Materials (BOM). The purpose of the BOM is to ensure that:
- We don't violate any licenses.
- We are aware of the risks involved with "one men shows" and components getting abandoned.
- We are aware of the risks with various copyright owners, e.g., bankruptcy, change in license, etc.
The BOM essentially allows us to verify that we comply with [ADR-0015](https://elastisys.io/compliantkubernetes/adr/0015-we-believe-in-community-driven-open-source/).
Automating the whole process across Helm Charts, Ansible scripts and Python dependencies, etc. is a tedious work. Partial solutions exist out [there](https://github.com/kubernetes-sigs/bom), but don't quite suit our needs.
This script …
=> Script to get BOM

WIP-CHANGELOG.md, helmfile/charts/prometheus-servicemonitor/templates/rook-monitor.yaml
The ceph dashboard has been half broken for some time and we found that the scrape interval was too fast so something wierd happened there. However when upping the scrape interval things started working again, so lets increase it.
**Checklist:**
E.g. …
=> apps: Increased scrape interval for rook-ceph

WIP-CHANGELOG.md, helmfile/values/fluentd/forwarder-common.yaml.gotmpl
To improve our kubernetes audit logs in opensearch to include relevant information
fixes #1455 
I haven't looked at the chunk settings in fluentd but they might need to be tweaked now that there is the possibliity that response or request bodies can be quite large.
**Checklist:**
I.e. full cluster migration is …
=> apps: log bodies from audit events

WIP-CHANGELOG.md, config/config/common-config.yaml, helmfile/values/ingress-nginx.yaml.gotmpl, migration/v0.30/README.md, migration/v0.30/apply/00-template.sh, migration/v0.30/apply/10-bootstrap.sh, migration/v0.30/apply/80-apply.sh, migration/v0.30/prepare/00-template.sh, migration/v0.30/prepare/10-init.sh
Added option to run nginx controller as deployment and option to use service type nodeport.
Default is still deamonset.
**Checklist:**
If you change some config options (e.g. add/rename variable …
=> apps: add deployment option for ingress and nodeport

WIP-CHANGELOG.md, scripts/migration/lib.sh
Found this bug when I demo:d the new upgrade method.
**Checklist:**
=> apps: Correct version checks in migration script library

WIP-CHANGELOG.md, migration/template/README.md, migration/template/apply/80-apply.sh, migration/v0.30/apply/80-apply.sh, scripts/migration/helmfile.sh
Bug that prevented the apply snippet to run when it doesn't have filters set.
**Checklist:**
=> apps: Run apply snippet without filters

WIP-CHANGELOG.md, helmfile/values/fluentd/forwarder-common.yaml.gotmpl
I think it might make more sense to base time from the timestamp for a request based on when it enters a stage.
Previously requests for all stages got the same timestamp.
Let me know what you think
Before
After (ignore the requestReceived stage)
**Checklist:**
- Chart checklist …
=> apps: use stageTimestamp as timekey for audit logs

migration/v0.30/README.md
Wasn't able to run the steps in the migration docs.
The command should take the version before the verb according to the comand info.
```
$ ./bin/ck8s upgrade prepare v0.30
COMMANDS:
...
upgrade <version-matching-migration> prepare      runs all prepare steps upgrading the configuration
upgrade <version-matching-migration> apply        runs all apply steps upgrading the environment
```
**Checklist:**
- Is this changeset backwards …
=> docs: fix migration arguments order

WIP-CHANGELOG.md, bootstrap/namespaces/helmfile/values/namespaces-sc.yaml.gotmpl, helmfile/14-podsecuritypolicies.yaml, helmfile/values/podsecuritypolicies/service/harbor.yaml.gotmpl
**What this PR does / why we need it**: Fix PSA and gatekeeper PSP for Harbor. Tested backup and restore as well.
Based on https://github.com/elastisys/compliantkubernetes-apps/pull/1477 but I will rebase once that is merged.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1450 
**Checklist:**
E.g. removes or changes any CK8S config options …
=> apps-sc: PSA and gatekeeper PSP for harbor

WIP-CHANGELOG.md, config/config/common-config.yaml, helmfile/50-applications.yaml, helmfile/charts/gatekeeper/mutations/.helmignore, helmfile/charts/gatekeeper/mutations/Chart.yaml, helmfile/charts/gatekeeper/mutations/templates/job-ttl.yaml, helmfile/charts/gatekeeper/mutations/values.yaml, helmfile/values/gatekeeper/mutations.yaml.gotmpl
Adds a new chart containing a single gatekeeper mutation for setting job ttl if not already set.
By default, a ttl of7 days is set.
Let me know what you think
**Checklist:**
I.e. full …
=> apps: add mutation for setting job ttl

WIP-CHANGELOG.md, bootstrap/namespaces/helmfile/values/namespaces-sc.yaml.gotmpl, bootstrap/namespaces/helmfile/values/namespaces-wc.yaml.gotmpl, helmfile/values/cert-manager.yaml.gotmpl, helmfile/values/dex.yaml.gotmpl
**What this PR does / why we need it**: to enabled PSA for dex and cert-manager
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1447 
- dex:
- changes: I added the necessary securitycontext setting to match the restricted policy
- tested: delete and re-install the chart, logs, login using dex
- cert-manager
- changes: nothing all the setting were add in the upstream chart
- tested: delete and re-install the chart, logs, force renew a certificate and check that it worked
- tbd: there are some situations when the webhook component might need hostNetwork and/or hostPorts, but as we do not use it at the moment I didn't switch to gatekeeper …
=> apps: enabled psa for dex and cert-manager

WIP-CHANGELOG.md, bootstrap/namespaces/helmfile/values/namespaces-sc.yaml.gotmpl, bootstrap/namespaces/helmfile/values/namespaces-wc.yaml.gotmpl, helmfile/14-podsecuritypolicies.yaml, helmfile/values/podsecuritypolicies/common/velero.yaml.gotmpl, helmfile/values/velero-sc.yaml.gotmpl, helmfile/values/velero-wc.yaml.gotmpl
Velero seems to be fine running using the default restricted securityContext.
Restic needs privilege, I used postgres for my test to confirm functionality by taking a backup and restoring that backup, and I couldn't get that to work unless running as privileged. 
fixes #1449 
**Checklist:**
I.e. full cluster migration …
=> apps: add gatekeeper psps for velero

WIP-CHANGELOG.md, helmfile/charts/user-rbac/templates/rolebindings/workload-admin.yaml
Else diff will report it as new all the time.
**Checklist:**
=> apps wc: Make user-rbac extra-workload-admins idempotent

WIP-CHANGELOG.md, helmfile/charts/grafana-ops/dashboards/harbor-dashboard.json, helmfile/charts/grafana-ops/values.yaml, helmfile/charts/networkpolicy/service-cluster/templates/harbor/allow-harbor-core.yaml, helmfile/charts/networkpolicy/service-cluster/templates/harbor/allow-harbor-database.yaml, helmfile/charts/networkpolicy/service-cluster/templates/harbor/allow-harbor-exporter.yaml, helmfile/charts/networkpolicy/service-cluster/templates/harbor/allow-harbor-jobservice.yaml, helmfile/charts/networkpolicy/service-cluster/templates/harbor/allow-harbor-redis.yaml, helmfile/values/grafana-ops.yaml.gotmpl, helmfile/values/harbor.yaml.gotmpl
**What this PR does / why we need it**: Dashboard is based on this one, but modified a bit to have datasource variable and shorter legends: https://github.com/goharbor/harbor/blob/main/contrib/grafana-dashborad/metrics-example.json
**Checklist:**
E.g. removes or changes any CK8S config …
=> apps-sc: add harbor metrics and dashboard

WIP-CHANGELOG.md, helmfile/values/fluentd/forwarder-workload-cluster-system.yaml.gotmpl
=> apps: indentation issue in fluentd values file

WIP-CHANGELOG.md, helmfile/charts/opensearch/configurer/templates/config.yml, helmfile/charts/opensearch/configurer/templates/job.yaml
Since else it requires a sync.
fixes #1507 
**Checklist:**
=> apps sc: Ensure opensearch-configurer runs on changes

WIP-CHANGELOG.md, helmfile/values/fluentd/forwarder-workload-cluster-user.yaml.gotmpl
Bugfix as it was not sourcing the config as it should have done.
**Checklist:**
=> apps wc: Source extra Fluentd config

WIP-CHANGELOG.md, config/config/sc-config.yaml, migration/v0.30/prepare/05-increase-promIndexAlerts-authlog.sh
Increase default promIndexAlerts alertsize for authlog from 0.2 to 2
**Checklist:** …
=> apps: Increase default promIndexAlerts alertsize for authlog

WIP-CHANGELOG.md, helmfile/50-applications.yaml, helmfile/upstream/dex/Chart.yaml, helmfile/upstream/dex/README.md, helmfile/upstream/dex/templates/_helpers.tpl, helmfile/upstream/dex/templates/ingress.yaml, helmfile/upstream/dex/values.yaml
**What this PR does / why we need it**: Upgraded dex to chart v0.14.1, app v2.36.0
**Which issue this PR fixes**: fixes #1406 
**Checklist:** …
=> apps sc: upgrade dex chart to v0.14.1, app v2.36.0

helmfile/11-prometheus-operator.yaml, migration/v0.30/apply/20-remove-kube-prometheus-components.sh, migration/v0.30/apply/80-apply.sh
**What this PR does / why we need it**: the script to remove monitoring components should run only when needed
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1496 
- the `app=prometheus-node-exporter` label does not exists in the new version of node-exporter, so the daemonset will not be removed if we re-run the upgrade scripts
**Checklist:**
- Chart …
=> apps: fix kube-prometheus-stack migration script

WIP-CHANGELOG.md, helmfile/values/fluentd/aggregator-common.yaml.gotmpl, helmfile/values/fluentd/aggregator-service-cluster.yaml.gotmpl, migration/v0.29/README.md, pipeline/test/services/service-cluster/testPodsReady.sh
**What this PR does / why we need it**: some fixes for the 0.29 release
**Checklist:**
=> Crssnd/fixes 0.29 release

WIP-CHANGELOG.md, helmfile/charts/node-local-dns/templates/node-local-dns.yaml
Upgrades node-local-dns image
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1408 
**Checklist:** …
=> apps: upgrade node-local-dns

WIP-CHANGELOG.md, config/config/common-config.yaml, helmfile/values/fluentd/aggregator-common.yaml.gotmpl
So we can tune buffer settings to cope with higher log volumes.
Should I do this for forwarder as well?
**Checklist:**
=> apps: Expose all `fluentd-aggregator` buffer settings

WIP-CHANGELOG.md, helmfile/values/grafana-user.yaml.gotmpl, helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
This should fix the issue that may come up on Cleura when Grafana can't resolve the IP to Dex.
**Checklist:**
=> apps sc: Use FQDN for Grafana to Dex communication

WIP-CHANGELOG.md, config/config/common-config.yaml, helmfile/11-prometheus-operator.yaml, helmfile/charts/kube-state-metrics-extra-resource-metrics/Chart.yaml, helmfile/charts/kube-state-metrics-extra-resource-metrics/README.md, helmfile/charts/kube-state-metrics-extra-resource-metrics/files/clusterapi-metrics.yaml, helmfile/charts/kube-state-metrics-extra-resource-metrics/templates/clusterapi-configmap.yaml, helmfile/charts/kube-state-metrics-extra-resource-metrics/values.yaml, helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl, helmfile/values/kube-prometheus-stack-wc.yaml.gotmpl, helmfile/values/kube-state-metrics-extra-resource-metrics.yaml.gotmpl
Wasn't able to find any prepared dashboards or alerts, will create issues to make our own.
fixes the metrics part of [this issue](https://github.com/elastisys/ck8s-cluster-api/issues/11).
Decided to add it to both SC & WC for flexibility, even though we will likely only use this in SC internally.
**Checklist:** …
=> apps: added the possibility to enable metrics for Cluster API

WIP-CHANGELOG.md, helmfile/charts/grafana-ops/dashboards/node-local-dns-dashboard.json, helmfile/charts/grafana-ops/values.yaml
#422 
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #422
**Checklist:** …
=> Grafana Dashboard for Node Local DNS

WIP-CHANGELOG.md, helmfile/charts/networkpolicy/common/templates/rook-ceph/mgr.yaml
**What this PR does / why we need it**: to allow prometheus scrape the rook-ceph metrics
**Checklist:**
=> apps: rook-ceph netpol allow prometheus

WIP-CHANGELOG.md, helmfile/charts/gatekeeper/podsecuritypolicies/templates/default/mutations/seccomp-profile.yaml, helmfile/charts/gatekeeper/podsecuritypolicies/values.yaml
Add default mutation for setting seccomp profile with the ability to disable the mutation.
**Checklist:** …
=> apps: add gatekeeper mutation for seccomp

migration/v0.30/apply/20-remove-kube-prometheus-components.sh
Can't run bare kubectl in this context, fails with
> The connection to the server localhost:8080 was refused - did you specify the right host or port?
> [ck8s] v0.30/apply: apply snippet execute failure
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes ... see above
**Checklist:** …
=> apps: really fix kube-prometheus-stack migration script

WIP-CHANGELOG.md, helmfile/values/kube-prometheus-stack-wc.yaml.gotmpl
Discovered today that not all probes where selected by prometheus in the workload cluster.
I decided to change that.
**Checklist:**
- Chart …
=> apps wc: allow discovery of all probes

WIP-CHANGELOG.md, helmfile/charts/opensearch/configurer/files/configurer.sh, helmfile/values/opensearch/securityadmin.yaml.gotmpl, migration/v0.30/README.md
Opensearch will check if the snapshot repo already exists and if it is pointing to the same bucket.
If bucket name changes it will re-register the repository.
**Checklist:** …
=> apps sc: opensearch configurer snapshot register logic rework

WIP-CHANGELOG.md, helmfile/values/falco.yaml.gotmpl
**What this PR does / why we need it**: Noticed that falco triggers alerts when containerd deletes images if they contain certain files (log files and shell config). So this will exclude any of those alerts if the file is deleted by containerd and it was in the image storage.
Link to the original falco rules:
https://github.com/elastisys/compliantkubernetes-apps/blob/ef3c1a55f529e3f75a4f17c91b3f01ad46d3aa07/helmfile/upstream/falco/rules/falco_rules.yaml#L453
https://github.com/elastisys/compliantkubernetes-apps/blob/ef3c1a55f529e3f75a4f17c91b3f01ad46d3aa07/helmfile/upstream/falco/rules/falco_rules.yaml#L2595
**Public facing …
=> apps: falco filter for image cleanup by containerd

helmfile/50-applications.yaml
**What this PR does / why we need it**: The trivy-operator chart wants to create some ClusterComplianceReport objects and the validation fails because the CRDs does not exist before this chart is installed. You get these kinds of errors: `Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ClusterComplianceReport" in version "aquasecurity.github.io/v1alpha1"`
Disabling the validation fixes this.
This should only be a problem on new clusters.
**Add a screenshot or an example to …
=> apps: fix trivy-operator installation

WIP-CHANGELOG.md, helmfile/upstream/prometheus-elasticsearch-exporter/Chart.yaml, helmfile/upstream/prometheus-elasticsearch-exporter/README.md, helmfile/upstream/prometheus-elasticsearch-exporter/ci/security-context.yaml, helmfile/upstream/prometheus-elasticsearch-exporter/templates/_helpers.tpl, helmfile/upstream/prometheus-elasticsearch-exporter/templates/deployment.yaml, helmfile/upstream/prometheus-elasticsearch-exporter/templates/podsecuritypolicies.yaml, helmfile/upstream/prometheus-elasticsearch-exporter/templates/servicemonitor.yaml, helmfile/upstream/prometheus-elasticsearch-exporter/values.yaml, helmfile/values/prometheus-opensearch-exporter.yaml.gotmpl
Upgrade prometheus-elasticsearch-exporter to 5.1.1
**Checklist:**
If …
=> apps: upgrade prometheus-elasticsearch-exporter to 5.1.1

WIP-CHANGELOG.md, config/config/wc-config.yaml
**What this PR does / why we need it**: to exclude fluentd-system ns from hnc and velero
**Checklist:**
=> apps wc: exclude fluentd-system ns from hnc

WIP-CHANGELOG.md, helmfile/14-podsecuritypolicies.yaml, helmfile/values/podsecuritypolicies/workload/default.yaml.gotmpl
Adds the default mutation for user namespaces that are locked down with the restricted pod security policy. The helm release is installed in the default namespace. This means that the gatekeeper constraints are applied to that namespace, which should be fine as no user should have access to the default namespace.
**Checklist:**
E.g. logs or metrics are not …
=> apps wc: add default securitycontext mutations for user namespaces

helmfile/values/opensearch/configurer.yaml.gotmpl, helmfile/values/prometheus-opensearch-exporter.yaml.gotmpl
**What this PR does / why we need it**: fixes to opensearch exporter
- I used this [list](https://github.com/prometheus-community/elasticsearch_exporter#elasticsearch-7x-security-privileges) to determine the permissions needed by the exporter
**Checklist:**
=> apps sc: missing uri and permissions for opensearch exporter

.github/workflows/pipeline.yml, scripts/restore/README.md
**What this PR does / why we need it**: Add a step to the harbor restore docs, that needs to be run if you are restoring to a new environment with a different domain.
**Which issue this PR fixes**: fixes elastisys/compliantkubernetes#492
**Checklist:** …
=> docs: add step for restoring harbor from backup in new env

WIP-CHANGELOG.md, bin/init.bash, config/config/common-config.yaml, helmfile/14-podsecuritypolicies.yaml, helmfile/charts/gatekeeper/podsecuritypolicies/templates/default/capabilities.yaml, helmfile/charts/gatekeeper/podsecuritypolicies/templates/default/mutations/privilege-escalation.yaml, helmfile/charts/gatekeeper/podsecuritypolicies/templates/default/privilege-escalation.yaml, helmfile/values/podsecuritypolicies/common/rook-ceph.yaml.gotmpl, migration/v0.30/README.md
add gatekeeper psps for rook-ceph
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1451 
**Checklist:**
If you change …
=> apps: add gatekeeper psps for rook-ceph

WIP-CHANGELOG.md, config/config/sc-config.yaml
Since the defaults for fluentd will cause a lot of chunks we should compact them more often so it won't need several hours each time.
**Checklist:**
=> apps sc: Run log-manager compact more frequently

WIP-CHANGELOG.md, config/config/sc-config.yaml, config/secrets/sc-secrets.yaml
=> apps sc: fix inconsistencies for rclone encyrption

WIP-CHANGELOG.md, helmfile/values/grafana-user.yaml.gotmpl, helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
**What this PR does / why we need it**: to use the latest patch release that has some security fixes
**Checklist:**
=> apps sc: use the latest patch release for grafana

WIP-CHANGELOG.md, helmfile/charts/grafana-ops/dashboards/falco-dashboard.json
Updates the Falco Grafana dashboard to be a bit more usable.
(Since I already had these changes made during the work with falco exceptions.)
**Checklist:** …
=> apps sc: Update Falco Grafana dashboard

WIP-CHANGELOG.md, bootstrap/namespaces/helmfile/values/namespaces-sc.yaml.gotmpl, bootstrap/namespaces/helmfile/values/namespaces-wc.yaml.gotmpl, config/config/common-config.yaml, helmfile/12-gatekeeper.yaml, helmfile/13-gatekeeper-templates.yaml, helmfile/50-applications.yaml, helmfile/values/networkpolicy/common.yaml.gotmpl, migration/v0.30/prepare/09-gatekeeper-enabled.sh, pipeline/test/services/workload-cluster/testPodsReady.sh
Since we rely on Gatekeeper for PSP, we can't really disable it nowadays.
**Checklist:**
=> apps: OPA always enabled

migration/v0.30/README.md, migration/v0.30/apply/99-psp-violations.sh
Add a step to the migration docs for restarting the pods that are or will be violating the new gatekeeper PSPs.
fixes #1495
```console
$ ./migration/v0.30/apply/90-psp-violations.sh execute
[ck8s] 90-psp-violations.sh: using config path: "/home/olle/Documents/olle-exoscale"
[ck8s] 90-psp-violations.sh: using sc kubeconfig unencrypted
[ck8s] 90-psp-violations.sh: using wc kubeconfig unencrypted
Will trigger a rollout restart of StatefulSet/alertmanager-kube-prometheus-stack-alertmanager in monitoring
Will trigger a rollout restart of DaemonSet/fluentd-forwarder in …
```
=> apps: add migrations step for gatekeeper psps violations

WIP-CHANGELOG.md, bin/ck8s, bin/test.bash, pipeline/test/services/funcs.sh, pipeline/test/services/service-cluster/testPodsReady.sh, pipeline/test/services/test-sc.sh, pipeline/test/services/test-wc.sh
Test scripts take a long time when writing logs/events to files, this is now disabled by default and can be enabled with the `--logging-enabled` flag.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1563 
**Checklist:**
=> bin: add logging flag

pipeline/config/exoscale/common-config.yaml, pipeline/config/exoscale/pipeline-sc-config/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml, pipeline/config/exoscale/pipeline-wc-config/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml
Fix pipeline failing at kubespray step
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1468 
I also verified that it can get past the kubespray step when checking out kubespray on main, after removing PSP from the configs. I left some comments for when the time comes for this.
**Checklist:** …
=> pipeline: fix kubespray failure

WIP-CHANGELOG.md, config/config/sc-config.yaml, helmfile/charts/networkpolicy/service-cluster/templates/grafana/allow-grafana.yaml, helmfile/charts/networkpolicy/service-cluster/values.yaml, helmfile/values/networkpolicy/service-cluster.yaml.gotmpl, pipeline/config/exoscale/sc-config.yaml
Allows sc-config to configure Grafana egress. / So it is easier to allow ip addresses and ports to access user Grafana.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1439
**Checklist:**
=> apps sc: Added so Grafana egress can be configured from sc-config.

WIP-CHANGELOG.md, config/config/sc-config.yaml, helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
Added templating to be able to change the Alertmanager template for slack alerts. An on-prem customer asked about this.
**Checklist:**
- Chart …
=> apps sc: Added possibility to change Alertmanager template for slack

WIP-CHANGELOG.md, helmfile/charts/networkpolicy/service-cluster/templates/harbor/allow-harbor-jobservice.yaml
Noticed that this was a problem for an environment I was working with on apps `v0.29`. Saw that there was a fix in the `v0.30` QA process but apparently port 5000 is also needed, as I got a few of these error messages:
```console
2023-05-26T11:54:24Z [ERROR] [/jobservice/job/impl/gc/garbage_collection.go:286]: [4/28394] failed to delete manifest with v2 API, ***, Get "http://harbor-registry:5000/v2/": dial tcp 10.233.54.101:5000: i/o timeout
```
And saw it was blocked by netpols:
**Checklist:**
I.e. …
=> apps sc: harbor jobservice netpol allow garbage collection

WIP-CHANGELOG.md, helmfile/charts/grafana-ops/dashboards/trivy-operator-dashboard.json
Updates the Trivy dashboard to be more usable, and not to multiply image stats with the number of uses.
(So instead of showing 100 000+ vulnerabilities for two versions of rook-ceph alone(!) it now shows 3108 for the same one.)
I will probably make some additional tweaks, but the main part is ready.
Light:
Dark:
**Checklist:** …
=> apps sc: Update Trivy Operator Dashboard

migration/v0.30/apply/14-hnc-labels.sh, migration/v0.31/apply/14-hnc-labels.sh
Fix when adding annotation and labels for hnc.
**Checklist:** …
=> apps: fix migration hnc label

WIP-CHANGELOG.md, helmfile/charts/networkpolicy/common/templates/rook-ceph/mgr.yaml
**What this PR does / why we need it**: fix the netpol for allow blackbox exporter probe
**Checklist:**
- [x ] I upgraded no Chart.
=> apps: fixed the rook-ceph mgr netpol to allow blackbox exporter

WIP-CHANGELOG.md, helmfile/charts/grafana-ops/values.yaml, helmfile/charts/node-local-dns/templates/node-local-dns.yaml, helmfile/charts/prometheus-alerts/templates/alerts/coredns.yaml, helmfile/charts/prometheus-alerts/values.yaml, helmfile/upstream/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-coredns.yaml
**What this PR does / why we need it**: exposed node-local-dns metrics and added them in the CoreDNS dashboard
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1607 
WIP: adding some alerts
**Checklist:**
=> apps: node-local-dns dashboard

helmfile/values/falco.yaml.gotmpl
**What this PR does / why we need it**: to add more exception for falco
**Checklist:**
=> apps: add more falco exceptions

WIP-CHANGELOG.md, helmfile/charts/user-rbac/templates/clusterroles/user-view.yaml
Allow user admin to view event and logs cluster-wide
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1616 
**Checklist:**
=> apps wc: allow user admin to view events/logs

.pre-commit-config.yaml, WIP-CHANGELOG.md, helmfile/charts/opensearch/curator/values.yaml, images/elasticsearch-curator/5/debian-10/Dockerfile, images/elasticsearch-curator/5/debian-10/docker-compose.yml, images/elasticsearch-curator/5/debian-10/prebuildfs/opt/bitnami/.bitnami_components.json, images/elasticsearch-curator/5/debian-10/prebuildfs/opt/bitnami/licenses/licenses.txt, images/elasticsearch-curator/5/debian-10/prebuildfs/usr/sbin/install_packages, images/elasticsearch-curator/5/debian-10/rootfs/opt/bitnami/scripts/locales/add-extra-locales.sh, images/elasticsearch-curator/LICENSE.md, images/elasticsearch-curator/README.md, images/elasticsearch-curator/docker-compose.yml
Noticed that the image had been removed from bitnamis docker hub. This is because the bitnami elasticsearch-curator was deprecated about a year ago, so now they removed the images.
Found the Dockerfile and related files in their repository by browsing the commit history, built it and pushed to our ghcr.
Now we can use the image again.
This warrants a patch version as the old image can not be pulled anymore.
**Checklist:** …
=> apps sc: changed location for opensearch-curator image

WIP-CHANGELOG.md, helmfile/charts/grafana-dashboards/dashboards/prometheus-blackbox-exporter-dashboard.json, helmfile/charts/grafana-dashboards/values.yaml
Adapted from https://grafana.com/grafana/dashboards/7587-prometheus-blackbox-exporter/
**What this PR does / why we need it**: #1437 
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1437
**Checklist:** …
=> apps sc: Add Prometheus Blackbox Exporter dashboard (fixes #1437)

WIP-CHANGELOG.md, config/config/sc-config.yaml, helmfile/values/opensearch/common.yaml.gotmpl
=> apps sc: add option to configure max shards in opensearch

WIP-CHANGELOG.md, bin/ck8s, bin/common.bash
So we can easily see when we've got different versions of bin script dependencies.
**Which issue this PR fixes**
fixes: #1478
When on a tty it will prompt if you want to abort, with default as no.
```console
$ ./bin/ck8s dry-run wc
[ck8s] Required dependency yq4 not using recommended version: (expected 4.26.1 - actual 4.33.3)
[ck8s] Required dependency kubectl not using recommended version: (expected 1.24.4 - actual 1.27.1)
[ck8s] Required dependency helm not using recommended version: (expected 3.8.0 - actual 3.12.0)
[ck8s] Required dependency helmfile not using recommended version: (expected …
```
=> Dependency check in bin scripts

WIP-CHANGELOG.md, config/config/common-config.yaml, helmfile/charts/prometheus-alerts/templates/alerts/node-exporter.yaml, helmfile/charts/prometheus-alerts/values.yaml, helmfile/values/prometheus-alerts-sc.yaml.gotmpl
Add option to config disk usage alerts, including pattern filtering. Which can be used for local disk alerts.
Im considering if i should split it out from node-exporter alert file and place them in a new file.
**Which issue this PR fixes**: fixes #1303
**Checklist:** …
=> apps: configurable disk alerts

WIP-CHANGELOG.md, helmfile/charts/log-manager/templates/cronjob-compaction.yaml, helmfile/charts/log-manager/values.yaml, helmfile/values/fluentd/log-manager.yaml.gotmpl, helmfile/values/podsecuritypolicies/common/fluentd.yaml.gotmpl
So it has space for files. (Else it would write to a tmpfs mount which is normally in memory, which is accounted towards it resources usage.)
**Checklist:**
=> apps sc: Use emptyDir with log-manager compaction

WIP-CHANGELOG.md, helmfile/values/networkpolicies/common/common.yaml.gotmpl, helmfile/values/networkpolicies/service/harbor.yaml.gotmpl
So the egress rule isn't hard coded.
**Checklist:**
=> apps: Use set cluster DNS for egress rule

WIP-CHANGELOG.md, bin/update-ips.bash
bin/ck8s update-ips should now add the IPs and port for the swift endpoint.
fixes #1629 
I'll need to test this a bit more but so far on our support infra provider elastx it works just fine with using application credentials.
**Checklist:** …
=> bin: swift support in update-ips

WIP-CHANGELOG.md, helmfile/upstream/grafana/Chart.yaml, helmfile/upstream/grafana/README.md, helmfile/upstream/grafana/templates/_pod.tpl, helmfile/upstream/grafana/values.yaml, helmfile/values/grafana/grafana-ops.yaml.gotmpl, helmfile/values/grafana/grafana-user.yaml.gotmpl
**What this PR does / why we need it**: to upgrade Grafana to the latest patch release
**Checklist:**
=> apps sc: upgraded grafana to the latest patch release

WIP-CHANGELOG.md, helmfile/charts/prometheus-alerts/templates/alerts/packets-dropped.yaml
Make FrequentPacketsDroppedFromWorkload less sensative
**Which issue this PR fixes**: fixes #1643 
**Checklist:** …
=> apps wc: make packets dropped less senastive

WIP-CHANGELOG.md, bin/update-ips.bash, config/config/sc-config.yaml, config/secrets/sc-secrets.yaml, helmfile/charts/networkpolicy/service-cluster/templates/rclone-sync.yaml, helmfile/charts/rclone-sync/files/rclone.conf, helmfile/charts/rclone-sync/templates/cronjob.yaml, helmfile/charts/rclone-sync/values.yaml, helmfile/values/networkpolicy/service-cluster.yaml.gotmpl, helmfile/values/rclone-sync.yaml.gotmpl
Added support for type swift in rclone-sync and made it so you can switch types for individual buckets as well. / Needed for when s3 has issues doing its job and to be able to choose type.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1305
Used different key: value pairs to minimize the amount needed to be configured. 
A restriction that requires the global.ck8sCloudProvider to be specific providers should not be relevant because this is a public repository which anyone can pull from.
**Checklist:**
E.g. logs or metrics are not …
=> apps sc: Added support for swift in rclone-sync.

WIP-CHANGELOG.md, helmfile/values/podsecuritypolicies/common/rook-ceph.yaml.gotmpl
=> apps: added secret as an allowed volume type for osd prepare jobs

WIP-CHANGELOG.md, helmfile/50-applications.yaml, helmfile/upstream/kured/Chart.yaml, helmfile/upstream/kured/README.md, helmfile/upstream/kured/values.yaml
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1489 
**Checklist:** …
=> apps: upgraded kured to 1.13.1

WIP-CHANGELOG.md, pipeline/test/services/service-cluster/testIngress.sh, pipeline/test/services/workload-cluster/testIngress.sh
**What this PR does / why we need it**: added proxy-protocol support for the testIngress scripts
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1469 
**Checklist:**
=> pipeline: added proxy-protocol support for ingress tests

WIP-CHANGELOG.md, helmfile/charts/user-alertmanager/templates/_helpers.tpl, helmfile/charts/user-alertmanager/templates/secret.yaml, migration/v0.32/apply/30-alertmanager-config.sh, migration/v0.32/apply/80-apply.sh, migration/v0.32/apply/alertmanager_velero_backup.yaml
**What this PR does / why we need it**: as the pre-install helm hook to handle the secret for user-alertmanager is not very clear I want to see if using a `_helper.tpl` to not update it if exists is a better solution
**Checklist:**
- [] is completely transparent, will not impact the workload in any way.
=> apps wc: user-alertmanager secret handling

WIP-CHANGELOG.md, helmfile/50-applications.yaml, helmfile/upstream/prometheus-blackbox-exporter/Chart.yaml, helmfile/upstream/prometheus-blackbox-exporter/README.md, helmfile/upstream/prometheus-blackbox-exporter/ci/icmp-values.yaml, helmfile/upstream/prometheus-blackbox-exporter/templates/NOTES.txt, helmfile/upstream/prometheus-blackbox-exporter/templates/_helpers.tpl, helmfile/upstream/prometheus-blackbox-exporter/templates/configmap.yaml, helmfile/upstream/prometheus-blackbox-exporter/templates/daemonset.yaml, helmfile/upstream/prometheus-blackbox-exporter/templates/deployment.yaml, helmfile/upstream/prometheus-blackbox-exporter/templates/extra-manifests.yaml, helmfile/upstream/prometheus-blackbox-exporter/templates/ingress.yaml, helmfile/upstream/prometheus-blackbox-exporter/templates/networkpolicy.yaml, helmfile/upstream/prometheus-blackbox-exporter/templates/poddisruptionbudget.yaml, helmfile/upstream/prometheus-blackbox-exporter/templates/podsecuritypolicy.yaml, helmfile/upstream/prometheus-blackbox-exporter/templates/prometheusrule.yaml, helmfile/upstream/prometheus-blackbox-exporter/templates/role.yaml, helmfile/upstream/prometheus-blackbox-exporter/templates/rolebinding.yaml, helmfile/upstream/prometheus-blackbox-exporter/templates/selfservicemonitor.yaml, helmfile/upstream/prometheus-blackbox-exporter/templates/service.yaml, helmfile/upstream/prometheus-blackbox-exporter/templates/serviceaccount.yaml, helmfile/upstream/prometheus-blackbox-exporter/templates/servicemonitor.yaml, helmfile/upstream/prometheus-blackbox-exporter/templates/verticalpodautoscaler.yaml, helmfile/upstream/prometheus-blackbox-exporter/values.yaml
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1230 
**Checklist:** …
=> apps: upgraded blackbox exporter to 8.2.0

WIP-CHANGELOG.md, config/config/sc-config.yaml, migration/v0.31/README.md, migration/v0.31/prepare/10-thanos-distrib-memory-limit.sh, migration/v0.32/README.md, migration/v0.32/prepare/10-thanos-distrib-memory-limit.sh
**What this PR does / why we need it**: after upgrading some env to apps v0.31 I noticed that one common problem was thanos distributor going into a crash loop due to OOMkilled
I increased the limit to avoid that.
**Checklist:**
=> apps sc: increase the default memeory limit for thanos distributor

WIP-CHANGELOG.md, bin/common.bash
Checks to see if there are invalid pgp keys in the sops config  / fixes the bug 
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1675
Because of this change this code piece will only print out the invalid pgp keys and not every key in the sops config.
yq4 'split(",") | {"fingerprints": .}' <<< "${fingerprints}" | cat
**Checklist:** …
=> bin: preflight check to see if all keys are valid

WIP-CHANGELOG.md, scripts/migration/lib.sh
It throws an error message if the common-configs have different ck8sVersion values / It can be good to be able to delete the override common-config version so it won't throw a error in the upgrade apply part of the script.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1539
**Checklist:**
=> bin: upgrade prepare script fix

WIP-CHANGELOG.md, config/config/sc-config.yaml, helmfile/values/thanos/receiver.yaml.gotmpl
**What this PR does / why we need it**: Reduced CPU requests for some components in SC after looking into how much CPU actually is utilized.
**Which issue this PR fixes**: fixes elastisys/ck8s-ops#4334
**Special notes for reviewer**: I found that for environments with 5x 2c worker nodes in SC, four of the nodes would have 90+% CPU requests and one node would be significantly lower (~40%), so these reductions are not urgently necessary but should be good to have regardless. If we want to try to ensure that the workload is spread out more evenly, we should consider prioritizing this task: https://github.com/elastisys/compliantkubernetes-apps/issues/1336
**Checklist:**
- Is this changeset backwards compatible for …
=> apps sc: reduced cpu requests for some components

WIP-CHANGELOG.md, helmfile/values/networkpolicies/service/harbor.yaml.gotmpl
**What this PR does / why we need it**: when the harbor notary certificates were renewed we saw some packets dropped
seems that harbor notary server needed an ingress rules for ingress-nginx
**Checklist:**
=> apps sc: netpol fix for harbor notary server

migration/template/README.md, migration/v0.31/README.md, migration/v0.32/README.md
**What this PR does / why we need it**: to update the netpol IPs before the maintenance 
for a more more automated method to run this script is created [this issue](https://github.com/elastisys/compliantkubernetes-apps/issues/1698) 
**Checklist:**
=> migration: added snippet to run update-ips

WIP-CHANGELOG.md, helmfile/charts/grafana-dashboards/dashboards/cluster-api-dashboard.json, helmfile/charts/prometheus-alerts/files/cluster-api.yaml, helmfile/charts/prometheus-alerts/templates/alerts/cluster-api.yaml, helmfile/charts/prometheus-alerts/values.yaml, helmfile/values/prometheus-alerts-sc.yaml.gotmpl
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes elastisys/ck8s-cluster-api#42
Main panels for each cluster:
One (hidden by default) row of more detailed graphs that works both with all clusters and for one specific one:
**Checklist:** …
=> Added alerts for cluster api and updated its grafana dashboard

WIP-CHANGELOG.md, config/config/sc-config.yaml, helmfile/values/harbor/harbor.yaml.gotmpl
This seems to fix the issue of larger image layers timing out and failing the push.
Searching a bit on the issue of larger image layers that fail to upload I found a couple of suggestions to set these annotations/config. For example here:
https://github.com/goharbor/harbor/issues/16623#issuecomment-1084582967
https://github.com/goharbor/harbor/issues/9394#issuecomment-541598184
**Checklist:**
- Is this changeset backwards compatible …
=> apps sc: Added annotation to harbor ingress to fix timeout

WIP-CHANGELOG.md, helmfile/values/fluentd/forwarder-common.yaml.gotmpl
**What this PR does / why we need it**: 10s scrape interval seems to be unnecessary for fluentd-forwarder pods so I increased it to the Prometheus default, 30s
**Checklist:**
=> apps: fluentd-forwarder set metrics scrape interval to 30s

migration/v0.32/README.md, migration/v0.32/apply/12-remove-no-ttl-jobs.sh
**What this PR does / why we need it**: to add a migration script to remove the jobs without ttl
Fixes [#4198](https://github.com/elastisys/ck8s-ops/issues/4198)
**Checklist:**
=> migration: added a script to remove the jobs without ttl

WIP-CHANGELOG.md, config/config/common-config.yaml, config/config/sc-config.yaml, helmfile/charts/gatekeeper/mutations/templates/ndot-amount-dns-policy.yaml, helmfile/charts/gatekeeper/mutations/values.yaml, helmfile/charts/grafana-dashboards/values.yaml, helmfile/values/gatekeeper/mutations.yaml.gotmpl, helmfile/values/grafana/grafana-dashboards.yaml.gotmpl, helmfile/values/grafana/grafana-ops.yaml.gotmpl, helmfile/values/grafana/grafana-user.yaml.gotmpl
We can now choose if grafana needs to have trailing dots and a gatekeeper mutation that makes pods have the specified amount of ndots if enabled.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1671
**Checklist:**
=> apps: configure trailing dots(grafana) and ndots for pods

WIP-CHANGELOG.md, helmfile/charts/prometheus-alerts/templates/alerts/opensearch.yaml
**What this PR does / why we need it**: to separate the apps opensearch alerts from the jaeger opensearch alerts
**Checklist:**
=> apps sc: limit the opensearch alerts to opensearch-system ns

migration/v0.32/README.md, migration/v0.32/prepare/30-rclone-sync-netpol-name-change.sh
Adds a migration script this [comment](https://github.com/elastisys/compliantkubernetes-apps/commit/c3ab16683791208dac4165ed13fc14c1b98f9147#r123797404) brought awareness to needing.
**Checklist:**
=> apps sc: rclone-sync migration script

WIP-CHANGELOG.md, helmfile/50-applications.yaml, helmfile/upstream/falco-exporter/CHANGELOG.md, helmfile/upstream/falco-exporter/Chart.yaml, helmfile/upstream/falco-exporter/README.md, helmfile/upstream/falco-exporter/templates/daemonset.yaml, helmfile/upstream/falco-exporter/templates/grafana-dashboard.yaml, helmfile/upstream/falco-exporter/templates/podsecuritypolicy.yaml, helmfile/upstream/falco-exporter/values.yaml
=> apps: falco-exporter chart v0.9.6

WIP-CHANGELOG.md, bootstrap/namespaces/helmfile/values/namespaces-sc.yaml.gotmpl, helmfile/50-applications.yaml, helmfile/charts/networkpolicy/service-cluster/templates/rclone-sync.yaml, helmfile/charts/rclone-sync/templates/cronjob.yaml, migration/v0.33/README.md, migration/v0.33/apply/00-template.sh, migration/v0.33/apply/20-bootstrap.sh, migration/v0.33/apply/40-rclone.sh, migration/v0.33/apply/80-apply.sh, migration/v0.33/prepare/00-template.sh, migration/v0.33/prepare/50-init.sh
This PR moves rclone from kube-system to its own namespace.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1544 
**Checklist:**
=> apps sc: move rclone from kube-system

WIP-CHANGELOG.md, helmfile/values/grafana/grafana-user.yaml.gotmpl
**What this PR does / why we need it**: the user grafana values file rendering fails during apply when `whitelistRange` is enabled, because the annotations key for ingress was missing
**Checklist:**
=> apps sc: grafana user values file

WIP-CHANGELOG.md, helmfile/charts/grafana-dashboards/files/welcome.md, helmfile/charts/opensearch/configurer/files/dashboards-resources/welcome.md
Refers to Grafana, OpenSearch and Harbor as Web Portals in Grafana and OpenSearch welcome dashboards.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1721
**Checklist:** …
=> apps sc: Refer to Grafana, OpenSearch and Harbor as Web Portals

WIP-CHANGELOG.md, config/config/sc-config.yaml, helmfile/charts/grafana-dashboards/dashboards/welcome-dashboard.json, helmfile/charts/grafana-dashboards/files/welcome.md, helmfile/charts/grafana-dashboards/values.yaml, helmfile/values/grafana/grafana-dashboards.yaml.gotmpl
Adds a way to list additional components, optionally with a link and/or referencing a release notes URL, see #1290
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1290
When looking at the diff, enable "Hide whitespace", changes to the dashboard.json is mostly indentation.
Adds `welcomingDashboard.extraVersions`, a list of entries. Each entry requires at least a `name` property. The corresponding version may be specified in `version`.  To link to a component that is available on a subdomain of `baseDomain`, set `subdomain` to that subdomain. An exact …
=> sc apps: way to include more component versions in welcome dasboard

WIP-CHANGELOG.md, config/config/common-config.yaml, config/config/sc-config.yaml, helmfile/values/prometheus-blackbox-exporter-wc.yaml.gotmpl, migration/v0.33/README.md, migration/v0.33/prepare/07-move-to-common-for-cross-cluster-probe.sh, scripts/migration/yq.sh
**What this PR does / why we need it**: to monitor how well WC can communicate with SC
**Which issue this PR fixes**: fixes #1437
**Special notes for reviewer**: Depends on Blackbox Exporter dashboard added in https://github.com/elastisys/compliantkubernetes-apps/pull/1542
**Checklist:**
If you change some config options (e.g. add/rename variable or change …
=> Probe public SC endpoints from WC

WIP-CHANGELOG.md, config/config/common-config.yaml, helmfile/charts/prometheus-alerts/templates/alerts/cluster-capacity-management-alerts.yaml, helmfile/values/prometheus-alerts-sc.yaml.gotmpl, helmfile/values/prometheus-user-alerts-wc.yaml.gotmpl, migration/v0.33/README.md, migration/v0.33/prepare/10-copy-capacity-alert-disklimit.sh
**What this PR does / why we need it:**
This PR separates limit configurations for node disk and PVC capacity alerts, as well as allowing PVC capacity alerts to be disabled.
_Reason:_ When using NFS and the [nfs-provisioner](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner) for provisioning Persistent Volumes, the metrics used for measuring PVCs shows the total capacity & usage of the entire NFS volume instead of the capacity of each PVC. As a result, we'd like to be able to turn off PVC capacity notifications and handle them individually.
**Which issue this PR fixes:** fixes #
**Special notes for reviewer:**
**Checklist:**
- Logs …
=> apps: separate capacity alert limits for pv

WIP-CHANGELOG.md, helmfile/charts/networkpolicy/common/templates/kube-system/csi-upcloud.yaml
**What this PR does / why we need it:** During DR exercise we found there is upcloud cs-controller netpols in the cluera environment. This fixes the issue .
Before:
```
NAME                                  POD-SELECTOR                            AGE
allow-coredns                         k8s-app=kube-dns                        41d
allow-csi-cinder-controller-plugin    app=csi-cinder-controllerplugin         41d
allow-csi-upcloud-controller-plugin   app=csi-upcloud-controller              41d
allow-dns-autoscaler                  k8s-app=dns-autoscaler                  41d
allow-metrics-server                  app.kubernetes.io/name=metrics-server   41d
allow-snapshot-controller             app=snapshot-controller                 41d
```
After:
```
NAME …
```
=> apps sc & wc: Fixed the csi-upcloud networkpolicy template

WIP-CHANGELOG.md, bin/test.bash, migration/template/README.md, pipeline/test/services/funcs.sh, pipeline/test/services/service-cluster/testCertManager.sh, pipeline/test/services/service-cluster/testIngress.sh, pipeline/test/services/service-cluster/testOpensearch.sh, pipeline/test/services/service-cluster/testPodsReady.sh, pipeline/test/services/test-sc.sh, pipeline/test/services/test-wc.sh, pipeline/test/services/workload-cluster/testCertManager.sh, pipeline/test/services/workload-cluster/testHNC.sh, pipeline/test/services/workload-cluster/testIngress.sh
Makes it more efficient if one is going to test all components.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1565
Do we want the all option to be able to use the *--logging-enabled*? because thats only for one component of the many that it tests.
**Checklist:**
**Pipeline …
=> tests: test script all at once option

WIP-CHANGELOG.md, helmfile/charts/harbor/init-harbor/templates/init-harbor-job.yaml, helmfile/charts/opensearch/configurer/values.yaml, helmfile/values/falco/falco-common.yaml.gotmpl, helmfile/values/opensearch/common.yaml.gotmpl
**What this PR does / why we need it:**
**Which issue this PR fixes:** fixes #
**Special notes for reviewer:**
**Checklist:**
- Logs checks: …
=> apps:Replace elastisys/curl-jq:latest

WIP-CHANGELOG.md, helmfile/values/gatekeeper/gatekeeper.yaml.gotmpl
**What this PR does / why we need it:**
Since else some pods with finalisers and less then ideal security contexts may become stuck forever as Gatekeeper will try to modify them in such ways that aren't allowed.
**Checklist:**
- Logs checks:
If you change some config options (e.g. add/rename variable or change the default value) you may need to update the config used by the pipeline …
=> apps: Only mutate pods on create

WIP-CHANGELOG.md, helmfile/values/ingress-nginx.yaml.gotmpl
**What this PR does / why we need it:** Increased the default proxy-buffer-size to 8k to fix the `502 Gateway error`
**Which issue this PR fixes:** fixes #
**Special notes for reviewer:**
**Checklist:**
- Logs checks: …
=> apps sc & wc: Increased the default proxy-buffer-size to 8k

WIP-CHANGELOG.md, config/config/sc-config.yaml, helmfile/charts/grafana-dashboards/dashboards/harbor-dashboard.json, helmfile/charts/prometheus-alerts/templates/alerts/harbor.yaml, helmfile/charts/prometheus-alerts/values.yaml, helmfile/values/prometheus-alerts-sc.yaml.gotmpl, helmfile/values/prometheus-user-alerts-wc.yaml.gotmpl
**What this PR does / why we need it**: to add alerts for Harbor, including the possibility to alert when the total storage used of number of artefacts goes above threshold (configurable, default is 500GB with 1000)
**Checklist:**
=> apps sc: added alerts for harbor and updated the dashboard

.pre-commit-config.yaml, WIP-CHANGELOG.md, bin/update-ips.bash, config/config/sc-config.yaml, config/secrets/sc-secrets.yaml, helmfile/charts/networkpolicy/service-cluster/templates/rclone-sync.yaml, helmfile/charts/rclone-sync/files/rclone.conf, helmfile/values/networkpolicy/service-cluster.yaml.gotmpl, helmfile/values/rclone-sync.yaml.gotmpl, migration/v0.32/README.md, migration/v0.32/prepare/20-sync-type-new-key-name.sh, migration/v0.33/README.md, migration/v0.33/prepare/20-sync-type-new-key-name.sh, scripts/migration/lib.sh
**What this PR does / why we need it:** rcone sync config apply to the default buckets and enable rclone sync with swift if swift is anebled
**Checklist:**
- Logs checks:
=> apps sc: rclone sync changes

WIP-CHANGELOG.md, helmfile/charts/harbor/init-harbor/files/init.sh, helmfile/charts/harbor/init-harbor/templates/init-harbor-job.yaml, helmfile/charts/opensearch/configurer/files/configurer.sh, helmfile/charts/opensearch/configurer/templates/job.yaml
**What this PR does / why we need it:** Seems that when we replaced the curl-jq images some pods started to fail
**Checklist:**
- Logs checks:
=> apps sc: add security context for the curl-jq images

WIP-CHANGELOG.md, bin/ck8s, bin/update-ips.bash
https://github.com/elastisys/compliantkubernetes-apps/issues/1453 https://github.com/elastisys/compliantkubernetes-apps/issues/1677
fixes #1453 
fixes #1677
Ready for review.
**Checklist:** …
=> apps sc & wc: private subnet as node-ips

WIP-CHANGELOG.md, helmfile/charts/prometheus-alerts/templates/alerts/kubernetes-apps.yaml
Updating `KubeContainerOOMKilled` prometheus alert  threshold to make less senisitive
> [!important]
...
- Fixes #
- Logs checks:
=> apps sc & wc: Updating KubeContainerOOMKilled threshold

WIP-CHANGELOG.md, migration/v0.30/README.md
> [!warning]
> [!important]
...
- Fixes #
- Logs checks:
=> migration: Fix broken link in v0.30 upgrade instructions

WIP-CHANGELOG.md, helmfile/charts/grafana-dashboards/dashboards/node-spread-dashboard.json, helmfile/values/kube-prometheus-stack-wc.yaml.gotmpl
> [!warning]
> [!important]
This dashboard lets you explore how well Pods are spread out across either Nodes or Zones. 
- Fixes #1345
- Logs checks:
=> sc apps: Dashboard for visualizing how spread-out pods are across nodes

helmfile/50-applications.yaml
> [!warning]
> [!important]
Previously, if `fluentd.enabled = false and fluentd.audit.enabled = true` the `fluentd-system` namespace was never created during bootstrap even though [Helmfile is configured to install the `log-manager` chart](https://github.com/elastisys/compliantkubernetes-apps/blob/fc9f07 …
=> apps: Only install log-manager if fluentd.enabled=true

WIP-CHANGELOG.md, helmfile/charts/gatekeeper/constraints/templates/disallow-tag/constraint.yaml, helmfile/charts/gatekeeper/constraints/templates/image-registry/constraint.yaml, helmfile/charts/gatekeeper/constraints/templates/networkpolicies/constraint.yaml, helmfile/charts/gatekeeper/constraints/templates/resource-requests/constraint.yaml, helmfile/charts/gatekeeper/constraints/templates/user-crds/constraint.yaml, helmfile/charts/gatekeeper/templates/policies/disallow-tag.rego, helmfile/charts/gatekeeper/templates/policies/image-registry.rego, helmfile/charts/gatekeeper/templates/policies/network-policies.rego, helmfile/charts/gatekeeper/templates/policies/resource-requests.rego
> [!warning]
> [!important]
Updated the Gatekeeper violation messages and added an `elastisys-` prefix to the policies. Also re-worded from `repo` to `registry` to be consistent with the docs.
- Fixes #1748 
- Logs checks: …
=> apps: update gatekeeper violation messages

WIP-CHANGELOG.md, config/config/sc-config.yaml, helmfile/values/thanos/receiver.yaml.gotmpl
It fixes thanos ingesting out-of-order by making a window of time where a thanos receiver pod does not drop metrics on a restart instead so long as its within the time limit it just pick up the metrics again.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1637
Do we want it to have a setting so that it can be enabled/disabled and or make --tsdb.out-of-order.time-window= adjustable from sc-config?
**Checklist:**
E.g. …
=> apps sc: thanos receiver out-of-order bug fix

helmfile/values/opensearch/common.yaml.gotmpl
> [!warning]
> [!important]
OpenSearch fails to start up successfully with the following config:
```
masterNode:
count: 1
dataNode:
dedicatedPods: true
count: 0
clientNode:
dedicatedPods: true
count: 0
```
It gets stuck on the security admin which repeatedly just times out while trying to access …
=> apps sc: fixes silent fail with opensearch when using certain configuration

helmfile/charts/user-rbac/templates/rolebindings/workload-admin.yaml
> [!warning]
> [!important]
The user-rbac RoleBinding is always deleted on the second apply. This is the expected behavior but could be confusing. A comment that shows up in the diff could help that.
- Logs checks: …
=> apps wc: Add comment explaining the user-rbac RoleBinding deletion

helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl, helmfile/values/kube-prometheus-stack-wc.yaml.gotmpl
> [!warning]
> [!important]
Fixes the metrics collection for CAPI clusters.
They changed the behaviour of it in the updated version.
- Logs checks:
=> apps: Fix CAPI metrics collection

config/config/common-config.yaml, helmfile/values/fluentd/forwarder-workload-cluster.yaml.gotmpl
> [!warning]
> [!important]
At times the default request_timeout of 5s is not enough for big bulk requests to opensearch (or just bulk requests to opensearch that's under load). This PR makes the [request_timeout](https://github.com/fluent/fluent-plugin-opensearch/tree/main#request_timeout) parameter …
=> apps sc: make forwarder request timeout configurable

migration/v0.34/apply/11-prometheus-operator-crds.sh, roles/get-requirements.yaml
> [!warning]
> [!important]
Checks the installed chart version of `kube-prometheus-stack` before applying CRDs to avoid repeated work. Unfortunately `kubectl diff` takes as long as just applying the CRDs so that approach doesn't work. Also bumped the `kubectl` dependency to the latest patch on `1.26` as …
=> migration: add version check before applying crds

config/config/common-config.yaml, helmfile/values/gatekeeper/gatekeeper.yaml.gotmpl
> [!warning]
> [!important]
This PR provides additional configuration through config files, making it possible to tune different parameters of gatekeeper `controllerManager` and `audit` pods.
- Fixes #1072 
The `controllerManager` already has [affinity](https://github.com/elastisys/compliantkubernetes-ap …
=> config: more templating for gatekeeper

helmfile/values/velero-sc.yaml.gotmpl, helmfile/values/velero-wc.yaml.gotmpl
> [!warning]
> [!important]
Restoring a volume in a restricted namespace was not possible before because the `velero-restore-helper` init container that Velero attaches to the pod did not run with a numeric non-root user.
- Fixes #1766 
- Logs checks:
- Network Policy …
=> apps: Run velero-restore-helper with numeric UID and GID

WIP-CHANGELOG.md, helmfile/charts/prometheus-alerts/templates/alerts/fluentd.yaml
- Modified the `FluentdQueueLength` prometheus alert condition to calculate the rate of change of the `fluentd_status_buffer_queue_length` metric from `5m` to `15m` and sustain the condition from `1m` to `5m`.
- Modified the `FluentdOutputError` & `FluentdRetry` prometheus alert condition to evaluate based on specific labels combination of `pod`, `cluster`, and `service`.
> [!important]
...
- Fixes #
- Logs checks:
- …
=> apps sc & wc: Modified the FluentdQueueLength/FluentdOutputError/FluentdRetry alert expression

tests/cypress.support.js, tests/end-to-end/grafana-admin.cy.js, tests/end-to-end/grafana-dashboards-discovery.bats, tests/end-to-end/grafana-dev.cy.js
> [!warning]
> [!important]
There in an issue that the container cannot access the users gpg keyring so I'll look into some solution for that.
Also I will add some bats tests to check the loader container for errors.
- Fixes https://github.com/elastisys/ck8s-ops/issues/1845
- Metrics …
=> tests: Add e2e tests for Grafana data sources

tests/cypress.support.js, tests/end-to-end/grafana-admin.cy.js, tests/end-to-end/grafana-dashboards-discovery.bats, tests/end-to-end/grafana-dev.cy.js
> [!warning]
> [!important]
Tests login to Grafana using Dex static user.
- Fixes https://github.com/elastisys/ck8s-ops/issues/1841
- Logs checks:
=> tests: Add e2e tests for Grafana Dex logins

migration/v0.34/README.md, migration/v0.34/apply/30-delete-obsolete-ns.sh, migration/v0.34/prepare/30-delete-obsolete-ns.sh
> [!warning]
> [!important]
**_Removes_** namespaces that have been obsolete since v0.20, namely:
- `elastic-system`
- `influxdb-prometheus`
Rollback not implemented because the namespaces have been obsolete so long, plus this wouldn't restore any resources in the deleted namespaces anyway, so restoring …
=> migration: Delete namespaces obsolete since v0.20

config/config/common-config.yaml, helmfile/values/falco/falco-common.yaml.gotmpl
> [!warning]
> [!important]
We encountered an issue where we got Falco alerts but could not find any logs tied to these alerts in the Falco pods (or in Opensearch) and could thus not further investigate what caused the alerts. Enabling `tty` (see upstream chart config …
=> config: add falco tty templating

bin/apps.bash, migration/template/README.md, migration/v0.33/README.md, migration/v0.34/README.md
> [!warning]
> [!important]
The migration steps for `update-ips` command had not been update to use `apply` instead of `update` (was changed [here](https://github.com/elastisys/compliantkubernetes-apps/pull/1582/files#diff-e2152e838d854d832a786626facd8174c460ba5ac8471bdaef3dab042b2b1ab1R39)). This PR …
=> docs: update-ips command to use apply

README.md, bin/common.bash, pipeline/Dockerfile, roles/get-requirements.yaml
> [!warning]
> [!important]
[Sops is now a CNCF Sandbox project](https://github.com/getsops/sops/releases/tag/v3.8.0) and has moved out of the Mozilla github organization to its own, https://github.com/getsops
All old URLs still work for now but redirect to the new ones. 
- Metrics …
=> Update sops URLs to account for it moving to a new github organization

helmfile/values/falco/falco-common.yaml.gotmpl
> [!warning]
> [!important]
Exempt calico-accountant from drop and execute rule in Falco.
As it is expected when it runs with the nftables backend.
- Logs checks:
=> apps: Allow calico-accountant drop and execute in Falco

helmfile/charts/log-manager/values.yaml
> [!warning]
> [!important]
...
- When we use PVCs having a history of 3 for the log management job reserves too much storage that is not actively used. 
- Logs checks:
=> apps sc: Log management set successfulJobsHistoryLimit to 1

helmfile/upstream/index.yaml, helmfile/upstream/kubernetes-ingress-nginx/ingress-nginx/Chart.yaml, helmfile/upstream/kubernetes-ingress-nginx/ingress-nginx/README.md, helmfile/upstream/kubernetes-ingress-nginx/ingress-nginx/README.md.gotmpl, helmfile/upstream/kubernetes-ingress-nginx/ingress-nginx/changelog.md.gotmpl, helmfile/upstream/kubernetes-ingress-nginx/ingress-nginx/changelog/Changelog-4.5.2.md, helmfile/upstream/kubernetes-ingress-nginx/ingress-nginx/changelog/Changelog-4.6.0.md, helmfile/upstream/kubernetes-ingress-nginx/ingress-nginx/changelog/Changelog-4.6.1.md, helmfile/upstream/kubernetes-ingress-nginx/ingress-nginx/changelog/Changelog-4.7.0.md, helmfile/upstream/kubernetes-ingress-nginx/ingress-nginx/changelog/Changelog-4.7.1.md, helmfile/upstream/kubernetes-ingress-nginx/ingress-nginx/changelog/Changelog-4.7.2.md, helmfile/upstream/kubernetes-ingress-nginx/ingress-nginx/changelog/Changelog-4.7.3.md, helmfile/upstream/kubernetes-ingress-nginx/ingress-nginx/templates/_helpers.tpl, helmfile/upstream/kubernetes-ingress-nginx/ingress-nginx/templates/controller-deployment.yaml, helmfile/upstream/kubernetes-ingress-nginx/ingress-nginx/templates/controller-hpa.yaml, helmfile/upstream/kubernetes-ingress-nginx/ingress-nginx/templates/controller-keda.yaml, helmfile/upstream/kubernetes-ingress-nginx/ingress-nginx/templates/controller-service-internal.yaml, helmfile/upstream/kubernetes-ingress-nginx/ingress-nginx/templates/controller-service.yaml, helmfile/upstream/kubernetes-ingress-nginx/ingress-nginx/values.yaml
> [!warning]
> [!important]
New curl release (CVE-2023-38545 and CVE-2023-38546)
New Go release (https://github.com/advisories/GHSA-qppj-fm5r-hxr3 and https://github.com/advisories/GHSA-4374-p667-p6c8)
Fix for HTTP/2 Rapid Reset Attack [CVE-2023-44487](https://nvd.nist.gov/vuln/detail/CVE-2023-44487)
To …
=> apps: upgrade ingress-nginx controller to 1.8.4 and chart to 4.7.3

README.md, bin/ck8s, bin/upgrade.bash, migration/template/README.md, migration/template/apply/00-template.sh, migration/template/apply/20-bootstrap.sh, migration/template/apply/80-apply.sh, migration/template/prepare/00-template.sh, migration/v0.34/README.md, migration/v0.34/apply/00-template.sh, migration/v0.34/apply/11-prometheus-operator-crds.sh, migration/v0.34/apply/20-bootstrap.sh, migration/v0.34/apply/30-delete-obsolete-ns.sh, migration/v0.34/apply/80-apply.sh, migration/v0.34/prepare/00-template.sh, migration/v0.34/prepare/30-delete-obsolete-ns.sh, scripts/migration/lib.sh
> [!warning]
> [!important]
This PR changes the number of arguments required to run the `upgrade` command, as you now have to specify the specific cluster, `sc`, `wc`, or `both` to apply to both clusters as the command did previously. The ck8s usage has been updated to clarify this:
```bash
➜ ./bin/ck8s …
```
=> Allow per cluster upgrades

scripts/charts.sh
> [!warning]
> [!important]
When pulling a new chart the script will fail due to the `WARNING` helm is generating when the kubeconfig file has read permissions for the group or other 
- Logs checks: …
=> apps: Fix for the charts script that failed when pull

helmfile/charts/node-local-dns/templates/node-local-dns.yaml, helmfile/values/node-local-dns.yaml.gotmpl
> [!warning]
> [!important]
Adds consolidation of error logs for node-local-dns to avoid log spam during incidents.
- Part of #1691 
- Logs checks:
=> apps: add consolidation of errors in node-local-dns

.github/pull_request_template.md, .pre-commit-config.yaml, tests/.dockerignore, tests/.gitignore, tests/Dockerfile, tests/Makefile, tests/README.md, tests/common/gen-bats.bash, tests/common/gen-cypress.bash, tests/common/lib.bash, tests/cypress.config.js, tests/cypress.support.js, tests/end-to-end/grafana-admin.cy.js, tests/end-to-end/grafana-dashboards-discovery.bats, tests/end-to-end/grafana-dev.cy.js, tests/integration/template.bats, tests/package-lock.json, tests/package.json, tests/regression/template.bats, tests/unit/pods-ready.bats.yaml
> [!important]
This paves the way for more structured unit, integration, and end-to-end testing by using bats.
This has a long way to go before it can be used in the pipeline, ~~and I want to integrate Cypress first so I know what requirements we have.~~ ~~I also aim to implement helpers for the current main test script and see if there is any way to generate tests from a matrix.~~
I've already did so for testing deployments and statefulsets, though we might want to rework it into a fetch-once-check-multiple …
=> New test harness

config/config/common-config.yaml, helmfile/50-applications.yaml, helmfile/charts/autoscaling-monitoring/.helmignore, helmfile/charts/autoscaling-monitoring/Chart.yaml, helmfile/charts/autoscaling-monitoring/templates/_helpers.tpl, helmfile/charts/autoscaling-monitoring/templates/service.yaml, helmfile/charts/autoscaling-monitoring/templates/servicemonitor.yaml, helmfile/charts/autoscaling-monitoring/values.yaml, helmfile/charts/grafana-dashboards/dashboards/cluster-api-autoscaling-dashboard.json, helmfile/values/autoscaling-monitoring.yaml.gotmpl, helmfile/values/grafana/grafana-dashboards.yaml.gotmpl, helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl, helmfile/values/kube-prometheus-stack-wc.yaml.gotmpl, helmfile/values/prometheus-alerts-sc.yaml.gotmpl, migration/v0.34/prepare/10-move-clusterapi-config.sh
> [!warning]
> [!important]
Adds servicemonitors for the cluster autoscaler pods and a grafana dashboard to visualize the metrics.
- Part of https://github.com/elastisys/ck8s-cluster-api/issues/14
- Logs checks:
- …
=> apps sc: Added monitoring and dashboard for cluster autoscaling

config/config/common-config.yaml, config/config/sc-config.yaml, helmfile/14-podsecuritypolicies.yaml, helmfile/50-applications.yaml, helmfile/charts/grafana-dashboards/files/welcome.md, helmfile/charts/networkpolicy/service-cluster/templates/ingress-nginx/controller.yaml, helmfile/values/fluentd/forwarder-workload-cluster.yaml.gotmpl, helmfile/values/grafana/grafana-dashboards.yaml.gotmpl, helmfile/values/networkpolicy/service-cluster.yaml.gotmpl
> [!warning]
> [!important]
Deploying Opensearch can now be disabled by setting `.opensearch.enabled=false` in `sc-config.yaml`
This introduces a flag that determines whether Opensearch is to be deployed in the service cluster, allowing it to _not_ be.
- Fixes #1370
Not an actual screenshot
```
DELETED …
```
=> Make deployment of Opensearch optional

helmfile/charts/user-alertmanager/templates/secret.yaml, migration/v0.34/README.md, migration/v0.34/apply/70-unmanage-user-alertmanager-secret.sh, scripts/migration/yq.sh
So that we only apply it once.
> [!warning]
> [!important]
So that devs can manage their secrets with any tool they see fit.
- Logs checks:
- Bug checks:
=> apps wc: Unmanaged user-alertmanager secret

scripts/deploy-wc.sh
> [!warning]
> [!important]
The `fluentd` namespace is not created during bootstrap if `fluentd.enabled = false` but the Fluentd "example resources" are still created which errors. This fixes that.
Alternatively I could remove the "example resources" as they seem pretty out of place. Does anyone know if …
=> apps wc: Skip installing fluentd example resources if disabled

tests/.gitignore, tests/Makefile, tests/README.md, tests/common/lib.bash, tests/common/lib/harbor.bash, tests/end-to-end/gatekeeper-policies.bats, tests/end-to-end/harbor-api.bats
> [!warning]
> [!important]
I'm not entirely happy with the execution of these tests, and I'm thinking of reworking them a bit.
I would like the setup of the user-demo image to be a one liner and that practically all that needs can create it's own project/repository/robot to ensure that each test suite …
=> End-to-end tests for Harbor API

helmfile/bases/environment.yaml
> [!warning]
> [!important]
Increased the default helm timeout to 30 mintues
It is not uncommon that upgrade operations fail due to the helm timeout being too short.
Two applications that do take long to upgrade are opensearch and ingress-nginx.
- Logs checks:
- …
=> increase helm timeout

helmfile/charts/calico-accountant/templates/daemonset.yaml
> [!warning]
> [!important]
There was a small typo in the `calico-accountant` helm chart where an environment variable is named `NODE_NAME` instead of `NODENAME` [meaning that the pods will use HOSTNAME instead of the actual name of the nodes](https://github.com/monzo/calico-accountant/blob/ea22244e2bdd1 …
=> config: fix typo in calico-accountant helm chart

.github/workflows/end-to-end.yml, README.md, bin/ck8s, bin/fix-psp-violations.bash, bin/init.bash, bin/upgrade.bash, migration/template/README.md, migration/template/prepare/50-init.sh, migration/v0.34/README.md, migration/v0.34/prepare/50-init.sh, pipeline/README.md, pipeline/init-unit-tests.bash, pipeline/init.bats, scripts/migration/lib.sh
> [!warning]
> [!important]
The `ck8s init` command now requires a cluster argument which can be either of `<wc|sc|both>`.
Allow for running the `init` command per cluster. This also fixes issue with running the `fix-psp-violations` command which got introduced with [this …
=> Allow per cluster init

config/config/common-config.yaml
> [!warning]
> [!important]
Alerts for low remaining free space has changed. There is no longer a **critical** level alert for when free disk space is predicted to run out, but a `warning` level alert remains. Other disk low free disk space alerts have been tweaked.
- Tweaks thresholds for low free …
=> Tweak disk usage alerts

bin/init.bash, migration/template/README.md, migration/v0.34/README.md
> [!warning]
> [!important]
The default config for storage class name on upcloud has changed from "upcloud-block-storage" to "standard". This will impact prometheus and log-manager PVCs if they are enabled.
The default storage class elastisys generally uses on Upcloud is called "standard", not …
=> Update default upcloud storage class to "standard"

config/config/common-config.yaml, helmfile/values/prometheus-blackbox-exporter-sc.yaml.gotmpl, helmfile/values/prometheus-blackbox-exporter-wc.yaml.gotmpl
> [!warning]
> [!important]
...
- Fixes [#1855](https://github.com/elastisys/compliantkubernetes-apps/issues/1855)
- Logs checks:
- Bug checks:
=> apps: config option to set hostAliases for blackbox exporter

.gitmodules, .pre-commit-config.yaml, bin/update-ips.bash, pipeline/resources/update-ips-dry-run-full-diff.out, pipeline/resources/update-ips-dry-run-zero-diff.out, pipeline/update-ips.bats
> [!warning]
> [!important]
- Part of #1750
Currently only added unit tests for the current state of the script and improved the error handling:
- Some errors didn't exit the script.
- Some errors didn't exit early or failed without a proper message.
I wanted to a fairly extensive test coverage before I …
=> Refactor update-ips script

.pre-commit-config.yaml, helmfile.yaml, helmfile/bases/v2environments.yaml, helmfile/bases/v2upstream.yaml, helmfile/stacks/calico.yaml, helmfile/stacks/cert-manager.yaml, helmfile/stacks/dex.yaml, helmfile/stacks/falco.yaml, helmfile/stacks/fluentd.yaml, helmfile/stacks/gatekeeper.yaml, helmfile/stacks/harbor.yaml, helmfile/stacks/hnc.yaml, helmfile/stacks/ingress-nginx.yaml, helmfile/stacks/kured.yaml, helmfile/stacks/monitoring-grafana.yaml, helmfile/stacks/monitoring-prometheus.yaml, helmfile/stacks/monitoring.yaml, helmfile/stacks/opensearch.yaml, helmfile/stacks/rbac.yaml, helmfile/stacks/rclone.yaml, helmfile/stacks/system.yaml, helmfile/stacks/thanos.yaml, helmfile/stacks/velero.yaml
Currently it is running in parallel with the old one which is still the one in use.
> [!warning]
> [!important]
- Helmfile now divides SC and WC releases via conditions, this means that it will list all releases for both SC and WC, although only enabled releases will be operated on.
- Helmfile labels …
=> apps: Add modular helmfile structure

.pre-commit-config.yaml, bin/update-ips.bash, pipeline/Dockerfile, pipeline/resources/get-swift-url.out, pipeline/resources/update-ips-dry-run-full-diff.out, pipeline/update-ips.bats
> [!warning]
> [!important]
(OpenStack only) You should see a new Network Policy for `.networkPolicies.rcloneSync.destinationObjectStorageSwift` after running `update-ips` if Swift and Keystone have separate IPs and/or ports.
Before this only the auth/Keystone endpoint would be allow-listed when …
=> Lookup Swift endpoint for RClone sync in update-ips script

bin/update-ips.bash, pipeline/resources/update-ips-dry-run-full-diff.out, pipeline/update-ips.bats
> [!warning]
> [!important]
update-ips now defaults to port 443 or 80 depending on the protocol of the Swift auth URL instead of 5000. Make sure to include the port if it's required.
Follow up from: https://github.com/elastisys/compliantkubernetes-apps/pull/1853#discussion_r1395829480
I had to patch the …
=> Determine default port by URL protocol in update-ips script

helmfile/stacks/harbor.yaml, helmfile/stacks/system.yaml
> [!warning]
> [!important]
Found some bugs with the new setup that made modularity a bit strange to say the least.
Like it trying to pull in user-rbac into SC and failing to deploy Harbor even with object storage disabled.
- Logs checks:
- Pod …
=> apps: Fixes to the new Helmfile setup

helmfile/charts/networkpolicy/service-cluster/templates/dex/allow-dex.yaml, helmfile/charts/networkpolicy/service-cluster/templates/opensearch/dashboard.yaml, helmfile/values/opensearch/dashboards.yaml.gotmpl
> [!warning]
> [!important]
Use inter-cluster communication between OpenSearch Dashboards and dex.
With this in place apps doesn't need correct DNS records during deployment.
:pray: Please test on a full dev cluster, my kind cluster still lacks ingress :sweat_smile: 
- …
=> apps sc: OpenSearch Dashboards use internal communication to dex

bin/apps.bash, bin/ck8s, bin/common.bash, scripts/deploy-sc.sh, scripts/deploy-wc.sh
> [!warning]
> [!important]
The commands `apps` and `apply` now sets helmfile concurrency to 8 by default to avoid memory issues
Sets helmfile concurrency to avoid oom issues with diff.
- Fixes #1880 
- Logs checks: …
=> bin: set helmfile concurrency to avoid out of memory issues

bin/update-ips.bash
> [!warning]
> [!important]
Since the word splitting changed for `ops kubectl`.
- Logs checks:
- Bug checks:
=> bin: Allow update-ips to fetch nodes without labels

bin/update-ips.bash, pipeline/update-ips.bats
> [!warning]
> [!important]
This allows update-ips to work on configs containing set-me without errors from the cidr check.
- Logs checks:
- Bug checks:
=> bin: Skip CIDR check on set-me in update-ips

config/config/common-config.yaml, helmfile/values/ingress-nginx.yaml.gotmpl
> [!warning]
> [!important]
Makes it possible to predefine the cluster IP of ingress-nginx which is required by the local-clusters setup.
- Logs checks:
- Bug checks:
=> apps: Allow ingress-nginx cluster IP to be predefined

config/config/common-config.yaml, helmfile/values/ingress-nginx.yaml.gotmpl
> [!warning]
> [!important]
Exposes the option to provide ingress-nginx with extra arguments.
- Fixes #1894 
I tested the `--metrics-per-host=false` extra argument and the loss of the `host` label of metrics doesn't seem to break any alerts/dashboards. The only reference to the `host` label I was able …
=> apps: expose extra arguments for ingress-nginx

pipeline/test/services/workload-cluster/testUserRbac.sh
> [!warning]
> [!important]
Allows for spaces in user and group names for the RBAC tests in wc. A self-managed customer uses spaces in their groups, which causes the RBAC tests to not work as expected.
- Logs checks: …
=> tests: allow spaces in RBAC users and groups

bin/ck8s, bin/kubeconfig.bash
> [!warning]
> [!important]
When running `ck8s kubeconfig` it showed the usage / command list for `ck8s` itself instead of usage information for the `ck8s kubeconfig` commmand.
- Logs checks:
- …
=> Let ck8s kubeconfig show its own usage on missing arguments

helmfile/charts/log-manager/files/compaction.sh, helmfile/charts/log-manager/values.yaml
> [!warning]
> [!important]
Fixes issue where log-manager compaction script isn't removing all files as it should
...
- Fixes #
Apparently the `--rm` flag for `zstd` doesn't seem to be reliable (don't ask me why). So I just replaced them with rm commands instead afterwards. And also removed the index …
=> apps-sc: Fixed storage leak in log-manager compaction

config/config/sc-config.yaml, helmfile/charts/harbor/harbor-backup/scripts/harbor-backup.sh, helmfile/charts/harbor/harbor-backup/templates/harbor-backup-job.yaml, helmfile/charts/harbor/harbor-backup/values.yaml, helmfile/values/harbor/harbor-backup.yaml.gotmpl, scripts/restore/restore-harbor.sh
> [!warning]
> [!important]
When harbor backups gets too large, the kubelet evicts it because it uses too much local storage so I added the option to enable an ephemeral volume and also updated the script to compress the backups.
- Fixes #
- Logs checks:
- Network …
=> Fixed issue where large harbor backups would fail

config/config/sc-config.yaml, helmfile.d/charts/prometheus-alerts/files/disk-perf.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/disk-perf.yaml, helmfile.d/charts/prometheus-alerts/values.yaml
> [!warning]
> [!important]
...
- Fixes #1302
- Logs checks:
=> Add some initial disk performance alerts

migration/v0.35/apply/11-trivy-operator-crds.sh
> [!warning]
> [!important]
The incorrect function was used to upgrade trivy-operator, and that made the migration script to fail during the upgrade.
- Logs checks:
- Bug checks:
=> Fix for v0.35 trivy migration script

config/config/common-config.yaml, helmfile.d/values/trivy/trivy-operator.yaml.gotmpl
> [!warning]
> [!important]
To have more control over the trivy-operator configuration we added the option to exclude namespaces and also disable reports from the overwrite configs. Also, the scrapeInterval was increased to 5m.
- Logs checks:
- …
=> Trivy-operator added the option to exclude namespaces and to disable scans

scripts/charts.sh
> [!warning]
> [!important]
Previously, when running `./scripts/charts.sh diff <chart> all <version>` you would only see diffs from the root directory. With this patch you now see the full diff between chart versions.
- Logs checks:
- Pod …
=> Diff charts recursively when diffing 'all'

helmfile.d/upstream/index.yaml, helmfile.d/upstream/vmware-tanzu/velero/Chart.yaml, helmfile.d/upstream/vmware-tanzu/velero/README.md, helmfile.d/upstream/vmware-tanzu/velero/ci/test-values.yaml, helmfile.d/upstream/vmware-tanzu/velero/crds/backups.yaml, helmfile.d/upstream/vmware-tanzu/velero/crds/downloadrequests.yaml, helmfile.d/upstream/vmware-tanzu/velero/crds/restores.yaml, helmfile.d/upstream/vmware-tanzu/velero/crds/schedules.yaml, helmfile.d/upstream/vmware-tanzu/velero/templates/NOTES.txt, helmfile.d/upstream/vmware-tanzu/velero/templates/_helpers.tpl, helmfile.d/upstream/vmware-tanzu/velero/templates/backupstoragelocation.yaml, helmfile.d/upstream/vmware-tanzu/velero/templates/deployment.yaml, helmfile.d/upstream/vmware-tanzu/velero/templates/node-agent-daemonset.yaml, helmfile.d/upstream/vmware-tanzu/velero/templates/prometheusrule.yaml, helmfile.d/upstream/vmware-tanzu/velero/templates/volumesnapshotlocation.yaml, helmfile.d/upstream/vmware-tanzu/velero/values.yaml, helmfile.d/values/velero-sc.yaml.gotmpl, helmfile.d/values/velero-wc.yaml.gotmpl
> [!warning]
> [!important]
Only perform the upgrade if no Velero backup or restore operation is active.
Upgrade the Velero client to v1.11.1 on your host machine.
...
- Fixes #1665 
Tested on a local (kind) cluster.
* Deployed 1.10.2
* Created a backup from daily schedule
* Upgraded to 1.11.1
* …
=> Upgrade Velero to v1.11.1

config/config/common-config.yaml, helmfile.d/charts/prometheus-alerts/files/webhooks.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/webhooks.yaml, helmfile.d/values/kube-prometheus-stack-sc.yaml.gotmpl, helmfile.d/values/kube-prometheus-stack-wc.yaml.gotmpl, helmfile.d/values/prometheus-alerts-sc.yaml.gotmpl, helmfile.d/values/prometheus-user-alerts-wc.yaml.gotmpl
> [!warning]
> [!important]
Added an alert for failing webhooks
- Fixes #1870 
Not sure if we would want to have it enabled by default, as of now I have disabled it by default.
- Logs checks:
- …
=> Added alert for failing webhooks

helmfile.d/values/velero-sc.yaml.gotmpl, helmfile.d/values/velero-wc.yaml.gotmpl
> [!warning]
> [!important]
Velero now adheres to the S3 option `s3ForcePathStyle` in the configuration. Previously it was always set to `true`.
Follow up from: https://github.com/elastisys/compliantkubernetes-apps/pull/1946#discussion_r1453165845
Added a platform admin notice to inform of the change …
=> Use objectStorage.s3.forcePathStyle in Velero values

helmfile.d/values/velero-sc.yaml.gotmpl, helmfile.d/values/velero-wc.yaml.gotmpl
> [!warning]
> [!important]
Excluded the trivy resources from velero backups in both mc and wc
- Logs checks:
- Bug checks:
=> Exclude trivy resources from velero backup

helmfile.d/stacks/ingress-nginx.yaml, helmfile.d/state.yaml, helmfile.d/values/networkpolicies/workload/ingress-nginx-probe.yaml.gotmpl
> [!warning]
> [!important]
The netpol for the http01-solver was missing, so I added that
I ma not super familiar with the new helm setup, so please comment if I missed anything.
- Logs checks:
- …
=> Added networkpolicy for wc ingress probe

bin/update-ips.bash
> [!warning]
> [!important]
This error message wasn't very helpful:
`[ck8s] Could not determine default port for: set-me`
Now it is:
`[ck8s] Could not determine default port for .objectStorage.s3.regionEndpoint, missing protocol: set-me`
- Logs checks:
- Network Policy …
=> Add context to update-ips port parsing error

tests/README.md, tests/unit/bin/update-ips/main.bats
> [!warning]
> [!important]
This adds the option and instruction to regenerate resources for tests that relies on them.
- Logs checks:
- Bug checks:
=> tests: Regenerate resources when variable is set

README.md, bin/common.bash, config/config/common-config.yaml, config/config/flavors/air-gapped/common-config.yaml, config/config/flavors/air-gapped/sc-config.yaml, config/config/flavors/air-gapped/wc-config.yaml, config/config/sc-config.yaml, helmfile.d/values/falco/falco-common.yaml.gotmpl, helmfile.d/values/kube-prometheus-stack-sc.yaml.gotmpl, helmfile.d/values/opensearch/common.yaml.gotmpl, helmfile.d/values/prometheus-blackbox-exporter-sc.yaml.gotmpl, helmfile.d/values/prometheus-blackbox-exporter-wc.yaml.gotmpl, helmfile.d/values/trivy/trivy-operator.yaml.gotmpl, tests/unit/bin/init.bats.yaml, tests/unit/validate.bats.yaml
> [!warning]
> [!important]
There is now an additional `CK8S_FLAVOR` called `air-gapped` with similar settings to `prod` but with some additional configuration to avoid any outgoing traffic to the Internet.
This PR introduces additional templating to be able to configure CK8s in an air-gapped …
=> Add templating for air-gapped environments

scripts/restore/restore-harbor.sh
> [!warning]
> [!important]
Restoring harbor backup failed because the backup_dir variable was incorrect
```console
$ k logs -n harbor restore-harbor-job-v7hxv 
Downloading backup from s3 bucket backups/1707474714.tgz
download: s3://<env-name>-harbor/backups/1707474714.tgz to ./harbor.tgz
Extracting …
```
=> scripts: fixed harbor restore backup dir

config/config/common-config.yaml, helmfile.d/charts/grafana-dashboards/dashboards/capacity-management-dashboard.json, helmfile.d/charts/prometheus-alerts/templates/alerts/cluster-capacity-management-alerts.yaml, helmfile.d/charts/prometheus-alerts/templates/records/node-exporter.rules.yaml, helmfile.d/charts/prometheus-alerts/values.yaml, helmfile.d/values/grafana/grafana-dashboards.yaml.gotmpl, helmfile.d/values/kube-prometheus-stack-sc.yaml.gotmpl, helmfile.d/values/kube-prometheus-stack-wc.yaml.gotmpl, helmfile.d/values/prometheus-alerts-sc.yaml.gotmpl, helmfile.d/values/prometheus-user-alerts-wc.yaml.gotmpl
> [!warning]
> [!important]
Capacity management has been reworked with new alerts and a Grafana dashboard. In order for these to work, nodes must be labeled with `elastisys.io/node-group=<node-group>`.
Adds capacity management alerts and a dashboard, based on our previous investigation regarding this.
- …
=> Rework capacity management alerts and add dashboard

roles/get-requirements.yaml
> [!warning]
> [!important]
Bump `kubectl` version as part of the Kubespray release.
- Logs checks:
- Bug checks:
=> release: bumped kubectl version to 1.28.6

config/config/sc-config.yaml, migration/v0.36/README.md, migration/v0.36/prepare/10-thanos-distrib-memory-limit.sh
> [!warning]
> [!important]
I had issues on multiple environments when Thanos Distributor was in a crash loop state at startup due to OOM. I decided the increase the default memory limit for it.
- Logs checks:
- …
=> Increase the memory limit for Thanos Distributor

config/config/common-config.yaml, helmfile.d/values/ingress-nginx.yaml.gotmpl
> [!warning]
> [!important]
By default, from ingress-nginx' helmcharts, the ingress controller will configure itself with IPv4 only, and with external
load balancers it is still possible to expose workloads on IPv6 as well. However, when exposing an internal load balancer service (ie MetalLB), it's not …
=> apps: Add ability to set IP families for the ingress-nginx service

helmfile.d/values/prometheus-blackbox-exporter-sc.yaml.gotmpl
> [!warning]
> [!important]
When we use external PostgreSQL or Redis for Harbor, the probes that come with those installations requite `tcp_connect` modules enabled for Blackbox-Exporter. This PR will add the module if any external service is used for Harbor.
Let me know if you prefer to add …
=> Enable tcp module for Blackbox exporter in sc

helmfile.d/values/velero-sc.yaml.gotmpl, helmfile.d/values/velero-wc.yaml.gotmpl, migration/v0.36/README.md, migration/v0.36/apply/50-velero-crds-upgrade.sh, migration/v0.36/apply/80-apply.sh
> [!warning]
> [!important]
During the upgrade to apps v0.36 the kubectl container used by Velero to apply the CRDs was failing with:
```console
/tmp/sh: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/sh)
/tmp/sh: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' …
```
=> Apply velero crds manually during apps v0.36 upgrade

helmfile/values/velero-sc.yaml.gotmpl, helmfile/values/velero-wc.yaml.gotmpl, migration/v0.35/README.md, migration/v0.35/apply/60-velero-crds-upgrade.sh, migration/v0.35/apply/80-apply.sh
> [!warning]
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Staging 0.35.2

scripts/clean-sc.sh, scripts/clean-wc.sh
> [!warning]
> [!important]
I have encountered cases where the clean scripts gets stuck deleting resources caused by timeouts when calling the gatekeeper service via the validating webhook after gatekeeper pods have been removed (mainly an issue during reruns, e.g. if something went wrong while deleting …
=> Improve clean scripts by removing gatekeeper webhook

config/config/sc-config.yaml, config/config/wc-config.yaml, helmfile.d/charts/user-alertmanager/templates/alertmanager.yaml, helmfile.d/charts/user-alertmanager/values.yaml, helmfile.d/values/kube-prometheus-stack-sc.yaml.gotmpl, helmfile.d/values/user-alertmanager.yaml.gotmpl
> [!warning]
> [!important]
The image used for alertmanager can now be customized by setting `.prometheus.alertmanagerSpec.image = {registry: "...", repository: "...", tag: "..."}` for sc, or `.user.alertmanager.image = "registry/repository:tag"` for wc.
This allows overriding the image(s) used for …
=> Ability to customize both Alertmanagers images

config/config/common-config.yaml, helmfile.d/charts/issuers/templates/letsencrypt-prod.yaml, helmfile.d/charts/issuers/templates/letsencrypt-staging.yaml, helmfile.d/upstream/index.yaml, helmfile.d/upstream/jetstack/cert-manager/Chart.yaml, helmfile.d/upstream/jetstack/cert-manager/README.md, helmfile.d/upstream/jetstack/cert-manager/templates/cainjector-deployment.yaml, helmfile.d/upstream/jetstack/cert-manager/templates/cainjector-poddisruptionbudget.yaml, helmfile.d/upstream/jetstack/cert-manager/templates/cainjector-rbac.yaml, helmfile.d/upstream/jetstack/cert-manager/templates/crds.yaml, helmfile.d/upstream/jetstack/cert-manager/templates/deployment.yaml, helmfile.d/upstream/jetstack/cert-manager/templates/poddisruptionbudget.yaml, helmfile.d/upstream/jetstack/cert-manager/templates/rbac.yaml, helmfile.d/upstream/jetstack/cert-manager/templates/startupapicheck-job.yaml, helmfile.d/upstream/jetstack/cert-manager/templates/webhook-deployment.yaml, helmfile.d/upstream/jetstack/cert-manager/templates/webhook-poddisruptionbudget.yaml, helmfile.d/upstream/jetstack/cert-manager/templates/webhook-psp-clusterrole.yaml, helmfile.d/upstream/jetstack/cert-manager/values.yaml, helmfile.d/values/cert-manager.yaml.gotmpl, migration/v0.37/README.md, migration/v0.37/apply/00-template.sh, migration/v0.37/apply/80-apply.sh, migration/v0.37/prepare/00-template.sh, migration/v0.37/prepare/50-init.sh, migration/v0.37/prepare/60-move-issuer-ingress-class.sh
> [!warning]
> [!important]
Cert-manager Issuers and ClusterIssuers have been updated to use the [recommended](https://cert-manager.io/docs/configuration/acme/http01/#ingressclassname) `ingressClassName` field over the `class` field. We recommend that Application Developers use the `ingressClassName` …
=> Upgrade cert-manager to v1.12.8

bin/ck8s, bin/diagnostics.bash, tests/unit/bin/diagnostics.bats
> [!warning]
> [!important]
Added a new diagnostics command with the primary goal of aiding in supporting self-managed customers. By default it encrypts the file with the sops config inside of `$CK8S_CONFIG_PATH` but setting `$CK8S_PGP_FP` will override this.
Added a new diagnostics command which …
=> Added new diagnostics script

pipeline/test/services/service-cluster/testIngress.sh, pipeline/test/services/workload-cluster/testIngress.sh
> [!warning]
>
> [!important]
curl does no longer exist in the ingress-nginx container which we relied on when testing the ingress health. This replaces it with a test using wget.
Unfortunately wget does not seem to support sending PROXY protocol headers so it will fail for clusters which uses …
=> Fix ingress test

helmfile.d/upstream/index.yaml, helmfile.d/upstream/prometheus-community/prometheus-blackbox-exporter/Chart.yaml, helmfile.d/upstream/prometheus-community/prometheus-blackbox-exporter/ci/config-reloader-values.yaml, helmfile.d/upstream/prometheus-community/prometheus-blackbox-exporter/templates/_helpers.tpl, helmfile.d/upstream/prometheus-community/prometheus-blackbox-exporter/templates/configmap.yaml, helmfile.d/upstream/prometheus-community/prometheus-blackbox-exporter/templates/daemonset.yaml, helmfile.d/upstream/prometheus-community/prometheus-blackbox-exporter/templates/deployment.yaml, helmfile.d/upstream/prometheus-community/prometheus-blackbox-exporter/templates/podmonitoring.yaml, helmfile.d/upstream/prometheus-community/prometheus-blackbox-exporter/templates/selfpodmonitoring.yaml, helmfile.d/upstream/prometheus-community/prometheus-blackbox-exporter/templates/selfservicemonitor.yaml, helmfile.d/upstream/prometheus-community/prometheus-blackbox-exporter/templates/service.yaml, helmfile.d/upstream/prometheus-community/prometheus-blackbox-exporter/templates/servicemonitor.yaml, helmfile.d/upstream/prometheus-community/prometheus-blackbox-exporter/values.yaml
> [!warning]
>
> [!important]
Upgrades prometheus-blackbox-exporter chart version from 8.2.0 to 8.13.0. Still same app version v0.24.0.
...
- Fixes #1902 
- Logs checks:
- …
=> apps: Upgrade prometheus blackbox exporter to chart v8.13.0

bin/init.bash, config/config/common-config.yaml
> [!warning]
>
> [!important]
Part of https://github.com/elastisys/mse-internal-docs/issues/181
Ever since https://github.com/elastisys/compliantkubernetes-apps/commit/a4baa4230871f3e53595b2ed890b67bebda7457b the init process has not been able to patch the nginx service annotations in the …
=> Make nginx service annotations configurable again

helmfile.d/charts/prometheus-alerts/templates/alerts/kured.yaml, helmfile.d/charts/prometheus-alerts/values.yaml, helmfile.d/values/prometheus-alerts-sc.yaml.gotmpl, helmfile.d/values/prometheus-user-alerts-wc.yaml.gotmpl
> [!warning]
>
> [!important]
Added an alert for Kured for when a node has required a reboot for 30 days
- Fixes #2062 
- Logs checks:
- Bug checks:
=> Added kured alert for when nodes have required reboot for 30 days

bin/init.bash, config/config/sc-config.yaml, config/config/wc-config.yaml, helmfile.d/values/networkpolicy/service-cluster.yaml.gotmpl, helmfile.d/values/networkpolicy/workload-cluster.yaml.gotmpl
> [!warning]
>
> [!important]
Without this fix `ingressNginx.ingressOverride.ips[0]` gets set to `set-me-if-enabled` because it was previously trying to set the value in the common config while the option is in the sc and wc configs.
Also had to patch the `replace_set_me` function to allow for …
=> Fix Azure ingress override config initialization

roles/get-requirements.yaml, roles/get-url.yaml
> [!warning]
>
> [!important]
When running `bin/ck8s install-requirements` I got the following error message:
```
TASK [Check /usr/local/bin/yajsv] ***************************************************************************************************************************************************** …
```
=> Fix yajsv version flag for install-requirements

config/config/sc-config.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/daily-checks.yaml, helmfile.d/values/prometheus-alerts-sc.yaml.gotmpl, migration/v0.38/README.md, migration/v0.38/prepare/30-check-upcloud-s3-version.sh
> [!warning]
>
> [!important]
This PR adds a new alert for whenever the total size of all S3 buckets exceeds a set quota. The alert is disabled by default and can be enabled with `s3BucketAlerts.totalSize.percent`. There is a migration script that will enable the alert for Upcloud environments …
=> Add S3 object storage total size alert

config/config/common-config.yaml, helmfile.d/charts/gatekeeper/constraints/templates/deployment-minimum-replicas/constraint.yaml, helmfile.d/charts/gatekeeper/constraints/values.yaml, helmfile.d/charts/gatekeeper/templates/policies/deployment-minimum-replicas.rego, helmfile.d/charts/gatekeeper/templates/templates/deployment-minimum-replicas/template.yaml, helmfile.d/charts/gatekeeper/templates/values.yaml, helmfile.d/values/gatekeeper/constraints.yaml.gotmpl, helmfile.d/values/gatekeeper/templates.yaml.gotmpl
> [!warning]
>
> [!important]
This PR adds a warning when a deployment has less than 2 replicas
- Fixes https://github.com/elastisys/compliantkubernetes-apps/issues/2034
- Logs checks:
- …
=> Add a gatekeeper constraint that warns application developers when they deploy with less then 3 replicas

bin/ck8s, bin/explain.bash
> [!warning]
>
> [!important]
I hacked this together so I might as well share it.
```console
$ ./bin/ck8s explain config
Compliant Kubernetes Apps settings
This describes the structure of the configuration for both the service
cluster and the workload cluster, but keep in mind that each …
```
=> bin: Naive implementation for explain config or secrets

DEVELOPMENT.md, scripts/local-cluster.sh, scripts/local-clusters/profiles/multi-node-cache.yaml, scripts/local-clusters/profiles/single-node-cache.yaml, scripts/local-clusters/registries/docker.io/hosts.toml, scripts/local-clusters/registries/ghcr.io/hosts.toml, scripts/local-clusters/registries/quay.io/hosts.toml
> [!warning]
>
> [!important]
This adds functions to the local clusters script to setup and use local caches for container images.
```bash
./scripts/local-cluster.sh cache create
./scripts/local-cluster.sh create local-cluster single-node-cache
./scripts/local-cluster.sh delete local-cluster …
```
=> scripts: Use local caches for local clusters

pipeline/test/services/workload-cluster/testHNC.sh
> [!warning]
>
> [!important]
Previously, the `hnc` test did not handle space separated user names. This PR addresses this and solves this by adding quotes to variables to avoid word splitting
- Fixes #
- Logs checks:
- Network …
=> Fix HNC test for space separated user names

helmfile.d/values/falco/falco-common.yaml.gotmpl
> [!warning]
>
> [!important]
When running with `calicoAccountant.backend=nftables` a `Drop and execute new binary in container` event is triggered by Falco when [calico-accountant calls `iptables`](https://github.com/elastisys/compliantkubernetes-apps/blob/v0.37.0/helmfile.d/charts/calico-accoun …
=> Add falco exception for calico-accountant with nftables

helmfile.d/values/fluentd/forwarder-common.yaml.gotmpl
> [!warning]
>
> [!important]
This pr disables Fluentd PrometheusRules that comes from upstream.
It is needed since we have our own [PrometheusRule](https://github.com/elastisys/compliantkubernetes-apps/blob/bd371e295fda3ec2648670e46d10af818be1d74f/helmfile.d/charts/prometheus-alerts/templates/al …
=> Disable upstream fluentd alerts

config/schemas/README.md, config/schemas/config.yaml, config/schemas/secrets.yaml, tests/common/lib/env.bash
> [!warning]
>
> [!important]
This adds structural validation for the following top-level config sections:
- user
- hnc
- clusterApi
- harbor
- clusterApi
- storageClasses
- objectStorage
- rookCeph
For more context including the required scripts and see #1862 
Part of issue #1427 
`ck8s …
=> Config Structural Validation Schema Part 1: Commons, HNC, CAPI, Harbor, Storage

config/config/wc-config.yaml, helmfile.d/values/networkpolicies/common/prometheus.yaml.gotmpl
> [!warning]
>
> [!important]
It is now possible to allow internal traffic to WC Prometheus from Pods with the label `elastisys.io/prometheus-access: allow` in a configurable list of namespaces. This can be configured under `.networkPolicies.prometheus.internalAccess.enabled` and …
=> Add config option to allow internal traffic to Prometheus

.editorconfig, helmfile.d/charts/gatekeeper/templates/policies/reject-loadbalancer-service.rego
> [!warning]
>
> [!important]
Because we want consistent code style in `.rego` files.
This both tells compatible code editors what the expected indentation should be, as well as enforces it in `pre-commit`.
Includes fix for one `.rego` file that used 2-space indentation.
All others already use …
=> Specify 4 space indentation for policy rules

helmfile.d/values/falco/falco-common.yaml.gotmpl
> [!warning]
>
> [!important]
When deploying Falco with the most recent changes, the pods got this error:
```
Tue May 14 09:49:08 2024: Falco version: 0.37.1 (x86_64)
...
Tue May 14 09:49:09 2024: Loading rules from file /etc/falco/rules.d/overwrites.yaml
Error: …
```
=> Fix falco condition for gatekeeper constraints api call

config/config/common-config.yaml, config/schemas/config.yaml, tests/common/lib/env.bash, tests/unit/bin/update-ips/resources/maximal-run-full-diff.out
> [!warning]
>
> [!important]
This adds structural validation for the following top-level config sections:
- clusterAdmin
- dex
- externalTrafficPolicy
- falco
- gatekeeper
- kured
- opa
- trivy
For more context including the required scripts and see #1862
Part of issue #1427
`ck8s validate` …
=> Config Structural Validation Schema Part 2: Security and Policy

bin/ck8s, bin/install-requirements.bash, roles/get-requirements.yaml
> [!warning]
>
> [!important]
Some users like to install their requirements in a user directory without root instead of globally. I found myself parsing the `get-requirements.yaml` file and installing things manually. This makes it useful for me (and others that have the same preference).
- …
=> Support installing requirements without root

helmfile.d/charts/grafana-dashboards/dashboards/kubernetesstatus-dashboard.json
> [!warning]
>
> [!important]
Updates the `Kubernetes cluster status` dashboard to ignore system namespaces in the "Pods/Containers missing resource requests" panels. This should make them more useful for Application Developers, as there is now less noise.
- Fixes #2134 
- …
=> Ignore system namespace pods with missing resource requests in cluster status dashboard

.gitignore, README.md, REQUIREMENTS, roles/get-requirements.yaml, scripts/requirements/packageurl.py, scripts/requirements/parse.py
> [!warning]
>
> [!important]
This PR declares ck8s-apps requirements as [PURLs](https://github.com/package-url/purl-spec). PURL (Package URL) is a standardized way of identifying software from different ecosystems.
I believe this will benefit us in that the requirements aren't sprawling all …
=> Declare requirements as PURLs

REQUIREMENTS, bin/ck8s, bin/ops.bash, roles/get-requirements.yaml, scripts/clean-sc.sh, scripts/clean-wc.sh
> [!warning]
>
> [!important]
It is now possible to run `velero` commands with `ck8s ops velero <wc|sc>`
Running clean script got stuck when trying to delete Velero CRDs after having upgraded to the new Velero chart. This was caused by newly added finalizers to Velero resources (see breaking …
=> Add `ck8s ops velero` command and clean up new velero finalizers

helmfile.d/upstream/index.yaml, helmfile.d/upstream/kubereboot/kured/Chart.yaml, helmfile.d/upstream/kubereboot/kured/README.md, helmfile.d/upstream/kubereboot/kured/templates/daemonset.yaml, helmfile.d/upstream/kubereboot/kured/templates/service.yaml, helmfile.d/upstream/kubereboot/kured/templates/servicemonitor.yaml, helmfile.d/upstream/kubereboot/kured/values.minikube.yaml, helmfile.d/upstream/kubereboot/kured/values.yaml, helmfile.d/values/podsecuritypolicies/common/kured.yaml.gotmpl
> [!warning]
>
> [!important]
Upgraded `kured` to Chart Version `5.4.5` and App Version `1.15.1`
- Fixes #1900 
Two security-related default-values were improved:
- `hostNetwork` is set to `false` by default now.
- `readOnlyRootFilesystem` is set to `true` by default now.
Also kured now wants to …
=> Upgrade Kured to v1.15.1

helmfile.d/charts/gatekeeper/templates/policies/network-policies.rego, helmfile.d/charts/gatekeeper/templates/policies/tests/network-policies.rego
> [!warning]
>
> [!important]
...
- Fixes #2073
When an application is being deleted using [finalizers](https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/), [the requirement for having a network policy](https://github.com/elastisys/compliantkubernetes-apps/blob/main/hel …
=> Allow changes to pods that are missing network policies when the pods are about to be deleted

helmfile.d/charts/gatekeeper/podsecuritypolicies/templates/_.tpl, helmfile.d/charts/gatekeeper/podsecuritypolicies/templates/custom/mutations/run-as-user.yaml, helmfile.d/charts/gatekeeper/podsecuritypolicies/templates/custom/users.yaml, helmfile.d/charts/gatekeeper/podsecuritypolicies/values.yaml, helmfile.d/values/podsecuritypolicies/common/velero.yaml.gotmpl
> [!warning]
>
> [!important]
...
- Fixes #2075
- Logs checks:
- Bug checks:
=> psps: allow matchexpressions in gatekeeper mutation for runasuser

migration/v0.38/README.md, migration/v0.38/prepare/60-set-nginx-annotations.sh
> [!warning]
>
> [!important]
This configuration option would remain unset when ingress-nginx service was enabled on an infra provider that doesn't have it enabled by default (e.g. Safespring with MetalLB). Added a migration script to set it during migration.
- …
=> Add migration script for setting ingress-nginx annotations if they are unset

helmfile.d/values/grafana/grafana-ops.yaml.gotmpl, helmfile.d/values/grafana/grafana-user.yaml.gotmpl
OAuth security improvement
> [!warning]
>
> [!important]
This enables the OAuth 2.0 [PKCE](https://oauth.net/2/pkce/) feature in Grafana marginally improving security when logging in with Dex.
PKCE is considered [best current practice](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-securi …
=> Enable OAuth PKCE in Grafana

config/schemas/config.yaml, helmfile.d/values/podsecuritypolicies/workload/default.yaml.gotmpl
> [!warning]
>
> [!important]
When configuring user namespaces custom constraints the PSA level wasn't configurable.
1. The schema did not allow it to be a string.
2. When running `helmfile diff` the value would be unset in a previous render.
- Logs checks:
- …
=> Fix bug preventing configuration of PSA level

bin/common.bash, tests/regression/issue2172.bats
> [!warning]
>
> [!important]
- Fixes #2172, wherein constraints are somehow lost on `ck8s init`
The regression test can be run by
```console
cd tests/
bats -r regression
```
- Logs checks: …
=> Preserve empty objects on init

README.md, bin/common.bash, config/providers/openstack/common-config.yaml, config/providers/openstack/sc-config.yaml, config/schemas/config.yaml, tests/unit/bin/init/template.bats.gotmpl, tests/unit/bin/init/template.gen.bats, tests/unit/bin/init/test-capi-openstack-air-gapped.gen.bats, tests/unit/bin/init/test-capi-openstack-dev.gen.bats, tests/unit/bin/init/test-capi-openstack-prod.gen.bats, tests/unit/bin/init/test-kubespray-openstack-air-gapped.gen.bats, tests/unit/bin/init/test-kubespray-openstack-dev.gen.bats, tests/unit/bin/init/test-kubespray-openstack-prod.gen.bats, tests/unit/validate/template.bats.gotmpl, tests/unit/validate/template.gen.bats, tests/unit/validate/test-capi-openstack-air-gapped.gen.bats, tests/unit/validate/test-capi-openstack-dev.gen.bats, tests/unit/validate/test-capi-openstack-prod.gen.bats, tests/unit/validate/test-kubespray-openstack-air-gapped.gen.bats, tests/unit/validate/test-kubespray-openstack-dev.gen.bats, tests/unit/validate/test-kubespray-openstack-prod.gen.bats
OAuth security improvement
> [!warning]
>
> [!important]
Adds openstack as a generic provider.
For situations when apps is deployed on a openstack cloud but not safespring, elastx or citycloud. 
...
- Fixes #
- Logs checks:
- …
=> config: add openstack as a provider

helmfile.d/charts/prometheus-alerts/files/cluster-api.yaml
> [!warning]
>
> [!important]
If a machinedeployment is set to 0 this metric will return NaN and trigger the alert.
This seeks to fix that bug
- Fixes #
- Logs checks:
- Bug …
=> apps sc: Fixed alert for capi if machinedeployment is 0 replicas

helmfile.d/values/networkpolicies/workload/fluentd.yaml.gotmpl
> [!warning]
>
> [!important]
I noticed some error logs from fluentd-elasticsearch in wc:
```logs
{"time":"2024-07-17 08:55:18 +0000","level":"warn","message":"[output-forwarding] failed to flush the buffer. retry_times=5418 next_retry_time=2024-07-17 08:55:45 +0000 …
```
=> Fixed netpol for fluentd-aggregator

helmfile.d/charts/grafana-dashboards/dashboards/kubernetesstatus-dashboard.json
> [!warning]
>
> [!important]
When looking at the kubernetes cluster status dashboard, the number and the list didn't add up. So this solves that by returning 0 when there's no pods with requests.
Also fixes a bug where the gauge shows 0 instead of 0%
- Fixes # …
=> apps sc: Fixed some panels in the kubernetes cluster status dashboard

helmfile.d/charts/grafana-dashboards/dashboards/kubernetesstatus-dashboard.json
> [!warning]
>
> [!important]
This PR makes it so more panels in the kubernetes status dashboard to include the "node" filtertf
- Fixes #
- Logs checks:
- Bug checks:
=> apps sc: Added node filter to more graphs in kubernetes status dashboard

config/schemas/secrets.yaml, config/secrets.yaml, helmfile.d/upstream/dexidp/dex/Chart.yaml, helmfile.d/upstream/dexidp/dex/README.md, helmfile.d/upstream/dexidp/dex/ci/label-annotations-values.yaml, helmfile.d/upstream/dexidp/dex/templates/deployment.yaml, helmfile.d/upstream/dexidp/dex/templates/hpa.yaml, helmfile.d/upstream/dexidp/dex/templates/servicemonitor.yaml, helmfile.d/upstream/dexidp/dex/values.yaml, helmfile.d/upstream/index.yaml, migration/v0.40/README.md, migration/v0.40/prepare/20-update-google-dex-config.sh, scripts/migration/lib.sh
> [!warning]
>
> [!important]
This upgrades dex to app version 2.40.0 and chart version 0.18.0
The google connector config `adminEmail: <email>` has been deprecated in favor of `domainToAdminEmail. '*': <email>`. It is now possible to have different admin emails for different domains, see the …
=> apps sc: dex upgraded to app version 2.40.0 and chart version 0.18.0

scripts/restore/README.md
> [!warning]
>
> [!important]
This adds a step to the process of restoring harbor to an environment with a different domain.
- Fixes #
- Logs checks:
- Bug checks:
=> docs: remove oidc-users if restoring harbor to new domain

config/schemas/config.yaml, helmfile.d/values/networkpolicies/service/rclone.yaml.gotmpl, helmfile.d/values/rclone/sync.yaml.gotmpl
> [!warning]
>
> [!important]
A collection of fixes discovered while testing rclone sync from azure to s3.
- Template issue when `.objectStorage.sync.syncDefaultBuckets` was set to `true` instead of using `.objectStorage.sync.buckets[]`
- Occurences of `rclone-restore` in `rclone-sync` templates …
=> Rclone sync fixes

helmfile.d/values/dex.yaml.gotmpl
> [!warning]
>
> [!important]
The upgrade to dex 2.40 the default for `skipApprovalScreen` had changed. This changes that setting back to how we had it before that upgrade
- Fixes #
- Logs checks:
- Audit …
=> apps sc: Added back the skip of the consent screen for dex

bin/ck8s, bin/diagnostics.bash
> [!warning]
>
> [!important]
The command usage for `ck8s` has been updated so that all commands are listed in ascending order.
The command `ck8s diagnostics` has a new flag to include config files in the output log file. The command usage has been changed: `ck8s diagnostics <wc|sc> [-n …
=> Add flag to include config files for diagnostics script

REQUIREMENTS, changelog/0.40.md, config/common-config.yaml, config/sc-config.yaml, helmfile.d/charts/grafana-dashboards/files/welcome.md, helmfile.d/charts/harbor/harbor-backup/scripts/harbor-backup.sh, helmfile.d/charts/harbor/harbor-backup/templates/harbor-backup-job.yaml, helmfile.d/charts/opensearch/configurer/files/dashboards-resources/welcome.md, images/backup-postgres/Dockerfile
> [!warning]
>
> [!important]
...
Some bugfixes for requirements script.
Increased the memory limits of sync resources, because thanos rclone job got OOMKilled.
Added tolerations for trivy node-collector, because it would be stuck in pending.
When Harbor was upgraded in v0.40, noticed that the …
=> Add changelog for release v0.40.0

helmfile.d/upstream/README.md, helmfile.d/upstream/grafana/grafana/Chart.yaml, helmfile.d/upstream/grafana/grafana/templates/_helpers.tpl, helmfile.d/upstream/grafana/grafana/templates/pvc.yaml, helmfile.d/upstream/grafana/grafana/templates/tests/test.yaml, helmfile.d/upstream/grafana/grafana/values.yaml, helmfile.d/upstream/index.yaml, helmfile.d/values/grafana/grafana-common.yaml.gotmpl
> [!warning]
>
> [!important]
Upgrades Grafana to patch version containing medium severity security fix for [CVE-2024-6837](https://grafana.com/blog/2024/08/14/grafana-security-release-medium-severity-security-fix-for-cve-2024-6837/) (v10.4.7) and chart to the latest chart version for Grafana …
=> Upgrade Grafana chart to 7.3.12 and set image to v10.4.7

config/wc-config.yaml
> [!warning]
>
> [!important]
Enabled matchConditions for the HNC validating webhook by default, which requires Kubernetes v1.28 or higher.
Enables matchConditions for the HNC validating webhook. This is necessary for velero restore to work in wc without removing the webhook first.
- Fixes #
We …
=> Enable matchConditions for HNC webhook by default

scripts/run-from-container.sh
> [!warning]
>
> [!important]
I like to run tests on save but these prompts prevents that.
I realize I can run it with `CK8S_AUTO_APPROVE` but I don't want to accidentally auto approve something else which I'm unaware of. :smile: 
@aarnq What was the rational for them? Is there a danger …
=> Remove prompts from run-in-container script

tests/bats.lib.bash, tests/end-to-end/grafana/grafana-authentication.cy.js
> [!warning]
>
> [!important]
Before:
```
$ make run-end-to-end/grafana/grafana-authentication.gen.bats
[ck8s] forward your environment and runtime to container compliantkubernetes-apps-tests:main? [y/N]: y
--- run end-to-end/grafana/grafana-authentication.gen.bats
1..4
ok 1 grafana admin …
```
=> Catch before-all test hook failures in Cypress tests

config/common-config.yaml, config/flavors/dev/common-config.yaml, config/flavors/prod/common-config.yaml, config/schemas/config.yaml, helmfile.d/values/networkpolicies/common/cert-manager.yaml.gotmpl, migration/v0.41/README.md, scripts/run-from-container.sh, tests/unit/general/bin-conditional-set-me.bats
> [!warning]
>
> [!important]
The default network policies for cert-manager has changed in `dev` and `prod` flavours allowing all egress traffic on `53/tcp`, `53/udp`, `80/tcp`, and `443/tcp` to provide a better certificate management experience for application developers.
The default network …
=> config: Open cert-manager netpols by default

config/sc-config.yaml, config/schemas/config.yaml
> [!warning]
>
> [!important]
Fixes the config for Slack `customTemplate` to be string and not object.
- Fixes #
- Logs checks:
- Bug checks:
=> Fix Slack customTemplate type

config/common-config.yaml, config/schemas/config.yaml, helmfile.d/values/ingress-nginx.yaml.gotmpl
> [!warning]
>
> [!important]
Add support for using predefined IP for the Load Balancer .
This PR enables the option to use an already created floating ip with ingress service .
- Fixes #
- Logs checks:
- …
=> apps: Add support for ingress to use predifined ips

config/common-config.yaml, config/schemas/config.yaml, helmfile.d/charts/node-local-dns/templates/node-local-dns.yaml, helmfile.d/charts/node-local-dns/values.yaml, helmfile.d/values/node-local-dns.yaml.gotmpl
> [!warning]
>
> [!important]
Added a new variable to configure extra config to the nodeLocalDns hostzone (.53). See this patch branch as an example of why this would be needed in some environments: https://github.com/elastisys/compliantkubernetes-apps/blob/v0.37.0%2BAAAA-noerror%2Bopensearch-2.1 …
=> Add extraconfig variable for nodelocaldns hostzone

helmfile.d/values/fluentd/forwarder-common.yaml.gotmpl
> [!warning]
>
> [!important]
While working on PR https://github.com/elastisys/compliantkubernetes-apps/pull/2242, I noticed we had panels in the fluentd dashboard that used metrics that we did not seem to expose. I found an example fluentd configuration to expose this metric …
=> Add Fluentd metric for incoming records per tag

config/common-config.yaml, config/schemas/config.yaml, helmfile.d/values/prometheus-blackbox-exporter-sc.yaml.gotmpl
> [!warning]
>
> [!important]
Tolerations and Affinity can now be set for Blackbox expoter 
This config changes allows to specify were the black box exporter pod is allowed to run.
Useful when ip allowlisting is enabled for just some of the nodes in the cluster. 
- Documentation …
=> Expose Tolerations and Affinity in config for blackbox exporter 

helmfile.d/charts/prometheus-alerts/files/rook-alerts.yaml
> [!warning]
>
> [!important]
Fixes Thanos not being able to evaluate the CephOSDFlapping alert rule.
- Fixes #
Error:
`many-to-many matching not allowed: matching labels must be unique on one side\"}\n" query="(rate(ceph_osd_up[5m]) * on (ceph_daemon) group_left (hostname) ceph_osd_metadata) * …
=> Fix rook-ceph alerts

config/common-config.yaml, config/schemas/config.yaml, helmfile.d/values/metrics-server.yaml.gotmpl
> [!warning]
>
> [!important]
Exposes affinity and tolerations for metrics-server. Preparing for https://github.com/elastisys/ck8s-issue-tracker/issues/313
- Logs checks:
- Audit …
=> Expose affinity and tolerations for metrics-server

migration/v0.42/README.md, migration/v0.42/apply/00-template.sh, migration/v0.42/apply/10-upgrade-grafana.sh, migration/v0.42/apply/80-apply.sh, migration/v0.42/prepare/00-template.sh, migration/v0.42/prepare/50-init.sh
> [!warning]
>
> [!important]
Migration script to fix issue with "false-diffs" for Grafana PVC volumeName, see [this](https://github.com/elastisys/compliantkubernetes-apps/pull/2278#discussion_r1761306187) for context.
- Fixes #
I tested running the script after having upgraded my cluster to …
=> Add migration script to fix Grafana lookup volumeName issue

migration/v0.41/README.md, migration/v0.42/README.md
> [!warning]
>
> [!important]
Move migration step to v0.42 as the change didn't make it into apps v0.41
- Fixes #
- Logs checks:
- Bug checks:
=> docs: move cert-manager netpol migration step to v0.42

bin/update-ips.bash, tests/common/bats/update-ips.bash, tests/unit/general/bin-update-ips-rclone.bats, tests/unit/general/bin-update-ips-swift.bats, tests/unit/general/resources/get-swift-url.out
> [!warning]
>
> [!important]
I noticed that the update-ips did not find the swift url. 
Im unsure if it is my version of curl that returns 1 less line. 
If that is the case, we probably need to find a more stable way extract the url from the response.
```
curl --version
curl 7.88.1 …
```
=> Fix update-ips fetch swift url

helmfile.d/upstream/grafana/grafana/Chart.yaml, helmfile.d/upstream/grafana/grafana/README.md, helmfile.d/upstream/grafana/grafana/templates/_pod.tpl, helmfile.d/upstream/grafana/grafana/values.yaml, helmfile.d/upstream/index.yaml, tests/end-to-end/grafana/authentication.cy.js, tests/end-to-end/grafana/dashboards.cy.js
> [!warning]
>
> [!important]
Fixes [cve-2024-8118](https://grafana.com/blog/2024/09/26/grafana-security-release-medium-severity-fix-for-cve-2024-8118/)
Upgraded Grafana chart to upgrade image version to v11.2.1 to address CVE. Also updated e2e tests for Grafana to perform a check that …
=> Upgrade grafana chart to v8.5.2

helmfile.d/values/admin-namespaces-sc.yaml.gotmpl
> [!warning]
>
> [!important]
Rclone namespaces is now added if sync or restore is enabled. Previously it only looked at sync.
- Logs checks:
- Bug …
=> apps sc: apply rclone namespace if sync or restore is enabled

scripts/local-cluster.sh
> [!warning]
>
> [!important]
Noticed that checks for `CK8S_CONFIG_PATH` and `CK8S_PGP_FP` were missing from the local-cluster script. If the envs were missing, then commands could fail with unexpected results.
- Logs checks:
- Pod …
=> scripts: check for missing env variables in local-cluster script

helmfile.d/values/hnc/controller.yaml.gotmpl
> [!warning]
>
> [!important]
Encountered a templating issue when you had more than one namespace under `user.constraints` in which the namespaces were added to a [Gatekeeper mutation for adding restricted pod-security labels](https://github.com/elastisys/compliantkubernetes-apps/blob/v0.41.0/hel …
=> Fix constraint for HNC user namespaces

scripts/run-from-container.sh, tests/Dockerfile, tests/common/bats/ctr.bash, tests/common/bats/harbor.bash, tests/end-to-end/velero/backup-restore-sc.gen.bats, tests/end-to-end/velero/backup-restore-wc.gen.bats, tests/end-to-end/velero/backup-restore.bats.gotmpl, tests/end-to-end/velero/backup-restore.gen.bats, tests/end-to-end/velero/common.bash, tests/end-to-end/velero/resources/backup-spec-sc.yaml, tests/end-to-end/velero/resources/backup-spec-wc.yaml, tests/end-to-end/velero/resources/test-application.yaml, tests/end-to-end/velero/resources/test-namespace.yaml, tests/end-to-end/velero/user-app.bats
> [!warning]
>
> [!important]
- Fixes #1850 
Added all QA and Velero GOTOs so that I get feedback from both parties. Does the tests look correct, does the test fixes look correct, am I testing Velero correctly and does it cover everything we want tested with Velero?
Me and @aarnq talked offline …
=> Add Velero e2e tests

config/providers/azure/sc-config.yaml, config/sc-config.yaml, migration/v0.42/README.md, migration/v0.42/prepare/40-azure-sync-destination-type.sh
> [!warning]
>
> [!important]
Changed the default `objectStorage.sync.destinationType` to azure, for azure clusters. Having this default to s3 caused issues with network policies / update-ips for clusters that are only using azure storage.
Init and migration script tested, but I have not …
=> config: change default destination sync type to azure for azure

helmfile.d/values/grafana/grafana-user.yaml.gotmpl
> [!warning]
>
> [!important]
This ensures that the user-grafana pvc is backed up when using velero snapshot feature and the user-grafana pod is down.
- Logs checks: …
=> Fix: add label user-grafana pvc for velero

helmfile.d/values/grafana/grafana-user.yaml.gotmpl, migration/v0.42/apply/10-upgrade-grafana.sh, tests/Dockerfile, tests/end-to-end/grafana/datasources.cy.js
> [!warning]
>
> [!important]
Makes sure there is always a default datasource in grafana even with multiple WCs.
Fixes grafana datasource test to include all wc datasources.
- Logs checks:
- Network Policy …
=> Fix grafana datasources and tests for multi wc

helmfile.d/upstream/grafana/grafana/Chart.yaml, helmfile.d/upstream/grafana/grafana/README.md, helmfile.d/upstream/grafana/grafana/templates/_config.tpl, helmfile.d/upstream/grafana/grafana/templates/_pod.tpl, helmfile.d/upstream/grafana/grafana/templates/deployment.yaml, helmfile.d/upstream/grafana/grafana/values.yaml, helmfile.d/upstream/index.yaml
> [!warning]
>
> [!important]
Upgrades Grafana to `11.3.0` to fix CVE-2024-9264
This PR upgrades the Grafana chart to v8.5.9 which upgrades the Grafana image to `11.3.0` containing a critical severity fix for [CVE-2024-9264](https://grafana.com/blog/2024/10/17/grafana-security-release-critical-se …
=> Upgrade Grafana to 11.3.0 and chart to 8.5.9 to fix CVE-2024-9264

helmfile.d/values/hnc/controller.yaml.gotmpl
> [!warning]
>
> [!important]
Now unpropagatedAnnotations and managedNamespaceAnnotations can be specified as lists as originally intended.
...
Values set
```yaml
hnc:
managedNamespaceAnnotations:
- asd
- hej
```
Before:
```diff
+             - --managed-namespace-annotation=asd hej
```
Now: …
=> config: fix HNC config templating

.github/CODEOWNERS
> [!warning]
>
> [!important]
This is a first draft of adding codeowners to this repo.
There are probably some things that could be changed or something that was missed. Please at least look at your goto areas to see that they seem sensible. We would also appreciate comments on the skipped files …
=> all: adding codeowners

helmfile.d/charts/prometheus-alerts/files/rook-alerts.yaml
> [!warning]
>
> [!important]
...
- Fixes [#335](https://github.com/elastisys/ck8s-issue-tracker/issues/335)
- Logs checks:
- Bug checks:
=> apps: remove ceph node packet drops alert

config/schemas/config.yaml, config/schemas/secrets.yaml
> [!warning]
>
> [!important]
The <https://elastisys.io> website was recently rebranded to Welkin. Some part of that website are generated from Apps configuration documentation. Therefore this PR rebrands those part of Apps which end up on <https://elastisys.io>.
Note that, rebranding the source …
=> Rebrand to Welkin in configuration documentation

helmfile.d/charts/grafana-dashboards/files/welcome.md, helmfile.d/charts/opensearch/configurer/files/dashboards-resources/welcome.md
Just wanted to have some more eyes on the public facing changelog. [Here's](https://github.com/elastisys/compliantkubernetes-apps/blob/staging-0.42.0/changelog/0.42.md) the full changelog for reference
=> Add changelog for release v0.42.0

tests/end-to-end/velero/resources/backup-spec-sc.yaml, tests/end-to-end/velero/resources/backup-spec-wc.yaml, tests/end-to-end/velero/user-app.bats
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> tests: update velero e2e backup specs and enable user app test

.pre-commit-config.yaml, config/schemas/README.md
> [!warning]
>
> [!important]
This adds guidelines on how to write schema.
Closes https://github.com/elastisys/ck8s-issue-tracker/issues/282
- Logs checks:
- Bug checks:
=> JSON schema contribution guide

helmfile.d/charts/networkpolicy/workload-cluster/templates/ingress-nginx/controller.yaml, helmfile.d/values/networkpolicy/workload-cluster.yaml.gotmpl
> [!warning]
>
> [!important]
...
- Fixes #
On clusters that didn't use host port for nginx, the ingress to nginx health didn't always work (If the request was bounced between nodes). This fixes that.
- Logs checks: …
=> apps wc: Fixed network policy to always allow ingress probe

scripts/clean-sc.sh, scripts/clean-wc.sh
> [!warning]
>
> [!important]
If cluster admin RBAC does not exist besides the one created with the `admin-rbac` chart part of apps, the clean scripts will not complete since the cluster user might not have permissions anymore:
```console
Error from server (Forbidden): …
```
=> Delete admin-rbac last in clean scripts

helmfile.d/charts/prometheus-alerts/files/thanos.yaml
> [!warning]
>
> [!important]
We have noticed that every 2nd week there are some jobs in thanos that will cause the 99th percentile latency to spike for storegateway for ~1 day. This does not seem to have any significant impact on the performance for other thanos components and their queries. …
=> apps sc: increase threshold for thanosobjstore latency alert

bin/diagnostics.bash, tests/end-to-end/general/bin-diagnostics.bats
> [!warning]
>
> [!important]
The diagnostics script now assumes to retrieve GPG keys from a file `$CK8S_CONFIG_PATH/diagnostics_receiver.gpg` if the `CK8S_PGP_FP` environment variable is not set.
Want to simplify the usage of the diagnostics script, the script will now by default import GPG …
=> Use file with GPG keys for diagnostics script and other improvements

config/sc-config.yaml, config/schemas/config.yaml, helmfile.d/charts/harbor/harbor-backup/values.yaml, helmfile.d/values/harbor/harbor-backup.yaml.gotmpl
> [!warning]
>
> [!important]
Default harbor backup schedule moved to after defaut velero schedule. This should ensure that images needed for resources in velero backup are present in harbor backup.
Also made the schedule configurable.
- …
=> config: move harbor backup schedule and make it configurable

helmfile.d/values/falco/falco-common.yaml.gotmpl
> [!warning]
>
> [!important]
Based on [this internal product management discussion](https://github.com/elastisys/ck8s-arch/issues/235).
This PR drops a few falco rules and removes some of our special modifications to those rules.
Dropping these rules since they are a relatively weak indication …
=> apps: dropping some falco rules

helmfile.d/charts/prometheus-alerts/templates/alerts/cluster-capacity-management-alerts.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/general.rules.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/kube-state-metrics.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/kubernetes-apps.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/kubernetes-resources.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/kubernetes-storage.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/kubernetes-system-apiserver.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/kubernetes-system-kube-proxy.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/kubernetes-system-kubelet.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/kubernetes-system.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/node-exporter.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/node-network.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/prometheus-operator.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/prometheus.yaml, helmfile.d/charts/prometheus-alerts/values.yaml
> [!warning]
>
> [!important]
The runbook_url for some officical prometheus alerts are missing or miscofigured, this is mainly due to the missing `.Values.defaultRules.runbookUrl` value in prometheus `values.yaml` file, as well as missing the alert categories in the urls.
- Fixes #1941
Some …
=> Fix runbook url for official prometheus alerts

bin/ck8s
> [!warning]
>
> [!important]
When trying to run `ck8s ops` commands from main branch, all I got was the `ops` usage:
```console
➜ ./bin/ck8s ops helmfile wc -l app=prometheus -i apply
Usage: kubectl <wc|sc> ...
kubecolor <wc|sc> ...
helm <wc|sc> ...
helmfile <wc|sc> ...
```
Seems like some …
=> Fix ck8s ops commands after refactor

helmfile.d/values/gatekeeper/templates.yaml.gotmpl, helmfile.d/values/thanos/query.yaml.gotmpl, helmfile.d/values/thanos/receiver.yaml.gotmpl, helmfile.d/values/velero-sc.yaml.gotmpl, helmfile.d/values/velero-wc.yaml.gotmpl, images/README.md
> [!warning]
>
> [!important]
This mirrors the Bitnami images used by Apps to ensure availability after their policy change is in effect starting the 7th.
I should note that this upgrades kubectl used by gatekeeper templates wait, as it was left on 1.25.
- Fixes …
=> apps: Mirror Bitnami images

helmfile.d/values/velero-sc.yaml.gotmpl, helmfile.d/values/velero-wc.yaml.gotmpl
> [!warning]
>
> [!important]
Tried deploying Velero with `uploaderType=kopia` and `useVolumeSnapshots=false` and ran into this error when attempting to create a backup:
```console
time="2024-12-23T10:54:12Z" level=error msg="Error backing up item" …
```
=> Fix Velero templating for kopia uploaderType

changelog/0.42.md, helmfile.d/values/gatekeeper/templates.yaml.gotmpl, helmfile.d/values/thanos/query.yaml.gotmpl, helmfile.d/values/thanos/receiver.yaml.gotmpl, helmfile.d/values/velero-sc.yaml.gotmpl, helmfile.d/values/velero-wc.yaml.gotmpl, images/README.md
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Staging 0.42.1

helmfile.d/stacks/monitoring-prometheus.yaml.gotmpl, helmfile.d/values/kube-prometheus-stack-wc.yaml.gotmpl
> [!warning]
>
> [!important]
Noticed a bunch of error logs in my Cluster API workload cluster from kube-state-metrics pod:
```console
E1217 14:47:13.509297       1 reflector.go:158] "Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.31.2/tools/cache/reflector.go:243: Failed to watch …
```
=> Don't get Cluster API resource metrics in workload cluster

config/sc-config.yaml, config/schemas/config.yaml, helmfile.d/charts/rclone/templates/cronjobs.yaml, helmfile.d/charts/rclone/values.yaml, helmfile.d/values/rclone/restore.yaml.gotmpl, helmfile.d/values/rclone/sync.yaml.gotmpl, migration/v0.43/README.md, restore/harbor/README.md, restore/harbor/harbor-rclone-azure.yaml
> [!warning]
>
> [!important]
Harbor in azure puts image data at `<bucket-name>//docker/` instead of `<bucket-name>/docker/`. This causes issues both when restoring data to harbor in azure and when rclone is syncing from azure.
Restoring from s3 to azure:
When rcloning to azure from s3 rclone …
=> apps sc: add sub path and name suffix to rclone jobs, harbor restore support azure

helmfile.d/charts/prometheus-alerts/templates/alerts/opensearch.yaml
> [!warning]
>
> [!important]
This changes the index over size limit alert to only consider indices with a positive document rate over the last hour, meaning it will eventually stop alerting for indices that are inactive such as after a successful rollover.
I haven't had the time to test it yet. …
=> apps sc: Alert size over limit only on active indicies

config/common-config.yaml, config/schemas/config.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/cluster-capacity-management-alerts.yaml, helmfile.d/charts/prometheus-alerts/values.yaml, helmfile.d/values/prometheus-alerts-sc.yaml.gotmpl, helmfile.d/values/prometheus-user-alerts-wc.yaml.gotmpl, migration/v0.43/README.md, migration/v0.43/prepare/10-capacity-alerts.sh
> [!warning]
>
> [!important]
The resource request capacity management alerts have been reworked to target the `elastisys.io/node-group` label instead of being based on node name patterns. As such, any previous override config for `prometheus.capacityManagementAlerts.requestLimit` will be …
=> apps: use node-group label in node resource request alerts

config/schemas/config.yaml, config/wc-config.yaml, helmfile.d/charts/user-crds/templates/rolebinding.yaml, helmfile.d/charts/user-rbac/templates/clusterrolebindings/user-crds.yaml, helmfile.d/stacks/rbac.yaml.gotmpl, helmfile.d/state.yaml, helmfile.d/values/dev-rbac-extra.yaml.gotmpl
> [!warning]
>
> [!important]
As an Platform Administrator, I want a declarative approach for providing additional RBAC to Application Developers without extending the current RBAC provided by Welkin. This can be used for special cases where an application developer might request a service that …
=> Add extra Application Developer RBAC config

helmfile.d/charts/prometheus-alerts/CHANGELOG.md, helmfile.d/charts/prometheus-alerts/templates/alerts/alertmanager.rules.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/kube-state-metrics.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/kubernetes-resources.yaml, helmfile.d/values/kube-prometheus-stack-sc.yaml.gotmpl, helmfile.d/values/kube-prometheus-stack-wc.yaml.gotmpl, helmfile.d/values/networkpolicies/common/prometheus.yaml.gotmpl
> [!warning]
>
> [!important]
Was looking through some of the alerts and when comparing them to upstream noticed some deviations:
- Some expressions in our alerts are not computer per cluster which is what we want. 
- Noticed that the alertmanager alerts we have did not have the `runbookURL` …
=> Fixes and improvements to kube-stack-prometheus alerts

tests/common/bats/gpg.bash, tests/end-to-end/grafana/authentication.cy.js, tests/end-to-end/grafana/dashboards.cy.js, tests/end-to-end/grafana/datasources.cy.js, tests/end-to-end/opensearch/authentication.cy.js, tests/end-to-end/opensearch/dashboards.cy.js
> [!warning]
>
> [!important]
The end-to-end tests for Grafana failed as they look for `Compliant Kubernetes` in the welcome dashboard, which has been updated to use `Welkin`:
```console
ok 1 grafana admin authentication can login via static admin user
ok 2 grafana admin authentication can login …
```
=> Replace ck8s with Welkin in tests

config/schemas/config.yaml
It seems like jsonschema2md ironically doesn't validate the schema of the input it receives. :)
It fails horribly with:
```
file:///home/cklein/elastisys/welkin/node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:697
...schema[keyword`examples`].map((example) => paragraph(code('yaml', yaml.dump(example, undefined, 2)))),
^
TypeError: schema[keyword].map is not a function or its return value is not iterable
at makeexamples (file:///home/cklein/elastisys/welkin/node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:697:38)
at file:///home/cklein/elastisys/welkin/node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:762:14
at Array.map (<anonymous>)
at makeproplist (file:///home/cklein/elastisys/welkin/node_modules/@adobe/jsonschema2md/lib/markdownBuilder.js:750:54)
at …
```
=> Fix config schema

config/schemas/config.yaml, config/wc-config.yaml, helmfile.d/values/hnc/controller.yaml.gotmpl, migration/v0.43/README.md, migration/v0.43/prepare/20-hnc-config.sh
> [!warning]
>
> [!important]
The `hnc.excludedNamespaces` configuration option has been removed, you can use `hnc.excludedExtraNamespaces` if you need additional excluded namespaces.
...
- Fixes #
- Logs checks: …
=> apps wc: exclude capi namespaces from hnc

helmfile.d/charts/grafana-label-enforcer/Chart.yaml, helmfile.d/charts/grafana-label-enforcer/templates/deployment.yaml, helmfile.d/charts/grafana-label-enforcer/values.yaml
> [!warning]
>
> [!important]
This component was using an `latest`-like tag which is against our policy.
It also stopped being updated somewhere between v0.5.0 and v0.6.0.
Also make image configurable via values.
- Part of Goto Monitoring
Running a query like `count by (tenant_id) …
=> apps: Update prometheus-label-enforcer to v0.11.0

bin/update-ips.bash, tests/unit/general/bin-update-ips.bats
> [!warning]
>
> [!important]
Allow update-ips to complete even if DNS records are not setup yet.
Needed for PR https://github.com/elastisys/compliantkubernetes-apps/pull/2364 to make any sense.
- Logs checks: …
=> Allow update-ips to finish when no DNS records exists

helmfile.d/charts/prometheus-alerts/templates/alerts/cluster-capacity-management-alerts.yaml
> [!warning]
>
> [!important]
Got alerts firing for new cluster with node-group labels. Saw some alerts had hardcoded values in their expression. This PR fixes this so that the trigger condition in the alert expression uses the templated values.
- Fixes # …
=> Fix node-groups capacity alerts templating

bin/ck8s, bin/common.bash
> [!warning]
>
> [!important]
This reduces the amount of output when the config is validated on load while running other commands by hiding the values that fail schema validation, which tends to become repetitive and overly verbose.
If you run `ck8s validate`, you are probably more interested in …
=> Only show values conflicting with schema when explicitly running validate

config/schemas/secrets.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/kubernetes-apps.yaml, migration/template/README.md
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> docs: small documentation fixes

config/sc-config.yaml, config/schemas/config.yaml, helmfile.d/values/thanos/receiver.yaml.gotmpl
> [!warning]
>
> [!important]
Not having these variables is stopping us from performing some tests, so I've added these variables so people can work on using different hashrings algorithm.
- Fixes #
- Logs checks:
- PodSecurityPolicy …
=> apps-sc: expose thanos receiveDistributor configs

helmfile.d/upstream/index.yaml, helmfile.d/upstream/kubereboot/kured/Chart.yaml, helmfile.d/upstream/kubereboot/kured/README.md, helmfile.d/values/kured.yaml.gotmpl, helmfile.d/values/podsecuritypolicies/common/kured.yaml.gotmpl
> [!warning]
>
> [!important]
Updates the kured version.
Also changes the reboot method to "signal". This allows us to make the pod not run with privileged.
- Logs checks:
- Audit …
=> apps sc: upgrade kured to 1.16.2 and switch reboot method to signal

changelog/0.43.md, config/sc-config.yaml, config/schemas/config.yaml, helmfile.d/values/thanos/receiver.yaml.gotmpl
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Port 0.43.0

helmfile.d/charts/node-local-dns/templates/node-local-dns.yaml
> [!warning]
>
> [!important]
To keep the version from not falling to far behind I upgraded it.
Included some vulnerability fixes.
Also the upstream had dropped privileged in favor of just NET_ADMIN cap, so I adapted this. 
- Fixes #
- …
=> apps: Upgraded node local dns to v1.25.0 and dropped priviledged

config/common-config.yaml, config/schemas/config.yaml, helmfile.d/charts/gatekeeper/constraints/templates/disallow-localhost-seccomp/constraint.yaml, helmfile.d/charts/gatekeeper/constraints/templates/prevent-accidental-deletion/constraint.yaml, helmfile.d/charts/gatekeeper/constraints/values.yaml, helmfile.d/charts/gatekeeper/templates/policies/prevent-accidental-deletion.rego, helmfile.d/charts/gatekeeper/templates/policies/tests/prevent-accidental-deletion.rego, helmfile.d/charts/gatekeeper/templates/templates/prevent-accidental-deletion/template.yaml, helmfile.d/stacks/gatekeeper.yaml.gotmpl, helmfile.d/values/gatekeeper/constraints.yaml.gotmpl, helmfile.d/values/gatekeeper/gatekeeper.yaml.gotmpl, helmfile.d/values/gatekeeper/templates.yaml.gotmpl, helmfile.d/values/userCRDs/userCRDs.yaml.gotmpl, migration/v0.44/apply/20-gatekeeper-crds.sh, migration/v0.44/apply/80-apply.sh
> [!warning]
>
> [!important]
Adds a new gatekeeper policy that protects the resources of kinds `Cluster`, `OpenStackCluster` and `AzureCluster` from deletion. To delete the resources one must add the annotation `elastisys.io/ok-to-delete=""`
Since we don't ever want to get into the situation …
=> apps: Safeguard to prevent accidental cluster deletion

helmfile.d/charts/prometheus-alerts/templates/alerts/kubernetes-apps.yaml
> [!warning]
>
> [!important]
Update the query for the `KubeContainerOOMKilled` alert so that it's able to fire immediately after pod creation.
- Fixes #2423 
The alert will now stay open for 30 minutes after being resolved.
- Logs …
=> Fix KubeContainerOOMKilled alert for newly created pods

config/sc-config.yaml, config/schemas/config.yaml, helmfile.d/values/harbor/harbor.yaml.gotmpl, migration/v0.44/README.md, migration/v0.44/prepare/20-jobservice-replicas.sh
> [!warning]
>
> [!important]
I saw that the Jobservice pods were using the cores replica key when it should be using its own for additional replicas so I fixed it in this PR.
...
- Fixes #
- Logs checks:
- …
=> apps sc: fix harbor jobservice replicas

config/sc-config.yaml, config/schemas/config.yaml, helmfile.d/values/kube-prometheus-stack-sc.yaml.gotmpl
> [!warning]
>
> [!important]
This enables us to add additional receivers for alertmanager via config. For example if you want to add another null receiver for some specific alerts.
- Logs checks:
- Network …
=> apps sc: Added possibility to add additional receivers for alertmanager

README.md
> [!warning]
>
> [!important]
Tries to improve the readme so that it is possible to install apps solely based on it.
Decided in https://github.com/elastisys/ck8s-arch/issues/215
- Logs checks:
- Network …
=> Improve readme steps for installation of apps

config/common-config.yaml, config/schemas/config.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/kubernetes-system-kubelet.yaml, helmfile.d/charts/prometheus-alerts/values.yaml, helmfile.d/values/kube-prometheus-stack-sc.yaml.gotmpl, helmfile.d/values/kube-prometheus-stack-wc.yaml.gotmpl, helmfile.d/values/prometheus-alerts-sc.yaml.gotmpl, helmfile.d/values/prometheus-user-alerts-wc.yaml.gotmpl
> [!warning]
>
> [!important]
This change should mitigate the chances of false firing the **LessKubeletsThanNodes** alerts during autoscaling process.
The old query checks if there's any kubelet job down.
The new query compare the number of running kubelet jobs and the total number of nodes in …
=> apps: change query expression for LessKubeletsThanNodes alerts

helmfile.d/charts/prometheus-alerts/templates/alerts/daily-checks.yaml
> [!warning]
>
> [!important]
When postgres is running with s3 monitoring it will add more metrics and thus count the postgres bucket size as ~2x.
This aims to fix that.
- Fixes #
- Logs checks:
- …
=> apps sc: Fixed s3 size alert to not double count postgres buckets

config/common-config.yaml, config/k8s-installers/capi/wc-config.yaml, config/schemas/config.yaml, helmfile.d/charts/gatekeeper/constraints/templates/reject-local-storage-empty-dir/constraint.yaml, helmfile.d/charts/gatekeeper/constraints/values.yaml, helmfile.d/charts/gatekeeper/templates/policies/reject-local-storage-empty-dir.rego, helmfile.d/charts/gatekeeper/templates/policies/tests/reject-local-storage-empty-dir.rego, helmfile.d/charts/gatekeeper/templates/templates/reject-local-storage-empty-dir/template.yaml, helmfile.d/values/gatekeeper/constraints.yaml.gotmpl
> [!warning]
>
> [!important]
A new guardrail is added that is enabled by default on ClusterAPI environments. It will by default warn but not deny usage of emptyDir storage, since this can stop cluster autoscaler from scaling down nodes. Read more on [this …
=> apps-sc: add policy to reject local storage emptydir

config/common-config.yaml, config/k8s-installers/capi/wc-config.yaml, config/schemas/config.yaml, helmfile.d/charts/gatekeeper/constraints/templates/reject-pod-without-controller/constraint.yaml, helmfile.d/charts/gatekeeper/constraints/values.yaml, helmfile.d/charts/gatekeeper/templates/policies/reject-pod-without-controller.rego, helmfile.d/charts/gatekeeper/templates/policies/tests/reject-pod-without-controller.rego, helmfile.d/charts/gatekeeper/templates/templates/reject-pod-without-controller/template.yaml, helmfile.d/values/gatekeeper/constraints.yaml.gotmpl
> [!warning]
>
> [!important]
A new guardrail is added that is enabled by default on ClusterAPI environments. It will by default warn but not deny usage of Pods without backing controllers, since this can stop cluster autoscaler from scaling down nodes. Read more on [this …
=> apps: gatekeeper policy to reject pods without controller

scripts/clean-sc.sh, scripts/clean-wc.sh
> [!warning]
>
> [!important]
Without this you would get this output when running `ck8s clean` on a non-local cluster:
```
Listing releases matching ^minio$
in /home/simon/git/elastisys/compliantkubernetes-apps/helmfile.d/state.yaml: command "/home/simon/bin/helm" exited with non-zero status: …
```
=> Only uninstall with local environment if local cluster exist

bin/update-ips.bash
> [!warning]
>
> [!important]
Currently if you run `ck8s update-ips both apply` and a diff is applied the command exits with a non-zero status. That is incorrect because the command did what it was supposed to do successfully.
@Xartos added you as a reviewer well since this has been the behavior …
=> Make update-ips apply exit 0 even if it has applied diffs

bin/ck8s, bin/update-ips.bash, tests/common/bats/update-ips.bash, tests/unit/general/bin-update-ips-swift.bats, tests/unit/general/bin-update-ips.bats, tests/unit/general/resources/zero-diff.out
> [!warning]
>
> [!important]
Adds support for IPv6 to update-ips script.
- Fixes #2342 
- Logs checks:
- Bug checks:
=> add ipv6 support to update-ips

changelog/0.42.md, changelog/0.43.md, changelog/0.44.md
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Port patch changelogs v0.42.2, v0.43.1, v0.44.1

config/flavors/air-gapped/common-config.yaml, config/flavors/prod/common-config.yaml, config/k8s-installers/capi/common-config.yaml, config/providers/elastx/common-config.yaml, config/providers/elastx/sc-config.yaml, config/providers/elastx/wc-config.yaml, config/providers/safespring/common-config.yaml, config/providers/upcloud/sc-config.yaml, config/sc-config.yaml, helmfile.d/values/opensearch/client.yaml.gotmpl, helmfile.d/values/opensearch/data.yaml.gotmpl, helmfile.d/values/opensearch/master.yaml.gotmpl, migration/v0.46/README.md, migration/v0.46/apply/00-template.sh, migration/v0.46/apply/80-apply.sh, migration/v0.46/prepare/00-template.sh, migration/v0.46/prepare/40-preserve-current-os-setup.sh, migration/v0.46/prepare/50-init.sh
> [!warning]
>
> [!important]
Default Opensearch setup has been changed. Opensearch is now configured to use 3 master nodes, 0 data nodes and 0 client nodes by default. There's no easy migration path for the new configuration, if the old default Opensearch setup is used it should be added to the …
=> Revise default config

config/sc-config.yaml, config/schemas/config.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/harbor.yaml, helmfile.d/charts/prometheus-alerts/values.yaml, helmfile.d/values/prometheus-alerts-runbook-urls.yaml.gotmpl, migration/v0.46/README.md, migration/v0.46/prepare/10-harbor-alerts.sh
> [!warning]
>
> [!important]
As part of some recent discussions we have concluded that the harbor alerts for number of artifacts and total size of artifacts have been to strict. This PR both increases the thresholds and updates the wording of the alert to make it clear that this is not a strict …
=> apps sc: update harbor storage alerts

config/common-config.yaml, config/schemas/config.yaml, helmfile.d/values/ingress-nginx.yaml.gotmpl
> [!warning]
>
> [!important]
Had an issue in an environment that required us to configure `extraEnvs` for the `ingress-nginx-controller`, thought it be a good idea to expose this in the Welkin templating.
But I also understand if we do not want to expose more "snowflake" config, so let me know …
=> Add extraEnvs templating for ingress-nginx-controller 

pipeline/test/services/service-cluster/testOpensearch.sh
> [!warning]
>
> [!important]
Had configured a role mapping for OpenSearch with a name containing hyphens, this caused the `ck8s test sc opensearch` tests to fail:
```console
checking user roles mappings ... jq: error: access/0 is not defined at <top-level>, line 1:
.user-log-access         
jq: …
```
=> Fix OpenSearch tests with mapping names containing hyphens

scripts/local-cluster.sh, tests/bats.lib.bash, tests/common/bats/local-cluster.bash, tests/common/exec.bash, tests/integration/general/local-clusters.bats, tests/integration/harbor/setup_suite.bash
> [!warning]
>
> [!important]
Makes the test harness work with the new additions to local clusters.
Had to change some of the logic in setup node-local-dns, as else it was required to have both clusters even if you only need to test on SC.
- Metrics …
=> tests: Update for sc and wc local clusters

config/common-config.yaml, config/schemas/config.yaml, helmfile.d/values/kube-prometheus-stack-sc.yaml.gotmpl, helmfile.d/values/kube-prometheus-stack-wc.yaml.gotmpl
> [!warning]
>
> [!important]
Had an issue when upgrading Prometheus in an environment which was solved by increasing the scrapeTimeout for the Prometheus Node Exporter ServiceMonitor.
- Fixes #
- Logs checks: …
=> Add Prometheus Node Exporter ServiceMonitor scrapeTimeout override

config/schemas/config.yaml
> [!warning]
>
> [!important]
This reverts fixes to the schema as it for some reason breaks jsonschema2md.
What happens is that the `$ref`s seem to hijack the origin schema object instead of generating their own pages (as all other `$ref`s do), and this causes [mkdocs to …
=> config: Revert schema fixes

config/common-config.yaml, config/providers/aws/wc-config.yaml, config/providers/azure/wc-config.yaml, config/providers/elastx/wc-config.yaml, config/providers/openstack/wc-config.yaml, config/schemas/config.yaml, config/wc-config.yaml, helmfile.d/values/ingress-nginx.yaml.gotmpl
> [!warning]
>
> [!important]
Exposes internal ingress-nginx load balancer config
It's possible to configure it for multiple providers
- Fixes #2504
- Logs checks:
- …
=> apps wc: expose internal ingress-nginx LB config

bin/kubeconfig.bash
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Fix kubeconfig dev error message

bin/kubeconfig.bash
> [!warning]
>
> [!important]
Normally the cluster name in the config and the kubecofig are the same but for local clusters it's prefixed with kind-.
- Logs checks:
- …
=> Get cluster from kubeconfig when creating dev kubeconfig

config/sc-config.yaml, config/schemas/config.yaml, helmfile.d/values/thanos/receiver.yaml.gotmpl
> [!warning]
>
> [!important]
This PR adds the default concurrency for the thanos receiver distributor configuration.
...
- Fixes #
https://github.com/elastisys/compliantkubernetes-apps/issues/2099
- Logs checks:
- PodSecurityPolicy …
=> apps sc: default Limitconfig for thanos

bin/ck8s, bin/ops.bash, completion/fish
> [!warning]
>
> [!important]
implement shell completion for the fish shell
- Logs checks:
- Bug checks:
=> add initial fish completion

config/common-config.yaml, config/schemas/config.yaml, config/wc-config.yaml, helmfile.d/values/ingress-nginx.yaml.gotmpl, tests/unit/general/bin-conditional-set-me.bats
> [!warning]
>
> [!important]
The conditional configuration validation for Ingress-NGINX is now within the schema rather than done through conditional set-me's.
This flattens the ingress-nginx service schema so that the generated documentation …
=> config: Flatten ingress-nginx schema

tests/Dockerfile, tests/common/bats/gpg.bash
> [!warning]
>
> [!important]
Small dependency of #2521 that just improves our Bats set-up:
- test key generation is set to the minimum possible length to prevent GPG from churning on big random integer generation
- bats-core is upgraded to 1.11.1 for getting our hands on dynamic test …
=> Bats love 🦇

scripts/local-cluster.sh, scripts/local-clusters/configs/partial/common-self-signed.yaml
> [!warning]
>
> [!important]
Adds option to enable self-signed certificates from start with local clusters.
(This is essentially how the tests do it, except this even disables Let's Encrypt.)
This makes it so the resulting configs _have no set-mes_.
```sh
./scripts/local-cluster.sh config local …
```
=> scripts: Add option to enable self-signed from start

scripts/run-from-container.sh, tests/Dockerfile
> [!warning]
>
> [!important]
This adds a bind mount to the DBus session bus into end-to-end tests, and adds flatpak-xdg-open as the provider for xdg-open within the tests container.
This allows it to open links in the web browser of the host, for example to prompt for kube-login.
Set a config …
=> tests: Enable xdg-open from end-to-end tests

helmfile.d/values/gpu-operator.yaml.gotmpl
> [!warning]
>
> [!important]
The `operator` top-level mapping was declared twice in `values/gpu-operator.yaml.gotmpl`, causing all values in the first declaration to be ignored
Resources, tolerations and affinity are currently affected, but this also blocks the implementation of configurable …
=> fix: later declaration of "operator" map overwrites all values in first

bin/common.bash, tests/bats.lib.bash, tests/unit/templates/releases.bash
> [!warning]
>
> [!important]
Removes a for loop that added 100 seconds for some tests on my machine.
Removes check tools for tests that adds 0.5-1 seconds per bin script invocation.
Simplifies a sort unique that could be done in yq before it.
- Metrics …
=> tests: Optimisations

config/sc-config.yaml, config/schemas/config.yaml
> [!warning]
>
> [!important]
Made disk performance alerts less sensitive, they should only fire if action is required
- Logs checks:
- Bug checks:
=> apps sc: make disk performance alerts less sensitive

bin/apply.bash, bin/common.bash, bin/test.bash, bin/upgrade.bash
> [!warning]
>
> [!important]
Part of https://github.com/elastisys/ck8s-issue-tracker/issues/429
- Logs checks:
- Bug checks:
=> Ensure that the node-group label is set on all nodes

tests/end-to-end/apps/status.bats, tests/end-to-end/cert-manager/status.bats, tests/end-to-end/hnc/status.bats, tests/end-to-end/ingress/status.bats, tests/end-to-end/opensearch/status.bats
> [!warning]
>
> [!important]
Expands the end-to-end test suit with wrappers that run the status checks through `./bin/ck8s test`.
Components are wrapped individually.
- Fixes https://github.com/elastisys/ck8s-issue-tracker/issues/446
- …
=> tests: add end-to-end wrappers for ck8s test components

bin/apply.bash, bin/ck8s, bin/common.bash, bin/init.bash, bin/upgrade.bash, config/schemas/config.yaml, scripts/local-clusters/configs/secrets.yaml, scripts/migration/lib.sh, tests/common/bats/env.bash, tests/common/bats/git-version.bash, tests/integration/general/local-clusters.bats, tests/integration/general/migration/v0.42/apply/00-template.sh, tests/integration/general/migration/v0.42/apply/80-apply.sh, tests/integration/general/migration/v0.42/prepare/00-template.sh, tests/integration/general/migration/v0.42/prepare/50-init.sh, tests/integration/general/migration/v0.43/apply/00-template.sh, tests/integration/general/migration/v0.43/apply/80-apply.sh, tests/integration/general/migration/v0.43/prepare/00-template.sh, tests/integration/general/migration/v0.43/prepare/50-init.sh, tests/integration/general/setup_suite.bash, tests/integration/general/upgrade.bats, tests/unit/general/bin-version.bats
> [!warning]
>
> [!important]
There are now safeguards in place to ensure `ck8s upgrade prepare` and `ck8s upgrade apply` are run in the correct order.
There's also a new `ck8s version` command that reports the verison of apps in the config and cluster(s).
```mermaid
flowchart TD;
init[ck8s …
```
=> Incremental version checks during migration

bin/update-ips.bash
> [!warning]
>
> [!important]
Fixes miss in https://github.com/elastisys/compliantkubernetes-apps/pull/2556
The dangers of setting the KUBECONFIG environment variable manually. :smile: 
- Logs checks:
- …
=> Fix update-ips

bin/common.bash
> [!warning]
>
> [!important]
As we are only interested in the client version we should use the flag to not trigger authentication to server.
- Fixes #
- Logs checks:
- …
=> Check Kubectl client version only to not prompt

config/sc-config.yaml, config/schemas/README.md, config/schemas/config.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/daily-checks.yaml, helmfile.d/charts/prometheus-alerts/values.yaml, helmfile.d/values/prometheus-alerts-sc.yaml.gotmpl
> [!warning]
>
> [!important]
...
- Fixes #2543 
* Would be happy if anyone got any suggestions/improvements to the schema titles/descriptions for the new buckets section.
* I changed how the S3 Bucket Alert expression works in general because of how it was leaving "gaps" of data when you query …
=> apps sc: S3 quota alerts per bucket

config/schemas/secrets.yaml, config/secrets.yaml, helmfile.d/values/dex.yaml.gotmpl, tests/bats.lib.bash, tests/cypress.config.js, tests/cypress.support.js, tests/end-to-end/kubernetes/allow-root-nginx.yaml, tests/end-to-end/kubernetes/authentication-admin.cy.js, tests/end-to-end/kubernetes/authentication-admin.gen.bats, tests/end-to-end/kubernetes/authentication-dev.cy.js, tests/end-to-end/kubernetes/authentication-dev.gen.bats, tests/end-to-end/kubernetes/bin-access.bats
> [!warning]
>
> [!important]
Adds end-to-end tests for Kubernetes access.
There are a few things of note here:
- ~~I implemented a cypress test for doing a static e-mail login, and I tried to do the same for "cluster admin" login but I'm not sure it will be possible. Since cypress doesn't have …
=> add kubernetes access tests

config/common-config.yaml, config/schemas/config.yaml, helmfile.d/charts/cilium-default-deny/.helmignore, helmfile.d/charts/cilium-default-deny/Chart.yaml, helmfile.d/charts/cilium-default-deny/README.md, helmfile.d/charts/cilium-default-deny/templates/clusterwidenetworkpolicy.yaml, helmfile.d/charts/grafana-dashboards/dashboards/cilium-dashboard.json, helmfile.d/charts/grafana-dashboards/dashboards/cilium-operator-dashboard.json, helmfile.d/charts/grafana-dashboards/dashboards/hubble-dashboard.json, helmfile.d/charts/grafana-dashboards/dashboards/hubble-dns-namespace.json, helmfile.d/charts/grafana-dashboards/dashboards/hubble-l7-http-metrics-by-workload.json, helmfile.d/charts/grafana-dashboards/dashboards/hubble-network-overview-namespace.json, helmfile.d/stacks/calico.yaml.gotmpl, helmfile.d/stacks/cilium.yaml.gotmpl, helmfile.d/state.yaml.gotmpl, helmfile.d/values/calico-accountant.yaml.gotmpl, helmfile.d/values/cilium-default-deny.yaml.gotmpl, helmfile.d/values/falco/falco-common.yaml.gotmpl, migration/v0.48/README.md, migration/v0.48/apply/00-template.sh, migration/v0.48/apply/80-apply.sh, migration/v0.48/prepare/00-template.sh, migration/v0.48/prepare/10-move-calico-config.sh, migration/v0.48/prepare/50-init.sh
> [!warning]
>
> [!important]
This added some config in apps so calico charts won't get installed if cilium is enabled.
Add all cilium dashboards for monitoring. Now they are in default format as provided in the upstream, need to be trimmed in later cilium support tasks.
I also add a …
=> Add cilium support for apps

migration/v0.47/apply/30-alertmanager.sh
> [!warning]
>
> [!important]
In v0.47.0 alertmanager migration scripts are modified to create temp file in /tmp folder. 
...
- Fixes #2578 
- Logs checks:
- Falco …
=> apps: alertmanager migration write to tmp

bin/update-ips.bash, tests/common/bats/update-ips.bash, tests/unit/general/bin-update-ips-rclone.bats, tests/unit/general/bin-update-ips-subnet.bats, tests/unit/general/bin-update-ips.bats
> [!warning]
>
> [!important]
The `get_tunnel_ips` function will abort the `update-ips` script when the cluster uses Cilium as its network plugin as it won't be able to find any calico tunneling IPs. 
This PR addresses the issue by first checking if we have the `CiliumNode` CRD installed (which …
=> cilium: include internal cilium IPs in the update-ips flow

config/sc-config.yaml
> [!warning]
>
> [!important]
This PR increases the memory limit for the Trivy operators scanner in sc from the standard upsteam value of 500Mi into 850Mi, as I have seen a pattern of it going OOM with the standard limit in sc.
...
- Fixes #
- Metrics …
=> apps sc: increase trivy scanners memory

config/sc-config.yaml, helmfile.d/lists/images.yaml, helmfile.d/upstream/README.md, helmfile.d/upstream/grafana/grafana/Chart.yaml, helmfile.d/upstream/grafana/grafana/README.md, helmfile.d/upstream/grafana/grafana/ci/with-sidecars-envvaluefrom-values.yaml, helmfile.d/upstream/grafana/grafana/templates/_config.tpl, helmfile.d/upstream/grafana/grafana/templates/_pod.tpl, helmfile.d/upstream/grafana/grafana/templates/extra-manifests.yaml, helmfile.d/upstream/grafana/grafana/templates/hpa.yaml, helmfile.d/upstream/grafana/grafana/templates/image-renderer-deployment.yaml, helmfile.d/upstream/grafana/grafana/templates/image-renderer-service.yaml, helmfile.d/upstream/grafana/grafana/templates/image-renderer-servicemonitor.yaml, helmfile.d/upstream/grafana/grafana/templates/poddisruptionbudget.yaml, helmfile.d/upstream/grafana/grafana/templates/route.yaml, helmfile.d/upstream/grafana/grafana/templates/statefulset.yaml, helmfile.d/upstream/grafana/grafana/templates/tests/test.yaml, helmfile.d/upstream/grafana/grafana/values.yaml, helmfile.d/upstream/index.yaml, helmfile.d/values/grafana/grafana-dashboards.yaml.gotmpl, tests/end-to-end/grafana/dashboards-discovery.bats, tests/end-to-end/grafana/datasources.cy.js
> [!warning]
>
> [!important]
Grafana was upgraded to new major version 12, this comes some new features such as the ["Drilldown" page](https://grafana.com/blog/2025/02/20/grafana-drilldown-apps-the-improved-queryless-experience-formerly-known-as-the-explore-apps/). Please refer to the upstream …
=> Upgrade Grafana chart to 9.2.10

helmfile.d/charts/gatekeeper/constraints/templates/restrict-pod-disruption-budgets/constraint.yaml
> [!warning]
>
> [!important]
In environments on apps v0.47, with the addition of new Gatekeeper constraint policy for PDBs, nodes running rook-ceph-osd pods cannot be properly drained (e.g. for Kured reboot or Kubespray upgrades), see the rook-ceph-operator logs:
```
2025-07-17 07:48:02.606197 …
```
=> Exclude rook-ceph namespace in pdb constraint policy

scripts/run-from-container.sh, tests/README.md, tests/bats.lib.bash
> [!warning]
>
> [!important]
You can now set the `CK8S_HEADED_CYPRESS=true` environment variable to tell the cypress tests to run in "headed" mode, which will show both the test interface and the testing browser.
NOTE: This works for running tests via `make` or `bats` but not directly through …
=> feat: tell cypress to run in "headed" mode

bin/update-ips.bash
> [!warning]
>
> [!important]
When running `update-ips` on Elastx where Swift buckets are used, I ran into this issue:
```console
jq: error (at <stdin>:2): Cannot iterate over null (null)
/compliantkubernetes-apps/bin/update-ips.bash: line 277: os_token: unbound variable
```
It was due to me …
=> bin: add error message for misconfigured swift config in update-ips

tests/README.md, tests/end-to-end/opa-gatekeeper/policies.bats
> [!warning]
>
> [!important]
Updates the OPA Gatekeeper tests.
Removes old Harbor code in favor of uploading the chart(OCI) and image to ghcr.io.
https://github.com/elastisys/welkin/pkgs/container/user-demo
https://github.com/elastisys/welkin/pkgs/container/welkin-user-demo
You have to add …
=> tests: update gatekeeper e2e

scripts/kubeproxy-wrapper.sh, tests/cypress.config.js, tests/cypress.support.js, tests/end-to-end/alertmanager/via-proxy.cy.js, tests/end-to-end/alertmanager/via-proxy.gen.bats, tests/end-to-end/kubernetes/authentication-admin.cy.js, tests/end-to-end/kubernetes/authentication-dev.cy.js, tests/end-to-end/prometheus/via-proxy.cy.js, tests/end-to-end/prometheus/via-proxy.gen.bats
> [!warning]
>
> [!important]
Adds support files and sample E2E tests for accessing proxy-able components such as Prometheus and Alertmanager.
- Fixes https://github.com/elastisys/ck8s-issue-tracker/issues/240
NOTE: this depends on the setup for access tests being done, so it has the [same …
=> E2E: kubectl proxy access tests for prometheus & alertmanager

helmfile.d/charts/gatekeeper/templates/policies/image-registry.rego, helmfile.d/charts/gatekeeper/templates/policies/tests/image-registries.rego, helmfile.d/charts/user-rbac/templates/clusterroles/user-admin.yaml
> [!warning]
>
> [!important]
This add new RBAC policies and opa policies to application developers have patch on pods/ephemeralcontainers in "", thus having the ability to run kubectl debug.
...
- Fixes #2422 
- 
- Logs checks:
- …
=> apps: added rbac and opa policies for allowing ephemeral containers

config/common-config.yaml
> [!warning]
>
> [!important]
Increase gatekeeper default memory limits. We added opa policies in v0.46 and upgrading to it caused gatekeeper pods to go OOM in multiple environments which made us add overrides. Increasing by 50 could be enough but i saw one environment where the usage had gone …
=> config: increase gatekeeper default memory limits

helmfile.d/values/networkpolicies/common/prometheus.yaml.gotmpl, helmfile.d/values/networkpolicies/service/alertmanager.yaml.gotmpl
…or kube proxy
> [!warning]
>
> [!important]
Fix on networkPolicies to allow ingress traffic from apiserver to alertmanager/prometheus for kube proxy on sc
- Logs checks:
- Audit …
=> Allow ingress traffic from apiserver to alertmanager/prometheus

tests/end-to-end/netpol/netpol.cy.js, tests/end-to-end/netpol/netpol.gen.bats
> [!warning]
>
> [!important]
Accesses metrics through the proxied Prometheus API endpoint and checks we're not dropping any packets to/from workloads due to missing network policies.
- Fixes https://github.com/elastisys/ck8s-issue-tracker/issues/241
```shell
make -C tests …
```
=> Add E2E tests for packets handled by network policies

tests/end-to-end/falco/alerts.cy.js, tests/end-to-end/falco/setup_suite.bash
> [!warning]
>
> [!important]
The OCD is strong today, found more nits in the main PR, though it's easier to go over them in a separate PR. 
Tried the test suite, works beautifully, just some troubles with idempotency (if namespace already exists, it will fail).
- Documentation …
=> Falco E2E nits

tests/end-to-end/opensearch/dashboards.cy.js, tests/end-to-end/opensearch/dashboards.gen.bats
> [!warning]
>
> [!important]
Removes the loop around `it`, defines each test case statically and extracts the common bits into a function. Should get rid of all the "Skipped" problems.
- Logs checks:
- …
=> Remove tests in a loop

.gitignore, REQUIREMENTS, roles/get-requirements.yaml, scripts/run-from-container.sh, tests/Dockerfile, tests/Makefile, tests/bats.lib.bash, tests/common/cypress/support.js, tests/common/exec.bash, tests/end-to-end/.bin/x-www-browser, tests/end-to-end/general/bin-diagnostics.bats, tests/end-to-end/grafana/dashboards-discovery.bats, tests/end-to-end/hnc/test-hnc.bats, tests/end-to-end/kubernetes/bin-access.bats, tests/end-to-end/opa-gatekeeper/policies.bats, tests/package-lock.json, tests/package.json
> [!warning]
>
> [!important]
Reminding people to go open "localhost:8000" in their browser if/when a test suite gets stuck is not exactly ergonomic. Additionally, if we want to run proxy tests for the MC, it will require authentication with admin users through the central Dex and we can't even …
=> Reliable socat popups for localhost:8000 during end-to-end-test runs

tests/Dockerfile, tests/bats.lib.bash, tests/common/bats/object-storage.bash, tests/end-to-end/fluentd/audit-sc.gen.bats, tests/end-to-end/fluentd/audit-wc.gen.bats, tests/end-to-end/fluentd/audit.bats.gotmpl, tests/end-to-end/fluentd/audit.gen.bats, tests/end-to-end/fluentd/sc-logs.bats, tests/end-to-end/log-manager/compaction-audit-sc.gen.bats, tests/end-to-end/log-manager/compaction-audit-wc.gen.bats, tests/end-to-end/log-manager/compaction-sc-logs.gen.bats, tests/end-to-end/log-manager/compaction.bats.gotmpl, tests/end-to-end/log-manager/compaction.gen.bats, tests/end-to-end/log-manager/retention-audit-sc.gen.bats, tests/end-to-end/log-manager/retention-audit-wc.gen.bats, tests/end-to-end/log-manager/retention-sc-logs.gen.bats, tests/end-to-end/log-manager/retention.bats.gotmpl, tests/end-to-end/log-manager/retention.gen.bats, tests/end-to-end/log-manager/setup_suite.bash
> [!warning]
>
> [!important]
This adds e2e tests for fluentd that verifies that audit and SC logs are forwarded to object storage as well as tests that verifies the log manager log compaction and retention.
- Fixes https://github.com/elastisys/ck8s-issue-tracker/issues/447
- …
=> Add fluentd and log-manager e2e tests

bin/common.bash
When the 'welkin-apps-meta' configmap exists, a stricter version check was enabled which prevented running 'apply' when
running on the main branch or any untagged git commit.
This bypasses the checks if .global.ck8sVersion is set to 'any' or a random untagged git commit has been checked out IFF
`ck8s init` has been run to explicitly mark that as the current version.
> [!warning]
>
> [!important]
> Breaking changes should be marked `kind/admin-change` …
=> bin: Do not block apply when version set to 'any' or git commit

tests/end-to-end/velero/backup-restore-sc.gen.bats, tests/end-to-end/velero/backup-restore-wc.gen.bats, tests/end-to-end/velero/backup-restore.bats.gotmpl, tests/end-to-end/velero/common.bash, tests/end-to-end/velero/resources/backup-spec-wc.yaml
> [!warning]
>
> [!important]
Decouples the `velero` end-to-end test suite assertions from "knowledge" that's specific to Devbox-based clusters. 
Let me explain: when making a cluster with Devbox, we add a few excluded namespaces to Velero's backup spec in the WC. These have leaked into the the …
=> Velero: set assertions for excluded namespaces

helmfile.d/charts/prometheus-alerts/templates/alerts/fluentd.yaml, helmfile.d/values/fluentd/forwarder-common.yaml.gotmpl, helmfile.d/values/prometheus-alerts-runbook-urls.yaml.gotmpl
> [!warning]
>
> [!important]
Added a new metric and alert for fluentd client errors
- Fixes #
The default `fluentd_output_status_num_errors` that we use for alerts doesn't include code 400 errors, as they are considered client errors. As a result, mapping conflicts can go unnoticed, which in …
=> Add fluentd client error metric and alert

tests/unit/upcloud/bin-update-ips-kubespray-prod.bats, tests/unit/upcloud/resources/sc-config/terraform.tfstate, tests/unit/upcloud/resources/wc-config/terraform.tfstate
> [!warning]
>
> [!important]
- Logs checks:
- Bug checks:
=> Fix update-ips UpCloud unit tests

scripts/backup-restore.sh
> [!warning]
>
> [!important]
Adds a backup and restore script that can target harbor, velero, opensearch and rclone to automatically perform QA steps of taking and restoring backups.
- Fixes https://github.com/elastisys/ck8s-issue-tracker/issues/448
Tested all backups and restores on cluster …
=> scripts: added backup and restore script for QA

tests/bats.lib.bash, tests/end-to-end/log-manager/compaction-audit-sc.gen.bats, tests/end-to-end/log-manager/compaction-audit-wc.gen.bats, tests/end-to-end/log-manager/compaction-sc-logs.gen.bats, tests/end-to-end/log-manager/compaction.bats.gotmpl, tests/end-to-end/log-manager/retention-audit-sc.gen.bats, tests/end-to-end/log-manager/retention-audit-wc.gen.bats, tests/end-to-end/log-manager/retention-sc-logs.gen.bats, tests/end-to-end/log-manager/retention.bats.gotmpl
Took a stab at cleaning up ongoing Jobs created by the compaction/retention Cronjobs, so we avoid the surprise of extra files popping up in the object storage during assertions.
=> test(log-manager): delete ongoing jobs during setup

tests/bats.lib.bash, tests/end-to-end/log-manager/compaction-audit-sc.gen.bats, tests/end-to-end/log-manager/compaction-audit-wc.gen.bats, tests/end-to-end/log-manager/compaction-sc-logs.gen.bats, tests/end-to-end/log-manager/compaction.bats.gotmpl, tests/end-to-end/log-manager/resources/calico-allow-all.yaml, tests/end-to-end/log-manager/retention-audit-sc.gen.bats, tests/end-to-end/log-manager/retention-audit-wc.gen.bats, tests/end-to-end/log-manager/retention-sc-logs.gen.bats, tests/end-to-end/log-manager/retention.bats.gotmpl, tests/end-to-end/log-manager/setup_suite.bash
> [!warning]
>
> [!important]
The main focus is avoiding a bad interaction between the `log-manager` test suite and the (in execution order following) `netpol` suite. 
Scaling down the `fluentd-aggregator` causes forwarder pods, as well as pods from the `monitoring` stack to try and contact it, …
=> Improve Log Manager E2E suite

tests/end-to-end/alertmanager/expected-alerts.cy.js
…bor-trivy
> [!warning]
>
> [!important]
Adds a few more tolerated alerts into the Alertmanager test suite to account for conditions in freshly installed clusters:
- `ThanosCompactHasNotRun` - since we don't control the cadence of Thanos compact jobs it can take a while for these to run and so …
=> Improve Alertmanager E2E suite

helmfile.d/charts/grafana-dashboards/dashboards/nginx-dashboard.json, tests/common/cypress/grafana.js, tests/common/cypress/support.js, tests/end-to-end/grafana/admin-promotion-ops.cy.js, tests/end-to-end/grafana/admin-promotion-ops.gen.bats, tests/end-to-end/grafana/admin-promotion-user.cy.js, tests/end-to-end/grafana/admin-promotion-user.gen.bats, tests/end-to-end/grafana/dashboards-admin.cy.js, tests/end-to-end/grafana/dashboards-dev.cy.js, tests/end-to-end/grafana/datasources.cy.js, tests/end-to-end/harbor/use-ui.cy.js, tests/end-to-end/opensearch/dashboards.cy.js, tests/integration/harbor/use-ui.cy.js
> [!warning]
>
> [!important]
Improves the Grafana E2E test suite in several aspects:
- use `.then()` instead of `.should()` in pre-condition checks to avoid unnecessary retries
- simplify demote/promote tests by using [chaining](https://docs.cypress.io/app/core-concepts/introduction-to-cypress#C …
=> Improve Grafana E2E test suite

tests/end-to-end/kubernetes/authentication-admin.cy.js, tests/end-to-end/kubernetes/authentication-dev.cy.js
> [!warning]
>
> [!important]
Fixes a small race condition between the `kubectlLogin` task finishing before the `:8000` port becomes open inside the test container, thus causing the `cy.visit('http://localhost:8000')` command to fail with a network error. We simply instruct Cypress to retry on …
=> Retry on network failure during access tests

helmfile.d/charts/calico-accountant/templates/service.yaml, helmfile.d/charts/grafana-dashboards/dashboards/README.md, helmfile.d/charts/grafana-dashboards/dashboards/cert-manager-mixin/cert-manager-dashboard.json, helmfile.d/charts/grafana-dashboards/dashboards/nginx-dashboard.json, helmfile.d/charts/tekton-pipelines/templates/controller/service-monitor.yaml, helmfile.d/values/cert-manager.yaml.gotmpl, helmfile.d/values/ingress-nginx.yaml.gotmpl, scripts/grafana-dashboards/configs/cert-manager-mixin/dashboards.jsonnet
The exported_namespace that was added by prometheus is kept for now But it is deprecated and will likely be removed in v0.52
> [!warning]
>
> [!important]
Prometheus by default overwrites the namespace label for metrics that already has a namespace label, to the namespace of the pod that was …
=> apps: make namespace label in metric refer to resource, not exporter

tests/Dockerfile, tests/unit/general/schema.bats
> [!warning]
>
> [!important]
With respect to the recent change in the Welkin repository(https://github.com/elastisys/welkin/blob/main/scripts/jsonschema2md.py), I updated the unit-test Dockerfile and the schema Bats test to use the new Python jsonschema2md.py script.
...
- Fixes #
- Change …
=> tests: changed unit test dockerfile and schema bats

scripts/S3/generate-s3cfg.sh
> [!warning]
>
> [!important]
This helps when doing development work, against a local cluster, that requires `ck8s s3cmd` to work.
- Logs checks:
- Bug …
=> Add support for generating s3cfg for proxied minio

scripts/qa/config.json.sample, scripts/qa/install_apps.py
> [!warning]
>
> [!important]
Tested to work with UpCloud, added:
- region and region endpoint for S3
- external loadbalancer support (and a bugfix for reconfigure IPs)
- made swift optional
Did some reshuffling to make it easier to go through for me at least but let me know if you disagree on …
=> scripts: QA install additions

tests/end-to-end/log-manager/resources/calico-allow-all.yaml
> [!warning]
>
> [!important]
The `GlobalNetworkPolicy` CRD (among others) is available under different api groups between Kubespray and CAPI installed clusters.
On a Kubespray cluster it's available under `crd.projectcalico.org/v1`.
```
globalnetworkpolicies  crd.projectcalico.org/v1  false …
```
=> fix: global network policy compatibility with kubespray

helmfile.d/charts/node-local-dns/templates/node-local-dns.yaml
> [!warning]
>
> [!important]
Node local DNS will now log non successful DNS requests
Given that currently node local DNS doesn't log anything other than application errors it's very silent and makes it hard to debug runtime issues.
This will hopefully not cause any significant increase in log …
=> apps both: Added logging for failing DNS requests

tests/bats.lib.bash
> [!warning]
>
`CronJob` names generated during test runs have UUID suffixes, but use an arbitrary cutoff point. This opens the possibility of cutting the name exactly after a `-` character, thus making the name invalid: 
```
[metadata.name: Invalid value: "audit-rar-spring-spray-v1-wc-retention-60a3a39b-19a5-412f-951a-": 
a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', 
and must start and end with an alphanumeric character 
(e.g. 'example.com', regex used for validation is …
```
=> fix: prevent cronjob name from ending in '-'

helmfile.d/lists/images.yaml, helmfile.d/stacks/opensearch.yaml.gotmpl, helmfile.d/state.yaml.gotmpl, helmfile.d/values/admin-namespaces-sc.yaml.gotmpl, helmfile.d/values/opensearch/common.yaml.gotmpl, helmfile.d/values/podsecuritypolicies/service/opensearch.yaml.gotmpl, migration/v0.49/README.md, migration/v0.49/apply/30-opensearch-initContainer.sh, tests/unit/general/resources/images-parametric-tests.json
> [!warning]
>
> [!important]
An initContainer running for OpenSearch which used to set the vm.max_map_count has been removed as new versions of Ubuntu sets it to a sufficiently high value by default. Environments running versions of Ubuntu older than 24 has to set this variable manually in some …
=> apps: Removal of previous work-around to increase vm.max_map_count for OpenSearch

scripts/qa/README.md, scripts/qa/boilerplate.py, scripts/qa/config.json.sample, scripts/qa/config.py, scripts/qa/install_apps.py, scripts/qa/secrets.json.sample, tests/common/exec.bash
> [!warning]
>
> [!important]
Implements an installer script for Apps that's as independent as possible from the "install" layer. 
NOTE: This script has been tested *only* on clusters installed with CAPI on the Elastx cloud provider. Should we want to extend support to other installers or cloud …
=> Apps install script for QA

config/common-config.yaml, config/schemas/config.yaml, helmfile.d/values/falco/falco-common.yaml.gotmpl, migration/v0.49/prepare/10-rename-falco-modern-bpf.sh, migration/v0.49/prepare/10-update-falco-driver.sh, tests/unit/general/images.bats
> [!warning]
>
> [!important]
The migration introduced in this PR will have two effects:
- environments that already use the `modern-bpf` driver will be updated to the correct `modern_ebpf` value
- environments using the `kmod` driver will be be updated to `modern_ebpf`
As the title suggests, …
=> falco: switch over to the 'modern_ebpf' driver by default

helmfile.d/charts/grafana-dashboards/dashboards/cilium-networkpolicy-dashboard.json, tests/end-to-end/grafana/dashboards-admin.cy.js, tests/end-to-end/grafana/dashboards-dev.cy.js
> [!warning]
>
> [!important]
Our Grafana end-to-end tests for checking the NetPol dashboard did not support the new Cilium specific dashboard.
This PR fixes these issues by checking which networkType is set in the end-to-end tests and based on that check the correct dashboard.
- Partially fixes …
=> Fix Grafana netpol dashboard tests for Cilium

helmfile.d/charts/prometheus-alerts/files/thanos.yaml
> [!warning]
>
> [!important]
Removing this alert as it has already been removed [upstream](https://github.com/thanos-io/thanos/pull/5824) due to being to noisy with the reasoning being:
> this alert tries to alert on cause and not the symptoms, making it more of an attempt to catch anomalies …
=> Remove noisy ThanosReceiveTrafficBelowThreshold alert

scripts/run-from-container.sh, tests/unit/general/chart-drift.bats
> [!warning]
>
> [!important]
These tests verify the integrity of the upstream charts.
- Logs checks:
- Bug checks:
=> tests: Add upstream chart drift tests

.github/CODEOWNERS, helmfile.d/values/prometheus-alerts-runbook-urls.yaml.gotmpl
> [!warning]
>
> [!important]
I was a bit too quick with merging https://github.com/elastisys/compliantkubernetes-apps/pull/2745 as I missed this templating that is used to configure the runbook for the removed alert. :face_exhaling: 
- Fixes #
- Metrics …
=> Remove ThanosReceiveTrafficBelowThreshold runbook templating

config/sc-config.yaml, config/schemas/config.yaml, helmfile.d/values/dex.yaml.gotmpl
> [!warning]
>
> [!important]
Adds templating and a default restricted Content-Security-Policy for Dex.
The CSP can be evaluated with https://csp-evaluator.withgoogle.com/.
For additional context, see arch topic here: https://github.com/elastisys/ck8s-arch/issues/303
- …
=> Add templating and default restricted CSP for Dex
