elastisys/compliantkubernetes-apps

- .github/pull_request_template.md
- .github/workflows/pipeline.yml
- .github/workflows/pre-commit.yml
- pipeline/README.md
- release/README.md
Changes references from a master branch to the main branch.
**Which issue this PR fixes**: -
**Checklist:**
> Target main branch instead of master

- WIP-CHANGELOG.md
- config/config/flavors/prod-sc.yaml
- config/config/sc-config.yaml
- helmfile/values/harbor.yaml.gotmpl
Makes harbor persistence size configurable
**Checklist:**
- re-run init and apply
> apps sc: Makes harbor storage size configurable

- WIP-CHANGELOG.md
- helmfile/01-applications.yaml
Updates the ingress helm chart to the new repo. It also bumps the version to 2.10 since the old version (1.26.2) does not exist in the new repo. Later versions (2.11 and onwards) are breaking the configuration. Deployment names and namespaces are NOT changed.
**Checklist:**
- [] is completely transparent, will not impact the workload in any way.
- Rerun apply …
> apps: Updating nginx ingress helm chart

- pipeline/test/services/workload-cluster/testUserRbac.sh
**What this PR does / why we need it**: Part of qa tests for v0.7.0. Simple fix for some rbac tests.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #17 
**Checklist:**
> pipeline: RBAC tests failed when usernames/namespaces had quotes

- WIP-CHANGELOG.md
- helmfile/values/fluentd-user.yaml.gotmpl
The user fluentd config used the wc fluentd values for tolerations, affinity and nodeselector.
This fix makes the user fluentd config use the already existing user fluentd values instead.
I do not have an environment up and have not tested this properly yet.
**Which issue this PR fixes**: -
**Checklist:**
> apps wc: Fix configuration error for user fluentd

- helmfile/charts/grafana-ops/dashboards/es-dashboard.json
- helmfile/charts/grafana-ops/dashboards/falco-dashboard.json
**What this PR does / why we need it**: Part of qa testing for v0.7.0. Adds datasources as an option in the elasticsearch and falco dashboards instead of having them hard-coded.
**Checklist:**
> apps sc: adds datasource option on dashboards

- bin/init.bash
- migration/v0.6.x-v0.7.x/migrate-issuer-config.sh
**What this PR does / why we need it**: This is part of the qa testing for the next release (0.7.0).
This changes the init script to never override any existing config values in a users config path. But it will still add any missing config values (that might have been added with a new feature).
This PR also adds back a migration script that is used in the migration to v0.7.0
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #16 
**Checklist:**
will not …
> Init script will not override config, plus missing migration script

- bin/init.bash
- config/config/sc-config.yaml
- helmfile/01-applications.yaml
- helmfile/values/opendistro-es.yaml.gotmpl
**What this PR does / why we need it**: Part of qa testing for v0.7.0. Fixes elasticsearch backups failing due to mismatching config in backup job and elasticsearch
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: #15 
**Checklist:**
> apps sc: fixes mismatched s3 config in elastic backup

- WIP-CHANGELOG.md
- bin/init.bash
- config/config/sc-config.yaml
- helmfile/values/harbor.yaml.gotmpl
**What this PR does / why we need it**: Part of qa testing for v0.7.0. Fixes the problem that images could not be pushed to Harbor on Safespring by adding config option (and correct defaults based on cloud provider). 
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #14 
**Checklist:**
> config: can now push images to Harbor on safespring

- WIP-CHANGELOG.md
- config/config/flavors/dev-sc.yaml
- config/config/flavors/prod-sc.yaml
**What this PR does / why we need it**: Part of qa testing for v0.7.0. This PR fixes a typo in the prod flavor regarding opsgenie heartbeat. Also removes some redundant config in dev flavor.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: #8 
**Checklist:**
> config: fixes typo in opsgenie hartbeat config

- WIP-CHANGELOG.md
- bin/common.bash
To deploy Compliant Kubernetes, one would generally include this repo as
a submodule, in which case tags might be unavailable. This commit allows
for the config to have the version 'latest', essentially meaning "I, the
operator, take responsibility to ensure the version of the config and
the version of ck8s match".
Does not really fix, but is related to #32 and #10.
**Checklist:**
- [NA] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset …
> bin: Assume 'latest' if version is unavailable

- WIP-CHANGELOG.md
- helmfile/01-applications.yaml
- helmfile/values/harbor.yaml.gotmpl
Upgrades Harbor to version 1.5.1.
This is required to access the `caBundleSecretName` Helm value, which is required to configure trust for a private CA.
Fixes #36 
Tested an upgrade which succeeded. `ck8s test sc` passes as well.
Have not done any more extensive validation of Harbor functionality.
**Checklist:**
> Upgrade Harbor chart to version 1.5.1

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- config/config/wc-config.yaml
- helmfile/01-applications.yaml
- helmfile/values/cert-manager.yaml.gotmpl
This commit gives one the option to configure pod assignment and
resources for cert-manager and it's "sub-components".
fixes: #43 
fixes #42 
**Checklist:**
> apps: Add config options for cert-manager

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- config/config/wc-config.yaml
- helmfile/values/velero.yaml.gotmpl
This commit fixes the slightly broken config
that had no effect. This also add some new configration options
with regards to pod placement. Also removes some default comments
and values from the values file for velero.
fixes #45  
fixes #46 
Tested backwards compatability by checking that there is no diff
```
git checkout main
helmfile -l app=velero apply
git checkout ol/fix-velero-conf;
Update my config
helmfile -l app=velero diff
```
**Checklist:** …
> apps: Fix and improve velero config

- pipeline/init-unit-tests.bash
- pipeline/init.bash
Since the pipeline is run from a different repository, it is required to be able to set the environment name outside the pipeline script.
**Which issue this PR fixes**: -
**Checklist:**
> Pipeline: allow setting env name outside script

- get-requirements.yaml
Ubuntu 20.04.1 LTS comes with s3cmd 2.0.2-1. Relax the requirement in
`get-requirements.yaml`.
This PR update `get-requirements.yaml` so it can be used on Ubuntu 20.04.1 LTS. In particular, it relaxes `s3cmd`s version.
Documentation on how to setup a Compliant Kubernetes cluster is missing (would be cool to add it, but this is a different issue).
**Checklist:**
- [NA] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [NA] …
> Relax s3cmd requirement

- README.md
- WIP-CHANGELOG.md
- bootstrap/storageclass/helmfile/helmfile.yaml
- get-requirements.yaml
- helmfile/01-applications.yaml
- helmfile/charts/blackbox/requirements.yaml
- pipeline/Dockerfile
Upgrades Helm to v3.4.1
**Which issue this PR fixes**: fixes #64 
**Checklist:**
> bin: Upgrade Helm to v3.4.1

- WIP-CHANGELOG.md
- helmfile/values/prometheus-operator-sc.yaml.gotmpl
The ops grafana url is not registered as a valid redirect url, and therefore login with oidc will not work.
There are decisions to be made regarding if/how to limit access to the ops grafana instance.
Therefore there is no clear fix to the broken configuration at the moment.
This PR removes the broken configuration.
fixes #52 
I do not believe that we have documented the ops grafana instance publicly yet.
I have tested deploying this, and validated that the dex login option is removed.
It is still possible use static login.
**Checklist:**
E.g. logs or metrics are …
> Remove broken ops grafana oidc config

- WIP-CHANGELOG.md
- bin/ck8s
- bin/ops.bash
This PR add `./bin/ck8s ops helm` to allow investigating issues with Helm releases, i.e., between `ops helmfile` and `ops kubectl`.
NA
**Checklist:**
- [NA] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
I.e. …
> bin: Add ck8s internal helm

- WIP-CHANGELOG.md
- helmfile/01-applications.yaml
Updates the grafana helm chart to the new repo. It also bumps the version to the latest version (6.1.0).
**Checklist:**
- Rerun apply
> apps sc: Updating Grafana helm chart

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- config/config/wc-config.yaml
- helmfile/values/ingress-nginx.yaml.gotmpl
Allows the specification of nginx configruation options, like logging format etc.
fixes #72 
Based from #69 where the migration to ingress-nginx has been made.
**Checklist:**
> Allows the specification of nginx configruation options.

- WIP-CHANGELOG.md
- bin/init.bash
- config/config/sc-config.yaml
- helmfile/values/fluentd-aggregator.yaml.gotmpl
The configuration key useRegionEndpoint was mistakenly placed under elasticsearch config when it should have been under fluentd. This PR corrects that.
fixes #265
**Checklist:**
- re-run init
> apps: moved misplaced fluentd conf

- bin/common.bash
Configuring SOPS to encrypt secrets with multiple GPG keys is an easy
solution to share a cluster across operators.
This patch allows spaces in the regex, which appear if multiple GPG keys
are configured with SOPS.
N/A
None yet.
**Checklist:**
- [NA] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [NA] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards …
> Fix: Accept multiple GPG keys

- WIP-CHANGELOG.md
- config/config/wc-config.yaml
- helmfile/01-applications.yaml
- helmfile/charts/examples/user-alertmanager/templates/ingress.yaml
- helmfile/charts/examples/user-alertmanager/values.yaml
- helmfile/charts/user-rbac/templates/rolebindings/alertmanager-configurer.yaml
- helmfile/charts/user-rbac/templates/roles/alertmanager-configurer.yaml
- helmfile/charts/user-rbac/values.yaml
- helmfile/values/prometheus-alerts-wc.yaml.gotmpl
- helmfile/values/prometheus-operator-wc.yaml.gotmpl
- helmfile/values/user-alertmanager.yaml.gotmpl
- helmfile/values/user-rbac.yaml.gotmpl
To deploy user-alertmanager in custom namespace.
The issuer for the ingress is now also configurable.
fixes #78 
fixes #80 
**Checklist:**
> apps wc: Confiugrable namespace and ingress issuer for user-alertmgr

- pipeline/test/services/service-cluster/testPodsReady.sh
- pipeline/test/services/workload-cluster/testPodsReady.sh
**What this PR does / why we need it**: Deployment name in tests updated to match actual deployment name.
**Checklist:**
> tests: updated ingress-nginx deployment name in tests

- README.md
- bin/common.bash
- bin/init.bash
Bare metal support is under development. This means that the apps repo must support it. This PR adds "baremetal" as a cloud provider setting in init so that when you run ck8s init for bare metal you  get settings based on that.
**Checklist:** …
> apps: add support for baremetal provider

- config/config/sc-config.yaml
**What this PR does / why we need it**: A miss in the config when the alertmanager namespace was parameterized.
**Checklist:**
> config: alertmanager namespace is needed in sc config

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- config/config/wc-config.yaml
- config/secrets/sc-secrets.yaml
- config/secrets/wc-secrets.yaml
- helmfile/01-applications.yaml
- helmfile/charts/harbor-backup/scripts/harbor-backup.sh
- helmfile/charts/harbor-backup/templates/harbor-backup-job.yaml
- helmfile/charts/harbor-backup/templates/harbor-backup-secret.yaml
- helmfile/charts/harbor-backup/values.yaml
- helmfile/charts/sc-logs-retention/scripts/logs-retention.sh
- helmfile/charts/sc-logs-retention/templates/configmap-env.yaml
- helmfile/charts/sc-logs-retention/templates/cronjob.yaml
- helmfile/charts/sc-logs-retention/templates/secret.yaml
- helmfile/charts/sc-logs-retention/values.yaml
- helmfile/values/fluentd-aggregator.yaml.gotmpl
- helmfile/values/harbor-backup.yaml.gotmpl
- helmfile/values/harbor.yaml.gotmpl
- helmfile/values/influxdb.yaml.gotmpl
- helmfile/values/opendistro-es.yaml.gotmpl
- helmfile/values/sc-logs-retention.yaml.gotmpl
- helmfile/values/velero.yaml.gotmpl
- migration/v0.7.x-v0.8.x/migrate-object-storage.sh
- pipeline/init.bash
- pipeline/test/infrastructure/s3-buckets.sh
- scripts/deploy-sc.sh
For the GCP support, we need to support GCS as object storage provider.
fixes #70 
**Checklist:**
> Added support for GCS

- WIP-CHANGELOG.md
- config/config/flavors/dev-sc.yaml
- config/config/flavors/prod-sc.yaml
- config/config/sc-config.yaml
- helmfile/01-applications.yaml
- helmfile/values/influxdb.yaml.gotmpl
Adds some more config options to InfluxDB.
Also a minor rework of the configuration.
**Which issue this PR fixes**
Any thoughts on the config?
The upgrade path is actully pretty lean:
```
git checkout main && ./bin/ck8s init
./bin/ck8s ops helmfile sc -l app=influxdb apply
git checkout ol/fix-influxdb && ./bin/ck8s init 
#
#
./bin/ck8s ops helmfile sc -l app=influxdb diff
❯ should see that one new config map and cronjob has been added
```
**Checklist:** …
> apps sc: Misc fixes and config improvments for influx

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- config/secrets/sc-secrets.yaml
- helmfile/values/dex.yaml.gotmpl
**What this PR does / why we need it**: allows okta to be used as an oidc provider to dex
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #201
**Special notes for reviewer**:oktaClientID and oktaClientSecret need to be added under dex in secrets.yaml.  We have an okta account - ask myself or Petter for access
**Checklist:**
> Petter okta

- helmfile/values/influxdb.yaml.gotmpl
Bug fix for clusters not working without s3 object storage.
fixes #112 
**Checklist:**
> influxdb: Fixed error when not using s3 as objectstorage

- WIP-CHANGELOG.md
- helmfile/01-applications.yaml
- helmfile/values/grafana-user.yaml.gotmpl
**What this PR does / why we need it**:user grafana updated so as to use JMES roles mapping for group claims
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #110 
**Checklist:**
> apps sc: update user grafana chart->6.1.11 and app version-> 7.3.3

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/values/dex.yaml.gotmpl
**What this PR does / why we need it**:using Okta as an OIDC provider to dex, dex is configured to accept groups
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #444
**Checklist:**
> apps sc: dex configured to accept OIDC groups from Okta

- WIP-CHANGELOG.md
- bin/user-kubeconfig.bash
- config/config/sc-config.yaml
- config/config/wc-config.yaml
- helmfile/values/fluentd-sc.yaml.gotmpl
- helmfile/values/fluentd-user.yaml.gotmpl
- helmfile/values/fluentd-wc.yaml.gotmpl
- migration/v0.7.x-v0.8.x/migrate-config.sh
- scripts/deploy-wc.sh
To support multi cluster we need to be able to differentiate between all logs in elasticsearch
fixes #93 
**Checklist:**
> fluentd: Added environment name as a record for all logs

- WIP-CHANGELOG.md
- helmfile/01-applications.yaml
**What this PR does / why we need it**: New version of the influxdb chart that pins the retention image version. See this PR for the actual changes: https://github.com/elastisys/influxdb-helm-charts/pull/6
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*:  This fixes the issue of us pulling the image each time the retention is run (2 jobs every 5 mins per service cluster). 
**Checklist:**
E.g. removes or changes any …
> apps sc: new influx chart version, pinning retention version

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/values/grafana-user.yaml.gotmpl
**What this PR does / why we need it**:Maps grafana roles to group claims 
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #99 
**Checklist:**
> Geoff grafana user group claims

- README.md
**What this PR does / why we need it**: Clarifies what needs to be changed in the config when setting up a new cluster, specifically `objectStorage` values which will cause errors when deploying apps if they are unset.
**Checklist:**
> docs: Update readme to clarify objectStorage config

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/charts/init-harbor/templates/init-harbor-cm.yml
- helmfile/charts/init-harbor/values.yaml
- helmfile/values/init-harbor.yaml.gotmpl
**What this PR does / why we need it**:Add group claims to harbor
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #97 
**Checklist:**
> apps sc: harbor group claims

- WIP-CHANGELOG.md
- bin/init.bash
- config/secrets/sc-secrets.yaml
**What this PR does / why we need it**: When running `ck8s init`, commented lines describing which `objectStorage` values need to be changed are now included in `secrets.yaml`. This will make it clearer what actually needs to be changed in the configuration when setting up a new cluster.
**Checklist:**
> bin: Include comments in secrets.yaml when initializing

- WIP-CHANGELOG.md
- bin/init.bash
- config/config/sc-config.yaml
- config/config/wc-config.yaml
- helmfile/01-applications.yaml
- helmfile/values/elasticsearch-backup.yaml.gotmpl
- helmfile/values/elasticsearch-slm.yaml.gotmpl
- helmfile/values/fluentd-aggregator.yaml.gotmpl
- helmfile/values/harbor-backup.yaml.gotmpl
- helmfile/values/harbor.yaml.gotmpl
- helmfile/values/influxdb.yaml.gotmpl
- helmfile/values/sc-logs-retention.yaml.gotmpl
- helmfile/values/velero.yaml.gotmpl
- pipeline/test/services/service-cluster/testPodsReady.sh
- pipeline/test/services/workload-cluster/testPodsReady.sh
**What this PR does / why we need it**: This makes object storage optional. It mostly adds some config options to disable all backups.
I have not fixed the tests yet. They should of course not give any error for a disabled feature.
**Checklist:**
> Making object storage optional

- README.md
- WIP-CHANGELOG.md
- get-requirements.yaml
- pipeline/Dockerfile
**What this PR does / why we need it**: We now have k8s v1.18 as default in ck8s-cluster, so it makes sense to have the same version here.
**Which issue this PR fixes**: -
**Checklist:**
> all: Bump kubectl to v1.18.13

- WIP-CHANGELOG.md
**What this PR does / why we need it**: It removes the parts of the WIP-CHANGELOG that was included in the last release.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: -
After this, we can hopefully merge #137. Otherwise I guess we can always cherry pick the patches from the release branch.
**Checklist:**
> release: Clear the WIP changelog of things already included in a release

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- config/config/wc-config.yaml
- migration/v0.8.x-v0.9.x/migrate-apps.md
I've been confused by this variable for a while now and I finally took the time to check if it was used or not.
As you can see, it's not https://github.com/elastisys/compliantkubernetes-apps/search?q=dnsPrefix.
**Checklist:**
> config: Remove dnsPrefix

- WIP-CHANGELOG.md
- helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
- helmfile/values/kube-prometheus-stack-wc.yaml.gotmpl
- helmfile/values/prometheus-wc-reader.yaml.gotmpl
The new prometheus version does not like running on NFS and it leads to issues with the wal.
```
fs_type=NFS_SUPER_MAGIC msg="This filesystem is not supported and may lead to data corruption and data loss. Please carefully read https://prometheus.io/docs/prometheus/latest/storage/ to learn more about supported filesystems."
...
msg="error tailing WAL" err="failed to find segment for index
```
**Checklist:**
> apps: Revert prometheus back to 2.19.1

- WIP-CHANGELOG.md
- helmfile/01-applications.yaml
- helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
Part of the initial multi workload cluster support.
The capability to expose the cluster label as a variable in grafana was [recently added in the kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/pull/357)
Now you'll see the cluster variable on  _**some**_  of the default dashboards
fixes #146 
The bump in chart version did bump the prometheus-operator version.
The resulting diff looks like
```
...
- name: kube-prometheus-stack
-           image: "quay.io/prometheus-operator/prometheus-operator:v0.43.1"
+           image: "quay.io/prometheus-operator/prometheus-operator:v0.44.0"
imagePullPolicy: "IfNotPresent"
args:
- …
```
> Grafana multicluster

- WIP-CHANGELOG.md
- helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
- helmfile/values/kube-prometheus-stack-wc.yaml.gotmpl
- helmfile/values/prometheus-wc-reader.yaml.gotmpl
To stay up to date :)
None
We had this version of prometheus for a brief period of time but i panic reverted when i saw 
```
ts=2020-12-29T11:44:44.209Z caller=dedupe.go:112 component=remote level=error remote_name=ce6a8f url="https://influxdb.ops.mtt-0.a1ck.io/api/v1/prom/write?db=workload_cluster&u=wcWriter&p=somelongsecret" msg="error tailing WAL" err="failed to find segment for index"
```
as I thought that this error was due to the version update, but as it turns out it does occur on the current version as well. Why? Not sure but it could be related to prometheus not supporting nfs for storage.
**Checklist:** …
> apps: Update prometheus to 2.23.0

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
**What this PR does / why we need it**:Adds sample mappings to config for OIDC groups to kibana roles
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #98 
**Checklist:**
> apps sc: added example config for mapping to groups in kibana from OIDC

- WIP-CHANGELOG.md
- helmfile/values/blackbox.yaml.gotmpl
**What this PR does / why we need it**: Blackbox needed an update after we switched to opendistro to check kibana properly.
**Checklist:**
> apps sc: fixes check for kibana in blackbox exporter

- WIP-CHANGELOG.md
- config/config/wc-config.yaml
- migration/v0.8.x-v0.9.x/upgrade-apps.md
**What this PR does / why we need it**: Removes duplicate OPA config for enforcement.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #154
**Checklist:**
> apps: removed duplicate OPA config

- WIP-CHANGELOG.md
- config/config/wc-config.yaml
- helmfile/values/falcosidekick.yaml.gotmpl
**What this PR does / why we need it**: Needed to upgrade getinges cluster properly. Did some quick tests and it seems to parse correctly.
Wondering slightly if the config under `falco.alert` should be moved to `falco.falcoSidekick`, but not sure that it's worth it right now.
**Checklist:**
I.e. …
> apps wc: adds more config options to falco sidekick

- README.md
- WIP-CHANGELOG.md
- get-requirements.yaml
- pipeline/Dockerfile
> all: Upgrade helm to v3.5.0

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/values/prometheus-elasticsearch-exporter.yaml.gotmpl
**What this PR does / why we need it**: For some customers we have had to increase the serviceMonitor config, so this gives that option.
**Checklist:**
> apps sc: adds config options to serviceMonitor for elasticsearch exporter

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/values/dex.yaml.gotmpl
**What this PR does / why we need it**: This gives the ability to add more redirect URIs to the static client for kubernetes in dex. Needed if the user wants to add the standard kubernetes dashboard or something similar.
**Checklist:**
> apps sc: adds option for additional kubelogin client URIs in dex

- WIP-CHANGELOG.md
- config/config/wc-config.yaml
- helmfile/charts/user-rbac/templates/namespaces.yaml
- helmfile/charts/user-rbac/values.yaml
- helmfile/values/user-rbac.yaml.gotmpl
**What this PR does / why we need it**: With this you can choose if you want to create the user namespaces or not. Note that user RBAC is always created.
**Checklist:**
> apps wc: adds option to choose if user namespaces are created

- WIP-CHANGELOG.md
- helmfile/01-applications.yaml
**What this PR does / why we need it**: 
To fix the issue where influxDB backup volume always gets filled up after a while. Dependent on https://github.com/elastisys/chart-repo/pull/10
fixes #180
**Checklist:**
> influxdb: Updated to 4.8.12

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/values/harbor.yaml.gotmpl
- migration/v0.8.x-v0.9.x/upgrade-apps.md
**What this PR does / why we need it**: This turns of clair in Harbor which was using a lot of resources even though trivy was the default scanner. It also adds resource requests to all Harbor pods based on numbers from running clusters.
**Checklist:**
> apps sc: disables clair and updates Harbor config with resource requests and more    

- pipeline/test/services/service-cluster/testPodsReady.sh
Updates the tests to work with trivy.
fixes #187 
**Checklist:**
> tests: Update tests for harbor

- WIP-CHANGELOG.md
- bootstrap/namespaces/helmfile/charts/namespaces/Chart.yaml
- bootstrap/namespaces/helmfile/charts/namespaces/templates/namespace.yaml
- bootstrap/namespaces/helmfile/helmfile.yaml
I found that the annotations in the namespace chart wasn't working.
So I fixed that and cleaned it up a bit.
N/A
**Checklist:**
> bootstrap: Fixed namespace chart to work with annotations

- bin/init.bash
**What this PR does / why we need it**: (QA 0.9) `fluentd.useRegionEndpoint` was changed to `fluentd.forwarder.useRegionEndpoint` in this PR: https://github.com/elastisys/compliantkubernetes-apps/pull/50, but the initialization of this value when running `ck8s init` was not changed. This PR fixes that.
**Checklist:**
> apps sc: fix setting fluentd.forwarder.useRegionEndpoint during init

- .github/workflows/pipeline.yml
- WIP-CHANGELOG.md
- bin/init.bash
- config/config/sc-config.yaml
- config/config/wc-config.yaml
- config/secrets/sc-secrets.yaml
- pipeline/lint.bash
Makes the linter stop on errors, as apposed to continuing, thereby exposing configuration errors. Also fixes some blank/errorneous configuration errors that made the linter unhappy.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #107
**Checklist:**
> apps: stop on lint errors

- migration/v0.8.x-v0.9.x/upgrade-apps.md
Cleanup from QA (I guess)
N/A
**Checklist:**
> Removed WIP tag on migration docs

- WIP-CHANGELOG.md
- helmfile/values/fluentd-configmap.yaml.gotmpl
- helmfile/values/fluentd-user.yaml.gotmpl
- helmfile/values/fluentd-wc.yaml.gotmpl
Since we want to update the audit path to use kubespray default we need to make sure that both the old and the new way is supported.
**Checklist:**
> fluentd: Added tail of kubespray default audit log location

- pipeline/test/infrastructure/s3-buckets.sh
We do no longer specify the same buckets for both wc and sc, thus the tests needs to adhere to this change.
This commit updates the tests a bit and simplifies it (imo).
**Tests**:
```
❯ ./pipeline/test/infrastructure/s3-buckets.sh sc
Checking status of bucket [olle-dev-harbor] at [exoscale]
Bucket [olle-dev-harbor] exists at [exoscale]
Checking status of bucket [olle-dev-velero] at [exoscale]
Bucket [olle-dev-velero] exists at [exoscale]
Checking status of bucket [olle-dev-es-backup] at [exoscale]
Bucket [olle-dev-es-backup] exists at [exoscale]
Checking status of bucket [olle-dev-influxdb] at [exoscale]
Bucket [olle-dev-influxdb] exists at [exoscale]
Checking status of bucket …
```
> tests: Improve s3 bucket tests

- scripts/deploy-wc.sh
To avoid fluentd(user) crashlooping in the workload cluster.
**Checklist:**
> apps wc: Install fluentd cm before fluentd itself

- .github/pull_request_template.md
Removes commit prefixes that should no longer be used in this repository.
**Checklist:**
> all: Remove infra releated commit prefixes

- bin/init.bash
Updates the default value for using the proxy protocol in nginx for safespring.
fixes #214 
**Checklist:**
> config: Use proxy protocol defaults to false for safespring

- helmfile/charts/grafana-ops/dashboards/falco-dashboard.json
- helmfile/charts/grafana-ops/dashboards/gatekeeper-dashboard.json
- helmfile/charts/grafana-ops/dashboards/nginx-dashboard.json
**What this PR does / why we need it**: Found some small errors/typos that this fixes
**Checklist:**
> apps: fixes some small errors in grafana dashboards

- pipeline/test/services/funcs.sh
To fail faster when testing service endpoints when the apps installation has completely failed.
This commit sets a couple of options for curl
- `--max-time <seconds> Maximum time allowed for the transfer`
- `--connect-timeout <seconds> Maximum time allowed for connection`
fixes #217 
I have not tested this.
We might want to lower the settings even more as we do 6 retries.
**Checklist:**
> Set timeout for service endpoint tests

- WIP-CHANGELOG.md
- bin/init.bash
- config/config/flavors/dev-sc.yaml
- config/config/sc-config.yaml
- helmfile/01-applications.yaml
- helmfile/values/opendistro-es.yaml.gotmpl
- migration/v0.9.x-v0.10.x/upgrade-apps.md
- pipeline/test/services/service-cluster/testPodsReady.sh
Upgrades the helm chart which gives us access to creating multirole nodes.
Updates test according to the new settings.
Updates the dev flavor to deploy a **single** multi-role node(kind of just to see if it works well for us or not).
fixes #164 
I've changed the init flow a bit.
The default value for storageclasses for elasticsearch has been changed to `null`, which means that the cluster default will be used. This makes sense imo as it decreases the init-complexity and is in line with most other helm charts.
With the new version there are some repeated deprecation (every 30s) logs in the client nodes
```
[2021-02-10T18:59:20,396][DEPRECATION][o.e.d.c.m.IndexNameExpressionResolver] …
```
> apps sc: Update opendistro helm chart to 1.12

- helmfile/values/fluentd-configmap.yaml.gotmpl
**What this PR does / why we need it**: Fixes an indentation error in the fluentd aggregator ConfigMap which caused problems when using gcs as object storage.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #244 
**Special notes for reviewer**: I feel like this is so minor that it didn't warrant adding to the changelog, but tell me if you think I should do that.
**Checklist:** …
> apps sc: fix fluentd configmap gcs keyfile indentation

- pipeline/test/services/workload-cluster/testPodsReady.sh
Test nfs-client-provisioner only if it is enable instead of looking at
what cloud provider is used. Also added test for local volume
provisioner.
None, part of QA for 0.10
**Checklist:**
> [QA] tests: Fix and update wc pod tests

- bootstrap/namespaces/helmfile/values/namespaces-wc.yaml.gotmpl
**What this PR does / why we need it**: This PR adds `admission.gatekeeper.sh/ignore="true"` label to `kube-system` and `gatekeeper-system` namespaces.
fixes #148 
**Checklist:**
> apps wc: Add admission.gatekeeper.sh/ignore label to kube-system and gatekeeper-system namespaces

- WIP-CHANGELOG.md
- helmfile/values/fluentd-configmap.yaml.gotmpl
- helmfile/values/fluentd-sc.yaml.gotmpl
- helmfile/values/fluentd-user.yaml.gotmpl
- helmfile/values/fluentd-wc.yaml.gotmpl
Remove monitoring fluentd metrics
fixes #246 
I have not tested upgrading. Although i dont see what whould could go wrong.
**Tests**
```
❯ ./bin/ck8s ops kubectl sc  get servicemonitor -n fluentd
No resources found in fluentd namespace.
❯ ./bin/ck8s ops kubectl wc -n fluentd get servicemonitors
No resources found in fluentd namespace.
❯ ./bin/ck8s ops kubectl wc -n kube-system get servicemonitors 
No resources found in kube-system namespace.
```
Prometheus-sc
wc-reader
**Checklist:**
E.g. removes or changes …
> Don't capture fluentd metrics

- WIP-CHANGELOG.md
- helmfile/charts/sc-logs-retention/values.yaml
**What this PR does / why we need it**: Fixes the incorrect sc log retention service account. (`fluentd-aggregator` -> `fluentd-forwarder`)
**Which issue this PR fixes**: fixes #224 
**Checklist:**
> apps sc: fix sc log retention service account

- scripts/deploy-sc.sh
- scripts/deploy-wc.sh
To get rid of warning when applying.
```
[ck8s] Applying applications in workload cluster
Creating Elasticsearch and fluentd secrets
W0222 13:42:32.890541  576671 helpers.go:553] --dry-run is deprecated and can be replaced with --dry-run=client.
secret/elasticsearch configured
W0222 13:42:33.519425  576693 helpers.go:553] --dry-run is deprecated and can be replaced with --dry-run=client.
```
**Checklist:**
I.e. full cluster migration is …
> Use dry-run=client in apply scripts

- README.md
We no longer update ck8s-cluster and thus it does not make sense to refer people to that repository.
fixes #195 
This is just an initial attempt to address the linked issue.
I don't know if we have to make it more complicated than this.
Preferably we should have the "migration" docs (if at all possible) from `ck8s-cluster` to `compliantkubernetes-kubespray` in the kubespray repo as that's what superseded the cluster repo, in order to have this repo be as agnostic as possible and just have a set of requirements on the kubernetes clusters themselves.
Related: https://github.com/elastisys/ck8s-cluster/pull/120
**Checklist:**
- Is this changeset backwards compatible for existing clusters? …
> docs: Replace ck8s-cluster with ck8s-kubespray

- README.md
- WIP-CHANGELOG.md
- get-requirements.yaml
- pipeline/Dockerfile
To get security fixes
fixes #239 
**Checklist:**
> Bump helm to v3.5.2

- README.md
- WIP-CHANGELOG.md
- get-requirements.yaml
- pipeline/Dockerfile
Default kubernetes version in kubespray 2.15 is 1.19
fixes #264 
With this new version i noticed that we get a warning when bootstrapping our crds
```
❯ ./bin/ck8s apply sc
[ck8s] Validating sc config
[ck8s] Bootstrapping service cluster
customresourcedefinition.apiextensions.k8s.io/certificaterequests.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/certificates.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/challenges.acme.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/clusterissuers.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/issuers.cert-manager.io configured …
```
> Bump kubectl to v1.19.8

- README.md
- WIP-CHANGELOG.md
- get-requirements.yaml
- pipeline/Dockerfile
fixes #261  
Been using this version for the last 1-2 weeks and i have not run into any trouble.
**Checklist:**
> Bump helmfile to v0.138.4

- pipeline/list-releases.bash
To get some kubernetes output when a release has failed installing in the pipeline.
Now if there are releases that are not found it will still check for failed releases.
None
**Tests**
- Fluents user is failed due to timeout
- Issuers has not been installed
Before fix - it stops at listing releases which fails becase issers has not been installed.
```
in /home/olle/Documents/github/elastisys/compliantkubernetes-apps/helmfile/01-applications.yaml: release "issuers" failed: command "/usr/local/bin/helm" exited with non-zero status:
PATH:
/usr/local/bin/helm
ARGS:
0: helm (4 bytes)
1: status (6 bytes)
2: issuers (7 bytes)
3: --namespace (11 bytes)
4: cert-manager (12 bytes)
ERROR:
exit …
```
> tests: Always continue on helmfile status in list releases test

- bin/apps.bash
- bin/ck8s
This pr makes it so that by default before running helmfile apply the charts are templated and validated.
This validation can be skipped by passing `--skip-template-validation` to the apps/apply commands.
Somewhat fixes #105 
**Checklist:**
> bin: run helmfile template on apply

- WIP-CHANGELOG.md
- helmfile/values/grafana-user.yaml.gotmpl
Set deploymentStrategy to Recreate for user Grafana, so that upgrades
work. A rollingUpdate strategy fails, due to persistence being set to
ReadWriteOnce.
Treat this as a temporary fix for #185. A permanent fix will likely come
with #242.
**Checklist:** …
> Fix user Grafana Deployment

- release/README.md
Updates the the release docs in the repo.
We don't have any "QA" test in this repo so i just mentioned that you should do some QA after creating the branch off main.
fixes #209 
**Checklist:**
> release: Add QA step to release process

- helmfile/01-applications.yaml
Remove deprecated releases from statefile.
fixes #275 
**Checklist:**
> apps: Remove ck8sdash entry from apps statefile

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- config/config/wc-config.yaml
- helmfile/01-applications.yaml
- migration/v0.10.x-v0.11.x/upgrade-apps.md
To be able to deploy clusters on clusters with metrics server already installed we need a way of disabling it.
fixes #283 
**Checklist:**
> Added option to disable metric server

- .github/pull_request_template.md
Make it harder to forget updating the pipeline
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #278
This is a reference to a private repository. Do you think it is OK or should we try to do it some other way? For example, keep the config in this repo as an "example" that we just happen to use for the pipeline.
**Checklist:**
E.g. removes or changes any CK8S config options …
> pipeline: Mention that the pipeline may need updating in PR template

- config/config/flavors/prod-sc.yaml
Set the request and limit higher for prod flavor.
Now it basically "forces" you to have a single node with 16 gb or greater for influxdb.
N/A
Not sure if I used the correct commit prefix.
**Checklist:**
> config: Increase memory for prod influxdb

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- config/config/wc-config.yaml
- helmfile/01-applications.yaml
- helmfile/charts/calico-accountant/.helmignore
- helmfile/charts/calico-accountant/Chart.yaml
- helmfile/charts/calico-accountant/README.md
- helmfile/charts/calico-accountant/templates/daemonset.yaml
- helmfile/charts/calico-accountant/templates/rbac.yaml
- helmfile/charts/calico-accountant/templates/service.yaml
- helmfile/charts/calico-accountant/values.yaml
- helmfile/charts/grafana-ops/dashboards/networkpolicy-dashboard.json
- helmfile/charts/grafana-ops/templates/dashboard-configmap.yaml
- helmfile/charts/grafana-ops/values.yaml
- helmfile/values/grafana-ops.yaml.gotmpl
**What this PR does / why we need it**: Adds a NetworkPolicy dashboard in Grafana which displays packets that are accepted/rejected by NetworkPolicies in the clusters.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #234 
If you want to test it yourself, you can test the dashboard using [these Pods and NetworkPolicies.](https://github.com/elastisys/compliantkubernetes-apps/tree/vf/netpol-dashboard/netpol-dashboard/test-manifests)
The metrics exporter (calico-accountant) currently uses our Docker image because there is no official Docker image available of the latest version, awaiting response …
> apps: Add NetworkPolicy dashboard in Grafana

- README.md
- WIP-CHANGELOG.md
- helmfile/01-applications.yaml
- scripts/clean-sc.sh
- scripts/clean-wc.sh
**What this PR does / why we need it**: Adds some simple scripts that can clean up your clusters.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #213 
https://github.com/elastisys/compliantkubernetes/pull/72
This should remove everything except storage classes and any labels on the namespaces that are not deleted (e.g. kube-system). Do you think that I should remove that as well?
**Checklist:** …
> bin: adds cleanup scripts

- release/README.md
- release/release.sh
- release/reset-changelog.sh
From the last release I updated the documentation to reflect the flow.
**Checklist:**
If you change some config options (e.g. add/rename variable or change the default value) you …
> Updated release documentation to reset CHANGELOG before QA

- WIP-CHANGELOG.md
- bin/init.bash
- config/config/sc-config.yaml
- config/config/wc-config.yaml
- helmfile/charts/examples/user-alertmanager/templates/ingress.yaml
- helmfile/charts/issuers/templates/letsencrypt-prod.yaml
- helmfile/charts/issuers/templates/letsencrypt-staging.yaml
- helmfile/charts/kubeapi-metrics/templates/ingress.yaml
- helmfile/charts/kubeapi-metrics/values.yaml
- helmfile/values/dex.yaml.gotmpl
- helmfile/values/grafana-user.yaml.gotmpl
- helmfile/values/harbor.yaml.gotmpl
- helmfile/values/influxdb.yaml.gotmpl
- helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
- helmfile/values/kubeapi-metrics.yaml.gotmpl
- helmfile/values/letsencrypt.yaml.gotmpl
- helmfile/values/opendistro-es.yaml.gotmpl
- migration/v0.11.x-v0.12.x/upgrade-apps.md
- pipeline/config/exoscale/sc-config.yaml
- pipeline/config/exoscale/wc-config.yaml
See #287 for why we want to use ClusterIssuers. I also disabled the (Cluster)Issuers in WC since we don't really need them there. We only used them with kubeapi-metrics for health checking the API server. But this check [doesn't need a trusted certificate](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/values/blackbox.yaml.gotmpl#L23).
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #287
A nicer solution would be to make the blackbox exporter use `tls_verify` depending on what issuer we use and add a config option to specify …
> Use ClusterIssuer in SC and disable in WC

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- config/config/wc-config.yaml
- helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
- helmfile/values/kube-prometheus-stack-wc.yaml.gotmpl
- helmfile/values/prometheus-wc-reader.yaml.gotmpl
- migration/v0.11.x-v0.12.x/upgrade-apps.md
- pipeline/config/exoscale/sc-config.yaml
- pipeline/config/exoscale/wc-config.yaml
Removing persistent volumes for prometheus.
fixes #285 
**Checklist:** …
> apps: Removed persistent volumes for prometheus

- bin/ck8s
We shouldn't need to validate the config twice in the comand :)))
**Checklist:**
> bin: Fix duplicate tests in config validation

- WIP-CHANGELOG.md
- bootstrap/crds/velero/backups.yaml
- bootstrap/crds/velero/backupstoragelocations.yaml
- bootstrap/crds/velero/deletebackuprequests.yaml
- bootstrap/crds/velero/downloadrequests.yaml
- bootstrap/crds/velero/podvolumebackups.yaml
- bootstrap/crds/velero/podvolumerestores.yaml
- bootstrap/crds/velero/resticrepositories.yaml
- bootstrap/crds/velero/restores.yaml
- bootstrap/crds/velero/schedules.yaml
- bootstrap/crds/velero/serverstatusrequests.yaml
- bootstrap/crds/velero/volumesnapshotlocations.yaml
- helmfile/01-applications.yaml
- helmfile/values/velero.yaml.gotmpl
To support S3 region we need to upgrade velero to use at least version 1.3.0. 
fixes #289 
**Checklist:**
If you change some config options (e.g. add/rename variable or change the …
> Updated velero chart to 2.15.0

- WIP-CHANGELOG.md
- bootstrap/namespaces/helmfile/values/namespaces-sc.yaml.gotmpl
- bootstrap/namespaces/helmfile/values/namespaces-wc.yaml.gotmpl
Removed depricated label
fixes #291 
**Checklist:** …
> bootstrap: Removed label from cert-manager namespace

- WIP-CHANGELOG.md
- helmfile/values/fluentd-configmap.yaml.gotmpl
Changed to always include `s3_region` for fluentd
fixes #282 
**Checklist:** …
> Changed fluentd forwarder config to always include `s3_region`

- bin/common.bash
- config/config/wc-config.yaml
To lessen the likelihood that a user deploys apps with a bad config.
Before our validation gave warning on `""` and empty/missing paths.
Now it has been update to warn on the following
- `"set-me"`
- `set-me`
- and empty/missing path/field.
This means that if there is a field that we want the user to configure it should prefereably be set to `"set-me"` by default.
part of #300 
**Checklist:** …
> bin: Update config validation

- config/config/sc-config.yaml
Adds a clarifying comment to the useRegionEndpoint config value for fluentd.
Part of #300 
**Checklist:**
> apps sc: Clarify use region endpoint for fluentd

- README.md
- scripts/S3/entry.sh
- scripts/S3/generate-s3cfg.sh
- scripts/S3/manager.sh
Moves s3 bucket management back to this repository as the buckets are tightly coupled with apps.
Should reduce the number of times users forget to create the appropriate buckets when s3 object storage is enabled.
The bucket manager part is virtually the same as the one we have in out private bucketmanager repo, i've just made a few tweaks to the genereate-s3cfg config, and made the files comply with shellcheck.
Part of #300 
fixes #321
I have not yet updated the pipeline.
**Checklist:** …
> all: Add S3 management scripts

- migration/v0.11.x-v0.12.x/upgrade-apps.md
**What this PR does / why we need it**: Some clarifications to the migration doc.
**Checklist:** …
> update v0.12 migration instructions

- README.md
fixed in earlier commit
**What this PR does / why we need it**: I forgot to remove this note when I fixed this issue.
**Checklist:** …
> docs: remove note about gatekeeper not working on k8s v1.19+

- WIP-CHANGELOG.md
- helmfile/charts/elasticsearch-slm/values.yaml
Increased SLM active deadline to 1h
**Checklist:**
If you change some config options (e.g. add/rename variable or change the default value) you may need to update the config used …
> SLM active deadline increase more

- WIP-CHANGELOG.md
- helmfile/values/fluentd-configmap.yaml.gotmpl
FluentId logs stop being shipped to S3.
fixes #332 
**Testing**
To generate Fluentd logs, pods could be shut down to then reset automatically. The initial logging then got shipped to S3. If the initial logging didn't get shipped to S3 after my changes without any errors - success.
**Checklist:**
> apps: fix s3 logs

- CHANGELOG.md
- WIP-CHANGELOG.md
**What this PR does / why we need it**: Reset the changelog for v0.13
**Checklist:** …
> Reset changelog for release v0.13.0

- get-requirements.yaml
This PR fixes a bug in Ansible `get-requirements.yaml` script, which uses wrong keyword for privilege escalation.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #366
**Checklist:** …
> Fix privilege escalation bug in Ansible get-requirements.yaml script

- release/README.md
- Fix broken links
- Fix git command for pushing tags
- Add note for how to create a release in case of no QA commits.
Fixing some minor things in the release documentation.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: none
**Checklist:**
**Pipeline config** *(if …
> docs: Update release document

- WIP-CHANGELOG.md
- helmfile/charts/prometheus-alerts/templates/rules/falco-alerts.yaml
- helmfile/charts/prometheus-alerts/values.yaml
Falco alerts get routed through Prometheus to the alert manager in the wc-cluster as it cannot be delivered by falcon itself.
fixes elastisys/ck8s-ops#106
This could be developed further. Instead of having one generic FalcoAlert-rule, we could have one alert for each rule defined in  https://github.com/falcosecurity/charts/blob/d7f1fbb31b94ecc28cfd1693bdcf8d867ce6d39d/falco/rules/falco_rules.yaml. Is it wanted?
**Checklist:**
> apps wc: falco-alert routing to alertmanager in sc

- WIP-CHANGELOG.md
- bootstrap/namespaces/helmfile/values/namespaces-wc.yaml.gotmpl
- scripts/clean-wc.sh
I noticed that the bootstrap step creates both `gatekeeper` and `gatekeeper-system` namespaces. The gatekeeper namespace seems to be empty so I figured that it was simply not removed when we moved to the new gatekeeper chart.
**Checklist:** …
> Remove gatekeeper namespace

- WIP-CHANGELOG.md
- helmfile/charts/elasticsearch-slm/scripts/slm-retention.bash
**What this PR does / why we need it**: We have had some problems with slm taking a long time to delete indices, hopefully it helps if we try to delete indices in bulk instead.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: no issue
**Checklist:** …
> apps sc: elasticsearch slm script deletes indices in bulk

- WIP-CHANGELOG.md
- scripts/restore/README.md
- scripts/restore/restore-harbor.sh
**What this PR does / why we need it**: This adds the restore script for harbor. I debated putting some documentation here but I though it might be better to just have it on compliantkubernetes.io (PR with that is coming later)
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: part of elastisys/compliantkubernetes#77
Coming later
**Checklist:**
I.e. …
> apps sc: add script to restore Harbor from backup

- WIP-CHANGELOG.md
- config/config/flavors/dev-sc.yaml
- config/config/flavors/dev-wc.yaml
Object storage gets disabled by default to fasten a developers creation of a cluster for test-purposes.
fixes #361 
**How to enable ObjectStorage?**
Before or after https://github.com/elastisys/compliantkubernetes-apps quickstart 5-6:
sc-config:
Set objectStorage:type: s3
Set harbor:persistence:type: objectStorage
Set elasticsearch:snapshot:enabled: true
Set elasticsearch:fluentd:enabled: true
Set influxDB:backup:enabled: true
Set ingressNginx:velero:enabled: true
wc-config:
Set objectStorage:type: s3
Set ingressNginx:velero:enabled: true
When finished editing:
ln -sf $CK8S_CONFIG_PATH/.state/kube_config_${SERVICE_CLUSTER}.yaml $CK8S_CONFIG_PATH/.state/kube_config_sc.yaml
./bin/ck8s apply sc  # Respond "n" if you get a …
> apps wc & sc: default to object storage disabled

- WIP-CHANGELOG.md
- helmfile/charts/user-rbac/templates/rolebindings/alertmanager-configurer.yaml
- helmfile/charts/user-rbac/templates/roles/alertmanager-configurer.yaml
- helmfile/charts/user-rbac/values.yaml
- helmfile/values/user-rbac.yaml.gotmpl
Makes it so that rbac for user alertmanager is only installed when it is actually enabled.
**Checklist:**
> apps wc: Only install alertmgr rbac if enabled

- manifests/restore/restore-influx.yaml
**What this PR does / why we need it**: As mentioned here: https://github.com/elastisys/compliantkubernetes/pull/102#discussion_r614817642, the "restore influxdb" manifest does not use an image that matches the images we use for the influxdb instance: https://github.com/elastisys/compliantkubernetes-apps/blob/5dac15b02e3510fc571e9a70aebdad9e22fc093a/helmfile/values/influxdb.yaml.gotmpl#L44
**Special notes for reviewer**: This has not been tested.
**Checklist:**
E.g. logs or metrics are not being collected or …
> apps sc: update image for influx restore to match influx

- CODEOWNERS
**What this PR does / why we need it**: Removes the default codeowner, which used a deprecated team.
**Special notes for reviewer**: Should the CODEOWNERS file just be removed entirely, or is there still use for it?
**Checklist:**
> all: remove default codeowner

- pipeline/config/exoscale/sc-config.yaml
Fixes https://github.com/elastisys/compliantkubernetes-apps/runs/2416547200?check_suite_focus=true#step:20:174
**Checklist:**
> pipeline: Add auth log retention variables

- pipeline/test/services/workload-cluster/testPodsReady.sh
- scripts/S3/generate-s3cfg.sh
Two small fixes detected in v0.14.0 QA
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: none
**Checklist:**
If you change some config options (e.g. add/rename variable or change the default value) you may need to update the config used …
> Cherry picks from 0.14

- WIP-CHANGELOG.md
- helmfile/01-applications.yaml
When using harbor together with rook there is a potential bug that appears if the database pod is killed and restarted on a new node. This is fixed by upgrading Harbor to version 1.6.1.
fixes #173
**Way to test**:
Run ._/bin/ck8s ops kubectl sc delete pod harbor-harbor-database-0 --namespace harbor_
If the pod restarts with status: CrashLoopBackOff, the bug persist. If not, it runs correctly.
**Checklist:**
> apps sc: upgrade harbor to fix rook bug

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- migration/v0.14.x-v0.15.x/upgrade-apps.md
- pipeline/config/exoscale/sc-config.yaml
- scripts/deploy-sc.sh
**What this PR does / why we need it**: Removes the automatic restore of influxdb/grafana when `deploy-sc.sh` is run, as well as the related config.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #389 
**Checklist:** …
> all: remove automatic restore when applying, and related config

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/01-applications.yaml
- helmfile/charts/grafana-ops/Chart.yaml
- helmfile/charts/grafana-ops/dashboards/daily-dashboard.json
- helmfile/charts/grafana-ops/templates/dashboard-configmap.yaml
- helmfile/charts/grafana-ops/values.yaml
- helmfile/charts/s3-exporter/.helmignore
- helmfile/charts/s3-exporter/Chart.yaml
- helmfile/charts/s3-exporter/templates/NOTES.txt
- helmfile/charts/s3-exporter/templates/_helpers.tpl
- helmfile/charts/s3-exporter/templates/configmap.yaml
- helmfile/charts/s3-exporter/templates/deployment.yaml
- helmfile/charts/s3-exporter/templates/secret.yaml
- helmfile/charts/s3-exporter/templates/service.yaml
- helmfile/charts/s3-exporter/templates/serviceaccount.yaml
- helmfile/charts/s3-exporter/templates/servicemonitors.yaml
- helmfile/charts/s3-exporter/values.yaml
- helmfile/values/fluentd-configmap.yaml.gotmpl
- helmfile/values/grafana-ops.yaml.gotmpl
- helmfile/values/s3-exporter.yaml.gotmpl
- migration/v0.13.x-v0.14.x/upgrade-apps.md
- pipeline/config/exoscale/sc-config.yaml
- pipeline/init-unit-tests.bash
This adds an s3-exporter and service monitor so that we get metrics about our buckets. These metrics can be used to check if backups and retention jobs are working as they should, and keep an eye on the size.
**Which issue this PR fixes**: fixes #373. 
I'm not happy with the templating of the dashboard to add thresholds. It feels bad in many ways so I would suggest that we drop the last commit and go with a dashboard without thresholds for now.
**Checklist:**
E.g. removes or changes …
> Add S3-exporter for metrics about buckets and dashboard for daily tasks

- WIP-CHANGELOG.md
- bin/team.bash
The check was for a normal bash environment variable, but it is actually an array.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: none
**Checklist:** …
> bin: Fix check for bash array in team.bash

- .github/workflows/end-to-end.yml
- config/config/wc-config.yaml
- pipeline/config/exoscale/sc-config.yaml
- pipeline/config/exoscale/wc-config.yaml
This makes the pipeline work again. It is currently failing because the admin kubeconfig is missing. Most likely, this is because we used the master branch of kubespray to get the terraform code for Exoscale. It was recently changed so that the [group names no longer match](https://github.com/kubernetes-sigs/kubespray/pull/7552/files#diff-ffddece82112cdcc07c642b22e3b12843e253f17177885fddb2b4695797dd297) what kubespray v2.15.0 expects.
We checkout master of kubespray here:
https://github.com/elastisys/compliantkubernetes-apps/blob/77011fc0aa6c4c93779ab6fab30942e292dcb896/.github/workflows/end-to-end.yml#L43-L48
This is used to run terraform [here](https://github.com/elastisys/compliantkubernetes-apps/blob/main/.github/workflows/end-to-end.yml#L79). …
> Fix pipeline

- CHANGELOG.md
- helmfile/values/harbor.yaml.gotmpl
In order to be able to update harbor smoothly we need to use the recreate updatestrategy as we don't have rwm volumes.
**Checklist:**
> QA: change updateStrategy for harbor deployments

- pipeline/test/services/workload-cluster/testPodsReady.sh
> tests: Use correct namespace for user-alertmgr

- CHANGELOG.md
- helmfile/values/harbor.yaml.gotmpl
- pipeline/test/services/workload-cluster/testPodsReady.sh
**What this PR does / why we need it**: Three fixes from the QA process of v0.15.0
**Checklist:** …
> Cherry picks from v0.15.0

- WIP-CHANGELOG.md
- config/config/flavors/dev-sc.yaml
- config/config/sc-config.yaml
The resources allocated to certain tasks or functions should be accurate. It turns out the storage needed for retention is about 10MB a day. The retention values have been changed to fit this.
fixes #401 
**Checklist:**
> apps sc: change default retention values

- WIP-CHANGELOG.md
- bin/common.bash
- config/config/sc-config.yaml
- config/config/wc-config.yaml
The version validation now checks if you are at the exact tag/branch rather then just the latest tag.
fixes #189 
**Checklist:**
> apps sc & wc: fix ck8s version validate

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- config/config/wc-config.yaml
- helmfile/50-applications.yaml
- helmfile/charts/grafana-ops/Chart.yaml
- helmfile/charts/grafana-ops/dashboards/README.md
- helmfile/charts/grafana-ops/dashboards/ceph-cluster_rev14.json
- helmfile/charts/grafana-ops/dashboards/ceph-osd-single_rev5.json
- helmfile/charts/grafana-ops/dashboards/ceph-pools_rev5.json
- helmfile/charts/grafana-ops/templates/dashboard-configmap.yaml
- helmfile/charts/grafana-ops/values.yaml
- helmfile/charts/prometheus-alerts/Chart.yaml
- helmfile/charts/prometheus-alerts/files/rook-rules.yaml
- helmfile/charts/prometheus-alerts/templates/rook-monitor.yaml
- helmfile/charts/prometheus-alerts/templates/rules/rook.rules.yaml
- helmfile/charts/prometheus-alerts/values.yaml
- helmfile/values/grafana-ops.yaml.gotmpl
- helmfile/values/prometheus-alerts-sc.yaml.gotmpl
- helmfile/values/prometheus-alerts-wc.yaml.gotmpl
- helmfile/values/prometheus-user-alerts-wc.yaml.gotmpl
- migration/v0.14.x-v0.15.x/upgrade-apps.md
- migration/v0.15.x-v0.16.x/upgrade-apps.md
This adds ServiceMonitors, PrometheusRules (alerts) and Grafana dashboards for monitoring Rook-Ceph. It is based on the docs [here](https://rook.io/docs/rook/v1.6/ceph-monitoring.html) which uses the resources [here](https://github.com/rook/rook/tree/master/cluster/examples/kubernetes/ceph/monitoring).
**Which issue this PR fixes**: fixes #381
The current monitoring configuration is starting to show its limits unfortunately. We run Rook both in SC and WC. We want alerts from both instances, but we should not push these alerts to the users (and probably not the metrics either).
I'm getting a bit lost in this and there is still somethings that doesn't quite work. Some …
> Rook monitoring

- pipeline/config/exoscale/sc-config.yaml
- pipeline/config/exoscale/wc-config.yaml
Forgott pipeline config...
**Checklist:** …
> Forgott pipeline config (again) for rook monitoring

- WIP-CHANGELOG.md
- helmfile/charts/node-local-dns/templates/node-local-dns.yaml
Since we've had some issues with node-local-dns for external DNS lookup we may want to update it to see if it works better.
fixes #227  
**Checklist:**
> apps sc: update node-local-dns chart

- helmfile/50-applications.yaml
- helmfile/upstream/starboard-operator/Chart.yaml
- helmfile/upstream/starboard-operator/crds/vulnerabilityreports.crd.yaml
- helmfile/upstream/starboard-operator/values.yaml
Fixed starboard from using a too new version.
**Checklist:** …
> Fixed issue with starboard-operator

- WIP-CHANGELOG.md
- bootstrap/storageclass/helmfile/helmfile.yaml
- bootstrap/storageclass/helmfile/values/nfs-subdir-external-provisioner.yaml.gotmpl
- bootstrap/storageclass/scripts/install-storage-class-provider.sh
- helmfile/charts/common-psp-rbac/templates/nfs-client-provisioner-psp-rbac.yaml
- pipeline/test/services/service-cluster/testPodsReady.sh
- pipeline/test/services/workload-cluster/testPodsReady.sh
Replaced depricated nfs-client-provisioner to the new [nfs-subdir-external-provisioner](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/tree/master/charts/nfs-subdir-external-provisioner)
**Checklist:** …
> apps: Updated nfs provisioner to the new one

- WIP-CHANGELOG.md
- helmfile/charts/sc-logs-retention/scripts/logs-retention.sh
The sc-logs-retention CronJob failed when their was no logs to be deleted. This is now fixed.
fixes #418 
**Test** 
s3cmd -c ~/.s3cfg del --recursive s3://exoscale-sc-logs/logs/{The latest folder} until all logs are gone
./bin/ck8s ops kubectl sc create job sc-logs-retention-1 --namespace fluentd --from=cronjob/sc-logs-retention
**Checklist:**
> apps sc: logs-retention run even when their is no logs to delete

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- config/config/wc-config.yaml
- pipeline/config/exoscale/sc-config.yaml
- pipeline/config/exoscale/wc-config.yaml
**What this PR does / why we need it**: In kubespray the default ip for cluster DNS (the coredns service) is 10.233.0.3, this updates our values to match that. Without this node-local-dns is never used.
```
kubectl get svc -n kube-system
NAME                               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                        AGE
...
coredns                            ClusterIP   10.233.0.3      <none>        53/UDP,53/TCP,9153/TCP         17d
...
```
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: not planned
**Checklist:**
- Is this changeset backwards compatible for existing …
> config: update default cluster DNS IP to match kubespray defaults

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- config/config/wc-config.yaml
- helmfile/charts/cluster-admin-rbac/templates/clusterrolebindings/cluster-admin.yaml
- helmfile/charts/cluster-admin-rbac/values.yaml
- helmfile/values/cluster-admin-rbac.yaml.gotmpl
- migration/v0.16.x-v0.17.x/upgrade-apps.md
- pipeline/config/exoscale/sc-config.yaml
- pipeline/config/exoscale/wc-config.yaml
Simple option to add cluster admin groups
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: N/A
**Checklist:** …
> [1] Added possibility to specify cluster admin groups

- pipeline/apply-sc.bash
- pipeline/apply-wc.bash
- pipeline/list-releases.bash
**What this PR does / why we need it**: We removed some files from the pipeline folder that we didn't think was used. But seems like we didn't look properly. This should return the files that we need.
Here is a pipeline that failed because of the missing files: https://github.com/elastisys/compliantkubernetes-apps/actions/runs/911463783
Also see this line: https://github.com/elastisys/compliantkubernetes-apps/blob/417f3c148c6510222d0b2031ae869cc35e904045/.github/workflows/end-to-end.yml#L158
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: not planned
**Checklist:**
- Is this changeset backwards …
> pipeline: add back missing files

- .github/ISSUE_TEMPLATE/chart_upgrade.md
- .github/pull_request_template.md
As discussed during the architecture meeting on 2021-05-06, this implements a more orderly process to ensure we check migration steps when upgrading Charts.
> Add Chart Upgrade issue and PR template

- WIP-CHANGELOG.md
- config/secrets/sc-secrets.yaml
- helmfile/values/dex.yaml.gotmpl
- migration/v0.16.x-v0.17.x/dex-update-script.yaml
- migration/v0.16.x-v0.17.x/migrate-dex-additional-static-clients.sh
- migration/v0.16.x-v0.17.x/upgrade-apps.md
- pipeline/config/exoscale/secrets.yaml
In this PR I've added `dex.additionalStaticClients` to be able to specify Dex clients for application that do not belong to CK8s. More details in #456.
This PR also contains a migration script that will pull any custom static clients already defined for Dex and move it into the `secrets.yaml` at the appropriate place.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #456
**Checklist:**
will not be responding …
> Enable additional static clients for dex

- WIP-CHANGELOG.md
- bin/apps.bash
- bin/ck8s
- bin/dry-run.bash
- scripts/deploy-sc.sh
- scripts/deploy-wc.sh
The dry-run.sh and deploy scripts we currently use will not check against the actual state of the cluster. We are now adding commando flags to enable the option of using sync if a user want to.
fixes #382
**Message to reviewers**
Im not sure if this is the right way to do it. This was the closest i could figure out. Feel free to point me out in the right direction if needed.
**Checklist:**
> apps sc & wc: improve dry-run and deploy scripts

- WIP-CHANGELOG.md
- helmfile/values/blackbox.yaml.gotmpl
- migration/v0.16.x-v0.17.x/upgrade-apps.md
Blackbox-exporter checks harbor endpoint even if harbor is disabled. This is now disabled if harbor is disabled.
fixes #482 
**Checklist:**
> apps sc: if-case for if harbor is enabled or not in blackbox-exporter

- scripts/S3/entry.sh
To make the S3 scripts safer.
This just adds some more output to the entry script:
- Print buckets the will be operated on
- Print which s3cfg config is used
- Print command executed - this really contains the above information as well
fixes #424 
Printing region or endpoint is not very useful imo as that would require the script to parse the s3cfg file.
I find it more sensical to really just present that "Hey, this is the s3cfg file you passed", if you need more information then a simple cat should do :)
I did not create a Yes/no promt for creating buckets as that is not really an intrusive operation.
Feedback appreciated :) 
**Example run**:
**Checklist:**
- Is this changeset backwards …
> bin: Make S3 entry script more verbose

- WIP-CHANGELOG.md
- helmfile/values/opendistro-es.yaml.gotmpl
- migration/v0.16.x-v0.17.x/migrate-openid.sh
- migration/v0.16.x-v0.17.x/upgrade-apps.md
In my work with the release, i discovered that the port used for connecting with openid for authentication have been changed from 32000 to 5556. This made the authentication for Kibana fail.
fixes #503 
**Checklist:**
> apps sc: openid url port fix

- WIP-CHANGELOG.md
- helmfile/charts/sc-logs-retention/scripts/logs-retention.sh
Right now, all logs doesn't get removed at the same time which results in that the job have to be ran multiple times potentially. This is now fixed by adding a while-loop with a 5 second delay.
fixes #340 
**Checklist:**
> apps sc: sc-log-retention deletion fix

- WIP-CHANGELOG.md
- helmfile/elastisys/opendistro-es/templates/curator/curator-cm.yaml
Bug fix that made curator always fail when enabling postgres retention.
The `toYaml` function added a `|` to the config which would render it a unvalid yaml
Diff after applying, highlighting the issue.
```
source: creation_date
direction: older
unit: days
unit_count: 30
- filtertype: kibana
exclude: True
-       |
+   
9:
action: delete_indices
description: "Clean up the oldest postgresql-* indices that exceeds total disk space 30 GB"
```
**Checklist:**
- Is this changeset backwards compatible for …
> Fixed issue where curator would fail to start with postgres enabled

- migration/v0.16.x-v0.17.x/migrate-openid.sh
- migration/v0.16.x-v0.17.x/upgrade-apps.md
Fixes from QA. Finale push for release! :-D
**Checklist:** …
> apps sc & wc: release 0.17 fixes

- helmfile/50-applications.yaml
**What this PR does / why we need it**: We noticed that the `user-alertmanager` has a dependency on `user-barc` if you put the alertmanager in one of the users namespaces, because then there is a race condition where the alertmanager tries to be installed before the namespaces is created.
**Checklist:** …
> apps wc: add dependency on user-rbac for alertmanager

- WIP-CHANGELOG.md
- helmfile/values/ingress-nginx.yaml.gotmpl
**What this PR does / why we need it**: to decrease the number of warnings generated by nginx for elastic and influxdb hosts when request body is larger than the buffer
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #537 
client_body_buffer_size default value is 16K (buffer size is equal to two memory pages.) on a 64-bit platform. In case the request body is larger than the buffer, the whole body or only its part is written to a temporary file and a warning message is logged.
Increasing it from 64k to 256k seems to solve the issue on an dev cluster with low load.
**Caution**: settings this …
> Nginx client body buffer size

- WIP-CHANGELOG.md
- config/config/wc-config.yaml
- pipeline/config/exoscale/wc-config.yaml
**What this PR does / why we need it**: Falco have been requesting way too much memory, which is a bit of a problem since it is running on all nodes. 
I have looked at several clusters over a longer period of time. Falco usually uses less than 100MB and I have never seen it go above 150 MB, so this seemed like reasonable values.
**Checklist:** …
> apps wc: lowered default resource request based on running clusters

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/values/opendistro-es.yaml.gotmpl
- pipeline/config/exoscale/sc-config.yaml
This pr allows to configure elasticsearch ingress max body size via `elasticsearch.ingress.maxBodySize`.
fixes #514
**Checklist:** …
> apps sc: Configuration max body for elasticsearch

- WIP-CHANGELOG.md
- helmfile/charts/user-rbac/templates/clusterroles/user-view.yaml
Allow users to get/list PVs.
fixes #521
Before Apply:
```
$ kubectl auth can-i get persistentvolumes --as=admin@example.com
Warning: resource 'persistentvolumes' is not namespace scoped
no
```
```
$ kubectl get pv --as=admin@example.com
Error from server (Forbidden): persistentvolumes is forbidden: User "admin@example.com" cannot list resource "persistentvolumes" in API group "" at the cluster scope
```
After Apply:
```
$ kubectl auth can-i get persistentvolumes --as=admin@example.com
Warning: resource 'persistentvolumes' is not namespace scoped
yes
```
```
$ kubectl get pv --as=admin@example.com
NAME …
```
> apps wc: allow users to view PVs

- WIP-CHANGELOG.md
- config/config/flavors/prod-wc.yaml
- config/config/wc-config.yaml
- helmfile/charts/user-rbac/templates/clusterrolebindings/user-view.yaml
- helmfile/charts/user-rbac/templates/rolebindings/workload-admin.yaml
- helmfile/charts/user-rbac/values.yaml
- helmfile/values/user-rbac.yaml.gotmpl
- pipeline/config/exoscale/wc-config.yaml
Since users might want to use a admin group rather than specific users we should allow for that
**Checklist:** …
> Added user rbac groups

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/values/elasticsearch-slm.yaml.gotmpl
- pipeline/config/exoscale/sc-config.yaml
Taking snapshots in elasticsearch takes longer than the default configured deadline of 10 minutes.
This results in false-postive failed SLM retention jobs, which is annoying.
This PR makes the deadline for the SLM configurable via `elasticsearch.snapshot.retentionActiveDeadlineSeconds` option.
```
❯ curl -u admin:`sops -d secrets.yaml | yq r - elasticsearch.adminPassword` https://elastic.`yq r wc-config.yaml global.opsDomain`/_cat/snapshots/elastic-snapshots/?v
id                         status start_epoch start_time end_epoch  end_time duration indices successful_shards failed_shards total_shards
snapshot-20210801_120004z SUCCESS 1627819205  12:00:05   1627820374 12:19:34    19.4m     206               206             0          206
```
**Which …
> apps sc: Make deadline configurable for the SLM job

- WIP-CHANGELOG.md
- helmfile/values/prometheus-elasticsearch-exporter.yaml.gotmpl
When changing the scrape timeout for prometheus-elasticsearch-exporter, the timeout is currently only changed in the service monitor and not in the exporter itself. These timeouts need to be synched. This is fixed by setting the timeout of the exporter to be 5s lower than the service monitor programmatically.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #511 
**Checklist:**
I.e. full …
> apps sc: prometheus-elasticsearch-exporter timeout fix

- WIP-CHANGELOG.md
- config/config/wc-config.yaml
- helmfile/values/falco-exporter.yaml.gotmpl
- pipeline/config/exoscale/wc-config.yaml
Adds configuration properties for falco-exporter from wc-config.yaml.
fixes #218
Added in my wc-config.yaml
```
...
falcoExporter:
resources:
limits:
cpu: 20m
memory: 50Mi
requests:
cpu: 10m
memory: 25Mi
...
```
```
$ ./bin/ck8s ops helmfile wc -l app=falco-exporter diff
...
resources:
-             {}
+             limits:
+               cpu: 100m
+               memory: 128Mi
+             requests:
+               cpu: 100m
+               memory: 128Mi
...
```
**Checklist:**
will not be …
> apps wc: added configuration for falco-exporter

- WIP-CHANGELOG.md
- helmfile/values/fluentd-configmap.yaml.gotmpl
- helmfile/values/fluentd-wc.yaml.gotmpl
**What this PR does / why we need it**: to fix the kube-audit time key
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes 188 from ck8s-apps 
Previously we were using time for the kube-audit time_key. This key is not available in the kube-audit logs so the current time was used.
I replaced with requestReceivedTimestamp - Time the request reached the apiserver.
The full list of events can be viewed here: [kube-apiserver Audit Configuration](https://kubernetes.io/docs/reference/config-api/apiserver-audit.v1/)
**Checklist:**
E.g. logs or metrics are not being collected or …
> apps: fluentd for kube-audit fixed the time key

- WIP-CHANGELOG.md
- config/secrets/sc-secrets.yaml
Adding JumpCloud as IDP
fixes #561
There is a document describing how to create a bind user and other users in Jumpcloud: [JumpCloud Dex](https://docs.google.com/document/d/1fRJUMmdgBl2_QFwtld81951dx1wctN4W5H_1W1g223A/edit#). 
Please also take a look at it.
**Checklist:** …
> apps sc: Added JumpCloud as a IDP

- WIP-CHANGELOG.md
- helmfile/50-applications.yaml
As of now, authentication by dex in Kibana doesn't work without restarting Kibana on a completely fresh cluster. This makes opendistro-es be installed when dex is ready.
fixes #523 
**Checklist:**
> apps sc: apply dex kibana fix

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
- pipeline/config/exoscale/sc-config.yaml
At the moment we have hardcoded values for the group_by config in alertmanager. This makes it configurable values in sc-config.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #540 
This issue is on re-evaluation. No hurry to review it.
**Checklist:**
> apps sc: group_by in alertmanager made configurable

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/values/fluentd-sc.yaml.gotmpl
- pipeline/config/exoscale/sc-config.yaml
This allow us to set the `chunk_limit_size` and `queue_limit_length` from the `sc-config`.  Set these to a reasonable size for the clusters so that fluentd does not complain about `record is larger than buffer chunk limit size`.
fixes #586
This does not fix the problem of crash-loop. That is a separat issue.
**Checklist:** …
> apps sc: Added buffer configuration for fluentd

- WIP-CHANGELOG.md
- helmfile/charts/harbor-backup/templates/harbor-backup-job.yaml
- scripts/restore/README.md
- scripts/restore/restore-harbor-job.yaml
- scripts/restore/restore-harbor.sh
This PR converts the harbor backup script into a k8s job. This reduces the need to have aws cli and postgres installed locally. Also the documentation on how to restore a backup has been updated, including from specific backups.
It also include a fix for harbor backup job, ensuring it run as a non-root user. 
**Which issue this PR fixes** : 
fixes #386
Tried on safespring with no specific backup and specific backup set. Both worked.
**Checklist:**
E.g. removes or changes any CK8S …
> apps sc: reworked harbor restore script

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/values/fluentd-sc.yaml.gotmpl
- pipeline/config/exoscale/sc-config.yaml
Fluentd sometimes stalls which makes the liveness probe believe it is dead with its default configured timeouts. Leading to alerts and situations where it has to be manually restarted.
This PR makes the timeouts configurable under the `fluentd.forwarder.livenessProbe` which allows this to be tuned.
This PR also includes an increased deadline for the SLM job, as some do take long enough to be failed. 
For now the liveness probe is only set to the default values, as I have no understanding of how long …
> apps sc: Make fluentd liveness probe configurable

- README.md
**What this PR does / why we need it**: This PR fixes the filename used in a command generating S3 config file
**Checklist:** …
> docs: fix S3 config generation command

- WIP-CHANGELOG.md
- config/config/flavors/dev-sc.yaml
- config/config/sc-config.yaml
- config/config/wc-config.yaml
- helmfile/charts/vulnerability-exporter/templates/deployment.yaml
- helmfile/values/blackbox.yaml.gotmpl
- helmfile/values/grafana-user.yaml.gotmpl
- helmfile/values/influxdb.yaml.gotmpl
- helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
- helmfile/values/kube-prometheus-stack-wc.yaml.gotmpl
- helmfile/values/metrics-server.yaml.gotmpl
- helmfile/values/vulnerability-exporter.yaml.gotmpl
- pipeline/config/exoscale/sc-config.yaml
- pipeline/config/exoscale/wc-config.yaml
**What this PR does / why we need it**: added resources requests for apps
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #580 and #545 
- the values for the resource requests and limits are based on what I observed on 3 prod cluster;
- the remaining containers without resource requests are rook-ceph (I will fix them from the kubespray repo);
- I didn't find a solution for adding resource requests to kube-proxy, kube-apiserver, kube-scheduler and kube-controller. The manifests from kubernetes do not contain this fields and cannot be added or costumized via kubeadm.
- sc:
- wc:
**Checklist:** …
> Add resource requests

- WIP-CHANGELOG.md
- helmfile/charts/grafana-ops/dashboards/elasticsearch-dashboard.json
- helmfile/charts/grafana-ops/dashboards/kubernetesstatus-dashboard.json
- helmfile/charts/grafana-ops/dashboards/uptime-dashboard.json
**What this PR does / why we need it**: to fix some issues with the grafana dashboards
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #534 and fixes #439 
Below you can find the changes:
1. **Uptime and status dashboard**
- edit the value mapping to map "null+nan" to "N/A"
- updated the Up panel from "Graph (old)" to "Time series" visualization
- set "timezone": "utc"
- set "time": "from": "now-1h"
- set "refresh": "30s"
2. **ElasticSearch dashboard**
- updated the panels from "Graph (old)" to "Time series" visualization
- added a description for some of the panels
- fixed the panels that …
> Grafana dashboards fixes

- WIP-CHANGELOG.md
- helmfile/values/velero.yaml.gotmpl
- migration/v0.17.x-v0.18.x/remove-velero-backupstoragelocation.sh
- migration/v0.17.x-v0.18.x/upgrade-apps.md
Removed warning from velero which said that `The specified default backup location named \"default\" was not found`. 
fixes #519
Should be investigated if it can be reverted once velero v1.6 is used. 
**Checklist:** …
> apps sc: fixed warning for velero backup location

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- config/config/wc-config.yaml
- pipeline/config/exoscale/sc-config.yaml
- pipeline/config/exoscale/wc-config.yaml
We noticed during migration from rook to cinder using Velero that it required a higher limit to succeed.
fixes #
**Checklist:**
If you change some config options (e.g. add/rename variable or change the default value) you may need to update the config used by the pipeline …
> apps: Increased Velero and Restic limits

- WIP-CHANGELOG.md
- helmfile/values/cert-manager.yaml.gotmpl
- helmfile/values/falco.yaml.gotmpl
- helmfile/values/falcosidekick.yaml.gotmpl
- helmfile/values/fluentd-user.yaml.gotmpl
- helmfile/values/fluentd-wc.yaml.gotmpl
- helmfile/values/prometheus-elasticsearch-exporter.yaml.gotmpl
**What this PR does / why we need it**: the pods for fluentd and falco weren't created due to the missing psp
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #610 
**Checklist:** …
> apps: enabled PSP in some helm charts

- helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
Fix of https://github.com/elastisys/compliantkubernetes-apps/pull/578
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #540
Needed to fix the pipeline
**Checklist:**
> apps sc: group_by in alertmanager made configurable fix

- release/README.md
This updates the release documents to include updating the user-facing release notes.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes elastisys/compliantkubernetes#148
**Checklist:**
If you …
> docs: Update release document to include user-facing release notes

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- config/config/wc-config.yaml
- helmfile/50-applications.yaml
- helmfile/values/grafana-user.yaml.gotmpl
- helmfile/values/velero-sc.yaml.gotmpl
- helmfile/values/velero-wc.yaml.gotmpl
- pipeline/config/exoscale/sc-config.yaml
- pipeline/config/exoscale/wc-config.yaml
All user namespaces are now backed up by default. It is possible to opt-out using the label `nobackup: velero`. 
Also restic volume backup is now on by default.
fixes #608
See [#183](https://github.com/elastisys/compliantkubernetes/pull/183) for compliantkubernetes.io update
Images showing that velero did a daily backup on the user namespaces and that the pods with the label `nobackup: velero` was skipped.
Pod included
Pod excluded
Backup describe
Backup described with details about pods
Backup described with details about restic
**Checklist:**
E.g. logs or …
> apps: restic and opt-out velero backups wc

- helmfile/charts/prometheus-servicemonitor/values.yaml
- helmfile/values/sc-servicemonitor.yaml.gotmpl
- helmfile/values/wc-servicemonitor.yaml.gotmpl
Needed to render the prometheus-servicemonitor chart with rook monitor enabled, occurs after the split of alerts/servicemonitors.
I don't really know if the labels are used or if they should have a different value, but with this they will have the same as they would have had before the split.
**Checklist:**
> apps: Add missing value for prometheus-servicemonitor

- migration/v0.17.x-v0.18.x/remove-velero-backupstoragelocation.sh
- migration/v0.17.x-v0.18.x/upgrade-apps.md
**What this PR does / why we need it**: QA: A few minor fixes I noticed were necessary while doing the migration steps.
**Checklist:** …
> all: update 0.17-0.18 migration guide and script

- config/config/sc-config.yaml
I noticed during deployment of user-demo that harbor had some troubles. It keept logging me out, scanning images and accepting pushing of layers.
**Checklist:**
**Pipeline …
> apps sc: increase harbor limits even more

- WIP-CHANGELOG.md
- helmfile/charts/grafana-ops/dashboards/falco-dashboard.json
Right now in the current falco dashboard, instead of giving the name of the misbehaving pod, the name of the reporting pod is given. This is fixed by changing "hostname" to "k8s_pod_name" and also add "instance" to make it possible to trace the pod host in case the misbehaving pod name is missing.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #400
**Checklist:** …
> apps sc: grafana falco dashboard legend fix

- WIP-CHANGELOG.md
I messed up and managed to merge the old WIP-CHANGELOG into the new one in my latest merge. This needs to be fixed.
**Checklist:**
If you …
> apps sc: fix WIP-CHANGELOG.md

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/values/grafana-user.yaml.gotmpl
- helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
This adds and enables the option for Grafana Viewers to temporarily edit dashboards and panels without saving.
Fixes #687
**Checklist:**
**Pipeline config**:
Picked up by init.
> apps sc: Add and enable Viewers can edit in Grafana

- WIP-CHANGELOG.md
- helmfile/values/grafana-user.yaml.gotmpl
- helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
**What this PR does / why we need it**: fixes grafana [security bug](https://grafana.com/blog/2021/12/07/grafana-8.3.1-8.2.7-8.1.8-and-8.0.7-released-with-high-severity-security-fix/?utm_source=tw&utm_medium=social)
**Checklist:** …
> apps: grafana security fix

- helmfile/values/fluentd-user.yaml.gotmpl
- helmfile/values/fluentd-wc.yaml.gotmpl
Installing apps on master does not work as it fails to install fluentd in the workload cluster.
This is because enabling the servicemonitor also creates a service which looks exactly the same as the one you get when specifying 
```bash
service:
ports:
- name: metrics
type: ClusterIP
port: 24231
```
I decided to remove that snippet from the values files as it still works to get metrics even if you don't have the port specifiction in the daemonset.
```diff
ports:
-           - name: metrics
-             containerPort: 24231
```
fixes #683 
**Checklist:**
E.g. logs …
> apps wc: fix fluentd in wc not being installable

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- config/config/wc-config.yaml
- helmfile/charts/prometheus-alerts/templates/rules/node-exporter.yaml
- helmfile/charts/prometheus-alerts/templates/rules/predict-linear.yaml
- helmfile/charts/prometheus-alerts/values.yaml
- helmfile/values/prometheus-alerts-sc.yaml.gotmpl
- helmfile/values/prometheus-alerts-wc.yaml.gotmpl
- pipeline/config/exoscale/sc-config.yaml
- pipeline/config/exoscale/wc-config.yaml
We need to improve our capacity management posture. While the Kubernetes status dashboards help, it would be great to improve scalability by avoiding more daily checks and getting P2 (requires attention within 24 hours) alert. Therefore, new rules have been added to forewarn against when memory and disk (PVC and host disk) capacity is predicted to hit 66% in 3 days. CPU alert triggers when the CPU usage has been over eighty percent on average over the span of 24h.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #625
The CPU rule couldn't be written …
> apps sc: predict linear rules

- WIP-CHANGELOG.md
- config/config/common-config.yaml
- helmfile/values/ingress-nginx.yaml.gotmpl
So we could whitlist IP address to the loadbalancer service.
fixes #
Two commits so it is possible to cherrypick for older versions of apps.
**Checklist:** …
> apps: ingres nginx lb sourceranges

- WIP-CHANGELOG.md
- helmfile/charts/prometheus-alerts/values.yaml
- helmfile/values/prometheus-user-alerts-wc.yaml.gotmpl
Fixes the prometheus alert rule so it properly renders and get admitted by the operator.
**Checklist:** …
> apps wc: Fix prometheus alert not rendering

- WIP-CHANGELOG.md
- helmfile/values/s3-exporter.yaml.gotmpl
Just a small fix to sort the results of the values function to make it consistent whenever s3-exporter is reapplied.
**Public facing documentation PR**:
**Checklist:**
> apps sc: Fix rendering of s3-exporter to be idempotent

- README.md
- WIP-CHANGELOG.md
- get-requirements.yaml
- pipeline/Dockerfile
**What this PR does / why we need it**: updated the kubectl version to v1.20.7
https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
**Checklist:**
> docs: updated the kubectl version

- WIP-CHANGELOG.md
- bin/init.bash
- pipeline/init.bats
When initing a config path the second time without the `CK8S_FLAVOR` variable set it fails. This fixes that.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #727
**Checklist:**
If you change …
> Fixed flavor issue with init script

- WIP-CHANGELOG.md
- helmfile/charts/prometheus-servicemonitor/templates/cert-monitor.yaml
- helmfile/charts/prometheus-servicemonitor/values.yaml
- helmfile/values/sc-servicemonitor.yaml.gotmpl
The relabelings for the cert-manager and rook service monitors are not correct
fixes #721
Notice in second image the addition of cluster: service_cluster
Before:
After:
**Checklist:** …
> apps: added relabling for rook/cert servicemonitor

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/values/harbor-backup.yaml.gotmpl
- pipeline/config/exoscale/sc-config.yaml
This PR exposes Harbor's backup retention period through Config. 
**Which issue this PR fixes** : fixes #698 
**Checklist:**
> apps sc: added backup retention in config

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- config/secrets/sc-secrets.yaml
- helmfile/50-applications.yaml
- helmfile/charts/grafana-ops/dashboards/backup-dashboard.json
- helmfile/charts/grafana-ops/templates/configmap-dashboards.yaml
- helmfile/charts/grafana-ops/values.yaml
- helmfile/charts/rclone-sync/Chart.yaml
- helmfile/charts/rclone-sync/Dockerfile
- helmfile/charts/rclone-sync/files/rclone.conf
- helmfile/charts/rclone-sync/templates/cronjob.yaml
- helmfile/charts/rclone-sync/templates/rclone-config.yaml
- helmfile/charts/rclone-sync/values.yaml
- helmfile/values/grafana-ops.yaml.gotmpl
- helmfile/values/rclone-sync.yaml.gotmpl
Upstreams the work done on enabling off-site backup replication using rclone sync.
Includes additional section in the "Backup status" dashboard to show the
state of it and successful sync jobs.
fixes #318 
Pictures of dashboard additions, note that the text has been changed to "Off-site backup replication is..." instead to make it a bit clearer.
Enabled, with one suspended cronjob:
Disabled, with all cronjobs and jobs removed:
The state of the cronjobs and jobs are extracting the bucket name using a regex, and it has been tested to work with a suffix containing `manual`.
**Checklist:**
- Is this changeset backwards compatible for …
> apps sc: Add off-site backup replication using rclone sync

- WIP-CHANGELOG.md
- config/config/common-config.yaml
- config/config/flavors/prod/sc-config.yaml
- config/config/wc-config.yaml
**What this PR does / why we need it**: there were a lot of issues cause by resource requests or limits values
**Checklist:**
> apps: updated the default resources

- WIP-CHANGELOG.md
- config/config/common-config.yaml
- helmfile/values/velero-sc.yaml.gotmpl
- helmfile/values/velero-wc.yaml.gotmpl
This PR expose velero's backup retention as config 
**Which issue this PR fixes** : fixes #697
**Checklist:**
> apps: Expose velero's backup retention

- WIP-CHANGELOG.md
- helmfile/values/opensearch/common.yaml.gotmpl
- migration/v0.18.x-v0.19.x/opensearch-migration-run.sh
- migration/v0.18.x-v0.19.x/upgrade-apps.md
Some fixes for OpenSearch:
- Enable the OpenSearch migration script to run on dev clusters that don't use snapshots.
- Enable OpenSearch to actually run without snapshots enabled.
- Give the init container permission to actually use sysctl (thanks busybox for making that error silent :sweat_smile:).
Indentation is off, but I didn't want to spend too much time fixing it as I would have to rewrite big chunks of it.
**Checklist:**
- …
> apps sc: OpenSearch bugfixes

- WIP-CHANGELOG.md
- helmfile/values/influxdb.yaml.gotmpl
- migration/v0.18.x-v0.19.x/upgrade-apps.md
**What this PR does / why we need it**: to disable internal database on influxsb
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #743 
**Special notes for reviewer**: i didn't find a  "nicer" way to reload the config on influx
**Checklist:**
If you change some config options (e.g. add/rename variable or change the …
> apps sc: disabled internal database on influxdb

- pipeline/test/services/service-cluster/testPodsReady.sh
Fix OpenSearch client tests
Missed that it was deployed as a StatefulSet rather than Deployment.
**Checklist:**
> tests: Fix OpenSearch client tests

- WIP-CHANGELOG.md
- config/config/wc-config.yaml
Since the blocking issue has been resolved, we should now enforce (deny) opa policies for the prod flavor.
fixes #19
**Checklist:**
If you change …
> apps: enforce opa policies in prod flavor

- helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
**What this PR does / why we need it**: we want to set clusterName as cluster label for service cluster when writing data to Thanos
**Checklist:**
> apps: set clusterName for sc cluster label in thanos

- helmfile/charts/opensearch/curator/values.yaml
The client library was updated in recent releases containing the non-Elasticsearch server check.
**Checklist:** …
> apps sc: Pin Elasticsearch Curator version

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/values/sc-logs-retention.yaml.gotmpl
- migration/v0.19.x-v0.20.x/move_log_retention_days.sh
- migration/v0.19.x-v0.20.x/upgrade-apps.md
Exposed the sc-log-retention resource requests. As i have noticed that sc-logs-retention job is throttled.  
**Checklist:**
If you change …
> apps sc: expose sc-log-retention jobs resource requests

- WIP-CHANGELOG.md
- helmfile/values/dex.yaml.gotmpl
See #680 
fixes #680 
Test (the same test at Cristian did in the issue):
```
❯ diff -y before-keys.json after-keys.json 
{								{
"keys": [							 "keys": [
{								   {
"use": "sig",						     "use": "sig",
"kty": "RSA",						     "kty": "RSA",
"kid": "6a33a10b93067988e6b320399c17e645f765fb87",      |	     "kid": "485d638a1309f9fa670ec5095a342253a5c7f739",
"alg": "RS256",						     "alg": "RS256",
"n": "19lpWXTZdw37C2c5wtNrdwPwcpk1vIZJeoBxKEEcvpsQ2fiWL |	     "n": "yC9CDsranNlnVyK6qQN67nMN_kGyIf5kcdBDonoxPKpinjTOD
"e": "AQAB"						     "e": "AQAB"
}								   }
]								 ]
}								}
❯ diff -y dex-after-crds/before-keys.json …
```
> apps-sc: Enable dex kubernetes persistence

- WIP-CHANGELOG.md
- helmfile/charts/grafana-ops/dashboards/backup-dashboard.json
This PR adds a new panel to reflect veleros partial, failed and successful backups
**Which issue this PR fixes** : fixes #733
**Checklist:** …
> apps: backup dashboard now reflects partial and failed backups

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
We had the issue of that all FalcoAlerts came in the same alert, not separated by a rule. Now, a separation of rules has been made. There are 12 different falco-rules.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #696
**Checklist:** …
> apps sc: falco alert group-by

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/charts/opensearch/slm/scripts/slm-retention.bash
- helmfile/charts/opensearch/slm/templates/cronjob.yaml
- helmfile/charts/opensearch/slm/values.yaml
- helmfile/values/opensearch/slm.yaml.gotmpl
Have noticed that slm jobs crashes because of error 28 which is curls error code for timeout. As such i exposed the max seconds for requests for curl. Also changed --silent to --no-progress-meter to make the curl request more verbose. 
From curl man:
```
--no-progress-meter
Option to switch off the progress meter output without muting or 
otherwise affecting warning and informational messages like --silent does.
```
```
Error code 28
Operation timeout. The specified time-out period was reached according to the conditions.
```
```
kubectl describe pod -n elastic-system elasticsearch-slm-manual-x9kpc
Name:         elasticsearch-slm-manual-x9kpc
Namespace:    elastic-system
...
Status:       Succeeded
IP:           10.233.115.12
IPs:
IP: …
```
> apps sc: expose max seconds for curl and verbose curl for slm job

- WIP-CHANGELOG.md
- helmfile/values/opensearch/configurer.yaml.gotmpl
This PR allows fluentd to create and write to .orphaned indexes
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #746 
**Checklist:** …
> apps: fluentd can now create and write to .orphaned indexes

- WIP-CHANGELOG.md
This PR fixes a mistake in Readme.
**Checklist:** …
> Readme mistake

- WIP-CHANGELOG.md
- helmfile/50-applications.yaml
- helmfile/upstream/prometheus-elasticsearch-exporter/Chart.yaml
- helmfile/upstream/prometheus-elasticsearch-exporter/README.md
- helmfile/upstream/prometheus-elasticsearch-exporter/ci/pod-security-policies.yaml
- helmfile/upstream/prometheus-elasticsearch-exporter/templates/_helpers.tpl
- helmfile/upstream/prometheus-elasticsearch-exporter/templates/deployment.yaml
- helmfile/upstream/prometheus-elasticsearch-exporter/templates/role.yaml
- helmfile/upstream/prometheus-elasticsearch-exporter/templates/rolebinding.yaml
- helmfile/upstream/prometheus-elasticsearch-exporter/templates/serviceaccount.yaml
- helmfile/upstream/prometheus-elasticsearch-exporter/values.yaml
- helmfile/values/prometheus-elasticsearch-exporter.yaml.gotmpl
This PR upgrades prometheus-elasticsearch-exporter to v4.11.0 
**Which issue this PR fixes** : fixes #826 
**Checklist:**
> apps: upgrade prometheus-elastic-search exporter

- WIP-CHANGELOG.md
- config/config/wc-config.yaml
- helmfile/charts/gatekeeper-constraints/templates/disallow-tag/constraint.yaml
- helmfile/charts/gatekeeper-constraints/values.yaml
- helmfile/charts/gatekeeper-templates/policies/disallow-tag.rego
- helmfile/charts/gatekeeper-templates/policies/tests/disallow-tag.rego
- helmfile/charts/gatekeeper-templates/templates/disallow-tag/template.yaml
- helmfile/values/gatekeeper-constraints.yaml.gotmpl
**What this PR does / why we need it**: New OPA policy - Disallow latest image tag . 
I have upgraded the charts and not sure if the migrations steps is needed or not . Please review and suggest that too . 
**Checklist:** …
> apps WC : New OPA policy disallow latest image tag

- WIP-CHANGELOG.md
- config/config/common-config.yaml
- config/config/sc-config.yaml
- helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
- migration/v0.19.x-v0.20.x/move-alertmanager-groupby.sh
- migration/v0.19.x-v0.20.x/upgrade-apps.md
Moved alertmanager from user to prometheus
**Which issue this PR fixes**: fixes #755
**Checklist:**
> apps sc: move alertmanager group by

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/values/grafana-user.yaml.gotmpl
- migration/v0.19.x-v0.20.x/move-usergroups-user-grafana.sh
- migration/v0.19.x-v0.20.x/upgrade-apps.md
Move the userGroups for user grafana under oidc path. To unify the config with ops grafana.
**Which issue this PR fixes**: fixes #846
**Checklist:** …
> apps sc: move user grafana groups path under oidc

- WIP-CHANGELOG.md
- bin/kubeconfig.bash
This is changed to have https://github.com/elastisys/ck8s-ops/pull/835 work. Check it out to read the details.
**Checklist:**
If you change …
> secret structure for kubeconfig.bash

- scripts/restore/README.md
**What this PR does / why we need it**: use s3cmd instead of aws s3 when listing harbor backups
**Checklist:**
> docs: use s3cmd instead of aws s3 when listing backups

- config/config/common-config.yaml
- config/config/wc-config.yaml
**What this PR does / why we need it**: to avoid any mistakes and setup the custom registry for cert-manager acme image for both sc and wc, I moved the example from common-config.yaml to wc-config.yaml
**Special notes for reviewer**: let me know if you have a better idea on how to do this
**Checklist:** …
> config: moved custom acme example to wc config

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
**What this PR does / why we need it**: 
1. I noticed that thanos receiver needs a bigger volume
2. during a recovery process thanos-receiver-receive-distributor needed more memory, so I increased the limit
**Checklist:** …
> config: increased thanos resources

- WIP-CHANGELOG.md
- helmfile/charts/grafana-ops/dashboards/fluentd-dashboard.json
- helmfile/charts/grafana-ops/values.yaml
- helmfile/charts/prometheus-alerts/README.md
- helmfile/charts/prometheus-alerts/templates/rules/fluentd.yaml
- helmfile/charts/prometheus-alerts/values.yaml
- helmfile/values/grafana-ops.yaml.gotmpl
**What this PR does / why we need it**: adds alerts and a Grafana dashboards for flunetd
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #781 
**Checklist:**
**Screenshots** …
> apps sc: fluentd alerts and dashboard

- WIP-CHANGELOG.md
- config/config/common-config.yaml
- helmfile/values/fluentd-configmap.yaml.gotmpl
- helmfile/values/fluentd-user.yaml.gotmpl
- helmfile/values/fluentd-wc.yaml.gotmpl
- migration/v0.19.x-v0.20.x/upgrade-apps.md
To support kubespray 2.18 where containerd cri is default we want containerd support
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #815 
**Checklist:** …
> apps: Updated fluentd filter to match cri logformat

- WIP-CHANGELOG.md
- helmfile/values/fluentd-user.yaml.gotmpl
When gatekeeper-controller-manager starts up it prints the line below. Which includes `"source":{}`
```bash
{"level":"info","ts":1646635981.7427528,"logger":"controller","msg":"Starting EventSource","controller":"cert-rotator","source":{}}
```
Later `source` is a string. This messes with opensearch when it should index source.
This time it had set `source` as `text` which gives an error when gatekeeper started up.
```
'failed to parse field [source] of type [text] in document with id 'C9MfVH8Bb86XbYgaCkxr'. Preview of field's value: '{}''\"
```
I decided to exclude the log lines with `"source":{}` from getekeeper to opensearch. To remove this error. 
**Which issue this PR fixes**: fixes #811 …
> apps wc: fixed gatekeeper log fails to be indexed

- helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
- helmfile/values/kube-prometheus-stack-wc.yaml.gotmpl
**What this PR does / why we need it**: Since the `storageClasses.nfs` and `nfsProvisioner` values were removed from the config in PR https://github.com/elastisys/compliantkubernetes-apps/pull/879, this prevents the `kube-prometheus-stack` chart from trying to use these now non-existent values.
**Checklist:**
- Chart …
> apps: remove nfs config from kube-prometheus-stack

- WIP-CHANGELOG.md
- config/config/wc-config.yaml
**What this PR does / why we need it**: Adding this new repo - `quay.io/jetstack/cert-manager-acmesolver`  in safeguard else creation of certificate will be blocked . 
**Checklist:**
- …
> apps-wc: adding-new-repo-safeguard-default

- WIP-CHANGELOG.md
- config/config/wc-config.yaml
- helmfile/values/velero-wc.yaml.gotmpl
The operator namespaces cant be backuped currently. This change adds the option to add namespaces you want as an extra parameter in velero.veleroNamespaces.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #835
**Checklist:**
I.e. full …
> apps wc: backup operator namespaces

- config/config/wc-config.yaml
**What this PR does / why we need it**: As requested by CK , added the comment why we added this repo - ` quay.io/jetstack/cert-manager-acmesolver` . 
**Checklist:**
- Chart checklist …
> apps-wc: adding-comment-on-new-repo-added-safeguard

- WIP-CHANGELOG.md
- helmfile/charts/grafana-label-enforcer/templates/deployment.yaml
```
❯ sudo docker pull quay.io/prometheuscommunity/prom-label-proxy@sha256:574bc3be1e514767530d555097e2ff01a774b2c9a04b9327810619cb9cbee721
Error response from daemon: manifest for quay.io/prometheuscommunity/prom-label-proxy@sha256:574bc3be1e514767530d555097e2ff01a774b2c9a04b9327810619cb9cbee721 not found: manifest unknown: manifest unknown
```
**Checklist:** …
> apps sc: user master tag in grafana label enforcer

- WIP-CHANGELOG.md
- helmfile/charts/opensearch/curator/templates/configmap.yaml
Makes curator always complete sucessfully.
This means that there won't be any failed curator jobs.
We have alerts in this repository that warns about high disk usage, and eluding such an alert back to curator failing isn't that hard.  
fixes #750 
Works as expected
```
$ k -n opensearch-system logs -f ct-tbb2n
...
2022-03-15 15:21:57,060 INFO      Trying Action ID: 8, "delete_indices": Delete authlog-* indices that are older than 1 days
2022-03-15 15:21:57,746 INFO      Deleting 29 selected indices: ['authlog-default-2022.03.01-000037', 'authlog-default-2022.02.17-000025', 'authlog-default-2022.03.12-000048', 'authlog-default-2022.02.22-000030', 'authlog-default-2022.03.14-000050', …
```
> apps sc: curator ignore all exceptions

- WIP-CHANGELOG.md
- helmfile/charts/opensearch/slm/scripts/slm-retention.bash
fixes #868 
Test with the following setup
```
MIN_SNAPSHOTS=1
MAX_SNAPSHOTS=2
MAX_AGE_SECONDS=1000
snapshot-20220310_125821z SUCCESS 1646917101 12:58:21 1646917254 13:00:54 2.5m 120 120 0 120
snapshot-20220311_000002z SUCCESS 1646956802 00:00:02 1646957106 00:05:06   5m 123 123 0 123
snapshot-20220311_064510z SUCCESS 1646981110 06:45:10 1646981276 06:47:56 2.7m 120 120 0 120
```
Output:
```
❯ ./slm-retention.bash # with the removal skipped
SLM retention procedure started
Removing snapshots older than 1000 seconds but keeping at least 1 snapshots and at most 2 snapshots.
Checking for old snapshots.
Snapshot snapshot-20220310_125821z is 65462 s old, max 1000 s
Snapshot …
```
> apps sc: cat snapshots in slm job

- WIP-CHANGELOG.md
- config/config/common-config.yaml
This PR adds vulnerability report time to live
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #853
Older reports must be manually deleted.
**Checklist:** …
> added vulnerability report ttl

- WIP-CHANGELOG.md
- helmfile/charts/user-rbac/templates/clusterroles/user-view.yaml
Allows users to get and list ClusterIssuers
**Which issue this PR fixes** : fixes #904
**Checklist:** …
> config: allow users get clusterissuers

- WIP-CHANGELOG.md
- helmfile/charts/vulnerability-exporter/templates/deployment.yaml
> removed influx stuff

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
Added persistence to alertmanager, alerts that get closed during alertmanager restart/downtime now automatically close in opsgenie once alertmanager is started again.
**Which issue this PR fixes** : fixes #888 
Is 1Gi of storage enough?
**Checklist:** …
> apps sc: Added persistence to alertmanager

- WIP-CHANGELOG.md
- helmfile/charts/prometheus-alerts/templates/alerts/predict-linear.yaml
**What this PR does / why we need it**: to fix some issue with the predict linear alerts
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #884 
**Checklist:** …
> apps: fix minor issues with predict linear alerts

- WIP-CHANGELOG.md
- helmfile/charts/vulnerability-exporter/templates/deployment.yaml
**What this PR does / why we need it**: to be able to set tolerations and affinity for vulnerability-exporter
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #670
**Checklist:** …
> apps wc:tolerations and affinity for vulnerability-exporter

- WIP-CHANGELOG.md
- config/config/wc-config.yaml
- helmfile/values/falco.yaml.gotmpl
**What this PR does / why we need it**: to ad the possibility to add falco custom rules for each env
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #889
**Checklist:**
If you change some config options (e.g. add/rename variable or change the …
> Add custom falco rules

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/values/opensearch/common.yaml.gotmpl
Makes indices.query.bool.max_clause_count configurable.
**Which issue this PR fixes** : fixes #690 
**Checklist:**
> apps sc: made max_clause_count configurable

- WIP-CHANGELOG.md
- helmfile/values/dex.yaml.gotmpl
[Since kubelogin will try to use port 18000 if port 8000 is already bound](https://github.com/int128/kubelogin/blob/master/docs/usage.md#authorization-code-flow), we should allow for that by default.
**Checklist:**
E.g. removes or changes any CK8S …
> apps sc: Added alternative port for kubelogin as allowed redirect

- WIP-CHANGELOG.md
- helmfile/values/falco.yaml.gotmpl
**What this PR does / why we need it**: Based on the issue - https://github.com/elastisys/compliantkubernetes-apps/issues/896, Upstream a patch to falco rules
As discussed with @cristiklein , This PR against the https://github.com/elastisys/compliantkubernetes-apps still exists to gain the speed , and remove those values if and when Falco upstream accepts your changes ( refer - https://github.com/falcosecurity/charts/pull/319 )
So , please continuing approving this current PR here too . 
**Add a screenshot or an example to illustrate the …
> apps-wc: Upstream a patch to falco rules

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
**What this PR does / why we need it**: Enables the user-permission for alerting in OpenSearch. Refer - https://github.com/elastisys/compliantkubernetes-apps/issues/747
This feature has to be enabled in 0.21.0 apps release.
**Checklist:** …
> apps-sc: OpenSearch user permission roles for alerting

- bin/ck8s
- bin/ops.bash
I wanted kubecolor to work with ck8s ops and using an alias is not enough as bash does not expand aliases. 
**Checklist:**
- Chart checklist …
> bin: added support for kubecolor

- WIP-CHANGELOG.md
- helmfile/charts/user-rbac/templates/clusterrolebindings/user-admin-cluster-wide-delegation.yaml
- helmfile/charts/user-rbac/templates/clusterroles/user-admin-cluster-wide-delegation.yaml
- manifests/user-rbac/clusterrolebindings/extra-user-view.yaml
- scripts/deploy-wc.sh
**What this PR does / why we need it**: Self service userAdmin creation based on issue - https://github.com/elastisys/compliantkubernetes-apps/issues/738
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #738
**Checklist:**
- Chart …
> apps-wc: Self service userAdmin creation

- WIP-CHANGELOG.md
- helmfile/charts/sc-logs-retention/scripts/logs-retention.sh
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #933 
Screenshot first shows what happens without the fix (clears one day of logs, then gives an error) and then with the fix (clears all old logs and does not give an error)
**Checklist:** …
> apps sc: fix sc log retention script to not silently fail

- WIP-CHANGELOG.md
- helmfile/values/opensearch/configurer.yaml.gotmpl
This elevates the privileges for curator as to be able to delete all but for `.` indices even when the index per namespace feature is disabled.
I deem this as fine as we don't create any indices manually that might cause curator to accidentally delete it.
One of the main reasons for this change is to be able to remove security-auditlog indices.
**Checklist:** …
> Allow curator to delete all but for system indices

- WIP-CHANGELOG.md
- config/config/wc-config.yaml
- helmfile/values/falco.yaml.gotmpl
**What this PR does / why we need it**: to enabled falcosidekick alertmanager only if user alertmanager is enabled
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #745 
**Checklist:** …
> apps wc: add condition to enable falcosidekick alertmanager

- WIP-CHANGELOG.md
- helmfile/values/grafana-user.yaml.gotmpl
- helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
Patch to reduce vulnerabilities
**Checklist:** …
> patched grafana image tag to a less vunerable tag

- config/config/sc-config.yaml
- pipeline/list-releases.bash
Following https://github.com/elastisys/ck8s-ops/pull/1736, we are now to make something out of our observations!
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #780
As my investigation suggests, some pods need more resources and some less. Feel free to chimp in if any of you have seen stuff I haven't and feel it needs to be added! :+1: 
**Checklist:**
E.g. logs or metrics are not being collected or Kubernetes …
> apps sc: thanos and prometheus proposal

- WIP-CHANGELOG.md
- helmfile/charts/user-alertmanager/templates/role.yaml
Since users need to be able to do `POST` and `DELETE` requests to alertmanager to create/delete silences we need to add this to the role as well.
**Checklist:** …
> apps wc: Updated alertmanager proxy permissions

- .pre-commit-config.yaml
- CHANGELOG.md
- config/config/wc-config.yaml
- helmfile/charts/prometheus-alerts/templates/alerts/fluentd.yaml
- helmfile/charts/prometheus-alerts/templates/alerts/kubernetes-apps.yaml
- helmfile/upstream/fluentd-elasticsearch/values.yaml
- helmfile/values/fluentd-user.yaml.gotmpl
- helmfile/values/fluentd-wc.yaml.gotmpl
- migration/v0.20.x-v0.21.x/upgrade-apps.md
Merges fixes from 0.21 into main
**Checklist:** …
> Release 0.21 fixes

- WIP-CHANGELOG.md
- scripts/deploy-wc.sh
**What this PR does / why we need it**: Fixing a path. We should probably put this in the next patch release for v0.21.
**Checklist:**
**Pipeline …
> apps wc: fix path to extra-user-view manifest in deploy script

- CHANGELOG.md
adds changelog for patch release onto main 
**Checklist:**
If you …
> Reset changelog for release v0.21.1

- WIP-CHANGELOG.md
- bin/common.bash
Fix the issue when keys have "." in the name. 
Also added a check if the key it tries to copy from does not have a value it should fail.
I did try to just replace keys containing "." but it was quite slow.
**Which issue this PR fixes**: fixes #955
**Checklist:** …
> apps: fixed issue when keys has . in name

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
We should investigate what is needed to make Alertmanager highly available. Any single Node failure should not impact application or platform alerting. This is now done.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #856
**Checklist:** …
> apps sc: alertmanager HA

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- config/config/wc-config.yaml
- helmfile/values/kubeapi-metrics.yaml.gotmpl
- helmfile/values/thanos/receiver.yaml.gotmpl
Add allowlisting for thanos-receiver endpoint, the rest can already be set.
Fixes #840 
Do we want to update anything else about how we configure allowlisting, renaming the setting, convert it into a yaml sequence, prepare so ops endpoints and/or public endpoints can set common ranges?
**Checklist:** …
> apps sc: Add allowlisting for thanos-receiver endpoint

- WIP-CHANGELOG.md
- helmfile/values/fluentd-user.yaml.gotmpl
- helmfile/values/fluentd-wc.yaml.gotmpl
Index per namespace was broken for opensearch. This fixes it.
This should be part of a patch release for v0.21
**Checklist:** …
> apps: fix index per namespace opensearch

- WIP-CHANGELOG.md
- helmfile/charts/opensearch/configurer/files/index-templates/kubernetes.template.json
- helmfile/values/fluentd-configmap.yaml.gotmpl
- helmfile/values/fluentd-user.yaml.gotmpl
- helmfile/values/fluentd-wc.yaml.gotmpl
Fixed issue when fluentd start adding `\` to a log after failing to push to opensearch.
Also fixed two mapping issues. 
**Which issue this PR fixes**: fixes #544 
**Checklist:** …
> apps: fluentd ignore own logs and set type of keys

- WIP-CHANGELOG.md
- helmfile/charts/grafana-ops/templates/configmap-dashboards.yaml
Makes each dashboard a separate configmap instead of a massive configmaplist that sometimes causes issues in helm. 
fixes #
I had strange issues when running dry-run on the service cluster and narrowed it down to the `grafana-ops`, where the command would fail and close the shell session. And it only happened when I tried to enable rclone-sync which adds changes into the backup dashboard. But I knew it could render the chart so the problem was when it tried to run diff or apply.
So I look in to it and saw that it rendered all dashboards into one massive resource, which I think is to large for helm to handle properly in all situations. …
> apps sc: Split dashboard configmaplist into separate configmaps

- WIP-CHANGELOG.md
- config/config/flavors/dev/sc-config.yaml
- config/config/flavors/prod/sc-config.yaml
- config/config/sc-config.yaml
Updates the _default_ retention for curator.
fixes #26 
**Checklist:** …
> apps sc: add retention for security-auditlog

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
- helmfile/values/kube-prometheus-stack-wc.yaml.gotmpl
- helmfile/values/thanos/query.yaml.gotmpl
- helmfile/values/thanos/receiver.yaml.gotmpl
And option for Thanos compactor to do deduplication.
HA metrics collection for the masses.
fixes #855
Basically adds the option to have multiple Prometheus replicas, and adds a replica label to them when they are more than one.
Thanos Query will then deduplicate based on this label (in addition to the already set Receiver label).
Thanos Compactor can be configured to run this deduplication as well when it runs.
Though due to the time it takes for it to progress I've haven't seen it actually dedup the `prometheus_replica` label just yet.
With one Prometheus down in …
> apps: Add option for HA Prometheus

- WIP-CHANGELOG.md
- helmfile/values/falco.yaml.gotmpl
Saw that the falco ds rollout was stuck due to a missing macro in the falco rule.
```console
Tue May 24 13:44:05 2022: Runtime error: Could not load rules file /etc/falco/rules.d/overwrites.yaml: 1 errors:
Compilation error when compiling "...": Undefined macro calico_node used in filter.
---
- macro: write_etc_common
condition: >
...
and not calico_node
---
. Exiting.
```
I don't know if there is one that should be included instead.
I tried to include the one in the default rules but it did not work, it still failed to compile.
**Checklist:**
will not be responding while …
> apps wc: Remove undefined macro preventing falco rule compilation

- WIP-CHANGELOG.md
- config/config/common-config.yaml
Fix rendering error for missing config option for prometheus replicas
~~I set HA as standard for prod and single for dev.~~ Reverted this, 1 replica it the default for all.
**Checklist:** …
> apps: Add missing config option for prometheus replicas

- .github/workflows/end-to-end.yml
- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/values/prometheus-blackbox-exporter-sc.yaml.gotmpl
- pipeline/opensearch.bash
Our pipeline crashes every now and again and I gave it a try to figure out what's up!
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #913
This branch was first created to work with https://github.com/elastisys/compliantkubernetes-apps/issues/913 interactively. It has now turned into a regular branch as solutions to the problems our pipeline was having has been found.
**Checklist:**
E.g. logs or metrics are …
> pipeline fixing

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- config/secrets/sc-secrets.yaml
- helmfile/charts/rclone-sync/files/rclone.conf
- helmfile/charts/rclone-sync/templates/cronjob.yaml
- helmfile/charts/rclone-sync/values.yaml
- helmfile/values/rclone-sync.yaml.gotmpl
- helmfile/values/velero-sc.yaml.gotmpl
- helmfile/values/velero-wc.yaml.gotmpl
- scripts/restore-sync/README.md
- scripts/restore-sync/template.job.yaml
Allows the contents of a bucket to be encrypted before it's sent when using rclone sync.
fixes #
**Checklist:** …
> apps sc: Add option to encrypt with rclone sync

- CHANGELOG.md
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1008
**Checklist:** …
> Reset changelog for release v0.21.2

- WIP-CHANGELOG.md
- helmfile/charts/user-alertmanager/templates/role.yaml
- helmfile/charts/user-alertmanager/templates/rolebinding.yaml
Added group support for user-alertmanger and port-forward support
**Checklist:**
> apps wc: Added groups for alertmanager rbac

- WIP-CHANGELOG.md
- helmfile/charts/prometheus-alerts/templates/alerts/opensearch.yaml
- helmfile/values/opensearch/configurer.yaml.gotmpl
- helmfile/values/prometheus-elasticsearch-exporter.yaml.gotmpl
We want to be notified before customers hit the field limit. 
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1031
**Checklist:**
**Pipeline config** *(if …
> apps sc: Added field mapping metric for opensearch

- WIP-CHANGELOG.md
- helmfile/50-applications.yaml
- helmfile/upstream/ingress-nginx/CHANGELOG.md
- helmfile/upstream/ingress-nginx/Chart.yaml
- helmfile/upstream/ingress-nginx/README.md
- helmfile/upstream/ingress-nginx/README.md.gotmpl
- helmfile/upstream/ingress-nginx/ci/daemonset-tcp-udp-portNamePrefix-values.yaml
- helmfile/upstream/ingress-nginx/ci/deployment-tcp-udp-portNamePrefix-values.yaml
- helmfile/upstream/ingress-nginx/templates/NOTES.txt
- helmfile/upstream/ingress-nginx/templates/_helpers.tpl
- helmfile/upstream/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
- helmfile/upstream/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
- helmfile/upstream/ingress-nginx/templates/controller-daemonset.yaml
- helmfile/upstream/ingress-nginx/templates/controller-deployment.yaml
- helmfile/upstream/ingress-nginx/templates/controller-psp.yaml
- helmfile/upstream/ingress-nginx/templates/controller-service-internal.yaml
- helmfile/upstream/ingress-nginx/templates/controller-service.yaml
- helmfile/upstream/ingress-nginx/values.yaml
- migration/v0.22.x-v0.23.x/upgrade-apps.md
**What this PR does / why we need it**: to upgrade the ingress-nginx helm chart to v4.1.3 and ingress-nginx-controller image to 1.2.1
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1789
**Checklist:**
If you change some config options (e.g. add/rename variable or change the default value) you may need to update …
> ingress-nginx: upgrade helm chart to v4.1.3

- WIP-CHANGELOG.md
- config/config/flavors/dev/sc-config.yaml
- config/config/flavors/prod/sc-config.yaml
- config/config/sc-config.yaml
**What this PR does / why we need it**: remove wcReader mentions from config files
**Checklist:**
> config: remove wcReader from configs

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/50-applications.yaml
- helmfile/charts/opensearch/configurer/templates/job.yaml
- helmfile/charts/opensearch/configurer/values.yaml
- helmfile/charts/opensearch/securityadmin/.helmignore
- helmfile/charts/opensearch/securityadmin/Chart.yaml
- helmfile/charts/opensearch/securityadmin/templates/NOTES.txt
- helmfile/charts/opensearch/securityadmin/templates/_helpers.tpl
- helmfile/charts/opensearch/securityadmin/templates/job.yaml
- helmfile/charts/opensearch/securityadmin/templates/secret.yaml
- helmfile/charts/opensearch/securityadmin/values.yaml
- helmfile/values/opensearch/common.yaml.gotmpl
- helmfile/values/opensearch/configurer.yaml.gotmpl
- helmfile/values/opensearch/securityadmin.yaml.gotmpl
- migration/v0.22.x-v0.23.x/migrate-opensearch-roles.sh
- migration/v0.22.x-v0.23.x/upgrade-apps.md
- pipeline/lint.bash
To automatically reload security config in OpenSearch.
To use the "predefined" alerting roles.
Fixes #804 
I figured it was best to set it up as a separate job since it would allow a simple way to disable it completely, and you also get a release you can sync to run it manually.
**Checklist:** …
> apps sc: Add securityadmin job and alerting roles

- WIP-CHANGELOG.md
- scripts/clean-sc.sh
- scripts/clean-wc.sh
Make the clean script indicate which config that is used. This to reduce the change of cleaning the wrong cluster. 
Before:
After:
**Checklist:** …
> apps: make clean script more verbose

- WIP-CHANGELOG.md
- helmfile/values/falco.yaml.gotmpl
**What this PR does / why we need it**: Fixes the Hard alert with adding the exceptions as per apps !! - Refer - https://github.com/elastisys/compliantkubernetes-apps/issues/898
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #898 
**Checklist:**
I.e. full cluster migration …
> apps-wc: Patch Falco rules

- WIP-CHANGELOG.md
- helmfile/charts/user-alertmanager/files/alertmanager-config.yaml
- migration/v0.22.x-v0.23.x/upgrade-apps.md
- migration/v0.22.x-v0.23.x/user-alertmanager-reconfig.sh
**What this PR does / why we need it**: when using the default slack receiver alertmanager will generate errors
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1049 
**Checklist:**
> apps wc: set user-alertmanager default receiver to null

- CHANGELOG.md
- WIP-CHANGELOG.md
Reset changelog for v0.23.0
**Checklist:** …
> Reset changelog for release v0.23.0

- get-requirements.yaml
In ubuntu 22.04 version 2.2.* is available via apt. This pr releaxes the requirement on s3cmd to 2.*
**Checklist:** …
> all: relax s3cmd version requirement

- WIP-CHANGELOG.md
- helmfile/charts/opensearch/slm/scripts/slm-retention.bash
This prevents the SLM job from failing on clusters having a lot of snapshots.
**Checklist:**
> apps sc: Pass snapshot list by tempfile in opensearch-slm

- WIP-CHANGELOG.md
- config/config/common-config.yaml
- helmfile/values/ingress-nginx.yaml.gotmpl
**What this PR does / why we need it**: we added the option to enable publish service in ingress-nginx from configs
**Checklist:**
> apps: enable publishService in ingress-nginx

- WIP-CHANGELOG.md
- config/config/wc-config.yaml
- helmfile/values/velero-wc.yaml.gotmpl
**What this PR does / why we need it**: velero to create a backup of the alertmanager ns in wc only if `user.alertmanager` is enabled
**Checklist:**
> apps wc: velero will backup alertmanager ns on condition

- WIP-CHANGELOG.md
- helmfile/50-applications.yaml
- helmfile/charts/node-local-dns/Chart.yaml
- helmfile/charts/node-local-dns/templates/node-local-dns.yaml
Tested upgrading node-local-dns on a apps v0.23.0 cluster and everything seems to be working as expected.
**Which issue this PR fixes** : fixes #1056 
**Checklist:** …
> apps: upgrade node local dns

- WIP-CHANGELOG.md
- config/config/common-config.yaml
https://github.com/elastisys/compliantkubernetes-apps/issues/1063
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1063
**Checklist:** …
> apps sc & wc: enable lockReleaseDelay in kured

- WIP-CHANGELOG.md
- helmfile/charts/grafana-ops/dashboards/kubernetesstatus-dashboard.json
**What this PR does / why we need it**: to have a better visibility on the resource requests and limits per node
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1045 
- added node name as filter
- new graphs to show the CPU and Memory requests/limits per node
- replaced the top10 and bottom10 usage/requested graphs (as they didn't display the correct data) with 2 new graphs showing all pods. We can use the Max, Min or Mean for sort the pods
**Checklist:**
E.g. logs or metrics are not being collected …
> apps sc: updated the k8s status grafana dashboard

- WIP-CHANGELOG.md
- config/config/common-config.yaml
- config/secrets/sc-secrets.yaml
- helmfile/charts/issuers/templates/letsencrypt-prod.yaml
- helmfile/charts/issuers/templates/letsencrypt-staging.yaml
- helmfile/charts/issuers/templates/secrets.yaml
- helmfile/charts/issuers/values.yaml
- helmfile/values/letsencrypt.yaml.gotmpl
Adds an option for custom solvers for letsencrypt issuers and includes a simple way to add secrets.
This enables support for DNS01 challenges.
fixes #841
Was easier to add it on both, it can still be configured per cluster.
And it can be useful in some scenarios where we want a certificate for something that isn't exposed through an ingress.
Running with this test (I already had it generate a cert for `test.aarnq.dev-ck8s.com` but forgot to capture the moment it got generated):
```yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
name: test-cert …
```
> apps: Add option for custom solver for letsencrypt issuers

- README.md
- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/values/harbor.yaml.gotmpl
- migration/v0.24.x-v0.25.x/migrate-harbor-redis-variables.sh
- migration/v0.24.x-v0.25.x/upgrade-apps.md
**What this PR does / why we need it**: to expose external redis database for harbor
- the migration script works with yq4 only
**Checklist:**
> apps sc: expose external redis db for harbor

- WIP-CHANGELOG.md
- helmfile/charts/prometheus-alerts/CHANGELOG.md
- helmfile/charts/prometheus-alerts/templates/alerts/fluentd.yaml
**What this PR does / why we need it**: have alerts for when the fluentd buffers get full
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1102
**Checklist:**
> apps: added new fluentd buffer alerts

- WIP-CHANGELOG.md
- config/config/common-config.yaml
- helmfile/values/ingress-nginx.yaml.gotmpl
**What this PR does / why we need it**: to allow enabling allowSnippetAnnotations from configs
**Which issue this PR fixes**: fixes #1111
**Checklist:**
> apps: allow enabling allowSnippetAnnotations from configs

- README.md
- WIP-CHANGELOG.md
- bin/init.bash
- config/config/sc-config.yaml
- config/secrets/sc-secrets.yaml
- helmfile/values/harbor-backup.yaml.gotmpl
- helmfile/values/harbor.yaml.gotmpl
- migration/v0.24.x-v0.25.x/migrate-harbor-database-variables.sh
- migration/v0.24.x-v0.25.x/upgrade-apps.md
Expose external db settings for harbor 
**Checklist:** …
> apps sc: expose external db values for harbor

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
**What this PR does / why we need it**: to add an exception for a know falco alert
**Which issue this PR fixes**: fixes #1115 
**Checklist:**
> apps sc: add exception for elastisys/curl-jq used by opensearch

- WIP-CHANGELOG.md
- config/config/common-config.yaml
- config/config/wc-config.yaml
- helmfile/charts/calico-accountant/values.yaml
- migration/v0.24.x-v0.25.x/add-control-plane-toleration.sh
- migration/v0.24.x-v0.25.x/upgrade-apps.md
- pipeline/test/services/service-cluster/testPrometheusTargets.sh
- pipeline/test/services/workload-cluster/testPrometheusTargets.sh
**What this PR does / why we need it**: to support the new `node-role.kubernetes.io/control-plane:NoSchedule` taint
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #970 
**Checklist:**
> apps: tolerate control-plane taint

- config/config/common-config.yaml
In the current version of ck8s, fluentd-aggregator fails to communicate with s3 for non-AWS implementation without prepending http(s) protocol in **_regionEndpoint_** . This PR adds a comment regarding the issue. Here is an example:
```  
objectStorage:
type: s3
s3:
region: sto1
regionEndpoint: https://s3.sto1.safedc.net
forcePathStyle: true
```
The log below shows the error encountered:
`022-08-23 13:25:02 +0000 [info]: adding match …
> for non-AWS implementation of s3 prepend protocol in the url

- WIP-CHANGELOG.md
- helmfile/values/thanos/query.yaml.gotmpl
Since we are using thanos and only store 30 days worth of non-downsampled data but keep downsampled data for even longer, we would like to be able to actually look at that.
According to [this issue](https://github.com/thanos-io/thanos/issues/1353) the issue is that grafana doesn't query the data and requeets the downsampled data. So the fix is to add the flag `--query.auto-downsampling` and let querier make this automatically.
I tried it on long-running and it looks like it works. (see screenshot)
So now when you have a window larger than 30 days (roughly) the querier will automatically use the downsampled data while using the raw data when zoomed in further
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes …
> apps-sc: Fixed bug where thanos didn't show downsampled only data

- WIP-CHANGELOG.md
- helmfile/charts/prometheus-alerts/CHANGELOG.md
- helmfile/charts/prometheus-alerts/files/missing-metrics-alerts.yaml
- helmfile/charts/prometheus-alerts/files/thanos.yaml
- helmfile/charts/prometheus-alerts/templates/alerts/blackbox.yaml
- helmfile/charts/prometheus-alerts/templates/alerts/opensearch.yaml
https://github.com/elastisys/compliantkubernetes-apps/issues/1054
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1054
Sometimes easy solutions are the best ones? After thinking a bit about it, it seems like the best solution is to increase the "for"-parameter to make sure the alert is triggered by a long-term state rather than just a temporary one? It feels like a bad idea to increase the limits themselves - for example, ThanosReceiveHttpRequestErrorRateHigh has peaks over 35%(https://elastisys.app.eu.opsgenie.com/alert/detail/5c660bc7-e722-4df0-bc13-a …
> apps sc: kured prometheus-alert optimization

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
**What this PR does / why we need it**: We want this in all clusters anyway. It also does not seem to conflict with setups where the dex connector does not have group support, so the changes should be rather safe.
**Checklist:** …
> config: update OIDC config

- .github/workflows/release.yml
- release/README.md
- release/common.sh
- release/create-major-minor-release.sh
- release/create-patch-release.sh
- release/feature-freeze-for-major-minor-release.sh
- release/prepare-patch-release.sh
- release/reset-changelog.sh
Simplifies the release process by automating most steps, and also changed the action trigger to trigger on the tag rather than the merge to the release branch. This makes it so we're not forced to fast-forward merge into the release branch.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes elastisys/ck8s-ops#1895
**Checklist:**
will not be …
> release: Updated release scripts and document

- release/README.md
Added back a point in release docs that was removed by accident.
**Checklist:**
> docs: update release notes

- WIP-CHANGELOG.md
- config/config/common-config.yaml
- config/secrets/sc-secrets.yaml
- config/secrets/wc-secrets.yaml
- helmfile/50-applications.yaml
- helmfile/charts/kured-secret/Chart.yaml
- helmfile/charts/kured-secret/templates/kured-secret.yaml
- helmfile/charts/kured-secret/values.yaml
- helmfile/values/kured.yaml.gotmpl
Enables the possibility for kured to notify to slack. 
**Which issue this PR fixes**: fixes #1092 
**Checklist:** …
> apps: kured notify to slack

- WIP-CHANGELOG.md
- helmfile/charts/user-rbac/templates/rolebindings/falco-viewer.yaml
- helmfile/charts/user-rbac/templates/rolebindings/fluentd-configurer.yaml
Added missing group subjects in some rolebindings.
**Which issue this PR fixes** : fixes #1141 
**Checklist:**
> apps wc: added group subjects to rolebindings

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- migration/v0.25.x-v0.26.x/upgrade-apps.md
This was just once an example on how to configure extra role mappings that seemingly ended up being something that one "is supposed to" configure now.
This role is not something that users of opensearch needs.
**Checklist:**
E.g. removes or changes any …
> config: remove readall_and_monitor from opensearch config

- migration/v0.25.x-v0.26.x/add-support-message.sh
This script gave an old/wrong error output
**Checklist:**
> bin: fix error output

- WIP-CHANGELOG.md
- helmfile/charts/user-rbac/templates/rolebindings/prometheus.yaml
- helmfile/charts/user-rbac/templates/roles/prometheus-port-fwd.yaml
fixes #819 
Naming suggestions for the role/binding is welcome
Proxy:
```
$ kubectl -n monitoring --as admin@example.com proxy
Starting to serve on 127.0.0.1:8001
```
Port-forward:
```
Forwarding from 127.0.0.1:9090 -> 9090
Forwarding from [::1]:9090 -> 9090
```
**Checklist:** …
> apps wc: gives users web access to prometheus

- WIP-CHANGELOG.md
- helmfile/charts/prometheus-alerts/templates/alerts/opensearch.yaml
Added `max_over_time(...[5m])` to handle metrics drops better for opensearch field limit.
**Checklist:** …
> apps sc: field limit alert handle metric drops better

- migration/v0.25.x-v0.26.x/upgrade-apps.md
Found an issue with the migration guide, so I added a step that's needed
**Checklist:**
**Pipeline …
> docs: Added migration step for upgrading from v0.25 -> v0.26

- WIP-CHANGELOG.md
- get-requirements.yaml
Bump kubectl to support 1.23, 1.24, and 1.25
**Checklist:**
If you …
> all: bump kubectl to v1.24.4

- WIP-CHANGELOG.md
- helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
Typo in sc-config caused resources for Grafana test framework to be installed in the sc cluster.
This PR fixes the typo.
fixes #531 
```diff
monitoring, kube-prometheus-stack-grafana-test, Role (rbac.authorization.k8s.io) has been removed:
- # Source: kube-prometheus-stack/charts/grafana/templates/tests/test-role.yaml
- apiVersion: rbac.authorization.k8s.io/v1
- kind: Role
- metadata:
-   name: kube-prometheus-stack-grafana-test
-   namespace: monitoring
-   labels:
-     helm.sh/chart: grafana-6.17.2
-     app.kubernetes.io/name: grafana
- …
```
> apps sc: fix removal of grafana test resources

- WIP-CHANGELOG.md
- config/config/flavors/prod/sc-config.yaml
To be in line with the ToS
**Checklist:** …
> config: set kubernetes logs age to 30 days

- pipeline/test/services/service-cluster/testPodsReady.sh
As harbor have been updated, name syntaxes have changed slightly.
Noted in testing.
**Checklist:** …
> apps sc: harbor test fixes

- WIP-CHANGELOG.md
- config/config/common-config.yaml
- helmfile/50-applications.yaml
- helmfile/charts/calico-default-deny/.helmignore
- helmfile/charts/calico-default-deny/Chart.yaml
- helmfile/charts/calico-default-deny/README.md
- helmfile/charts/calico-default-deny/templates/globalnetworkpolicy.yaml
- helmfile/values/calico-default-deny.yaml.gotmpl
**What this PR does / why we need it**: Add option for denying network traffic by default.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1040
**Special notes for reviewer**: Note that if you apply this setting to a cluster, you need to set several `additionalEgressPolicies` / `additionalIngressPolicies` in order for the cluster to function properly. Perhaps we would like a config option to add this automatically, but I deemed it not part of this task.
**Checklist:**
E.g. logs …
> apps: add option for denying network traffic by default

- pipeline/config/exoscale/secrets.yaml
Fix for the pipeline
```
in ./50-applications.yaml: failed processing release harbor: failed to render values files "values/harbor.yaml.gotmpl": failed to render [values/harbor.yaml.gotmpl], because of template: stringTemplate:102:5: executing "stringTemplate" at <fail "\nERROR: The xsrf key (found at harbor.xsrf) must be exactly 32 characters long">: error calling fail: 
ERROR: The xsrf key (found at harbor.xsrf) must be exactly 32 characters long
exit status 1
```
**Checklist:** …
> pipeline: Fix harbor xsrf length

- WIP-CHANGELOG.md
- helmfile/values/prometheus-blackbox-exporter-sc.yaml.gotmpl
We got an alert saying opensearch-dashboards endpoint was down but it wasn't, blackbox exporter was looking for the wrong error code at the opensearch-dashboards target because opensearch-dashboards had done some changes.
**Checklist:** …
> apps sc: fix blackbox exporter target

- WIP-CHANGELOG.md
- helmfile/charts/harbor/harbor-backup/templates/harbor-backup-job.yaml
- helmfile/charts/harbor/harbor-backup/values.yaml
- scripts/restore/restore-harbor-job.yaml
Harbor backup was pointed to the wrong service name, so it could not take backups.
@OlleLarsson Also made a new tag for the `elastisys/backup-postgres` image which uses newer postgres version
**Checklist:**
> apps sc: fix harbor backup

- WIP-CHANGELOG.md
- pipeline/test/services/workload-cluster/testUserRbac.sh
Fixes the test user rbac for the wc cluster test.
**Checklist:**
If …
> pipeline: fix test user RBAC

- helmfile/11-prometheus-operator.yaml
- helmfile/12-gatekeeper.yaml
- helmfile/13-gatekeeper-templates.yaml
- helmfile/14-cert-manager.yaml
- helmfile/50-applications.yaml
The default behavior for missing files is to error out so I don't think that we need to specify that in our releases.
Also removed `installed: true` for opensearch, as I only think that `installed` should be in the release spec if it is actually possible to disable.
**Checklist:**
I.e. full cluster migration is …
> all: minor cleanup of helmfile statefiles

- WIP-CHANGELOG.md
- config/config/common-config.yaml
**What this PR does / why we need it**: increased the default disklimit alert threshold
**Checklist:**
> apps: changed the default disklimit alert threshold

- .github/workflows/end-to-end.yml
**What this PR does / why we need it**: to temporary disable it, until we fix it
**Checklist:**
> pipeline: temporary disable it

- WIP-CHANGELOG.md
- pipeline/test/services/service-cluster/testPodsReady.sh
- pipeline/test/services/workload-cluster/testPodsReady.sh
In Kubespray 2.20 the `calico-kube-controllers` pod is no longer being created, so the pipeline test failed as it does not exist.
**Checklist:**
> pipeline: removed check for calico-kube-controller

- WIP-CHANGELOG.md
- helmfile/charts/grafana-ops/dashboards/kubernetesstatus-dashboard.json
**What this PR does / why we need it**: fixed the k8s cluster status Grafana dashboard not loading data for some panels 
**Checklist:**
> apps sc: fixed k8s cluster status grafana dashboard

- WIP-CHANGELOG.md
- helmfile/charts/prometheus-alerts/CHANGELOG.md
- helmfile/charts/prometheus-alerts/templates/alerts/kubernetes-apps.yaml
**What this PR does / why we need it**: to add an alert to detect evicted pods
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1173 
**Checklist:**
> apps sc: added alert for evicted pods

- .github/workflows/end-to-end.yml
**What this PR does / why we need it**: re-enable the pipeline and use v2.20.0 for kubespray
**Checklist:**
> pipeline: re-enable it and use kubespray v2.20.0

- WIP-CHANGELOG.md
- helmfile/values/fluentd-user.yaml.gotmpl
- helmfile/values/fluentd-wc.yaml.gotmpl
Our fluentd pods in the workload cluster started to have problems. The issue turned out to be an updated "fluentd-elasticsearch" image which then didn't match with the other updates we did in apps v0.26.0. We have now created an image that fits our needs and works.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1210
The image branch - https://github.com/elastisys/fluentd-elasticsearch/tree/kubernetes-metadata-filter-downgrade
**Checklist:**
- Is this changeset backwards compatible …
> apps wc: dynamic add map fixing

- CHANGELOG.md
These points were already listed for `v0.25` so I removed them from `v0.26`
**Checklist:**
> docs: removed duplicate points from changelog

- WIP-CHANGELOG.md
- helmfile/charts/rclone-sync/templates/cronjob.yaml
- helmfile/charts/rclone-sync/values.yaml
Sets the backofflimit for jobs that interact with s3 to 0.
**Which issue this PR fixes**: fixes #1232 
**Checklist:** …
> apps: backofflimit set to 0 for s3 jobs

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/values/dex.yaml.gotmpl
Made dex id token expiration time configurable
Tested setting it to `1m`, then `5m` and then `24h` in my cluster and it worked as expected
**Which issue this PR fixes** : fixes #1242
**Checklist:**
> apps sc: made dex id token expiration time configurable

- release/README.md
Add note to release process for new patch release to make it clear that we do not need to create a PR and merge it back to main at the end of the new patch release process.
**Checklist:** …
> Add note to release process for new patch release

- WIP-CHANGELOG.md
- helmfile/values/velero-wc.yaml.gotmpl
remove gatekeeper-system namespace from velero backups in workload cluster
I think gatekeeper-system namesppace should be removed from velero backups.
**Checklist:** …
> apps-wc:remove gatekeeper-system namespace from velero backups

- WIP-CHANGELOG.md
- helmfile/charts/grafana-ops/files/welcome.md
- helmfile/charts/opensearch/configurer/files/dashboards-resources/welcome.md
- release/README.md
Added a new 'What's new' section to the welcoming dashboards.
**Checklist:**
> apps sc: added new section to welcoming dashboards

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
- helmfile/charts/prometheus-alerts/CHANGELOG.md
- helmfile/charts/prometheus-alerts/templates/alerts/opensearch.yaml
- helmfile/values/prometheus-alerts-sc.yaml.gotmpl
**What this PR does / why we need it**: to detect when an index size becomes too big. that might indicate an issue with the ISM
- I also added alerts for cluster status to alerts on issues that are not covered by the existing alerts
- the default index size is based on the highest value from a dev cluster multiplied by 2
**Checklist:**
> apps sc: added index size alerts for opensearch

- migration/v0.26.x-v0.27.x/upgrade-apps.md
**What this PR does / why we need it**: to fix an issue while upgrading from apps v0.26 to v0.27
>   Error: rendered manifests contain a resource that already exists. Unable to continue with install: NetworkPolicy "allow-cert-manager-resolver" in namespace "staging" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "common-np": current value is "workload-cluster-np
**Checklist:** …
> release: migration steps fix

- helmfile/charts/networkpolicy-common/templates/cert-manager/startupapicheck.yaml
- pipeline/Dockerfile
- pipeline/config/exoscale/common-config.yaml
- pipeline/config/exoscale/sc-config.yaml
- pipeline/config/exoscale/wc-config.yaml
**What this PR does / why we need it**: 
- the cert-manager helm chart included a job that checks if the [webhook is available](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/upstream/cert-manager/values.yaml#L445:L453). In a new installation the helm chart will fail because this job doesn't have a network policy defined. I added the necessary networkpolicy for this job to run.
- not necessary, but I added `dnsutils` in the pipeline docker image to be able to run [update-ips.bash](https://github.com/elastisys/compliantkubernetes-apps/blob/main/bin/update-ips.bash)
**Alternatives:**
- disable the startupapicheck job
Green pipeline: https://github.com/elastisys/compliantkubernetes-apps/actions/runs/3362027852
**Checklist:**
- Is this …
> pipeline: fix missing dependency

- WIP-CHANGELOG.md
- helmfile/charts/rclone-sync/templates/cronjob.yaml
- helmfile/values/rclone-sync.yaml.gotmpl
Enable quotes to allow rclone to be schedulled every x minnutes
**Checklist:**
- [x Proper commit message prefix on all commits
- Chart …
> apps:enable quotes to allow rclone to be scheduled every x minutes

- WIP-CHANGELOG.md
- config/config/wc-config.yaml
Prompted by internal discussion
**Checklist:**
> apps wc: enable user alertmanager by default

- WIP-CHANGELOG.md
- scripts/clean-sc.sh
- scripts/clean-wc.sh
Else CCM might not delete the volume.
**Checklist:**
> script: Fix cleanup script to remove PVCs instead of PVs

- WIP-CHANGELOG.md
- config/config/wc-config.yaml
- helmfile/values/hnc.yaml.gotmpl
- helmfile/values/velero-wc.yaml.gotmpl
- migration/v0.26.x-v0.27.x/add-extra-excluded-namespaces.sh
- migration/v0.26.x-v0.27.x/upgrade-apps.md
**What this PR does / why we need it**: to move the excluded namespaces to configs
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1159 
My proposal is:
- to keep the more "static" namespaces in defaults wc-config.yaml under `velero|hnc.excludedNamespaces`
- to add the more "fluid" namespaces in the overwrite wc-config.yaml under `velero|hnc.excludedExtraNamespaces`, to add and remove them more easily
**Checklist:**
will not be …
> apps wc: move excluded namespaces to configs

- WIP-CHANGELOG.md
- bin/update-ips.bash
Bug that caused exoscale s3 endpoint to parse strangely
**Checklist:**
**Pipeline config** *(if …
> apps both: Fixed update script s3 port parser

- WIP-CHANGELOG.md
- helmfile/charts/networkpolicy-service/templates/ingress-nginx/controller.yaml
- helmfile/charts/networkpolicy-workload/templates/ingress-nginx/controller.yaml
It was missing ingress for blackbox-exporter and egress for thanos-receiver-distributor remote write.
There is still something that is blocked going into ingress-nginx.
And in the setup with service type loadbalancer we need to add node IPs for the ingress into ingress-nginx as it will only see node and tunnel IPs.
**Checklist:**
E.g. logs or metrics are not …
> apps: Fix ingress-nginx controller netpol

- WIP-CHANGELOG.md
- helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
- helmfile/values/kube-prometheus-stack-wc.yaml.gotmpl
Images says it all.
We now have:
What this PR does
As you might understand the metrics will be "separeted" after this install since the labels doesn't match anymore so I would like to hear your opinion on this switch
**Checklist:** …
> apps: Fixed instance label for node-exporter

- WIP-CHANGELOG.md
- config/config/common-config.yaml
- helmfile/charts/starboard/ciskubebench-exporter/templates/deployment.yaml
- helmfile/charts/starboard/vulnerability-exporter/templates/deployment.yaml
It just felt unnecessary for the node-exporter
```
level=info ts=2022-11-23T15:12:47.920Z caller=node_exporter.go:177 msg="Starting node_exporter" version="(version=1.0.1, branch=HEAD, revision=3715be6ae899f2a9b9dbfd9c39f3e09a7bd4559f)"
level=info ts=2022-11-23T15:12:47.920Z caller=node_exporter.go:178 msg="Build context" build_context="(go=go1.14.4, user=root@1f76dbbcfa55, date=20200616-12:44:12)"
level=info ts=2022-11-23T15:12:47.920Z caller=node_exporter.go:105 msg="Enabled collectors"
level=info ts=2022-11-23T15:12:47.920Z caller=node_exporter.go:112 collector=btrfs
level=info ts=2022-11-23T15:12:47.920Z caller=node_exporter.go:112 collector=powersupplyclass
level=info ts=2022-11-23T15:12:47.920Z caller=node_exporter.go:112 collector=rapl …
```
> apps: Disabled all collectors except textfile for cisbench exporter

- WIP-CHANGELOG.md
- helmfile/values/fluentd-user.yaml.gotmpl
- helmfile/values/fluentd-wc.yaml.gotmpl
- helmfile/values/kube-prometheus-stack-wc.yaml.gotmpl
To prevent scenarios with resolve timeouts, which we've seen most frequently with fluentd.
Fixes #1314
All seem to be working fine, I'll monitor and see if fluentd still presents resolve issues.
**Checklist:** …
> apps wc: Use FQDN when connecting to service cluster

- WIP-CHANGELOG.md
- scripts/clean-sc.sh
- scripts/clean-wc.sh
> all: add removal of starboard resource in cleanup scripts

- WIP-CHANGELOG.md
- config/config/common-config.yaml
- helmfile/values/ingress-nginx.yaml.gotmpl
- migration/v0.27.x-v0.28.x/move-nginx-controller-service-annotation-to-map.sh
- migration/v0.27.x-v0.28.x/upgrade-apps.md
Allow us to set multiple annotations for Ingres controller service with a map. Currently it only supports a single string. 
**Checklist:** …
> apps: nginx controller service annotations now a map

- WIP-CHANGELOG.md
- config/config/common-config.yaml
- helmfile/charts/networkpolicy-common/templates/rook-ceph/ceph-tools.yaml
- helmfile/charts/networkpolicy-common/templates/rook-ceph/csi-rbdplugin-provisioner.yaml
- helmfile/charts/networkpolicy-common/templates/rook-ceph/default-deny.yaml
- helmfile/charts/networkpolicy-common/templates/rook-ceph/detect-version.yaml
- helmfile/charts/networkpolicy-common/templates/rook-ceph/mgr.yaml
- helmfile/charts/networkpolicy-common/templates/rook-ceph/mon.yaml
- helmfile/charts/networkpolicy-common/templates/rook-ceph/operator.yaml
- helmfile/charts/networkpolicy-common/templates/rook-ceph/osd-prepare.yaml
- helmfile/charts/networkpolicy-common/templates/rook-ceph/osd.yaml
- helmfile/values/networkpolicy-common.yaml.gotmpl
**What this PR does / why we need it**: apps-sc/wc: Adding network-policy rook-ceph in sc and wc cluster 
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1135 
1) Please read more details on the Github issue - https://github.com/elastisys/compliantkubernetes-apps/issues/1135 
**Checklist:** …
> apps-sc/wc: Adding network-policy rook-ceph

- WIP-CHANGELOG.md
- bin/init.bash
- helmfile/values/harbor.yaml.gotmpl
- migration/v0.27.x-v0.28.x/add-registry-credentials.sh
- migration/v0.27.x-v0.28.x/upgrade-apps.md
While waiting for some other stuff I manage to find the root cause of this annoying issue.
**Checklist:** …
> apps sc: Fixed so registry doesn't restart each apply

- WIP-CHANGELOG.md
- helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
Fixes an issue with templating that occurs when multiple workload clusters are specified in the `sc-config.yaml` under the `global.clustersMonitoring` field. This makes it possible to distinguish metrics between different workload clusters.
**Checklist:**
will not be responding while …
> apps sc: fixed templating when monitoring multiple workload clusters

- WIP-CHANGELOG.md
- config/config/wc-config.yaml
- helmfile/values/velero-wc.yaml.gotmpl
Added templating for wc Velero bucket prefix. This will be useful for environments with multiple workload clusters connected to a single service cluster, allowing the wc backups to be stored in the same bucket but under different directories.
**Checklist:**
will not be responding while …
> apps wc: added templating for wc velero bucket prefix

- WIP-CHANGELOG.md
- bin/init.bash
- config/config/common-config.yaml
- helmfile/charts/networkpolicy-common/templates/kube-system/csi-cinder.yaml
- helmfile/charts/networkpolicy-common/templates/kube-system/csi-upcloud.yaml
- helmfile/charts/networkpolicy-common/templates/kube-system/metrics-server.yaml
- helmfile/charts/networkpolicy-common/templates/kube-system/snapshot-controller.yaml
- helmfile/charts/networkpolicy-common/values.yaml
- helmfile/values/networkpolicy-common.yaml.gotmpl
Adds netpols for kube-system components.
Let me know if I should rename the config key for `openstack` to `cinder`, though I felt like `openstack` was more fitting as it touches multiple components.
The ports `5000`, `8774`, and `8776` seem to be their default and matches across Cleura, Elastx, and Safespring.
Fixes #1134
**Checklist:** …
> apps: Add network policies for kube-system components

- WIP-CHANGELOG.md
- config/config/common-config.yaml
**What this PR does / why we need it**: rook network policies should be enabled only on env that are using rook-ceph. I propose to disabled them in the default configs.
**Checklist:**
> apps: disable rook network policies by default

- WIP-CHANGELOG.md
- helmfile/values/opensearch/securityadmin.yaml.gotmpl
Add cluster_permission `cluster:admin/opensearch/notifications/*`  to opensearch `alerting_full_access role` to be able to view notification channels.
Fixes #1325
**Checklist:**
I.e. …
> apps sc: Add cluster_permission to opensearch alerting_full_access role

- WIP-CHANGELOG.md
- helmfile/charts/networkpolicy-common/templates/cert-manager/certmanager.yaml
- helmfile/charts/networkpolicy-service/templates/opensearch/master.yaml
Fix for when traffic to an ingress LB isn't short circuited by kube-proxy which prevented cert-managers self-checks.
fixes #1344
**Checklist:**
> apps: Fix netpols for traffic going to service LB with PROXY protocol

- WIP-CHANGELOG.md
- helmfile/values/prometheus-user-alerts-wc.yaml.gotmpl
**What this PR does / why we need it**: We noticed that users currently get falco alerts from both falco sidekick and this prometheus alert.
**Checklist:** …
> apps wc: disable duplicate falco alerts for users

- WIP-CHANGELOG.md
- helmfile/upstream/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml
- helmfile/values/grafana-user.yaml.gotmpl
- migration/v0.27.x-v0.28.x/upgrade-apps.md
**What this PR does / why we need it**: to remove the some old datasources from user-grafana
- let me know if I should add the option to remove datasources in the configs
- the kube-prometheus-stack chart version that we use doesn't support `deleteDatasource`, we can do it after we upgrade the chart
**Checklist:**
> apps sc: removed legacy datasources from ops and user grafana

- WIP-CHANGELOG.md
- config/config/wc-config.yaml
- helmfile/values/fluentd-user.yaml.gotmpl
- helmfile/values/fluentd-wc.yaml.gotmpl
https://github.com/elastisys/compliantkubernetes-apps/issues/1317
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1317
This is a solution that at least seems to work. Is it perfect? Not sure. Removing the limits of the pod may not be needed to stop the error from happening in the first place but it seems to be needed to get rid of it in practice when it have been going on for a long time.
**Checklist:**
E.g. …
> apps wc: stuck ingesting ingress-nginx logs

- bin/test.bash
- pipeline/test/services/service-cluster/testCertManager.sh
- pipeline/test/services/workload-cluster/testCertManager.sh
Compliant Kubernetes needs more troubleshooting scripts to help operators quickly figure out faults in an environment.
We need checks for the status for the certificates and ingresses so we can assert that they work as they should.
**Which issue this PR fixes** : fixes #1190
> tests: Add troubleshooting script for certificates/ingress

- WIP-CHANGELOG.md
- scripts/restore/network-policies-harbor.yaml
**What this PR does / why we need it**: 
Found this issue while trying to restore a harbor database, so this fix is tested.
I could probably fix something more exact, but this felt good enough for now.
**Checklist:**
I.e. …
> apps sc: fix harbor restore networkpolicy

- CHANGELOG.md
- migration/v0.26.x-v0.27.x/upgrade-apps.md
- migration/v0.27.0-v0.27.1/upgrade-apps.md
**What this PR does / why we need it**: to update main branch with the patch release v0.27.1 instructions
**Checklist:**
> release: updated the docs for v0.27.1

- bin/ck8s
- bin/test.bash
- pipeline/test/services/funcs.sh
- pipeline/test/services/service-cluster/testCertManager.sh
- pipeline/test/services/service-cluster/testIngress.sh
- pipeline/test/services/service-cluster/testOpensearch.sh
- pipeline/test/services/workload-cluster/testCertManager.sh
- pipeline/test/services/workload-cluster/testIngress.sh
Compliant Kubernetes needs more troubleshooting scripts to help operators quickly figure out faults in an environment.
We could use some checks for the logging stack so we can quickly assert that it works as it should.
**Which issue this PR fixes** : fixes #1193 #1191
> tests: Add troubleshooting script for logging/certificates/ingress

- WIP-CHANGELOG.md
- bin/init.bash
- bin/update-ips.bash
- helmfile/values/harbor.yaml.gotmpl
- migration/v0.27.x-v0.28.x/add-registry-credentials.sh
Fixes the Harbor registry credentials which prevented it from authenticating.
**Checklist:**
> apps sc: Fix Harbor registry credentials

- WIP-CHANGELOG.md
- config/config/sc-config.yaml
**What this PR does / why we need it**: to speed up the startup of Grafana
**Checklist:**
> apps sc: increased cpu requests and limits for grafana

- WIP-CHANGELOG.md
- bin/update-ips.bash
On environments with Wireguard enabled the traffic may come on different IPs than the ones of the node or IPIP tunnel.
**Checklist:**
> bin: Update IPs with Calico Wireguard enabled

- WIP-CHANGELOG.md
- bin/ck8s
- bin/test.bash
Since some of the tests now run with functions instead of separate scripts we need to change where we expose the kubeconfig.
Will fix the issue in the pipeline.
We should reconsider how we manage the kubeconfig in our scripts.
**Checklist:** …
> bin: Test scripts can now always access the kubeconfig

- .github/workflows/end-to-end.yml
- pipeline/config/exoscale/pipeline-sc-config/default.tfvars
- pipeline/config/exoscale/pipeline-sc-config/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml
- pipeline/config/exoscale/pipeline-wc-config/default.tfvars
- pipeline/config/exoscale/pipeline-wc-config/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml
**What this PR does / why we need it**: to upgrade the terraform version and implement a retry strategy for the terraform and kubespray steps
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1079 
- [green pipeline 1](https://github.com/elastisys/compliantkubernetes-apps/actions/runs/3931622349)
- [green pipeline 2](https://github.com/elastisys/compliantkubernetes-apps/actions/runs/3937226277)
**Checklist:**
will not be responding …
> pipeline: upgrade terraform

- WIP-CHANGELOG.md
- helmfile/charts/grafana-ops/dashboards/networkpolicy-dashboard.json
Updated the netpol dashboard to be more clear, I've had a version for quite some time so I thought it was time to push it.
Let me know what you think.
(By default it will use last 15 minutes + auto update on 10s.)
**Checklist:** …
> apps sc: Update NetworkPolicy Dashboard

- WIP-CHANGELOG.md
- helmfile/charts/networkpolicy-service/templates/grafana/allow-grafana.yaml
- helmfile/charts/networkpolicy-service/templates/thanos/allow-thanos-query.yaml
- helmfile/charts/networkpolicy-service/templates/thanos/allow-thanos-ruler.yaml
- helmfile/values/grafana-user.yaml.gotmpl
- helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
- helmfile/values/thanos/query.yaml.gotmpl
- helmfile/values/thanos/receiver.yaml.gotmpl
This makes some changes to improve our setup, especially to make the Rulers access to metrics more redundant, and make it easier in dev environments to inspect alerts.
Part of #1205
Inspection of alerts have been disabled in user Grafana.
We probably need to update more of the netpols to allow DNS with TCP to reduce potential resolve errors.
**Checklist:**
I.e. full …
> apps sc: Thanos configuration updates

- WIP-CHANGELOG.md
- bin/init.bash
- helmfile/charts/networkpolicy-common/templates/rook-ceph/csi-detect-version.yaml
- helmfile/charts/networkpolicy-common/templates/rook-ceph/csi-rbdplugin-provisioner.yaml
- helmfile/charts/networkpolicy-common/templates/rook-ceph/mon.yaml
Add missing np for rook-ceph-csi-detect-version
**Which issue this PR fixes**: fixes #1329 
Definition of Done
**Checklist:** …
> apps: missing np for rook-ceph

- WIP-CHANGELOG.md
- bin/test.bash
- pipeline/test/services/workload-cluster/testHNC.sh
- pipeline/test/services/workload-cluster/testUserRbac.sh
Compliant Kubernetes needs more troubleshooting scripts to help operators quickly figure out faults in an environment.
We could use some checks for user access and namespaces so we can quickly assert that they work as they should.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1198
> tests: Add troubleshooting script for user access & sub namespaces

- pipeline/test/services/service-cluster/testPrometheusTargets.sh
**What this PR does / why we need it**: the test sc was failing when checking service monitor for thanos ruler and query:
> serviceMonitor/thanos/thanos-receiver-ruler/0	❌
> serviceMonitor/thanos/thanos-query-query/0	❌
**Checklist:**
> tests sc: fix thanos ruler and query tests

- WIP-CHANGELOG.md
- config/secrets/sc-secrets.yaml
- helmfile/values/opensearch/configurer.yaml.gotmpl
**What this PR does / why we need it**: to enable static users in opensearch
**Which issue this PR fixes**: fixes #1067
1. `GET _plugins/_security/api/internalusers`
```
{
"static-user2" : {
"hash" : "",
"reserved" : false,
"hidden" : false,
"backend_roles" : [
"backed_role2"
],
"attributes" : {
"foo" : "boo",
"red" : "blue"
},
"opendistro_security_roles" : [
"kibana_user"
],
"static" : false
},
"static-user" : {
"hash" : "",
"reserved" : false,
"hidden" : false,
"backend_roles" : [
"backed_role"
],
"attributes" : {
"green" : "yellow",
"too" : "roo"
},
"opendistro_security_roles" : [
"kibana_user"
],
"static" : false
},
```
2. I disabled SSO and I could successfully login to opensearch dashboard
**Checklist:**
- Is …
> apps sc: support for opensearch static users

- WIP-CHANGELOG.md
- helmfile/upstream/starboard-operator/Chart.yaml
- helmfile/upstream/starboard-operator/crds/clustercompliancedetailreports.crd.yaml
- helmfile/upstream/starboard-operator/crds/clustercompliancereports.crd.yaml
- helmfile/upstream/starboard-operator/crds/clusterconfigauditreports.crd.yaml
- helmfile/upstream/starboard-operator/crds/clustervulnerabilityreports.crd.yaml
- helmfile/upstream/starboard-operator/crds/configauditreports.crd.yaml
- helmfile/upstream/starboard-operator/crds/kubehunterreports.crd.yaml
- helmfile/upstream/starboard-operator/crds/vulnerabilityreports.crd.yaml
- helmfile/upstream/starboard-operator/templates/NOTES.txt
- helmfile/upstream/starboard-operator/templates/config.yaml
- helmfile/upstream/starboard-operator/templates/deployment.yaml
- helmfile/upstream/starboard-operator/templates/policies.yaml
- helmfile/upstream/starboard-operator/templates/rbac.yaml
- helmfile/upstream/starboard-operator/values.yaml
- helmfile/values/starboard/starboard-operator.yaml.gotmpl
- migration/v0.28.x-v0.29.x/upgrade-apps.md
This was part of my QA for ck8s-kubespray `v2.21.0-ck8s1`. In Kubernetes version `1.25` the apiGroup `batch/v1beta1` is removed. Our current version of starboard-operator tries to use that apiGroup for some cronjob and gets stuck in a crashloop. Upgrading starboard to this version fixes that.
I did not do a super thorough QA check for the new version of the starboard-operator but I basically just disabled all the new values that were introduced and it seems to work well. Vulnerabilityreports are able to run and there are no alerts firing related to it.
There is this "[ClusterComplianceReport](https://github.com/aquasecurity/starboard/blob/main/deploy/specs/nsa-1.0.yaml)" that I haven't tried yet, could be worth looking at if someone is interested, …
> apps: upgraded starboard operator to 0.15.11

- WIP-CHANGELOG.md
- helmfile/charts/networkpolicy-service/templates/opensearch/client.yaml
- helmfile/charts/networkpolicy-service/templates/opensearch/data.yaml
So they can now reach the snapshot repository as well.
fixes #1410
~~I'm not really able to test but would dedicated client nodes access S3 directly as well?~~ There is good reason to assume they may so I added that as well.
**Checklist:** …
> apps sc: Fix OpenSearch netpol for dedicated nodes

- WIP-CHANGELOG.md
- scripts/clean-sc.sh
In certain situations cert-manager Challenges gets stuck in a pending state with a finalizer which would prevent certain namespaces such as monitoring and harbor from terminating after running the `clean-sc.sh` script. This PR solves this issue.
**Which issue this PR fixes:**
fixes [#1396](https://github.com/elastisys/compliantkubernetes-apps/issues/1396)
**Note** that I have not been able to fully replicate the situation described in the issue, but it has been tested that you can run the script without getting an error and that it can patch a Challenge, removing any finalizers.
The solution uses `kubectl patch` in this case, but a shorter version that should also …
> bin: Added patching of pending challenges with finalizers

- WIP-CHANGELOG.md
- bin/update-ips.bash
**What this PR does / why we need it**: when sync to a different S3 bucket is enabled the update-ips script is throwing an error without adding the destination IP in the sc-config.yaml:
`[ck8s] No ips for s3-region.provider.com:8080 was found`
**Checklist:**
> bin: fix destinationObjectStorage ips

- WIP-CHANGELOG.md
- helmfile/50-applications.yaml
- helmfile/charts/networkpolicy-common/templates/kured/allow.yaml
- helmfile/upstream/kured/Chart.yaml
- helmfile/upstream/kured/README.md
- helmfile/upstream/kured/templates/NOTES.txt
- helmfile/upstream/kured/templates/_helpers.tpl
- helmfile/upstream/kured/templates/daemonset.yaml
- helmfile/upstream/kured/values.minikube.yaml
- helmfile/upstream/kured/values.yaml
- helmfile/values/kured.yaml.gotmpl
Upgraded kured chart to 4.4.1 and app version to 1.12.1
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1226 
**Checklist:**
**Pipeline config** *(if …
> apps: upgraded kured to 1.12.1

- WIP-CHANGELOG.md
- helmfile/50-applications.yaml
- helmfile/charts/grafana-ops/dashboards/opensearch-dashboard.json
- helmfile/values/prometheus-opensearch-exporter.yaml.gotmpl
- pipeline/test/services/service-cluster/testPodsReady.sh
- pipeline/test/services/service-cluster/testPrometheusTargets.sh
apps sc: Renamed ElasticSearch dashboard
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1382 
**Checklist:**
If you …
> apps sc: Renamed ElasticSearch dashboard

- pipeline/test/services/workload-cluster/testCertManager.sh
**What this PR does / why we need it**:  hnc certificate has a different name from the one in the test script `hnc-controller-webhook-server-cert`. I updated the name in the script.
**Checklist:** …
> bin: fix test wc cert-manager script for hnc

- WIP-CHANGELOG.md
- helmfile/values/falco.yaml.gotmpl
Since we don't want to get alerts for redis we need to add some exceptions for it.
**Checklist:** …
> apps: Added falco rules for redis

- WIP-CHANGELOG.md
- config/config/wc-config.yaml
- migration/v0.28.x-v0.29.x/upgrade-apps.md
Update Gatekeeper default enforcements
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1326 
[Docs PR](https://github.com/elastisys/compliantkubernetes/pull/510)
**Checklist:**
- Chart …
> apps wc: Update Gatekeeper default enforcements

- WIP-CHANGELOG.md
Fixing a conflict that was missed and merged in [this PR](https://github.com/elastisys/compliantkubernetes-apps/pull/1416)
**Checklist:**
- …
> docs: Fix changelog

- WIP-CHANGELOG.md
- scripts/deploy-wc.sh
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1393 
**Checklist:** …
> Add extra-workload-admins role binding
