config/config/flavors/prod-sc.yaml
**What this PR does / why we need it**: Part of qa testing for v0.7.0. Fixes minor typo in elasticsearch config for prod flavor.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #9 
**Checklist:**
=> config: fixes typo in elasticsearch resource config

WIP-CHANGELOG.md, helmfile/values/elasticsearch-slm.yaml.gotmpl
**What this PR does / why we need it**: Part of qa testing for v0.7.0. Fixes typo in slm config
**Checklist:**
=> apps sc: elastic slm schedule typo fixed

helmfile/01-applications.yaml
Just a minor cleanup in the apps helmfile.
**Checklist:**
=> apps: Don't add falco repo for sc

config/config/sc-config.yaml
**What this PR does / why we need it**: Part of qa testing for v0.7.0. If you only have one entry in this list in your config, then the validation will complain. So removing one of these entries will prevent the errors. This is just a partial fix and we should do some better handling of lists later on.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: part of #41 
**Checklist:**
E.g. removes or changes any CK8S config …
=> Minor fix to prevent errors in config validation

bin/common.bash
One possible solution on how we can relax the configuration validation.
fixes #59 
I am not sure if it is smart to read user input or not. Might not be so good for the pipeline.
This is what it looks like right now:
```
[ck8s] Validating wc config
[ck8s] WARN: fluentd.nodeSelector."node-role.kubernetes.io/master" is not set in /home/user/.ck8s/cloud_p/env_name/wc-config.yaml
[ck8s] Do you want to exit? (y/n): y
```
**Checklist:**
=> bin: Warn if config options are missing

WIP-CHANGELOG.md, helmfile/01-applications.yaml, helmfile/values/dex.yaml.gotmpl
**What this PR does / why we need it**: Updates dex application and chart
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #193
**Checklist:**
=> Dex update

pipeline/init.bash
Hotfix to make pipeline work again
fixes #101 
**Checklist:**
=> pipeline: Fixed error where pipeline always fails

WIP-CHANGELOG.md, bin/init.bash, bootstrap/storageclass/bootstrap.sh, config/config/flavors/dev-sc.yaml, config/config/flavors/prod-sc.yaml, config/config/sc-config.yaml, helmfile/01-applications.yaml, helmfile/values/elasticsearch-exporter.yaml.gotmpl, helmfile/values/opendistro-es.yaml.gotmpl, migration/v0.7.x-v0.8.x/opendistro.md, pipeline/test/services/service-cluster/testPodsReady.sh
fixes #94 
fixes https://github.com/elastisys/ck8s-apps/issues/244
fixes https://github.com/elastisys/ck8s/issues/622
fixes https://github.com/elastisys/ck8s-apps/issues/135
fixes https://github.com/elastisys/ck8s-apps/issues/223
I have only tested the upgrade path for the dev-flavor.
**Checklist:**
=> Opendistro configuration

WIP-CHANGELOG.md, helmfile/values/user-alertmanager.yaml.gotmpl
=> apps wc: Use correct password key for user-alertmgr

pipeline/test/services/service-cluster/testEndpoints.sh, pipeline/test/services/workload-cluster/testEndpoints.sh
```
❯ ./bin/ck8s test wc
....
Successes: 185
Failures: 0
All tests succeded
```
**Checklist:**
=> Update pipeline endpoint tests

CHANGELOG.md
This is already on the release branch, just missing on main.
**What this PR does / why we need it**: Just makes it easier to see all releases directly on the main branch.
**Checklist:**
=> release: Add v0.8.0 changelog

WIP-CHANGELOG.md, helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
=> apps sc: Fix opengenie config

README.md
=> docs: Add issue about es and local volumes

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/investigation.md
To make issues more consistent and easier to write/read I added these templates (github default with minor changes)
part of elastisys/compliantkubernetes-kubespray#13
=> Added issue templates

config/config/wc-config.yaml
Part of
- https://github.com/elastisys/compliantkubernetes/issues/8
- https://github.com/elastisys/ck8s-apps/issues/228
I've used [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml) as reference.
**Checklist:**
=> config: Document settings in wc-config.yaml

helmfile/01-applications.yaml
Removes the helm releases that were deprecated in 0.9.0
fixes #155 
Have not tested yet.
**Checklist:**
=> apps: Remove deprecated helm releases

README.md, WIP-CHANGELOG.md, migration/v0.9.x-v0.10.x/upgrade-apps.md
=> [QA] docs: Complement upgrade docs and add note on k8s 1.19

helmfile/charts/issuers/templates/NOTES.txt, helmfile/charts/issuers/templates/_helpers.tpl, pipeline/init-unit-tests.bash
This PR adds validation for emails set to Issuers. Previously, setting an invalid email address lead to hard-to-find issues, like Certificates not becoming ready, because Issuers are not ready, because Issuer emails are incorrect. This PR makes the `apply` step fail. 
N/A
**Checklist:**
- [NA?] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/compliantkubernetes-apps/blob/main/WIP-CHANGELOG.md)
- [NA] Updated the [public facing …
=> Validate issuers email

migration/v0.10.x-v0.11.x/upgrade-apps.md
Updated the migration guide to include all steps neccessary.
=> Migration scrip update 

README.md, config/config/sc-config.yaml
Document a known limitation with Kibana and SSO via OpenID/Dex.
Known issues are currently only captured in this repo. Unsure if it makes sense to make them "more public" than that.
**Checklist:** …
=> docs: Document Kibana SSO limitation

migration/v0.10.x-v0.11.x/upgrade-apps.md
Cherry-picked the minor changes from QA for release 0.11
=> Cherry pick release

WIP-CHANGELOG.md, config/config/sc-config.yaml, config/config/wc-config.yaml, pipeline/config/exoscale/sc-config.yaml, pipeline/config/exoscale/wc-config.yaml
Removes some old leftover tolerations configuration for nginx.
**Checklist:**
=> config: Remove default tolerations for ingress-nginx

WIP-CHANGELOG.md, config/config/sc-config.yaml, config/config/wc-config.yaml, migration/v0.11.x-v0.12.x/upgrade-apps.md, pipeline/config/exoscale/sc-config.yaml, pipeline/config/exoscale/wc-config.yaml
Removes unsused config option `objectStorage.s3.regionAddress` that might have caused some confusion.
Related to #300 
**Checklist:**
=> config: Remove objectStorage.s3.regionAddress

helmfile/values/opendistro-es.yaml.gotmpl
Removed a field from the opendistro helm values file that was not used.
**Checklist:**
=> apps sc: Remove unused s3 config value for opendistro

WIP-CHANGELOG.md, helmfile/01-applications.yaml, helmfile/charts/gatekeeper-metrics/.helmignore, helmfile/charts/gatekeeper-metrics/Chart.yaml, helmfile/charts/gatekeeper-metrics/templates/gatekeeper-audit-metrics.yaml, helmfile/charts/gatekeeper-metrics/templates/gatekeeper-controller-metrics.yaml, helmfile/charts/grafana-ops/dashboards/gatekeeper-dashboard.json, helmfile/values/gatekeeper.yaml.gotmpl, migration/v0.11.x-v0.12.x/upgrade-apps.md
Change to official gatekeeper chart
Add new chart for metrics service/servicemonitor
Update gatekeeper dashboard slightly
I have not tested to migrate a cluster to this update, I might have to add some instructions on that but I'm hoping that a regular apply will work.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #230 
**Checklist:**
E.g. removes or changes any CK8S …
=> apps wc: update gatekeeper to v3.3.0

README.md
To lessen the likelihood that people run apps apply without having configured s3 properly.
Part of #300 
This is just a check for S3, one could make a similar one for gcp i guess but i have no experice with it.
As we are talking about moving away from wrappers i did not bother to implement a check for this in ./bin/ck8s.
**Checklist:** …
=> docs: Add note to check S3 configuration before apply

.github/workflows/end-to-end.yml
Updates the pipeline to use the S3 scripts in this repository.
**Checklist:**
=> Update bucket creation and deletion in e2e pipeline

WIP-CHANGELOG.md, helmfile/values/elasticsearch-slm.yaml.gotmpl
Without the quote helm/helmfile converts the integer to scientific
notation
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #337
**Checklist:** …
=> Fix elasticsearch-slm value conversion

CHANGELOG.md, config/config/sc-config.yaml
Small fix to minimize default warnings when applying
**Checklist:** …
=> config: Changed default value for disabled option

WIP-CHANGELOG.md, helmfile/charts/elasticsearch-slm/values.yaml
Increases the active deadline for the slm job so it can complete the task within the timeline.
**Checklist:** …
=> Increased slm job active deadline from 5 to 10 minutes

README.md
The spelling/path error was annoying
**Checklist:** …
=> docs: fixed a minor error where it said /scrips/ instead of /scripts/

CHANGELOG.md, config/config/sc-config.yaml, migration/v0.11.x-v0.12.x/upgrade-apps.md
**What this PR does / why we need it**: Fixes from the 0.12 release QA.
**Checklist:** …
=> Release 0.12 fixes

SECURITY.md
New URL for subscribing to security list
**Checklist:** …
=> Updated security list subscription link

WIP-CHANGELOG.md, config/config/flavors/dev-sc.yaml, config/config/flavors/prod-sc.yaml, config/config/sc-config.yaml, helmfile/01-applications.yaml, helmfile/values/fluentd-user.yaml.gotmpl, helmfile/values/fluentd-wc.yaml.gotmpl, helmfile/values/opendistro-es.yaml.gotmpl
The authlog (/var/log/authlog) contains information about failed access attempts to the nodes. This PR tails the authlog, formats the message and sends it to opendistro.
**NOTE that in order for this to work you need to use version 1.12.1 or later of the elastisys/opendistro-es chart** 
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #140
**Checklist:** …
=> Petter od authlog

helmfile/values/opendistro-es.yaml.gotmpl
Fixed typo from https://github.com/elastisys/compliantkubernetes-apps/pull/365
**Checklist:** …
=> apps sc: Fixed typo in auth log

CODEOWNERS
Removes non-dev-ops people from codeowners.
**Checklist:**
=> all: Clear non DevOps people from codeowners

helmfile/values/dex.yaml.gotmpl
CRDs are now no longer installed before the apps are installed.
Dex need permission to create them.
**Checklist:** …
=> apps sc: Fix Dex RBAC

pipeline/Dockerfile
**What this PR does / why we need it**: The version was recently updated for ck8s, but the pipeline was missed.
Related to https://github.com/elastisys/compliantkubernetes-apps/commit/bca28e5e9479116c4ad4e749d73e11c5f9659fd1
**Checklist:**
**Pipeline …
=> pipeline: bump version of helm diff

WIP-CHANGELOG.md, bin/kubeconfig.bash, config/config/sc-config.yaml, config/secrets/sc-secrets.yaml, helmfile/values/dex.yaml.gotmpl, helmfile/values/grafana-user.yaml.gotmpl, migration/v0.15.x-v0.16.x/migrate-apps.sh, migration/v0.15.x-v0.16.x/update-script.yaml, migration/v0.15.x-v0.16.x/upgrade-apps.md, pipeline/config/exoscale/sc-config.yaml, pipeline/config/exoscale/secrets.yaml
Rework of how we configure dex connectors to enable multiple connectors.
fixes #448
**Checklist:** …
=> [1] Rework of dex connectors config

pipeline/config/exoscale/sc-config.yaml
Fixes error introduced in https://github.com/elastisys/compliantkubernetes-apps/pull/451
=> Fixed pipeline error from oidc PR

WIP-CHANGELOG.md, config/config/sc-config.yaml, config/secrets/sc-secrets.yaml, helmfile/values/dex.yaml.gotmpl, helmfile/values/grafana-user.yaml.gotmpl, helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl, pipeline/config/exoscale/sc-config.yaml
Since we want to use dex for everything I added support for ops grafana
**Checklist:**
=> [1] Added support for OIDC for ops grafana

WIP-CHANGELOG.md, config/config/sc-config.yaml, helmfile/charts/init-harbor/templates/init-harbor-cm.yml, helmfile/charts/init-harbor/values.yaml, helmfile/values/init-harbor.yaml.gotmpl, pipeline/config/exoscale/sc-config.yaml
This adds the option to set the admin group in harbor for when OIDC is used
**Checklist:** …
=> [1] Added option to set harbor admin group

pipeline/config/exoscale/sc-config.yaml
=> Added missed pipeline config

CHANGELOG.md, helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
Since grafana are using a PV rolling upgrade wont work.
**Checklist:** …
=> Fixed issue where grafana got stuck on upgrade

helmfile/values/prometheus-alerts-sc.yaml.gotmpl
=> fix rook monitoring

migration/v0.15.x-v0.16.x/migrate-crd.sh, migration/v0.15.x-v0.16.x/upgrade-apps.md
Needed for migration if CRDs
**Checklist:** …
=> Added migration script for the CRDs

CHANGELOG.md, helmfile/50-applications.yaml, helmfile/upstream/starboard-operator/Chart.yaml, helmfile/upstream/starboard-operator/crds/vulnerabilityreports.crd.yaml, helmfile/upstream/starboard-operator/values.yaml, helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl, helmfile/values/prometheus-alerts-sc.yaml.gotmpl, migration/v0.15.x-v0.16.x/migrate-crd.sh, migration/v0.15.x-v0.16.x/upgrade-apps.md
Merge QA into release branch
**Checklist:** …
=> Qa 0.16 fixes to release

CHANGELOG.md, helmfile/values/prometheus-user-alerts-wc.yaml.gotmpl
=> apps: fixed rook monitor in user alertmanager

CHANGELOG.md, helmfile/50-applications.yaml, helmfile/upstream/starboard-operator/Chart.yaml, helmfile/upstream/starboard-operator/crds/vulnerabilityreports.crd.yaml, helmfile/upstream/starboard-operator/values.yaml, helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl, helmfile/values/prometheus-alerts-sc.yaml.gotmpl, helmfile/values/prometheus-user-alerts-wc.yaml.gotmpl, migration/v0.15.x-v0.16.x/migrate-crd.sh, migration/v0.15.x-v0.16.x/upgrade-apps.md
Merge QA into main branch
**Checklist:** …
=> Qa 0.16 fixes to main

.github/workflows/pipeline.yml, .gitmodules, bin/init.bash, config/config/flavors/dev-sc.yaml, config/config/flavors/prod-sc.yaml, config/config/sc-config.yaml, config/config/wc-config.yaml, pipeline/Dockerfile, pipeline/README.md, pipeline/init.bats, pipeline/test-opa.bash, pipeline/test/services/unit-tests/test-opa.sh
This adds a few tests for the init command. It uses Bats which was recently added to our tech radar in [ADR-0014](https://compliantkubernetes.io/adr/0014-use-bats-for-testing-bash-wrappers/).
It also does a bit of cleaning and adds some minor fixes.
**Checklist:** …
=> Init command tests

README.md, WIP-CHANGELOG.md, scripts/generate-secrets.sh
I had this scrip laying around so I thought I would add it here.
Makes it easier to generate secrets for a new deployment (Or to update existing ones)
**Checklist:**
If you …
=> [1] Added script to make it easier to update secrets

WIP-CHANGELOG.md, helmfile/values/elasticsearch-slm.yaml.gotmpl
Slightly increased slm cpu request to match real world use.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes not-planned
**Checklist:**
If you change some config options (e.g. add/rename variable or change the default value) you …
=> Increased slm cpu request slightly

helmfile/charts/grafana-ops/dashboards/calico-felix-dashboard.json, helmfile/charts/grafana-ops/templates/dashboard-configmap.yaml, helmfile/charts/grafana-ops/values.yaml
**What this PR does / why we need it**: This will add a Grafana dashboard for calico felix metrics.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #529 
**Checklist:**
If you change some config options (e.g. add/rename variable …
=> apps sc: added the calico-felix grafana dashboard

WIP-CHANGELOG.md, helmfile/50-applications.yaml, helmfile/elastisys/influxdb/Chart.yaml, helmfile/elastisys/influxdb/templates/backup-cronjob.yaml
To move the `rm` command to before the backup rather than after (will fix some issues)
**Checklist:** …
=> Updated influxdb to 4.8.13

WIP-CHANGELOG.md, helmfile/50-applications.yaml, helmfile/elastisys/influxdb/Chart.yaml, helmfile/elastisys/influxdb/templates/elastisys_custom/monitoring-service.yaml
Removes unnecessary alerts from influxdb backups
**Which issue this PR fixes**
fixes #411
**Checklist:**
=> apps sc: Upgraded influxdb to 4.8.14

WIP-CHANGELOG.md, config/config/sc-config.yaml, config/config/wc-config.yaml, helmfile/50-applications.yaml, helmfile/charts/calico-felix-metrics/.helmignore, helmfile/charts/calico-felix-metrics/Chart.yaml, helmfile/charts/calico-felix-metrics/README.md, helmfile/charts/calico-felix-metrics/templates/service.yaml, helmfile/charts/grafana-ops/dashboards/calico-felix-dashboard.json, helmfile/charts/grafana-ops/templates/dashboard-configmap.yaml, helmfile/charts/grafana-ops/values.yaml, pipeline/config/exoscale/sc-config.yaml, pipeline/config/exoscale/wc-config.yaml
**What this PR does / why we need it**: this will allow us to scrape calico felix pods for metrics
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #527
**Special notes for reviewer**: my 1st PR for apps please let me know if I missed something 
**Checklist:**
If …
=> Calico metrics scrape

WIP-CHANGELOG.md, helmfile/50-applications.yaml, helmfile/elastisys/influxdb/Chart.yaml, helmfile/elastisys/influxdb/templates/elastisys_custom/common-env-vars-cm.yaml, helmfile/elastisys/influxdb/templates/elastisys_custom/cronjob-cm.yaml, helmfile/elastisys/influxdb/templates/elastisys_custom/script-cm.yaml
This fixes the problem when disabling retention for influxdb in sc-config breaks influxdb.
fixes #350 
**Checklist:** …
=> apps sc: Fixed influxdb retention disabled

.github/workflows/end-to-end.yml
**What this PR does / why we need it**: it added the failed job and step name to the alert message
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #526 
**Checklist:** …
=> Pipeline alerts more details

CHANGELOG.md, config/config/sc-config.yaml
Set resource request to be limits/2 for harbor.
**Checklist:**
If you change some config options (e.g. add/rename variable or change the …
=> apps sc: increase harbor requests

CHANGELOG.md, config/config/sc-config.yaml, config/config/wc-config.yaml, helmfile/charts/prometheus-servicemonitor/values.yaml, helmfile/values/sc-servicemonitor.yaml.gotmpl, helmfile/values/wc-servicemonitor.yaml.gotmpl, migration/v0.17.x-v0.18.x/remove-velero-backupstoragelocation.sh, migration/v0.17.x-v0.18.x/upgrade-apps.md
**What this PR does / why we need it**: Fixes from the QA process for release v0.18.0 of apps.
**Checklist:**
If you change some config options (e.g. add/rename variable or change …
=> Release v0.18.0 QA

CHANGELOG.md, config/config/sc-config.yaml, config/config/wc-config.yaml, helmfile/charts/prometheus-servicemonitor/values.yaml, helmfile/values/sc-servicemonitor.yaml.gotmpl, helmfile/values/wc-servicemonitor.yaml.gotmpl, migration/v0.17.x-v0.18.x/remove-velero-backupstoragelocation.sh, migration/v0.17.x-v0.18.x/upgrade-apps.md
**What this PR does / why we need it**: Cherry-picked commits from QA process of release v0.18.0
**Checklist:** …
=> Release 0.18 fixes

WIP-CHANGELOG.md, config/config/sc-config.yaml, helmfile/values/fluentd-configmap.yaml.gotmpl, helmfile/values/fluentd-sc.yaml.gotmpl, helmfile/values/fluentd-user.yaml.gotmpl, helmfile/values/fluentd-wc.yaml.gotmpl, migration/v0.18.x-v0.19.x/upgrade-apps.md
Doing some investigation on #520 this task revealed the use of some deprecated parameter, this PR aims to fix that and some other improvements of fluentd
fixes #597
**Checklist:** …
=> Update fluentd config

helmfile/elastisys/opendistro-es/files/qa.txt
Remove file that I assume was added by mistake.
It's not present in upstream at least.
**Public facing documentation PR** *(if applicable)*:
**Checklist:**
=> all: rm qa.txt from elastisys opendistro

release/README.md
Updates the patch release steps to make it easier.
I've changed some of the branch naming convention to reduce friction (to not use `release` prefix for a patch branch) and this would help reduce residual branches after patching.
Let me know if that is something I should revert, or something we should consider doing in the regular major/minor flow as well (in the case of merging fixes back into main).
**Checklist:**
E.g. removes or changes any CK8S config …
=> docs: Update patch release steps

helmfile/charts/blackbox/requirements.yaml
Fixes issue with the main branch where (at least for me) deployment fails because of a version missmatch
**Checklist:** …
=> apps: Fixed version error in blackbox exporter

helmfile/values/blackbox-sc.yaml.gotmpl
=> apps: minor config error

WIP-CHANGELOG.md, helmfile/charts/grafana-ops/dashboards/node-exporter-full-dashboard.json, helmfile/charts/grafana-ops/values.yaml
Unplanned PR, since we add this dashboard (that doesn't really work) to most clusters we should just add a working version
**Checklist:**
- [x is completely transparent, will not impact the workload in any way.
- …
=> apps sc: Added node exporter full dashboard

CHANGELOG.md, config/config/common-config.yaml, config/config/sc-config.yaml, config/config/wc-config.yaml, helmfile/charts/prometheus-alerts/files/thanos-rules.yaml, helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl, helmfile/values/kube-prometheus-stack-wc.yaml.gotmpl, helmfile/values/prometheus-alerts-sc.yaml.gotmpl, helmfile/values/prometheus-alerts-wc.yaml.gotmpl, helmfile/values/prometheus-wc-reader.yaml.gotmpl, migration/v0.18.x-v0.19.x/opensearch-migration-clean.sh, migration/v0.18.x-v0.19.x/opensearch-migration-configuration.sh, migration/v0.18.x-v0.19.x/opensearch-migration-run.sh, migration/v0.18.x-v0.19.x/upgrade-apps.md, migration/v0.18.x-v0.19.x/user-alertmanager-run.sh, pipeline/test/services/workload-cluster/testPodsReady.sh
**What this PR does / why we need it**: fixes for 0.19 release
=> Release 0.19 fixes

scripts/restore/README.md
Harbor backup restore docs update.
**Checklist:** …
=> apps sc: harbor docs update

WIP-CHANGELOG.md, helmfile/50-applications.yaml
Removes disabled helm releases from last release.
**Checklist:**
=> apps: Remove disabled helm releases

WIP-CHANGELOG.md, config/config/common-config.yaml, config/config/sc-config.yaml, helmfile/charts/prometheus-alerts/templates/rules/backup-status.yaml, helmfile/charts/prometheus-alerts/templates/rules/bucket-daily-checks.yaml, helmfile/charts/prometheus-alerts/templates/rules/daily-checks.yaml, helmfile/charts/prometheus-alerts/templates/rules/predict-linear.yaml, helmfile/charts/prometheus-alerts/values.yaml, helmfile/values/prometheus-alerts-sc.yaml.gotmpl, pipeline/config/exoscale/common-config.yaml
To be able to start relying on alerts to inform operators about bad clusters rather than having to look at the daily dashboards for all running cluster we need to create alerts for all the things we look at on the dashboards. This should be possible since we have the metrics for all the things.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #568
**Checklist:**
E.g. …
=> apps sc: daily task alerts

scripts/clean-sc.sh
**What this PR does / why we need it**: to delete the new thanos and opensearch-system namespaces while running clean-sc.sh
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #842
**Checklist:** …
=> scripts: delete thanos and opensearch-system ns

CHANGELOG.md, config/config/sc-config.yaml, helmfile/charts/gatekeeper-templates/templates/disallow-tag/template.yaml, helmfile/charts/gatekeeper-templates/templates/image-registry/template.yaml, helmfile/charts/grafana-ops/dashboards/backup-dashboard.json, helmfile/charts/grafana-ops/dashboards/daily-dashboard.json, helmfile/charts/grafana-ops/dashboards/kubernetesstatus-dashboard.json, helmfile/values/harbor.yaml.gotmpl, migration/v0.19.x-v0.20.x/remove-grafana-ops.sh, migration/v0.19.x-v0.20.x/remove-influxdb-pvc-ns.sh, migration/v0.19.x-v0.20.x/upgrade-apps.md, migration/v0.19.x-v0.20.x/upgrade-thanos-receiver-pvc.sh, pipeline/test/services/service-cluster/testPrometheusTargets.sh
Apply the changes made in Apps QA 0.20.0 to main.
**Checklist:**
If …
=> Qa fixes 0.20

.pre-commit-config.yaml
Added pre-commit hook to stop commits to the main branch.
**Which issue this PR fixes** : fixes ([1478](https://github.com/elastisys/ck8s-ops/issues/1478) in ck8s-ops )
**Checklist:**
=> tests: added pre-commit hook to stop commits to main

WIP-CHANGELOG.md, helmfile/charts/grafana-ops/dashboards/backup-dashboard.json, helmfile/charts/grafana-ops/dashboards/falco-dashboard.json, helmfile/charts/grafana-ops/dashboards/gatekeeper-dashboard.json, helmfile/charts/grafana-ops/dashboards/networkpolicy-dashboard.json, helmfile/charts/grafana-ops/dashboards/nginx-dashboard.json, helmfile/charts/grafana-ops/dashboards/vulnerability-dashboard.json, helmfile/values/grafana-ops.yaml.gotmpl, migration/v0.20.x-v0.21.x/remove-grafana-ops.sh, migration/v0.20.x-v0.21.x/upgrade-apps.md
**What this PR does / why we need it**: to make the ciso dashboards visible to the end-users
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #909 
**Checklist:** …
=> apps sc: enabled user view for ciso dashboards

WIP-CHANGELOG.md, helmfile/charts/grafana-ops/dashboards/prometheus-timeseries-dashboard.json, helmfile/charts/grafana-ops/values.yaml, helmfile/values/grafana-ops.yaml.gotmpl
Added a dashboard that shows how many time series we have in Prometheus.
**Which issue this PR fixes** : fixes #741 
Did not make an alert for when there are too many time series which was something @viktor-f considered in #741.
**Checklist:**
=> apps sc: added prometheus timeseries dashboard

WIP-CHANGELOG.md, config/config/common-config.yaml, config/config/sc-config.yaml, config/config/wc-config.yaml, helmfile/values/prometheus-blackbox-exporter-sc.yaml.gotmpl, helmfile/values/prometheus-blackbox-exporter-wc.yaml.gotmpl
We want checks for our internal services just as we have checks on our external endpoints!
https://github.com/elastisys/ck8s-ops/issues/711
**Checklist:**
I.e. full cluster migration is …
=> apps wc & sc: blackbox internal service checks

WIP-CHANGELOG.md, config/config/sc-config.yaml, helmfile/50-applications.yaml, helmfile/upstream/dex/Chart.yaml, helmfile/upstream/dex/README.md, helmfile/upstream/dex/README.md.gotmpl, helmfile/upstream/dex/templates/deployment.yaml, helmfile/upstream/dex/templates/rbac.yaml, helmfile/upstream/dex/templates/servicemonitor.yaml, helmfile/upstream/dex/values.yaml, helmfile/values/dex.yaml.gotmpl
OpenSearch had authentication problems as OpenSearch and Dex had a problem "syncing" at points which led to temporary issues. This has now been solved by moving OpenSearch and dex one later above the other applications.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #900
**Checklist:** …
=> apps sc: dex upgrade 0.8.1 and two replicas 

WIP-CHANGELOG.md, bin/common.bash, bin/init.bash, config/config/sc-config.yaml, helmfile/values/opensearch/common.yaml.gotmpl, helmfile/values/thanos/receiver.yaml.gotmpl
**What this PR does / why we need it**: Add UpCloud support to init scripts, and some config changes that are necessary for apps to work on UpCloud
**Which issue this PR fixes**: fixes #916
**Checklist:** …
=> Add UpCloud support

CHANGELOG.md
adds release changelog for patch 0.20.2 onto main 
**Checklist:**
If …
=> Reset changelog for release v0.20.2

README.md, WIP-CHANGELOG.md, bin/common.bash, bin/init.bash, scripts/S3/generate-s3cfg.sh
Apps support for Elastx
**Checklist:** …
=> Apps support for Elastx

migration/v0.21.x-v0.22.x/upgrade-apps.md
apps: added migration steps to v0.22.0
**Checklist:**
If you change …
=> apps: added migration steps to v0.22.0

.github/workflows/end-to-end.yml, .github/workflows/pipeline.yml, pipeline/Dockerfile, pipeline/config/exoscale/common-config.yaml, pipeline/config/exoscale/pipeline-sc-config/group_vars/k8s_cluster/ck8s-k8s-cluster-default.yaml, pipeline/config/exoscale/pipeline-sc-config/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml, pipeline/config/exoscale/pipeline-wc-config/group_vars/k8s_cluster/ck8s-k8s-cluster-default.yaml, pipeline/config/exoscale/pipeline-wc-config/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml, pipeline/config/exoscale/sc-config.yaml, pipeline/config/exoscale/wc-config.yaml, pipeline/init-unit-tests.bash, pipeline/init.bats, pipeline/lint.bash, pipeline/test/services/service-cluster/testPrometheusTargets.sh
**What this PR does / why we need it**: to fix the pipelines
**Which issue this PR fixes**: fixes #1061
**Comments:**
- kubespray still fails sometimes with `fatal: [pipeline-wc-master-0]: FAILED! => {"msg": "Timeout (62s) waiting for privilege escalation prompt: "}` at `[kubernetes/kubeadm : Check if kubeadm CA cert is accessible]` task. I ran ansible with -vvvvv, but didn't find anything useful.
- Green pipelines:
- https://github.com/elastisys/compliantkubernetes-apps/actions/runs/2616301995
- https://github.com/elastisys/compliantkubernetes-apps/actions/runs/2596839503
- https://github.com/elastisys/compliantkubernetes-apps/actions/runs/2616301996
**Checklist:**
E.g. logs or metrics are not being collected or …
=> pipeline: kubespray 2.19, fix configs, small changes

README.md, WIP-CHANGELOG.md, get-requirements.yaml, pipeline/Dockerfile
Upgraded Helm to v3.8.0,
helmfile to v0.144.0 and
helm-secrets to v3.12.0. (New maintained version)
**Which issue this PR fixes** : (fixes #820, #821, #822) 
I tested installing apps on a clean cluster after each upgrade and had no issues.
Also changed repo of helm-secrets to maintained repo.
**Checklist:**
=> bin: upgraded Helm, helmfile & helm-secrets

WIP-CHANGELOG.md, config/config/common-config.yaml
=> increased blackbox resources

CHANGELOG.md, config/config/sc-config.yaml, helmfile/upstream/harbor/values.yaml, helmfile/values/harbor.yaml.gotmpl
**What this PR does / why we need it**: v0.24 QA fixes
=> apps sc: made multipartcopythresholdsize configurable for harbor s3

README.md, WIP-CHANGELOG.md, bin/common.bash, bin/init.bash, bin/kubeconfig.bash, bin/team.bash, get-requirements.yaml, pipeline/Dockerfile, pipeline/common.bash, pipeline/init-unit-tests.bash, pipeline/init.bats, pipeline/test/services/service-cluster/testEndpoints.sh, pipeline/test/services/service-cluster/testPodsReady.sh, pipeline/test/services/service-cluster/testPrometheusTargets.sh, pipeline/test/services/workload-cluster/testEndpoints.sh, pipeline/test/services/workload-cluster/testPodsReady.sh, pipeline/test/services/workload-cluster/testUserRbac.sh, scripts/S3/entry.sh, scripts/deploy-sc.sh, scripts/deploy-wc.sh, scripts/restore-sync/README.md, scripts/restore/README.md
bash scripts are now migrated to yq v4
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes  #202
**Checklist:**
If you …
=> bash scripts are now migrated to yq v4

WIP-CHANGELOG.md, bin/init.bash, config/config/sc-config.yaml, helmfile/values/harbor.yaml.gotmpl, migration/v0.24.x-v0.25.x/migrate-harbor-affinity-variables.sh, migration/v0.24.x-v0.25.x/migrate-harbor-database-variables.sh, migration/v0.24.x-v0.25.x/upgrade-apps.md
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #854
**Checklist:** …
=> apps-sc: Updated harbor chart to work in HA

config/config/flavors/prod/sc-config.yaml, migration/v0.24.x-v0.25.x/migrate-harbor-database-variables.sh, scripts/S3/entry.sh
=> Release 0.25 fixes

WIP-CHANGELOG.md, config/config/sc-config.yaml, helmfile/charts/grafana-ops/files/welcome.md, helmfile/charts/grafana-ops/values.yaml, helmfile/charts/opensearch/configurer/files/dashboards-resources/welcome.md, helmfile/charts/opensearch/configurer/values.yaml, helmfile/values/grafana-ops.yaml.gotmpl, helmfile/values/opensearch/configurer.yaml.gotmpl, migration/v0.25.x-v0.26.x/add-support-message.sh, migration/v0.25.x-v0.26.x/upgrade-apps.md
Removed the "support" part of the welcoming dashboards from opensource project and added it as an option in the cluster configs.
Wasn't able to find a solution that didn't involve adding the config to customer envs, but I made a simple optional script to ease the "migration".
**Which issue this PR fixes** : fixes #1068 
Added a migration script, but is not required.
**Checklist:**
=> apps sc: update welcoming dashboard

WIP-CHANGELOG.md, config/config/common-config.yaml, config/config/sc-config.yaml, helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl, helmfile/values/kube-prometheus-stack-wc.yaml.gotmpl, helmfile/values/thanos/query.yaml.gotmpl, helmfile/values/thanos/receiver.yaml.gotmpl
Add topologySpreadConstraints to our apps that could use multiple replicas.
**Which issue this PR fixes** : fixes #1055 
**Checklist:**
=> apps: add missing topologyspreadconstraints

release/README.md
=> docs: fix link in release guide

CHANGELOG.md
As we messed up the changelog the first time we need to make it right!
**Checklist:** …
=> docs: opensearch changelog fix v0.26.0

DEVELOPMENT.md
=> sops plugin

config/secrets/sc-secrets.yaml, config/secrets/wc-secrets.yaml, helmfile/50-applications.yaml, helmfile/charts/kured-secret/templates/kured-secret.yaml, helmfile/values/kured.yaml.gotmpl, migration/v0.25.x-v0.26.x/upgrade-apps.md
**What this PR does / why we need it**: to fix some issues with the migration docs and kured
=> fixes: to migration docs and kured

WIP-CHANGELOG.md, config/config/common-config.yaml, config/config/sc-config.yaml, config/config/wc-config.yaml, helmfile/charts/networkpolicy-service/templates/monitoring-np.yaml, helmfile/charts/networkpolicy-service/templates/thanos-np.yaml, helmfile/charts/networkpolicy-workload/templates/monitoring-np.yaml, helmfile/charts/user-alertmanager/templates/alertmanager.yaml, helmfile/charts/user-alertmanager/values.yaml, helmfile/values/gatekeeper.yaml.gotmpl, helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl, helmfile/values/kube-prometheus-stack-wc.yaml.gotmpl, helmfile/values/user-alertmanager.yaml.gotmpl, migration/v0.26.x-v0.27.x/upgrade-apps.md
**What this PR does / why we need it**: Added some resource optimization based on a recent investigation (details in another PR). Also fixed some networkpolicy issues.
**Checklist:**
- …
=> all: resource optimization and netpol fixes

README.md
Remove some of the known issues that are no longer relevant,
NA
**Checklist:** …
=> docs: update known issues in readme

migration/v0.25.x-v0.26.x/upgrade-apps.md
Since this has become an discovered issue during upgrades.
**Checklist:**
=> docs: Add migration steps for rebuilding internal OpenSearch certs

bin/update-ips.bash
Apparently it didn't work as well as I thought.
Found it while creating a cluster on Cleura.
**Checklist:**
=> bin: Fix update-ips script for S3/Swift ports

helmfile/charts/rclone-sync/templates/cronjob.yaml
=> apps sc: fix backofflimit in rclone template

WIP-CHANGELOG.md, helmfile/charts/user-rbac/templates/clusterroles/user-view.yaml
Allow users to view gatekeeper constraints as a way to view violations.
fixes #1262 
https://github.com/elastisys/compliantkubernetes/pull/436
```console
$ k auth can-i --as canonical@elastisys.com get k8srequirenetworkpolicy
Warning: resource 'k8srequirenetworkpolicy' is not namespace scoped in group 'constraints.gatekeeper.sh'
yes
$ k --as canonical@elastisys.com get k8srequirenetworkpolicy.constraints.gatekeeper.sh  require-networkpolicy -oyaml | yq4 .status.violations
- enforcementAction: dryrun
kind: Pod
message: No matching networkpolicy found
name: test …
```
=> apps wc: gatekeeper constraints rbac

CHANGELOG.md, config/config/common-config.yaml, config/config/sc-config.yaml, get-requirements.yaml, helmfile/charts/grafana-ops/files/welcome.md, helmfile/charts/harbor/harbor-backup/templates/harbor-backup-job.yaml, helmfile/charts/networkpolicy-common/templates/falco/allow-falco-sidekick.yaml, helmfile/charts/networkpolicy-common/templates/falco/allow-falco.yaml, helmfile/charts/networkpolicy-common/templates/prometheus/allow-prometheus-operator.yaml, helmfile/charts/networkpolicy-common/values.yaml, helmfile/charts/networkpolicy-service/templates/harbor-np.yaml, helmfile/charts/networkpolicy-service/templates/ingress-nginx/controller.yaml, helmfile/charts/networkpolicy-service/templates/opensearch/dashboard.yaml, helmfile/charts/networkpolicy-service/templates/prometheus/allow-blackbox-exporter.yaml, helmfile/charts/networkpolicy-workload/templates/alertmanager/allow-alertmanager.yaml, helmfile/charts/networkpolicy-workload/templates/ingress-nginx/controller.yaml, helmfile/charts/networkpolicy-workload/templates/prometheus/allow-prometheus.yaml, helmfile/charts/opensearch/configurer/files/dashboards-resources/welcome.md, helmfile/values/harbor.yaml.gotmpl, helmfile/values/networkpolicy-common.yaml.gotmpl, helmfile/values/service-cluster-networkpolicy.yaml.gotmpl, helmfile/values/thanos/objectstorage-secret.yaml.gotmpl, migration/v0.26.x-v0.27.x/add-extra-excluded-namespaces.sh, migration/v0.26.x-v0.27.x/migrate-swift.sh, migration/v0.26.x-v0.27.x/reinstall-hnc.sh, migration/v0.26.x-v0.27.x/set-external-netpol-ips.sh, migration/v0.26.x-v0.27.x/upgrade-apps.md, pipeline/test/services/workload-cluster/testPodsReady.sh
**What this PR does / why we need it**: fixes from the QA
=> Release 0.27 fixes

release/README.md
Added instructions how one should create branches in the public docs. 
**Checklist:** …
=> release process: add branch steps for public docs

pipeline/config/exoscale/common-config.yaml, pipeline/config/exoscale/sc-config.yaml, pipeline/config/exoscale/wc-config.yaml, pipeline/opensearch.bash
**What this PR does / why we need it**: fix the pipeline
green pipeline: https://github.com/elastisys/compliantkubernetes-apps/actions/runs/3702725054
=> pipeline: fixes

WIP-CHANGELOG.md, helmfile/charts/grafana-ops/dashboards/calicofelix-dashboard.json, helmfile/charts/grafana-ops/dashboards/cephcluster-dashboard.json, helmfile/charts/grafana-ops/dashboards/cephosdsingle-dashboard.json, helmfile/charts/grafana-ops/dashboards/cephpools-dashboard.json, helmfile/charts/grafana-ops/dashboards/elasticsearch-dashboard.json, helmfile/charts/grafana-ops/dashboards/falco-dashboard.json, helmfile/charts/grafana-ops/dashboards/fluentd-dashboard.json, helmfile/charts/grafana-ops/dashboards/kubernetesstatus-dashboard.json, helmfile/charts/grafana-ops/dashboards/nginx-dashboard.json, helmfile/charts/grafana-ops/dashboards/node-exporter-full-dashboard.json, helmfile/charts/grafana-ops/dashboards/prometheus-timeseries-dashboard.json, helmfile/charts/grafana-ops/dashboards/thanos-compact-dashboard.json, helmfile/charts/grafana-ops/dashboards/thanos-overview-dashboard.json, helmfile/charts/grafana-ops/dashboards/thanos-query-dashboard.json, helmfile/charts/grafana-ops/dashboards/thanos-query-frontend-dashboard.json, helmfile/charts/grafana-ops/dashboards/thanos-receive-dashboard.json, helmfile/charts/grafana-ops/dashboards/thanos-rule-dashboard.json, helmfile/charts/grafana-ops/dashboards/thanos-store-dashboard.json, helmfile/charts/grafana-ops/dashboards/uptime-dashboard.json, helmfile/upstream/kube-prometheus-stack/values.yaml, helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
**Which issue this PR fixes** : fixes #1297
**Checklist:**
=> apps sc: synced timezone in all grafana dashboards

.github/workflows/end-to-end.yml, pipeline/Dockerfile, pipeline/cleanup-docker-image.bash
=> pipeline: Updated to use github package

.github/workflows/end-to-end.yml, .github/workflows/pipeline.yml, .github/workflows/pre-commit.yml, .pre-commit-config.yaml, pipeline/Dockerfile
=> pipeline: update actions

helmfile/charts/grafana-ops/files/welcome.md, helmfile/charts/opensearch/configurer/files/dashboards-resources/welcome.md, migration/v0.27.x-v0.28.x/upgrade-apps.md
**What this PR does / why we need it**: Patches from QA.
**Checklist:** …
=> Patches from release 0.28

migration/v0.28.x-v0.29.x/upgrade-apps.md
Adds migration steps for kured upgrade that were missing for the original PR.
**Checklist:**
**Pipeline …
=> docs: Add migration steps for kured upgrade

WIP-CHANGELOG.md, helmfile/01-user-rbac.yaml, helmfile/02-networkpolicies.yaml, helmfile/11-prometheus-operator.yaml, helmfile/12-gatekeeper.yaml, helmfile/13-gatekeeper-templates.yaml, helmfile/14-cert-manager.yaml, helmfile/50-applications.yaml
To support helmfile v0.150+
This has from my testing caused no change for v0.140+ but it will pave the way to move to v0.150 in the future which is needed for [my state template ideas](https://github.com/elastisys/compliantkubernetes-apps/tree/aarnq/helmfile-restructure-poc).
**Checklist:** …
=> bin: Add document splits for helmfile environment

CHANGELOG.md, WIP-CHANGELOG.md, get-requirements.yaml, helmfile/charts/grafana-ops/dashboards/gatekeeper-dashboard.json, helmfile/charts/grafana-ops/files/welcome.md, helmfile/charts/log-manager/templates/cronjob-compaction.yaml, helmfile/charts/log-manager/templates/cronjob-retention.yaml, helmfile/charts/opensearch/configurer/files/dashboards-resources/welcome.md, helmfile/values/fluentd/log-manager.yaml.gotmpl, helmfile/values/gatekeeper.yaml.gotmpl, migration/v0.29/README.md
**What this PR does / why we need it**: Patches from QA
**Checklist:** …
=> Patches from release 0.29

.github/workflows/pipeline.yml, helmfile/charts/opensearch/curator/templates/configmap.yaml, helmfile/charts/opensearch/secrets/templates/certificate.yaml, helmfile/values/fluentd/forwarder-common.yaml.gotmpl, pipeline/Dockerfile, pipeline/init-unit-tests.bash, pipeline/lint.bash, pipeline/validate-config.bash, pipeline/validate-template.bash, scripts/score.sh
More testing in the pipeline.
fixes #1334
**Checklist:**
=> pipeline: Add template and validate

WIP-CHANGELOG.md, helmfile/values/fluentd/aggregator-common.yaml.gotmpl
Fixes a bug that causes (at least on SC) fluentd-aggregator to fill up the PVC and then stop.
When this happens the PVC needs to be cleared.
**Checklist:**
=> apps: Correct fluentd-aggregator buffer settings

WIP-CHANGELOG.md, helmfile/charts/user-rbac/templates/clusterrolebindings/read-hierarchyconfigurations.yaml, helmfile/charts/user-rbac/templates/clusterroles/read-hierarchyconfigurations-role.yaml
Added so the user admins can read hierarchyconfigurations. /So we don't have to check them for the users.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1462
**Checklist:**
=> apps wc: Added so the user admins can read hierarchyconfigurations.

WIP-CHANGELOG.md
Fixes WIP-CHANGELOG.md.
**Checklist:** …
=> apps sc & wc: WIP-changelog fix after merge ignore

WIP-CHANGELOG.md, helmfile/upstream/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-pod.yaml
=> apps sc: Added annotation for container restart in grafana

helmfile/values/prometheus-blackbox-exporter-sc.yaml.gotmpl
See screenshots and https://github.com/elastisys/compliantkubernetes-apps/pull/1542#issuecomment-1521382910
Related to #1542 
**Before**
**After**
Further investigation needed to find out whether the probe is correct about fluentd being down. Could also be more wrong with the probe URL.
**Checklist:** …
=> Fix Fluentd probe

WIP-CHANGELOG.md, helmfile/charts/log-manager/files/compaction.sh, helmfile/charts/log-manager/templates/cronjob-compaction.yaml
When trying this out I found that the script wasn't downloading/expanding the files in the correct place so I fixed it.
**Checklist:**
=> apps sc: Fixed compaction job with ephemeral volume

WIP-CHANGELOG.md, get-requirements.yaml
Been using this version for a while now.
**Checklist:**
If you …
=> all: sops v3.7.3

WIP-CHANGELOG.md, helmfile/values/falco.yaml.gotmpl
Refresh the falco rules before release.
**Checklist:**
=> apps: Update Falco rules

WIP-CHANGELOG.md, config/config/sc-config.yaml, helmfile/50-applications.yaml, helmfile/charts/openstack-monitoring/.helmignore, helmfile/charts/openstack-monitoring/Chart.yaml, helmfile/charts/openstack-monitoring/templates/_helpers.tpl, helmfile/charts/openstack-monitoring/templates/clusterrolebinding.yaml, helmfile/charts/openstack-monitoring/templates/prometheusrule.yaml, helmfile/charts/openstack-monitoring/templates/service.yaml, helmfile/charts/openstack-monitoring/templates/servicemonitor.yaml, helmfile/charts/openstack-monitoring/values.yaml, helmfile/values/openstack-monitoring.yaml.gotmpl, helmfile/values/prometheus-alerts-sc.yaml.gotmpl
Adds metrics for the openstack api / could be good to have if the api fails in any way.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #1418 
**Checklist:**
=> apps sc: openstack api metrics

WIP-CHANGELOG.md, config/config/common-config.yaml, config/config/wc-config.yaml
=> config: remove leftover influxdb config

scripts/clean-sc.sh, scripts/clean-wc.sh
**What this PR does / why we need it**: I noticed some errors when running the clean-up scripts and also some resources not being removed
=> scripts: some fixes for the clean-up scripts

migration/v0.33/README.md
=> fix typo in rclone migration

WIP-CHANGELOG.md
This was was included in apps v0.32
=> fix changelog

helmfile/charts/grafana-dashboards/files/welcome.md, helmfile/charts/opensearch/configurer/files/dashboards-resources/welcome.md
> [!important]
...
- Fixes #
- Logs checks:
=> apps sc: Updated welcome dashboard for v0.33

helmfile/values/networkpolicies/service/harbor.yaml.gotmpl
> [!warning]
> [!important]
Fixes the network policies for harbor external access to postgres and redis.
...
- Fixes #
- Logs checks:
=> Fix harbor network policies for external db/redis

WIP-CHANGELOG.md, helmfile/values/gatekeeper/gatekeeper.yaml.gotmpl
> [!warning]
> [!important]
Add secrets to the list of audited resources by gatekeeper
- Part of elastisys/ck8s-argocd#74
- Logs checks:
=> config: Add secrets to the list of audited resources for Argocd access

WIP-CHANGELOG.md, bin/ck8s, bin/clean.bash, bin/fix-psp-violations.bash
> [!important]
No issue
- Logs checks:
=> ck8s fix-psp-violations and clean commands

helmfile/values/networkpolicy/service-cluster.yaml.gotmpl
> [!warning]
> [!important]
Fixed bug in rclone network policy that sometimes prevented destination IPs from getting added to the network policy.
- Fixes #
- Logs checks:
=> apps sc: fix bug in rclone networkpolicy

.github/workflows/end-to-end.yml, helmfile/50-applications.yaml, helmfile/charts/harbor/init-harbor/templates/init-harbor-job.yaml, pipeline/config/exoscale/rook/values.yaml
> [!warning]
> [!important]
Added various fixes after the rook rework and addition of test script.
- Fixes #1714 
- Logs checks:
=> pipeline: fixes for installing and testing rook

.github/workflows/end-to-end.yml
> [!warning]
> [!important]
Bump the kubespray image version.
Tested against the QA-Branch of the next 2.23 kubespray release that is currently in progress and it seems to be working mostly fine. 
https://github.com/elastisys/compliantkubernetes-apps/actions/runs/6392387762
Will have to wait until some …
=> pipeline: bump kubespray image

helmfile/charts/networkpolicy/common/templates/rook-ceph/crashcollector.yaml, helmfile/charts/networkpolicy/common/templates/rook-ceph/mgr.yaml, helmfile/charts/networkpolicy/common/templates/rook-ceph/mon.yaml
> [!warning]
> [!important]
Added netpols for the rook-ceph crashcollector
- Fixes #1794 
- Logs checks:
=> apps: add rook-ceph-crashcollector netpols

WIP-CHANGELOG.md, config/config/wc-config.yaml, helmfile/50-applications.yaml, helmfile/values/user-rbac.yaml.gotmpl, helmfile/values/userCRDs/flux/fluxv2.yaml.gotmpl, helmfile/values/userCRDs/userCRDs.yaml.gotmpl
> [!warning]
Adds support for Flux using self-managed CRDs ( #1716 )
It is needed to enable the use of self-managed Flux ( #1754 )
...
- Fixes #1804 
=> Added support for Flux with self-managed CRDs

config/config/wc-config.yaml, helmfile/values/prometheus-blackbox-exporter-wc.yaml.gotmpl
> [!warning]
> [!important]
The wc to sc blackbox probes could not be disabled and are always configured with `baseDomain`, which if wc and sc clusters have different `baseDomain` causes alerts as the probes will fail. This PR makes it possible to disable all wc to sc probes as well as setting …
=> config: add templating for enabling wc to sc probes

helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
> [!warning]
> [!important]
Moves some templating so that everything is customizable with a custom template
- Fixes #
- Logs checks:
=> apps sc: Improved alertmanager custom template

bin/update-ips.bash, helmfile/charts/networkpolicy/service-cluster/values.yaml, helmfile/charts/prometheus-alerts/templates/alerts/harbor.yaml, helmfile/charts/rclone-sync/files/rclone.conf, helmfile/charts/rclone-sync/values.yaml, helmfile/values/networkpolicy/service-cluster.yaml.gotmpl, helmfile/values/rclone-sync.yaml.gotmpl
> [!warning]
> [!important]
- issues found with the rclone sync
- Logs checks:
=> apps sc: Fixed rclone from patch and harbor alert description

helmfile/charts/grafana-dashboards/dashboards/node-exporter-disk-dashboard.json
> [!warning]
> [!important]
Adds a dashboard dedicated to disk and filesystem performance.
- Fixes #1304
Changes from "Node Exporter Full":
- Removed all rows except Disk and Filesystem related ones
- Allows selecting multiple hosts
- Selectable disk devices and filesystem mount points
- New Overview …
=> Disk performance dashboard

config/config/wc-config.yaml, helmfile/00-hnc-crds.yaml, helmfile/charts/hnc/config-and-crds/Chart.yaml, helmfile/charts/hnc/config-and-crds/crds/hncconfigurations.yaml, helmfile/charts/hnc/config-and-crds/templates/hnc-config.yaml, helmfile/charts/hnc/controller/Chart.yaml, helmfile/values/hnc/controller.yaml.gotmpl, migration/v0.34/README.md, migration/v0.34/apply/12-hnc-crds.sh
> [!warning]
> [!important]
Upgraded HNC to appversion 1.1.0 and exposed the "opt-in propagation" feature.
- Fixes #1837 
- Logs checks:
- Bug checks:
=> apps wc: upgrade hnc and expose opt-in propagation

config/config/wc-config.yaml, helmfile/charts/user-alertmanager/templates/alertmanager.yaml, helmfile/charts/user-alertmanager/values.yaml, helmfile/values/user-alertmanager.yaml.gotmpl
> [!warning]
> [!important]
Adds the option to configure tolerations, affinity, and topologySpreadConstraints to user alertmanager.
- Logs checks:
- Bug checks:
=> Add more user-alertmanager config options

helmfile/values/falco/falco-common.yaml.gotmpl
> [!warning]
Add exceptions for pods dying and restarting
Manually killing pods produced a number of alerts
=> apps: Increase number of falco exceptions

bin/update-ips.bash, pipeline/update-ips.bats
> [!warning]
> [!important]
...
- Fixes #1857
- Logs checks:
- Bug checks:
=> Support S3 region endpoint being IP address in update-ips script

bin/common.bash
> [!warning]
> [!important]
I think something in the output of gpg has changed in newer versions that was not captured previously.
Now it uses the `--with-colons` which should be more stable and more structured.
- Logs checks:
- Pod Security …
=> bin: Improve validate sops config

helmfile/values/networkpolicies/common/common.yaml.gotmpl
> [!warning]
> [!important]
Allows direct DNS traffic to CoreDNS, which can happen if node-local-dns isn't available.
- Logs checks:
- Bug checks:
=> apps: Allow DNS traffic directly to CoreDNS

changelog/0.34.md, config/config/common-config.yaml, helmfile/charts/grafana-dashboards/files/welcome.md, helmfile/charts/opensearch/configurer/files/dashboards-resources/welcome.md, helmfile/upstream/aquasecurity/trivy-operator/Chart.yaml, helmfile/upstream/aquasecurity/trivy-operator/README.md, helmfile/upstream/aquasecurity/trivy-operator/crds/aquasecurity.github.io_clustercompliancereports.yaml, helmfile/upstream/aquasecurity/trivy-operator/crds/aquasecurity.github.io_sbomreports.yaml, helmfile/upstream/aquasecurity/trivy-operator/crds/aquasecurity.github.io_vulnerabilityreports.yaml, helmfile/upstream/aquasecurity/trivy-operator/generated/role.yaml, helmfile/upstream/aquasecurity/trivy-operator/templates/_helpers.tpl, helmfile/upstream/aquasecurity/trivy-operator/templates/config.yaml, helmfile/upstream/aquasecurity/trivy-operator/templates/deployment.yaml, helmfile/upstream/aquasecurity/trivy-operator/templates/leader-election.yaml, helmfile/upstream/aquasecurity/trivy-operator/templates/ns.yaml, helmfile/upstream/aquasecurity/trivy-operator/templates/rbac.yaml, helmfile/upstream/aquasecurity/trivy-operator/templates/service.yaml, helmfile/upstream/aquasecurity/trivy-operator/templates/servicemonitor.yaml, helmfile/upstream/aquasecurity/trivy-operator/templates/specs/cis-1.23.yaml, helmfile/upstream/aquasecurity/trivy-operator/templates/specs/nsa-1.0.yaml, helmfile/upstream/aquasecurity/trivy-operator/templates/specs/pss-baseline.yaml, helmfile/upstream/aquasecurity/trivy-operator/templates/specs/pss-restricted.yaml, helmfile/upstream/aquasecurity/trivy-operator/templates/trivy-server.yaml, helmfile/upstream/aquasecurity/trivy-operator/values.yaml, helmfile/upstream/index.yaml, migration/v0.34/README.md, migration/v0.34/apply/12-hnc-crds.sh, migration/v0.34/apply/40-uninstalls.sh
> [!warning]
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> apps: QA fixes for apps v0.34.0

changelog/0.34.md
> [!warning]
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Fix security notice in v0.34 changelog

pipeline/test/services/service-cluster/testPrometheusTargets.sh
> [!warning]
> [!important]
Fixes `ck8s test sc` for when `prometheusBlackboxExporter.customKubeapiTargets` is set in `sc-config.yaml`, as otherwise, one of the tests fails:
```console
serviceMonitor/monitoring/prometheus-blackbox-exporter-user-api-server/0        ❌
``` 
- Metrics …
=> Fix test for custom kubeapi targets

SECURITY.md
> [!warning]
> [!important]
We reference this document from our Terms of Service.
The process for receiving security patches is deprecated, so this PR fixes that.
- Part of an internal ToS review
- Logs checks:
- …
=> Fix Security announcements

.github/workflows/cache-image.yml
> [!warning]
> [!important]
Fixes the cache-image workflow as I forgot to init the environment before building.
- Logs checks:
- Bug checks:
=> tests: Correct cache-image workflow

config/config/wc-config.yaml, helmfile.d/charts/ingress-nginx-probe-ingress/.helmignore, helmfile.d/charts/ingress-nginx-probe-ingress/Chart.yaml, helmfile.d/charts/ingress-nginx-probe-ingress/templates/_helpers.tpl, helmfile.d/charts/ingress-nginx-probe-ingress/templates/ingress.yaml, helmfile.d/charts/ingress-nginx-probe-ingress/values.yaml, helmfile.d/stacks/ingress-nginx.yaml, helmfile.d/state.yaml, helmfile.d/values/ingress-nginx-probe-ingress.yaml.gotmpl
> [!warning]
> [!important]
Adds an ingress in WC that can be used for probing purposes even if there's a wildcard ingress that points to a service that does not respond with code 200.
- Fixes #1869 
I would not say I'm super happy about the naming here, suggestions very much welcomed :smile: 
- Change …
=> Add probe ingress for ingress nginx

scripts/charts.sh
> [!warning]
> [!important]
Looks like the charts script was left out when the recent Helmfile changes were implemented.
- Logs checks:
- Bug checks:
=> Fix charts script

.github/pull_request_template.md
> [!warning]
> [!important]
https://github.com/elastisys/compliantkubernetes-apps/pull/1953#issuecomment-1887029097
- Logs checks:
- Bug checks:
=> Add scripts commit prefix

changelog/0.35.md, config/config/common-config.yaml, helmfile/charts/harbor/harbor-backup/scripts/harbor-backup.sh, helmfile/values/trivy/trivy-operator.yaml.gotmpl, migration/v0.35/apply/11-trivy-operator-crds.sh, scripts/restore/restore-harbor.sh
> [!warning]
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Staging 0.35.1

helmfile.d/values/networkpolicies/common/velero.yaml.gotmpl
> [!warning]
> [!important]
I missed adding the prometheus ingress when I updated the netpols.
- Logs checks:
- Bug checks:
=> apps: Add prometheus ingress for velero

migration/v0.36/apply/40-namespaces.sh
> [!warning]
> [!important]
I had some issues when running the migration script as it was syncing releases on the wrong cluster. I replaced `helmfile` with `helmfile_do`.
- Logs checks:
- Audit …
=> Update the migration script for namespaces

changelog/0.34.md, config/config/common-config.yaml, helmfile/values/trivy/trivy-operator.yaml.gotmpl
> [!warning]
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Staging 0.34.2

changelog/0.35.md
> [!warning]
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Add changelog for release v0.35.1

changelog/0.34.md
> [!warning]
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Add changelog for release v0.34.2

config/config/common-config.yaml
> [!warning]
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Enable webhook alert by default

DEVELOPMENT.md
> [!warning]
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Improve teardown instructions for local clusters

bin/init.bash
> [!warning]
> [!important]
This adds config backup retention to init.
So it will ask if you want to remove old config backups, with the default retention of 30 days, can be customised via the variable `CK8S_INIT_BACKUP_DAYS`.
Honours auto approves, and skips the prompt if not interactive. 
```console
$ …
```
=> Add config backup retention to init

helmfile.d/charts/grafana-dashboards/dashboards/README.md, helmfile.d/charts/grafana-dashboards/dashboards/cephosdsingle-dashboard.json
> [!warning]
> [!important]
The ceph osd dashboard had a hard coded value in a few places, which made it show incorrect information. Fixed by switching to a variable.
- Fixes #
- Logs checks:
- …
=> Changed hard coded value to variable in ceph dashboard

config/config/sc-config.yaml, helmfile.d/values/harbor/harbor.yaml.gotmpl
> [!warning]
> [!important]
Noticed that in the `kubernetes cluster status` Grafana dashboard that one of the ck8s-apps pods `harbor-exporter` did not have resources requests set (see image). This PR adds some arbitrary resource requests and limits to this pod.
- Logs …
=> Add harbor exporter resources

roles/get-requirements.yaml
> [!warning]
> [!important]
Remember to run `bin/install-requirements.bash` to update sops.
- Fixes [test failure](https://github.com/elastisys/compliantkubernetes-apps/actions/runs/7783062412/job/21220741816?pr=1924#step:5:31) identified in (but unrelated to) #1924 caused by a mismatch in sops version …
=> Update sops version to 3.8.1 in order to fix CI

bin/init.bash, config/config/common-config.yaml, helmfile.d/charts/gatekeeper/constraints/templates/reject-loadbalancer-service/constraint.yaml, helmfile.d/charts/gatekeeper/constraints/values.yaml, helmfile.d/charts/gatekeeper/templates/policies/reject-loadbalancer-service.rego, helmfile.d/charts/gatekeeper/templates/templates/reject-loadbalancer-service/template.yaml, helmfile.d/values/gatekeeper/constraints.yaml.gotmpl, helmfile.d/values/gatekeeper/gatekeeper.yaml.gotmpl, helmfile.d/values/gatekeeper/templates.yaml.gotmpl
Fixes #1839
> [!warning]
> [!important]
- Fixes #1839
- Logs checks:
- Bug checks:
=> apps: Add gatekeeper policy for rejecting loadbalancer services

changelog/0.36.md, config/config/common-config.yaml, helmfile.d/charts/node-local-dns/templates/node-local-dns.yaml, helmfile.d/values/node-local-dns.yaml.gotmpl
> [!warning]
> [!important]
Expose node-local-dns resource requests/limits in config
- Logs checks:
- Bug checks:
=> config: expose node-local-dns resources

changelog/0.36.md, config/config/common-config.yaml, config/config/wc-config.yaml, helmfile.d/charts/gatekeeper/constraints/templates/disallow-tag/constraint.yaml, helmfile.d/charts/gatekeeper/constraints/templates/image-registry/constraint.yaml, helmfile.d/charts/gatekeeper/constraints/templates/networkpolicies/constraint.yaml, helmfile.d/charts/gatekeeper/constraints/templates/resource-requests/constraint.yaml, helmfile.d/charts/grafana-dashboards/files/welcome.md, helmfile.d/charts/hnc/controller/values.yaml, helmfile.d/charts/node-local-dns/templates/node-local-dns.yaml, helmfile.d/charts/opensearch/configurer/files/dashboards-resources/welcome.md, helmfile.d/stacks/ingress-nginx.yaml, helmfile.d/values/gatekeeper/gatekeeper.yaml.gotmpl, helmfile.d/values/node-local-dns.yaml.gotmpl, migration/v0.36/README.md, migration/v0.36/apply/10-hnc-excluded-ns.sh, migration/v0.36/apply/80-apply.sh
> [!warning]
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Staging 0.36.0

README.md
> [!warning]
> [!important]
Added a section about Capacity Management in the docs.
- Fixes #
We had a meeting discussing this and decided that we should add a section regarding this.
- Logs checks: …
=> Add information about capacity management in docs

changelog/0.36.md, config/config/sc-config.yaml, helmfile.d/values/velero-sc.yaml.gotmpl, helmfile.d/values/velero-wc.yaml.gotmpl, migration/v0.36/README.md, migration/v0.36/apply/50-velero-crds-upgrade.sh, migration/v0.36/apply/80-apply.sh, migration/v0.36/prepare/10-thanos-distrib-memory-limit.sh
> [!warning]
> [!important]
Changes for the apps v0.36 patch release
- Logs checks:
- Bug checks:
=> Staging 0.36.1

helmfile.d/stacks/ingress-nginx.yaml
> [!warning]
> [!important]
Fixes a spelling error on the name of the ingress-nginx-probe-ingress
=> fixed a spelling error in ingress-nginx-probe

helmfile.d/values/ingress-nginx.yaml.gotmpl
> [!warning]
>
> [!important]
Ensures that the service for ingress-nginx is correct even when it is not a load balancer.
- Logs checks:
- Bug checks:
=> apps: Template allocate load balancer node ports conditionally

helmfile.d/upstream/grafana/grafana/Chart.yaml, helmfile.d/upstream/grafana/grafana/README.md, helmfile.d/upstream/grafana/grafana/templates/_pod.tpl, helmfile.d/upstream/grafana/grafana/templates/serviceaccount.yaml, helmfile.d/upstream/grafana/grafana/values.yaml, helmfile.d/upstream/index.yaml, helmfile.d/values/grafana/grafana-ops.yaml.gotmpl, helmfile.d/values/grafana/grafana-user.yaml.gotmpl, tests/common/lib/grafana.js, tests/end-to-end/grafana-dashboards.cy.js
> [!warning]
> [!important]
This upgrade mitigates the following medium security vulnerabilities:
- [CVE-2023-6152](https://github.com/advisories/GHSA-3hv4-r2fm-h27f)
- [CVE-2024-1442](https://github.com/advisories/GHSA-5mxf-42f5-j782)
I moved client secrets and password into a Kubernetes secret, to …
=> Upgrade Grafana helm chart to 7.3.7 and application to 10.4.0

DEVELOPMENT.md, config/config/common-config.yaml, helmfile.d/values/networkpolicies/common/cert-manager.yaml.gotmpl
> [!warning]
> [!important]
When trying out dns01 towards route53 in a full environment I noticed that cert-manager was blocked by the network policies. This allows the platform admin to configure the ip range when using dns01. 
- Logs checks: …
=> Config networkpolicies for certmanager when using dns01

config/config/common-config.yaml, config/config/sc-config.yaml, config/config/wc-config.yaml, migration/v0.37/prepare/10-increase-limits-to-avoid-oon.sh
> [!warning]
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> config: Increase limits to reduce OOM alerts

migration/v0.37/README.md, pipeline/Dockerfile, roles/get-requirements.yaml, tests/Dockerfile
> [!warning]
> [!important]
Local requirements have been updated, run `./bin/ck8s install-requirements` to update them.
Updates local requirements.
This enables helmfile value templates to use helper templates (must be suffixed with `.tpl` and placed in the same directory as your value template) that …
=> bin: Update dependencies

migration/v0.37/apply/11-kube-prometheus-stack.sh, migration/v0.37/prepare/10-increase-limits-to-avoid-oon.sh
> [!warning]
>
> [!important]
While running the migration scripts for v0.37 I had some errors. This PR should  fix them.
- Logs checks:
- Bug checks:
=> Changes to the v0.37 migration scripts

helmfile.d/stacks/monitoring-prometheus.yaml
> [!warning]
>
> [!important]
Ensures the `monitoring` namespace exist when installing `kube-state-metrics-extra-resource-metrics`.
- Fixes #2070
I'm evaluating ways to statically test this.
- Logs checks: …
=> apps: Add missing needs on admin namespaces

config/config/sc-config.yaml, helmfile.d/values/harbor/harbor.yaml.gotmpl
> [!warning]
>
> [!important]
To be able to configure more settings for harbors S3 multipart upload we need to have it in our config.
- Logs checks:
- Bug checks:
- Config …
=> apps sc: Added config for harbor s3 multipart settings

pipeline/test/services/service-cluster/testOpensearch.sh
> [!warning]
>
> [!important]
When snapshots fail the output from the `_cat/snapshots` endpoint spits out a large JSON blob with an error. Our test did not handle that and crashed. This fixes it and prints out the entire output. It ain't pretty but does it's job!
Diff without whitespace changes …
=> Check for error in OpenSearch snapshots output in test command

changelog/0.37.md, config/config/sc-config.yaml, helmfile.d/charts/grafana-dashboards/files/welcome.md, helmfile.d/charts/opensearch/configurer/files/dashboards-resources/welcome.md, helmfile.d/charts/user-rbac/templates/clusterroles/user-view.yaml, helmfile.d/values/falco/falco-common.yaml.gotmpl, helmfile.d/values/grafana/grafana-user.yaml.gotmpl, migration/v0.37/README.md, migration/v0.37/apply/30-reinstall-probe-ingress.sh, migration/v0.37/apply/40-upgrade-falco-wc.sh, migration/v0.37/apply/80-apply.sh, migration/v0.37/prepare/20-check-grafana-oidc-groups.sh
> [!warning]
>
> [!important]
Qa for apps v0.37.0 completed.
- Logs checks:
- Bug checks:
=> Staging 0.37.0

changelog/0.37.md, config/config/sc-config.yaml, helmfile.d/charts/grafana-dashboards/files/welcome.md, helmfile.d/charts/opensearch/configurer/files/dashboards-resources/welcome.md, helmfile.d/charts/user-rbac/templates/clusterroles/user-view.yaml, helmfile.d/values/falco/falco-common.yaml.gotmpl, helmfile.d/values/grafana/grafana-user.yaml.gotmpl, migration/v0.37/README.md, migration/v0.37/apply/30-reinstall-probe-ingress.sh, migration/v0.37/apply/40-upgrade-falco-wc.sh, migration/v0.37/apply/80-apply.sh, migration/v0.37/prepare/20-check-grafana-oidc-groups.sh
> [!warning]
>
> [!important]
Fixes from the apps v0.37 QA.
- Logs checks:
- Bug checks:
=> Port 0.37.0

scripts/clean-sc.sh, scripts/clean-wc.sh
> [!warning]
>
> [!important]
In Cluster API provisioned clusters, cert-manager is already installed and therefore:
1. Prevents the cert-manager namespace from being created.
2. Must remain after apps resources have been cleaned up.
- Logs checks:
- Pod …
=> Skip deleting cert-manager for Cluster API provisioned clusters

bin/init.bash, config/config/common-config.yaml
> [!warning]
>
> [!important]
This PR fixes the problem with dropped ingress packets to the ingress nginx on azure, it also enables preserving the source IP of incoming traffic.
- Fixes https://github.com/elastisys/ck8s-issue-tracker/issues/250
- Logs checks:
- …
=> Fix dropped ingress packets in azure

bin/init.bash
> [!warning]
>
> [!important]
AFAICT, it has not been used since https://github.com/elastisys/compliantkubernetes-apps/pull/1392
- Logs checks:
- Bug checks:
=> Remove unused function set_fluentd_config

migration/v0.35/README.md, migration/v0.35/apply/60-velero-crds-upgrade.sh, migration/v0.35/apply/80-apply.sh
> [!warning]
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Port 0.35.2

docs/restore/rclone.md
> [!warning]
>
> [!important]
This improves the rclone-restore docs so everything is copy-paste-able.
- Logs checks:
- Bug checks:
=> docs: Improve rclone-restore docs

tests/README.md
> [!warning]
>
> [!important]
This adds the command needed to regenerate resources, which needs to be run sometimes when editing config (or tests?) in order for CI to pass, making it easier to copy and paste it.
Reduces the amount of time it takes to reconstruct this precise command from the …
=> Include a copypastable command for regenerating test resources

helmfile.d/charts/gatekeeper/constraints/templates/deployment-minimum-replicas/constraint.yaml, helmfile.d/charts/gatekeeper/templates/policies/deployment-minimum-replicas.rego, helmfile.d/charts/gatekeeper/templates/values.yaml
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> gatekeeper minimum replicas constraint fix

helmfile.d/charts/grafana-dashboards/dashboards/velero-dashboard.json
> [!warning]
>
> [!important]
This fixes panels in the Velero dashboard in Grafana that contained [deprecated Angular plugins](https://grafana.com/docs/grafana/latest/developers/angular_deprecation/).
Part of:
- #2130
- #2031
Before:
After:
> [!NOTE]
> Row coloring is not supported in the …
=> Upgrade Velero dashboards

config/schemas/config.yaml
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Add schema for prometheus internal access

helmfile.d/charts/prometheus-alerts/templates/alerts/openstack.yaml
> [!warning]
>
> [!important]
Fixed some typos in alerts
- Logs checks:
- Bug checks:
=> apps sc: fixed some typos in alerts

bin/apply.bash, changelog/0.38.md, helmfile.d/charts/gatekeeper/constraints/templates/deployment-minimum-replicas/constraint.yaml, helmfile.d/charts/gatekeeper/templates/policies/deployment-minimum-replicas.rego, helmfile.d/charts/gatekeeper/templates/templates/deployment-minimum-replicas/template.yaml, helmfile.d/charts/gatekeeper/templates/values.yaml, helmfile.d/charts/grafana-dashboards/files/welcome.md, helmfile.d/charts/log-manager/templates/cronjob-compaction.yaml, helmfile.d/charts/log-manager/templates/cronjob-retention.yaml, helmfile.d/charts/opensearch/configurer/files/dashboards-resources/welcome.md
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Add changelog for release v0.38.0

config/schemas/config.yaml, config/schemas/secrets.yaml
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> schema: fluentdbuffer titles and descriptions

bin/common.bash
> [!warning]
>
> [!important]
Fix missing implementation in https://github.com/elastisys/compliantkubernetes-apps/pull/2145
- Logs checks:
- Bug checks:
=> Fix check_tools not using PURL requirements

scripts/clean-sc.sh, scripts/clean-wc.sh
> [!warning]
>
> [!important]
The clean scripts part for removing finalizers from challenge resources that are stuck in pending did no longer work for me. This PR should address this by refactoring this part in the clean scripts. It was also missing in the clean script for `wc`, so this adds it …
=> Fix challenges clean up

config/config/sc-config.yaml, config/schemas/config.yaml, helmfile.d/values/networkpolicies/service/rclone.yaml.gotmpl, helmfile.d/values/rclone/sync.yaml.gotmpl
> [!warning]
>
> [!important]
Noticed when applying apps v0.38.0 that rclone was failing to apply due to some config being missing or incorrect
- Fixes #
- Logs checks:
- Bug …
=> apps sc: fix rclone config

bin/apply.bash, changelog/0.38.md, helmfile.d/charts/gatekeeper/constraints/templates/deployment-minimum-replicas/constraint.yaml, helmfile.d/charts/gatekeeper/templates/policies/deployment-minimum-replicas.rego, helmfile.d/charts/gatekeeper/templates/templates/deployment-minimum-replicas/template.yaml, helmfile.d/charts/gatekeeper/templates/values.yaml, helmfile.d/charts/grafana-dashboards/files/welcome.md, helmfile.d/charts/log-manager/templates/cronjob-compaction.yaml, helmfile.d/charts/log-manager/templates/cronjob-retention.yaml, helmfile.d/charts/opensearch/configurer/files/dashboards-resources/welcome.md
> [!warning]
>
> [!important]
Port changes from v0.38.0 QA.
- Logs checks:
- Bug checks:
=> Port 0.38.0

changelog/0.38.md, config/config/sc-config.yaml, helmfile.d/values/networkpolicies/service/rclone.yaml.gotmpl, helmfile.d/values/rclone/sync.yaml.gotmpl
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Staging 0.38.1

config/config/common-config.yaml, config/config/sc-config.yaml, config/schemas/config.yaml, config/schemas/secrets.yaml, helmfile.d/values/falco/falco-common.yaml.gotmpl, tests/common/lib.bash, tests/common/lib/env.bash, tests/unit/schema.bats
> [!warning]
>
> [!important]
This aims to increase the quality on [the generated docs from the schemas introduced in the public docs](https://github.com/elastisys/compliantkubernetes/pull/874).
```bash
bats unit/schema.bats
```
- Logs checks:
- Pod Security …
=> Schema doc improvements and tests

bin/diagnostics.bash
> [!warning]
>
> [!important]
- Fixes #2116 
- Logs checks:
- Bug checks:
=> Improve diagnostics script

helmfile.d/charts/prometheus-alerts/templates/alerts/harbor.yaml, helmfile.d/values/networkpolicies/service/rclone.yaml.gotmpl
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Fixed issue with rclone networkpolicies and alert for harbor

roles/get-requirements.yaml
> [!warning]
>
> [!important]
Bugfix for the install-requirements script. It doesn't allow you to downgrade your apt packages to specific versions and exits out.
...
To reproduce error on a fresh machine:
* Install requirement script on any version v0.38 or under.
* Swap to main branch and try …
=> bin: bugfix for install-requirements to allow downgrades

helmfile.d/values/networkpolicies/service/rclone.yaml.gotmpl
> [!warning]
>
> [!important]
We had a separate branch of v0.38.1 with this fix, but we want it for v0.38.2 so it should be added to main as well.
- Logs checks:
- Bug …
=> Fixed issue with rclone networkpolicies

release/README.md
> [!warning]
>
> [!important]
The documentation for how to add public release notes for a new release didn't cover the case of patch releases. Updated the documentation to have separate steps for major/minor and patch releases.
Unfortunately the process is a bit cumbersome, but I think this is …
=> Update process for adding release notes for patches

helmfile.d/charts/prometheus-alerts/templates/alerts/harbor.yaml
> [!warning]
>
> [!important]
We had a separate branch of v0.38.1 for this fix, but we want it for v0.38.2 as well so it should be added to main as well.
- Logs checks:
- Bug …
=> Fixed bug in Harbor alert as warned by Thanos

REQUIREMENTS
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Bump dnsutils 1:9.18.24-0ubuntu0.22.04.1

config/sc-config.yaml, config/schemas/config.yaml, helmfile.d/charts/rclone/values.yaml, helmfile.d/values/rclone/sync.yaml.gotmpl
> [!warning]
>
> [!important]
- increases default rclone job deadline from 600 to 7200
- makes ``activeDeadlineSeconds`` an optional config in sc-config:
```yaml
objectStorage:
sync:
activeDeadlineSeconds: 1337
```
- Fixes #2173 
Not sure if changes to schema are correct
- …
=> increase rclone default job deadline and make it configurable

helmfile.d/values/prometheus-user-alerts-wc.yaml.gotmpl
> [!warning]
>
> [!important]
The alert for kured in wc will be removed since this didn't work as expected.
...
- Fixes #
- Logs checks:
- Bug checks:
=> apps-wc: Disabled kured alert in WC

changelog/0.38.md, config/config/sc-config.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/harbor.yaml, helmfile.d/charts/rclone/values.yaml, helmfile.d/values/networkpolicies/service/rclone.yaml.gotmpl, helmfile.d/values/rclone/sync.yaml.gotmpl, migration/v0.38/README.md, migration/v0.38/prepare/60-set-nginx-annotations.sh
> [!warning]
>
> [!important]
- Fixes some bugs in 0.38, see changelog diff
- Logs checks:
- Bug checks:
=> Staging 0.38.2

config/sc-config.yaml, config/schemas/config.yaml, helmfile.d/values/grafana/grafana-ops.yaml.gotmpl, helmfile.d/values/grafana/grafana-user.yaml.gotmpl
> [!warning]
>
> [!important]
Increases default grafana timeout, also adds a config option to configure this
- Logs checks:
- Bug checks:
=> apps sc: increase default grafana timeout

bin/ck8s, bin/install-requirements.bash
> [!warning]
>
> [!important]
Allows you to install-requirements without password for environments that has password-less sudo. All you need to do is use the --no-pass flag.
...
- Logs checks:
- Audit …
=> bin: allow password-less sudo for install-requirements script

helmfile.d/values/podsecuritypolicies/common/velero.yaml.gotmpl
> [!warning]
>
> [!important]
Fixes `RunAsNonRoot` rule config for Velero PSP.
- Fixes #
- Logs checks:
- Bug checks:
=> Fix velero psp

.github/ISSUE_TEMPLATE/release.md
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Remove some Infra Providers from release template issue

REQUIREMENTS
> [!warning]
>
> [!important]
When trying to install requirements I got this error:
```
1.294 TASK [Install apt-packages] ****************************************************
8.293 fatal: [127.0.0.1]: FAILED! => {"cache_update_time": 1720603441, "cache_updated": false, "changed": false, "msg": …
```
=> Update outdated apache-utils version

helmfile.d/charts/prometheus-alerts/templates/alerts/kured.yaml
> [!warning]
>
> [!important]
This fixes a bug where the kured alert is triggered for nodes that isn't part of the cluster anymore
- Fixes #
- Logs checks:
- Bug checks:
=> apps sc: Fixed kured alert to not alert for removed nodes

REQUIREMENTS
> [!warning]
>
> [!important]
When installing requirements, I got the following error since apache2-utils version `2.4.52-1ubuntu4.10` is no longer available
```bash
TASK [Install apt-packages] ******************************************************************************************************* …
```
=> config: use wildcard apache2-utils version

helmfile.d/charts/grafana-dashboards/dashboards/backup-dashboard.json, helmfile.d/charts/grafana-dashboards/dashboards/daily-dashboard.json
- apps: upgrade daily dashboard
- apps: update backup dashboard
> [!warning]
>
> [!important]
Replaces some deprecated panels based on Angular in two dashboards in order to get rid of the warnings.
- Part of #2130
- Updates two dashboards:
- Daily Checks
- Backup status
The dashboards should …
=> Replace deprecated Angular panels in Daily and Backup Dashboards

changelog/0.39.md, config/config/sc-config.yaml, config/schemas/config.yaml, helmfile.d/charts/rclone/values.yaml, helmfile.d/values/podsecuritypolicies/workload/default.yaml.gotmpl, helmfile.d/values/rclone/sync.yaml.gotmpl
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Staging 0.39.1

changelog/0.39.md, config/sc-config.yaml, config/schemas/config.yaml, helmfile.d/charts/rclone/values.yaml
> [!warning]
>
> [!important]
...
- Fixes [#297](https://github.com/elastisys/ck8s-issue-tracker/issues/297)
- Logs checks:
- Bug checks:
=> config: change rclone activedeadlineseconds to 14400

helmfile.d/charts/prometheus-alerts/files/cluster-api.yaml
> [!warning]
>
> [!important]
The fix that was merged earlier was apparently not working properly :facepalm: Well, this fix is verified to work
- Fixes #
- Logs checks:
- Bug …
=> Fixed bug with fix for capi alert

bin/ck8s
> [!warning]
>
> [!important]
Fixes that one of the `ck8s usage` lines were not sent to stderr, which can interfere with checks for empty output in scripts.
Discovered because this line made it into `dns.json`.
- Logs checks:
- …
=> bin: fix redirecting usage to stderr

REQUIREMENTS
> [!warning]
>
> [!important]
Since compliantkubernetes-kubespray have 1.29 as the default kubernetes version I updated the requirement
- Fixes #
- Logs checks:
- Bug checks:
=> bin: Updated kubectl requirement to match kubespray

scripts/restore/README.md
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> docs: add instructions for restoring harbor between swift and s3

pipeline/test/services/service-cluster/testIngress.sh, pipeline/test/services/workload-cluster/testHNC.sh, pipeline/test/services/workload-cluster/testIngress.sh
> [!warning]
>
> [!important]
I found that it was quite unclear what happened when the ingress tests failed while using proxy protocol, so I changed the test to tell the user that the test were skipped rather than failed.
I found an issue where the tests would error out if there were no admin …
=> tests: Improved tests

helmfile.d/charts/node-local-dns/templates/node-local-dns.yaml
> [!warning]
>
> [!important]
...
- Fixes #2033
- Logs checks:
- Bug checks:
=> apps: bump node-local-dns version to 1.23.1

config/common-config.yaml, config/schemas/config.yaml, helmfile.d/values/velero-sc.yaml.gotmpl, helmfile.d/values/velero-wc.yaml.gotmpl
> [!warning]
>
> [!important]
Adds option to use Velero CSI data movement using volume snapshots for improved backups and restores. Not enabled by default.
- Fixes #2076 
- Logs checks:
- …
=> apps: added option to use velero csi volume snapshot

config/sc-config.yaml, config/schemas/config.yaml, helmfile.d/stacks/tekton.yaml, helmfile.d/state.yaml, helmfile.d/values/networkpolicies/service/tektonPipelines.yaml.gotmpl, migration/v0.41/README.md, migration/v0.41/apply/00-template.sh, migration/v0.41/apply/80-apply.sh, migration/v0.41/prepare/00-template.sh, migration/v0.41/prepare/50-init.sh
> [!warning]
>
> [!important]
Added Network Policies for Tekton. If enabled, it requires the platform administrator to create pipeline specific network policies.
Requires additional network policies for the pipeline. These network policies are added via the config and are generated by the …
=> Add network policies for Tekton

helmfile.d/charts/calico-accountant/Chart.yaml, helmfile.d/charts/calico-accountant/values.yaml, images/calico-accountant/Dockerfile
> [!warning]
>
> [!important]
- This updates the [calico-accountant image](https://github.com/orgs/elastisys/packages/container/package/calico-accountant) to one with an [updated Alpine base system](https://github.com/orgs/elastisys/packages/container/calico-accountant/259885446?tag=0.1.6.ck8s1). …
=> Upgrade calico-accountant image and chart

REQUIREMENTS, changelog/0.40.md, config/common-config.yaml, config/sc-config.yaml, helmfile.d/charts/grafana-dashboards/files/welcome.md, helmfile.d/charts/harbor/harbor-backup/scripts/harbor-backup.sh, helmfile.d/charts/harbor/harbor-backup/templates/harbor-backup-job.yaml, helmfile.d/charts/opensearch/configurer/files/dashboards-resources/welcome.md, images/backup-postgres/Dockerfile
> [!warning]
>
> [!important]
...
Ports the changes made in QA for v0.40 apps release to main branch.
- Logs checks:
- Bug checks:
=> Port v0.40.0

scripts/run-from-container.sh
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Support graphics without XAUTHORITY in run-from-container script

changelog/0.39.md
> [!warning]
>
> [!important]
- Fixes #2267 
- Logs checks:
- Bug checks:
=> Port 0.39.2

helmfile.d/upstream/grafana/grafana/Chart.yaml, helmfile.d/upstream/grafana/grafana/README.md, helmfile.d/upstream/grafana/grafana/ci/with-image-renderer-values.yaml, helmfile.d/upstream/grafana/grafana/ci/with-nondefault-values.yaml, helmfile.d/upstream/grafana/grafana/ci/with-sidecars-envvaluefrom-values.yaml, helmfile.d/upstream/grafana/grafana/templates/NOTES.txt, helmfile.d/upstream/grafana/grafana/templates/_config.tpl, helmfile.d/upstream/grafana/grafana/templates/_helpers.tpl, helmfile.d/upstream/grafana/grafana/templates/_pod.tpl, helmfile.d/upstream/grafana/grafana/templates/configmap.yaml, helmfile.d/upstream/grafana/grafana/templates/dashboards-json-configmap.yaml, helmfile.d/upstream/grafana/grafana/templates/image-renderer-deployment.yaml, helmfile.d/upstream/grafana/grafana/templates/image-renderer-network-policy.yaml, helmfile.d/upstream/grafana/grafana/templates/pvc.yaml, helmfile.d/upstream/grafana/grafana/templates/service.yaml, helmfile.d/upstream/grafana/grafana/templates/statefulset.yaml, helmfile.d/upstream/grafana/grafana/templates/tests/test-configmap.yaml, helmfile.d/upstream/grafana/grafana/templates/tests/test-podsecuritypolicy.yaml, helmfile.d/upstream/grafana/grafana/templates/tests/test-role.yaml, helmfile.d/upstream/grafana/grafana/templates/tests/test-rolebinding.yaml, helmfile.d/upstream/grafana/grafana/templates/tests/test-serviceaccount.yaml, helmfile.d/upstream/grafana/grafana/templates/tests/test.yaml, helmfile.d/upstream/grafana/grafana/values.yaml, helmfile.d/upstream/index.yaml, helmfile.d/values/grafana/grafana-common.yaml.gotmpl
> [!warning]
>
> [!important]
Angular plugins for Grafana dashboards are no longer supported by default. Please migrate any dashboards that contain panels that use Angular plugins (see [here](https://grafana.com/docs/grafana/latest/developers/angular_deprecation/) for more information).
Upgrades …
=> Upgrade Grafana chart to v8.4.7 and image to v11.1.4

helmfile.d/values/kube-prometheus-stack-wc.yaml.gotmpl
> [!warning]
>
> [!important]
Adds the `node.kubernetes.io/instance-type` label to the `kube_node_labels` metric. This label contains the flavor of the node and is useful for billing.
- Fixes #
We had an internal discussion about billing for autoscaling and concluded that this label would be …
=> Add instance type to kube_node_labels metric

.github/ISSUE_TEMPLATE/release.md, .github/pull_request_template.md, release/README.md
> [!warning]
>
> [!important]
As discussed during meeting with @elastisys/goto-public-docs, added a checklist for documentation updates on PR template.
- Logs checks:
- Bug …
=> added documentation checklist for PR template

REQUIREMENTS
> [!warning]
>
> [!important]
Fixes install-requirements by adding minor version wildcards since upstream versions were removed
- Logs checks:
- Bug checks:
=> apps: fix install-requirements

changelog/0.40.md, migration/v0.40/README.md, migration/v0.40/apply/10-opensearch-exporter.sh, migration/v0.40/apply/10-upgrade-opensearch.sh
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Port 0.40.1

helmfile.d/charts/kubeapi-metrics/templates/ingress.yaml
> [!warning]
>
> [!important]
Currently ingress-nginx outputs `Error getting SSL certificate "kube-system/kubeapi-metrics-cert": local SSL certificate kube-system/kubeapi-metrics-cert was not found. Using default certificate` logs quite often in the Workload Cluster due to a secret being …
=> config: remove tls secret from kubeapi-metrics ingress template

config/providers/azure/sc-config.yaml, config/sc-config.yaml, config/schemas/config.yaml, helmfile.d/charts/log-manager/Chart.yaml, helmfile.d/charts/log-manager/files/compaction.sh, helmfile.d/charts/log-manager/files/retention.sh, helmfile.d/charts/log-manager/templates/cronjob-compaction.yaml, helmfile.d/charts/log-manager/templates/cronjob-retention.yaml, helmfile.d/charts/log-manager/values.yaml, helmfile.d/values/fluentd/aggregator-common.yaml.gotmpl, helmfile.d/values/fluentd/log-manager.yaml.gotmpl
> [!warning]
>
> [!important]
Updates the az cli commands and template files of log-manager.
- Fixes #2239 
- Logs checks:
- Bug checks:
=> Fix log-manager on Azure

restore/harbor/README.md, restore/harbor/restore-harbor-job-azure.yaml, scripts/azure/storage-manager.sh
> [!warning]
>
> [!important]
- Part of https://github.com/elastisys/ck8s-issue-tracker/issues/145
- Logs checks:
- Bug checks:
=> Improve Harbor restore for Azure

restore/rclone/README.md
> [!warning]
>
> [!important]
This adds links to the schemas for the more complicated parts of the restore configuration to complement the config examples.
- Part of https://github.com/elastisys/ck8s-issue-tracker/issues/145
- Logs …
=> Link to schemas in Rclone restore instructions

restore/rclone/README.md
> [!warning]
>
> [!important]
- Part of https://github.com/elastisys/ck8s-issue-tracker/issues/145
- Logs checks:
- Bug checks:
=> Add known issue restoring Harbor from S3 to Azure

bin/update-ips.bash, tests/common/bats/update-ips.bash, tests/unit/general/bin-update-ips-rclone.bats, tests/unit/general/bin-update-ips-swift.bats, tests/unit/general/resources/get-swift-url-application-credentails.out, tests/unit/general/resources/get-swift-url-username.out
> [!warning]
>
> [!important]
Continuation of this [PR](https://github.com/elastisys/compliantkubernetes-apps/pull/2289) that needed to be in a release.
Makes get swift ip simpler with extra test.
- Logs checks: …
=> bin: make update swift ip simpler

helmfile.d/values/falco/falco-common.yaml.gotmpl
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> apps sc: add falco exception for tekton cleanup

.github/CODEOWNERS
> [!warning]
>
> [!important]
...
Adds product architect as codeowner
- Logs checks:
- Bug checks:
=> all: add PA as codeowner

REQUIREMENTS
> [!warning]
>
> [!important]
update kubectl version to v1.30.4
- Part of https://github.com/elastisys/compliantkubernetes-kubespray/issues/394
- Logs checks:
- Falco …
=> release: update kubectl version to v1.30.4

.github/ISSUE_TEMPLATE/release.md, bin/diagnostics.bash, changelog/0.42.md, helmfile.d/charts/grafana-dashboards/files/welcome.md, helmfile.d/charts/opensearch/configurer/files/dashboards-resources/welcome.md, helmfile.d/upstream/grafana/grafana/Chart.yaml, helmfile.d/upstream/grafana/grafana/README.md, helmfile.d/upstream/grafana/grafana/templates/_config.tpl, helmfile.d/upstream/grafana/grafana/templates/_pod.tpl, helmfile.d/upstream/grafana/grafana/templates/deployment.yaml, helmfile.d/upstream/grafana/grafana/values.yaml, helmfile.d/upstream/index.yaml, tests/end-to-end/general/bin-diagnostics.bats, tests/end-to-end/velero/resources/backup-spec-sc.yaml, tests/end-to-end/velero/resources/backup-spec-wc.yaml
> [!warning]
>
> [!important]
- Add support for using predefined IP for the Load Balancer .
- The default network policies for cert-manager has changed in `dev` and `prod` flavours allowing all egress traffic on `53/tcp`, `53/udp`, `80/tcp`, and `443/tcp` to provide a better certificate …
=> Add changelog for release v0.42.0

.github/CODEOWNERS
> [!warning]
>
> [!important]
Upgrading upstream charts are huge changes but only changes a single line in the upstream Helmfile index. It does not make sense that the goto-scripts team should be requested to review those pull requests. …
=> Remove goto-scripts as code owners from upstream Helmfile index

helmfile.d/charts/log-manager/files/compaction.sh, helmfile.d/charts/log-manager/files/retention.sh
> [!warning]
>
> [!important]
Fixed issue with log-manager script for azure
- Logs checks:
- Bug checks:
=> apps sc: Fixed issues with log-manager script for azure

helmfile.d/values/falco/falco-common.yaml.gotmpl
> [!warning]
>
> [!important]
Adds the `azureserviceoperator-controller-manager` and `capz-controller-manager` as trusted images to contact the api server.
- Logs checks:
- Audit …
=> Add capi repositories as trusted for falco

config/schemas/config.yaml
> [!warning]
>
> [!important]
Updates the schema for Harbor `disableRedirect` config.
- Fixes #
- Logs checks:
- Bug checks:
=> Add harbor disableRedirect schema description

.github/CODEOWNERS
> [!warning]
>
> [!important]
Updates to the codeowners based on some new goto area changes.
- Logs checks:
- Bug checks:
=> all: update codeowners with new goto areas

bin/ck8s, bin/diagnostics.bash, tests/end-to-end/general/bin-diagnostics.bats
> [!warning]
>
> [!important]
Noticed that running `diagnostics` with a `namespace` exited if no logs were found due to the exit code of `grep` and the script setting `set -euo pipefail`. This PR fixes this, and also adds a test for running `diagnostics namespace`.
Also added some additional …
=> Fixes for diagnostics script with namespace

changelog/0.42.md
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Port 0.42.1

config/common-config.yaml, config/schemas/config.yaml
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Fix URL in config schema

.github/workflows/tests.yml
> [!warning]
>
> [!important]
Small improvement to run the tests at all times as it enters main and to remove the verbose messaging from the build step.
- Logs checks:
- …
=> tests: Workflow improvements

helmfile.d/charts/grafana-label-enforcer/Chart.yaml
> [!warning]
>
> [!important]
Fixes label enforcer using wrong tag for image.
- Fixes #
- Logs checks:
- Bug checks:
=> fix label enforcer chart

helmfile.d/values/kube-prometheus-stack-sc.yaml.gotmpl
> [!warning]
>
> [!important]
Updates alert severity so that both "high" and "warning" translate to P2 in OpsGenie, instead of "high" translating to P5.
- Fixes #
- Logs checks:
- Audit …
=> Update OpsGenie priority

changelog/0.43.md, config/sc-config.yaml, config/schemas/config.yaml, helmfile.d/charts/grafana-label-enforcer/Chart.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/cluster-capacity-management-alerts.yaml, helmfile.d/values/thanos/receiver.yaml.gotmpl
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Add changelog for release v0.43.0

helmfile.d/charts/grafana-label-enforcer/Chart.yaml, helmfile.d/charts/prometheus-alerts/templates/alerts/cluster-capacity-management-alerts.yaml
> [!warning]
>
> [!important]
Port some changes
- Fixes #
- Logs checks:
- Bug checks:
=> Port 0.43.0

REQUIREMENTS, pipeline/Dockerfile, tests/Dockerfile
> [!warning]
>
> [!important]
Update to latest version of sops.
- Logs checks:
- Bug checks:
=> scripts: update sops version to v3.9.4

release/README.md, release/qa-checklist.md
> [!warning]
>
> [!important]
This fixes the duplicated release issue templates.
- Logs checks:
- Bug checks:
=> docs: Update QA checklist

helmfile.d/charts/log-manager/Chart.yaml, helmfile.d/charts/log-manager/values.yaml, images/log-manager/Dockerfile
> [!warning]
>
> [!important]
Adds azCopy to log-manager image and updates the chart to use the new one.
- Fixes #2419 
- Logs checks:
- Bug checks:
=> update log-manager image

helmfile.d/charts/grafana-dashboards/dashboards/cert-manager-mixin/cert-manager-dashboard.json, scripts/grafana-dashboards/.gitignore, scripts/grafana-dashboards/Makefile, scripts/grafana-dashboards/configs/cert-manager-mixin/dashboards.jsonnet, scripts/grafana-dashboards/configs/cert-manager-mixin/mixin.libsonnet
> [!warning]
>
> [!important]
Adds [cert-manager mixin dashboard](https://cert-manager.io/docs/devops-tips/prometheus-metrics/#monitoring-mixin) configured for Welkin.
We do have e.g. the NGINX dashboard which shows the validity for Ingress certs using nginx metrics, but this dashboard would …
=> Add cert-manager mixin dashboard

config/schemas/config.yaml, config/wc-config.yaml, helmfile.d/upstream/index.yaml, helmfile.d/upstream/nvidia/gpu-operator/Chart.lock, helmfile.d/upstream/nvidia/gpu-operator/Chart.yaml, helmfile.d/upstream/nvidia/gpu-operator/charts/node-feature-discovery/Chart.yaml, helmfile.d/upstream/nvidia/gpu-operator/charts/node-feature-discovery/templates/master.yaml, helmfile.d/upstream/nvidia/gpu-operator/charts/node-feature-discovery/templates/nfd-gc.yaml, helmfile.d/upstream/nvidia/gpu-operator/charts/node-feature-discovery/templates/topologyupdater.yaml, helmfile.d/upstream/nvidia/gpu-operator/charts/node-feature-discovery/templates/worker.yaml, helmfile.d/upstream/nvidia/gpu-operator/charts/node-feature-discovery/values.yaml, helmfile.d/upstream/nvidia/gpu-operator/crds/nvidia.com_clusterpolicies.yaml, helmfile.d/upstream/nvidia/gpu-operator/crds/nvidia.com_nvidiadrivers.yaml, helmfile.d/upstream/nvidia/gpu-operator/templates/cleanup_crd.yaml, helmfile.d/upstream/nvidia/gpu-operator/templates/clusterpolicy.yaml, helmfile.d/upstream/nvidia/gpu-operator/templates/clusterrole.yaml, helmfile.d/upstream/nvidia/gpu-operator/templates/dcgm_exporter_config.yaml, helmfile.d/upstream/nvidia/gpu-operator/templates/role.yaml, helmfile.d/upstream/nvidia/gpu-operator/templates/upgrade_crd.yaml, helmfile.d/upstream/nvidia/gpu-operator/values.yaml, helmfile.d/values/gpu-operator.yaml.gotmpl, migration/v0.45/README.md, migration/v0.45/apply/20-gpu-operator.sh
> [!warning]
>
> [!important]
The GPU Operator has received some new configuration options in order to make it easier to deploy in a multi-tenant way
NVIDIA_VISIBLE_DEVICES is now set to volume mounts, which means you need to explicitly request an NVIDIA gpu resource if you want your container …
=> upgrade gpu operator to 24.9.2, allow additional configuration options

helmfile.d/upstream/grafana/grafana/Chart.yaml, helmfile.d/upstream/grafana/grafana/README.md, helmfile.d/upstream/grafana/grafana/ci/with-nondefault-values.yaml, helmfile.d/upstream/grafana/grafana/templates/_helpers.tpl, helmfile.d/upstream/grafana/grafana/templates/_pod.tpl, helmfile.d/upstream/grafana/grafana/templates/deployment.yaml, helmfile.d/upstream/grafana/grafana/templates/hpa.yaml, helmfile.d/upstream/grafana/grafana/templates/image-renderer-deployment.yaml, helmfile.d/upstream/grafana/grafana/templates/image-renderer-hpa.yaml, helmfile.d/upstream/grafana/grafana/templates/route.yaml, helmfile.d/upstream/grafana/grafana/templates/service.yaml, helmfile.d/upstream/grafana/grafana/templates/servicemonitor.yaml, helmfile.d/upstream/grafana/grafana/templates/statefulset.yaml, helmfile.d/upstream/grafana/grafana/templates/tests/test-configmap.yaml, helmfile.d/upstream/grafana/grafana/templates/tests/test-podsecuritypolicy.yaml, helmfile.d/upstream/grafana/grafana/templates/tests/test-role.yaml, helmfile.d/upstream/grafana/grafana/templates/tests/test-rolebinding.yaml, helmfile.d/upstream/grafana/grafana/templates/tests/test-serviceaccount.yaml, helmfile.d/upstream/grafana/grafana/templates/tests/test.yaml, helmfile.d/upstream/grafana/grafana/values.yaml, helmfile.d/upstream/index.yaml
> [!warning]
>
> [!important]
- Updates the Grafana chart to version 8.9.1
- Grafana to version 11.5.1.
High-level release info, with a couple of things that might be worth a second look:
- [Grafana 11.3](https://grafana.com/blog/2024/10/23/grafana-11.3-release-all-the-new-features/)
- …
=> Update Grafana to 11.5.1 (chart 8.9.1)

changelog/0.42.md, changelog/0.43.md, changelog/0.44.md, changelog/0.45.md, config/common-config.yaml, config/sc-config.yaml, config/wc-config.yaml, helmfile.d/charts/grafana-dashboards/files/welcome.md, helmfile.d/charts/opensearch/configurer/files/dashboards-resources/welcome.md, helmfile.d/values/external-dns/external-dns.yaml.gotmpl, helmfile.d/values/falco/falco-common.yaml.gotmpl, helmfile.d/values/gpu-operator.yaml.gotmpl, migration/v0.45/README.md, migration/v0.45/apply/20-gatekeeper-crds.sh, migration/v0.45/apply/40-migrate-gpu-operator-ns.sh
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Staging 0.45.0

changelog/0.45.md, config/common-config.yaml, config/sc-config.yaml, config/wc-config.yaml, helmfile.d/charts/grafana-dashboards/files/welcome.md, helmfile.d/charts/opensearch/configurer/files/dashboards-resources/welcome.md, helmfile.d/values/external-dns/external-dns.yaml.gotmpl, helmfile.d/values/falco/falco-common.yaml.gotmpl, helmfile.d/values/gpu-operator.yaml.gotmpl, migration/v0.45/README.md, migration/v0.45/apply/20-gatekeeper-crds.sh, migration/v0.45/apply/40-migrate-gpu-operator-ns.sh
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Port 0.45.0

changelog/0.43.md, config/common-config.yaml, config/schemas/config.yaml, helmfile.d/values/fluentd/forwarder-common.yaml.gotmpl
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Staging 0.43.3

changelog/0.42.md, config/common-config.yaml, config/schemas/config.yaml, helmfile.d/values/fluentd/forwarder-common.yaml.gotmpl
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Staging 0.42.4

REQUIREMENTS
> [!warning]
>
> [!important]
Bumped kubectl version in requirements, part of Kubespray release
- Logs checks:
- Bug checks:
=> requirements: bump kubectl version to v1.31.7

changelog/0.42.md, changelog/0.43.md, changelog/0.44.md, changelog/0.45.md
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Port patches v0.42.3, v0.42.4, v0.43.2, v0.43.3, v0.44.2, v0.45.1

docs/sbom.md, helmfile.d/charts/hnc/controller/values.yaml, helmfile.d/values/falco/falco-common.yaml.gotmpl
> [!warning]
>
> [!important]
This PR adds the changes required for the mirroring of  the hnc image.
...
- Fixes https://github.com/elastisys/ck8s-issue-tracker/issues/490
- Logs checks:
- NetworkPolicy …
=> apps: hnc mirror image

helmfile.d/charts/opensearch/secrets/values.yaml
> [!warning]
>
> [!important]
Increase renewBefore from 15 to 30 days for OpenSearch certificates. This will prevent the CertificateExpiringSoon alert from always firing for these certs.
- Fixes #
- Logs checks:
- PodSecurityPolicy …
=> Increase renewBefore time for OpenSearch Certificates

DEVELOPMENT.md, bin/ck8s, bin/common.bash, config/schemas/config.yaml, helmfile.d/bases/environments.yaml.gotmpl, scripts/local-cluster.sh, scripts/local-clusters/configs/common-config.yaml, scripts/local-clusters/configs/partial/sc-node-local-dns.yaml, scripts/local-clusters/configs/partial/wc-node-local-dns.yaml, scripts/local-clusters/profiles/multi-node-cache.yaml, scripts/local-clusters/profiles/multi-node.yaml, scripts/local-clusters/profiles/single-node-cache.yaml, scripts/local-clusters/profiles/single-node.yaml, scripts/local-clusters/resolves/Corefile, tests/bats.lib.bash, tests/common/bats/local-cluster.bash, tests/common/exec.bash, tests/integration/general/local-clusters.bats, tests/integration/harbor/setup_suite.bash
> [!warning]
>
This PR updates the documentation (and some configs and scripts) for standing up local development clusters with the aim of running both the SC and the WC on the same machine. 
=> Update local cluster setup & documentation

config/flavors/dev/wc-config.yaml
> [!warning]
>
> [!important]
To make it deploy without issues in single-node clusters.
- Logs checks:
- Bug checks:
=> Set HNC webhook replica count to 1 in dev flavor

.github/CODEOWNERS, .pre-commit-config.yaml, bin/apply.bash, helmfile.d/README.md
> [!warning]
>
> [!important]
Correct state path for apply.
The rest of scripts that uses helmfile only points the path to the state directory not the state file itself, so the same is used here.
- Logs checks:
- PodSecurityPolicy …
=> bin: Correct state path

restore/harbor/README.md
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> docs: Made some clarifications for harbor restore docs

helmfile.d/charts/node-local-dns/templates/node-local-dns.yaml
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Fix indentation in node-local-dns Corefile

bin/common.bash, bin/upgrade.bash, scripts/local-clusters/profiles/multi-node-cache.yaml, scripts/local-clusters/profiles/multi-node.yaml, scripts/local-clusters/profiles/single-node-cache.yaml, scripts/local-clusters/profiles/single-node.yaml
> [!warning]
>
> [!important]
Something got screwed up a long the way in the last PR.
- Logs checks:
- Bug checks:
=> Fix node label check

.github/CODEOWNERS
> [!warning]
>
> [!important]
Couldn't find an team named `goto-pipeline-qa-release` but there is one named `goto-qa` which I assume is the correct one.
- Logs checks:
- …
=> all: Fix goto-qa in CODEOWNERS

config/schemas/config.yaml
> [!warning]
>
> [!important]
This was missing from the config schema giving false warnings
- Fixes #
- Logs checks:
- Bug checks:
=> config: Fixed missed optional config option from schema

bin/update-ips.bash
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Suppress kubectl output in update-ips

tests/unit/general/images.bats
> [!warning]
>
> [!important]
Adds an extra kyverno config key to the images tests setup to get it rendering.
- Logs checks:
- Bug checks:
=> fix: kyverno setup needs some extra config to get going

tests/common/bats/harbor.bash, tests/end-to-end/harbor/use-api.bats, tests/end-to-end/harbor/use-ui.cy.js
> [!warning]
>
> [!important]
This PR adds:
- Test: pulling with vulnerability prevention enabled (should fail)
- Test: pulling with vulnerability prevention disabled (should succeed)
- New functions to be able to update existing projects
- Small optimization in …
=> Add vulnerability prevention to Harbor e2e testing

changelog/0.46.md
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Port v0.46.1

changelog/0.47.md, migration/v0.47/README.md
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Port v0.47.1

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, tests/.dockerignore, tests/.gitignore, tests/Dockerfile, tests/README.md, tests/common/typecheck.bash, tests/package-lock.json, tests/package.json
> [!warning]
>
> [!important]
This makes sure that all developers use the same dependencies when writing Cypress tests.
- Logs checks:
- Bug checks:
=> tests: Add package.json

changelog/0.47.md, config/providers/elastx/sc-config.yaml, helmfile.d/charts/prometheus-alerts/files/thanos.yaml
> [!warning]
>
> [!important]
Backport applicable changes from v0.47.2 patch release.
- Logs checks:
- Bug checks:
=> Port 0.47.2

changelog/0.48.md, config/sc-config.yaml, helmfile.d/charts/grafana-dashboards/files/welcome.md, helmfile.d/charts/opensearch/configurer/files/dashboards-resources/welcome.md, helmfile.d/values/falco/falco-workload-cluster.yaml.gotmpl
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Port 0.48.0

helmfile.d/values/opensearch/securityadmin.yaml.gotmpl, tests/common/cypress/opensearch.js, tests/common/cypress/support.d.ts, tests/end-to-end/grafana/datasources.cy.js, tests/end-to-end/opensearch/authentication.cy.js, tests/end-to-end/opensearch/check-jobs.bats, tests/end-to-end/opensearch/dashboards.cy.js, tests/end-to-end/opensearch/dashboards.gen.bats
> [!warning]
>
> [!important]
This PR adds QA tests for Opensearch component
- Fixes https://github.com/elastisys/ck8s-issue-tracker/issues/239
- Logs checks:
- Falco …
=> qa: Add OpenSearch end-to-end tests

config/sc-config.yaml, config/schemas/config.yaml, helmfile.d/charts/harbor/harbor-mpu-cleaner/Chart.yaml, helmfile.d/charts/harbor/harbor-mpu-cleaner/README.md, helmfile.d/charts/harbor/harbor-mpu-cleaner/scripts/mpu-tool.py, helmfile.d/charts/harbor/harbor-mpu-cleaner/templates/harbor-mpu-cleaner-cm.yaml, helmfile.d/charts/harbor/harbor-mpu-cleaner/templates/harbor-mpu-cleaner-job.yaml, helmfile.d/charts/harbor/harbor-mpu-cleaner/templates/harbor-mpu-cleaner-secret.yaml, helmfile.d/charts/harbor/harbor-mpu-cleaner/values.yaml, helmfile.d/lists/images.yaml, helmfile.d/stacks/harbor.yaml.gotmpl, helmfile.d/state.yaml.gotmpl, helmfile.d/values/harbor/harbor-mpu-cleaner.yaml.gotmpl, helmfile.d/values/networkpolicies/service/harbor.yaml.gotmpl, images/python-boto3/Dockerfile, tests/unit/general/images.bats, tests/unit/general/resources/images-parametric-tests.json
> [!warning]
>
> [!important]
This PR adds: 
- A python script to check for unfinished multipartUploads
- A dockerfile for a container to run the script in
- A Kubernetes cronjob wrapped in a Helm chart to run said container
- Fixes https://github.com/elastisys/compliantkubernetes-apps/issues/246 …
=> Adding files for new multipartUpload cleaner job

restore/rclone/README.md
> [!warning]
>
> [!important]
This adds a note on when you have existing config, but are using new names for the buckets.
- Logs checks:
- Bug checks:
=> docs: Add note on using same config with new names

REQUIREMENTS, tests/Dockerfile
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> other: Updated kubectl version

scripts/grafana-dashboards/Makefile
> [!warning]
>
> [!important]
This makes `make -C scripts/grafana-dashboards/ help` include the (relatively new) `cert-manager-mixin` target along with a descriptive text.
- Logs checks:
- NetworkPolicy …
=> bin: Add missing help text in dashbord update script

helmfile.d/lists/images.yaml, images/rclone-sync/Dockerfile
> [!warning]
>
> [!important]
Upgrade rclone to v1.70.3
Tested sync from s3 to azure for all buckets.
Then restore from azure to s3 for Harbor and everything worked fine.
- Logs checks: …
=> Upgrade rclone to v1.70.3

helmfile.d/values/_helpers.tpl
> [!warning]
>
> [!important]
Removed Quote in the object storage configuration. 
...
- Fixes #
- Logs checks:
- Bug checks:
=> apps: fixing quote issue in objectstorage config

.pre-commit-config.yaml, config/schemas/config.yaml, helmfile.d/charts/calico-accountant/values.yaml, helmfile.d/lists/images.yaml, helmfile.d/values/_helpers.tpl, helmfile.d/values/calico-accountant.yaml.gotmpl, tests/Dockerfile, tests/package-lock.json, tests/package.json, tests/unit/general/schema.bats
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> Staging 0.47.3
